load("//tools/build_rules:java_rules.bzl", "standard_java_test")

standard_java_test(
    name = "runner",
    deps = [
        "//src/com/facebook/buck/jvm/java/runner:runner",
        "//src/com/facebook/buck/jvm/java/version:version",
        "//test/com/facebook/buck/testutil:testutil",
        "//third-party/java/guava:guava",
        "//third-party/java/junit:junit",
    ],
)
