standard_java_test(
    name = "runner",
    deps = [
        "//src/com/facebook/buck/jvm/java/runner:runner",
        "//third-party/java/guava:guava",
        "//third-party/java/junit:junit",
    ],
)
