EMPTY_CONFIGS = {
  'Debug': {},
  'Release': {},
}

apple_binary(
  name = 'TestAppBinary',
  configs = EMPTY_CONFIGS,
  srcs = [],
  frameworks = [],
  deps = [
    '//Libraries/Dep1:Dep1',
  ],
)

apple_bundle(
  name = 'TestApp',
  deps = [':TestAppBinary'],
  binary = ':TestAppBinary',
  extension = 'app',
  visibility = ['PUBLIC'],
)
