standard_java_testutil(
    name = "testutil",
    exported_deps = [
        "//test/com/facebook/buck/jvm/java/testutil:testutil",
        "//third-party/java/asm:asm",
        "//third-party/java/junit:junit",
    ],
    deps = ["//test/com/facebook/buck/testutil/integration:util"],
)

standard_java_test(
    name = "abi",
    deps = [
        "//src/com/facebook/buck/io:io",
        "//src/com/facebook/buck/jvm/java/abi:abi",
        "//src/com/facebook/buck/util/sha1:sha1",
        "//src/com/facebook/buck/zip:unzip",
        "//test/com/facebook/buck/jvm/java/abi:testutil",
        "//test/com/facebook/buck/jvm/java/testutil:testutil",
        "//test/com/facebook/buck/testutil/integration:util",
        "//third-party/java/asm:asm",
        "//third-party/java/easymock:easymock",
        "//third-party/java/guava:guava",
        "//third-party/java/hamcrest:java-hamcrest",
        "//third-party/java/junit:junit",
    ],
)
