load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "config",
    srcs = glob(["*.java"]),
    exported_deps = [
        "//src/com/facebook/buck/core/config:config",
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/util:io",
        "//src/com/facebook/buck/util:process_executor",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//third-party/java/guava:guava",
    ],
)
