load("//tools/build_rules:java_rules.bzl", "buck_java_library")

buck_java_library(
    name = "compiler",
    srcs = glob(["*.java"]),
    visibility = [
        "//test/com/facebook/buck/jvm/...",
    ],
    deps = [
        "//test/com/facebook/buck/jvm/java/testutil/compiler:compiler",
        "//third-party/java/guava:guava",
        "//third-party/java/junit:junit",
        "//third-party/java/kotlin:kotlin-compiler",
        "//third-party/java/kotlin:kotlin-stdlib",
        "//third-party/java/kotlin:trove",
    ],
)
