load("//tools/build_rules:java_rules.bzl", "java_test")

java_test(
    name = "artifact",
    srcs = glob(["*Test.java"]),
    deps = [
        "//src/com/facebook/buck/core/artifact:artifact",
        "//test/com/facebook/buck/core/model:testutil",
        "//test/com/facebook/buck/io/filesystem:testutil",
        "//test/com/facebook/buck/io/filesystem/impl:testutil",
        "//test/com/facebook/buck/testutil:testutil",
        "//third-party/java/guava:guava",
        "//third-party/java/junit:junit",
    ],
)
