load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "rules",
    srcs = glob(
        ["*.java"],
    ),
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/core/rules/providers/collect:collect",
        "//src/com/facebook/buck/log/views:views",
        "//src/com/facebook/buck/util:util",
        "//src/com/facebook/buck/util/collect:collect",
        "//src/com/facebook/buck/util/concurrent:concurrent",
        "//third-party/java/guava:guava",
        "//third-party/java/infer-annotations:infer-annotations",
        "//third-party/java/jackson:jackson-annotations",
        "//third-party/java/jackson:jackson-databind",
        "//third-party/java/jsr:jsr305",
    ],
    exported_deps = [
        "//src/com/facebook/buck/core/build/action:action",
        "//src/com/facebook/buck/core/build/buildable/context:context",
        "//src/com/facebook/buck/core/build/context:context",
        "//src/com/facebook/buck/core/cell:cell",
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/core/model/targetgraph:targetgraph",
        "//src/com/facebook/buck/core/rules/config/registry:registry",
        "//src/com/facebook/buck/core/rules/providers:providers",
        "//src/com/facebook/buck/core/sourcepath:sourcepath",
        "//src/com/facebook/buck/core/sourcepath/resolver:resolver",
        "//src/com/facebook/buck/core/toolchain:toolchain",
        "//src/com/facebook/buck/io/filesystem:filesystem",
        "//src/com/facebook/buck/step:step",
    ],
)
