java_library(
    name = "rules",
    srcs = glob(
        ["*.java"],
    ),
    exported_deps = [
        "//src/com/facebook/buck/core/build/buildable/context:context",
        "//src/com/facebook/buck/core/build/context:context",
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/core/rules/provider:provider",
        "//src/com/facebook/buck/core/sourcepath:sourcepath",
        "//src/com/facebook/buck/io/filesystem:filesystem",
        "//src/com/facebook/buck/step:step",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/log/views:views",
        "//src/com/facebook/buck/util:util",
        "//src/com/facebook/buck/util/concurrent:concurrent",
        "//third-party/java/guava:guava",
        "//third-party/java/infer-annotations:infer-annotations",
        "//third-party/java/jackson:jackson-annotations",
        "//third-party/java/jackson:jackson-databind",
        "//third-party/java/jsr:jsr305",
    ],
)
