java_immutables_library(
  name = 'rules',
  srcs = glob(['*.java']),
  autodeps = True,
  tests = [
    '//test/com/facebook/buck/swift:swift_test_integration',
  ],
  visibility = [
    'PUBLIC'
  ],
)
