PLATFORM_SRCS = [
  'AbstractSwiftOutputEntry.java',
  'AbstractSwiftPlatform.java',
  'SwiftPlatforms.java',
]
java_immutables_library(
  name = 'platform',
  srcs = PLATFORM_SRCS,
  immutable_types = [
    'SwiftPlatform',
  ],
  autodeps = True,
  visibility = ['PUBLIC'],
)

standard_java_library(
  srcs = glob(['*.java',], excludes=PLATFORM_SRCS),
  tests = [
    '//test/com/facebook/buck/swift:swift',
  ],
)
