java_test(
  name = 'fs',
  srcs = glob(['*.java']),
  source_under_test = [
    '//src/com/facebook/buck/step/fs:fs',
  ],
  deps = [
    '//src/com/facebook/buck/event:event',
    '//src/com/facebook/buck/io:io',
    '//src/com/facebook/buck/shell:steps',
    '//src/com/facebook/buck/step/fs:fs',
    '//src/com/facebook/buck/step:step',
    '//src/com/facebook/buck/timing:timing',
    '//src/com/facebook/buck/util/environment:platform',
    '//test/com/facebook/buck/event:testutil',
    '//test/com/facebook/buck/io:testutil',
    '//test/com/facebook/buck/step:testutil',
    '//test/com/facebook/buck/testutil/integration:integration',
    '//test/com/facebook/buck/testutil:testutil',
    '//test/com/facebook/buck/timing:testutil',
    '//third-party/java/easymock:easymock',
    '//third-party/java/guava:guava',
    '//third-party/java/junit:junit',
    '//third-party/java/xz-java-1.3:xz',
  ],
)

