load("//tools/build_rules:java_rules.bzl", "standard_java_test")

standard_java_test(
    name = "nativelink",
    deps = [
        "//src/com/facebook/buck/core/rules:rules",
        "//src/com/facebook/buck/cxx:rules",
        "//src/com/facebook/buck/cxx/toolchain:toolchain",
        "//src/com/facebook/buck/cxx/toolchain/linker:linker",
        "//src/com/facebook/buck/cxx/toolchain/nativelink:nativelink",
        "//src/com/facebook/buck/model:model",
        "//src/com/facebook/buck/parser:rule_pattern",
        "//src/com/facebook/buck/rules/args:args",
        "//src/com/facebook/buck/util:exceptions",
        "//test/com/facebook/buck/core/rules/resolver/impl:testutil",
        "//test/com/facebook/buck/cxx/toolchain:testutil",
        "//test/com/facebook/buck/model:testutil",
        "//test/com/facebook/buck/rules:testutil",
        "//third-party/java/guava:guava",
        "//third-party/java/hamcrest:hamcrest-junit",
        "//third-party/java/junit:junit",
    ],
)
