load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "tool",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/core/model/impl:impl",
        "//src/com/facebook/buck/core/rules/actions/lib/args:args",
        "//src/com/facebook/buck/rules/args:args",
        "//src/com/facebook/buck/shell:steps",
        "//src/com/facebook/buck/step/fs:fs",
        "//src/com/facebook/buck/util/json:json",
    ],
    exported_deps = [
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/core/rules:rules",
        "//src/com/facebook/buck/core/rules/attr:attr",
        "//src/com/facebook/buck/core/rules/common:common",
        "//src/com/facebook/buck/core/rules/impl:impl",
        "//src/com/facebook/buck/core/test/rule:rule",
        "//src/com/facebook/buck/core/toolchain/tool:tool",
        "//src/com/facebook/buck/step:step",
    ],
)
