java_library(
    name = "tool",
    srcs = glob(["*.java"]),
    exported_deps = [
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/core/rules:rules",
        "//src/com/facebook/buck/core/rules/attr:attr",
        "//src/com/facebook/buck/core/rules/common:common",
        "//src/com/facebook/buck/core/rules/impl:impl",
        "//src/com/facebook/buck/core/toolchain/tool:tool",
        "//src/com/facebook/buck/step:step",
    ],
    visibility = ["PUBLIC"],
)
