CONFIG_SRCS = [
  'AbstractRageConfig.java',
  'AbstractUserLocalConfiguration.java',
]

java_immutables_library(
  name = 'config',
  srcs = CONFIG_SRCS,
  immutable_types = [
    'RageConfig',
  ],
  autodeps = True,
  visibility = [
    'PUBLIC'
  ]
)

java_immutables_library(
  name = 'rage',
  srcs = glob(['*.java'], excludes = CONFIG_SRCS),
  immutable_types = [
    'BuildLogEntry',
    'UserReport',
  ],
  autodeps = True,
  visibility = [
    'PUBLIC',
  ],
)
