java_library(
    name = "utils",
    srcs = glob(["**/*.java"]),
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src-gen:downward-model",
        "//src/com/facebook/buck/core/util/log:log",
    ],
)
