java_library(
  name = 'log',
  srcs = glob(['*.java']),
  deps = [
    '//src/com/facebook/buck/util/concurrent:concurrent',
    '//src/com/facebook/buck/util:constants',
    '//third-party/java/guava:guava',
    '//third-party/java/jsr:jsr305',
  ],
  visibility = [
    'PUBLIC',
  ]
)
