java_library(
  name = 'log',
  srcs = glob(['*.java']),
  deps = [
    '//src/com/facebook/buck/event:event',
    '//src/com/facebook/buck/util:constants',
    '//src/com/facebook/buck/util:io',
    '//lib:guava',
  ],
  visibility = [
    'PUBLIC',
  ]
)
