java_test(
  name = 'io',
  srcs = glob(['*Test.java']),
  deps = [
    '//src/com/facebook/buck/cli:config',
    '//src/com/facebook/buck/io:io',
    '//src/com/facebook/buck/io:watchman',
    '//src/com/facebook/buck/util:constants',
    '//src/com/facebook/buck/util:io',
    '//src/com/facebook/buck/util/environment:platform',
    '//src/com/facebook/buck/zip:stream',
    '//test/com/facebook/buck/cli:testutil',
    '//test/com/facebook/buck/testutil/integration:integration',
    '//test/com/facebook/buck/testutil:testutil',
    '//test/com/facebook/buck/util:testutil',
    '//third-party/java/commons-compress:commons-compress',
    '//third-party/java/guava:guava',
    '//third-party/java/hamcrest:hamcrest',
    '//third-party/java/jimfs:jimfs',
    '//third-party/java/junit:junit',
  ],
)

java_library(
  name = 'testutil',
  srcs = glob(['*.java'], excludes = ['*Test.java']),
  deps = [
    '//src/com/facebook/buck/io:io',
    '//third-party/java/guava:guava',
    '//third-party/java/jsr:jsr305',
  ],
  visibility = [
    '//test/...',
  ],
)
