load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "impl",
    srcs = glob(
        ["*.java"],
    ),
    exported_deps = [
        "//src/com/facebook/buck/core/rules/graphbuilder:graphbuilder",
    ],
    tests = [
        "//test/com/facebook/buck/core/rules/graphbuilder/impl:impl",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/core/graph/transformation:transformation",
        "//src/com/facebook/buck/core/rules:rules",
        "//third-party/java/guava:guava",
    ],
)
