android_build_config(
  name = 'build_config',
  package = 'exotest',
  values = [],
)

android_binary(
  name = 'exotest',
  manifest = 'AndroidManifest.xml',
  keystore = ':debug_keystore',
  use_split_dex = True,
  exopackage_modes = [
    'native_library',
    'secondary_dex',
  ],
  primary_dex_patterns = [
    '^exotest/AppShell^',
    '^exotest/BuildConfig^',
    '^com/facebook/buck/android/support/exopackage/'
  ],
  deps = [
    ':main-lib',
    ':app-lib',
  ],
)

android_binary(
  name = 'exotest-noexo',
  manifest = 'AndroidManifest.xml',
  keystore = ':debug_keystore',
  deps = [
    ':main-lib',
    ':app-lib',
  ],
)

android_library(
  name = 'app-lib',
  srcs = ['AppShell.java'],
  deps = [
    ':buck-android-support',
    ':build_config',
  ],
)

android_library(
  name = 'main-lib',
  srcs = [
    'LogActivity.java',
    '//:value',
  ],
  deps = [
    '//jni/one:one',
    '//jni/two:two',
    ':buck-android-support',
  ]
)

genrule(
  name = 'value',
  out = 'Value.java',
  srcs = [
    'value.txt',
    'Value.java.template',
  ],
  cmd = 'VALUE=`cat value.txt` ; sed s/HERE/$VALUE/ < Value.java.template > $OUT'
)

prebuilt_jar(
  name = 'buck-android-support',
  binary_jar = 'buck-android-support.jar',
)

keystore(
  name = 'debug_keystore',
  store = 'debug.keystore',
  properties = 'debug.keystore.properties',
)
