load("//tools/build_rules:java_rules.bzl", "standard_java_test")

standard_java_test(
    name = "cachestats",
    visibility = ["//test/..."],
    with_test_data = True,
    deps = [
        "//src-gen:thrift",
        "//src/com/facebook/buck/artifact_cache:artifact_cache",
        "//src/com/facebook/buck/core/build/engine/impl:impl",
        "//src/com/facebook/buck/core/build/event:event",
        "//src/com/facebook/buck/core/rulekey/calculator:calculator",
        "//src/com/facebook/buck/event:event",
        "//src/com/facebook/buck/event:interfaces",
        "//src/com/facebook/buck/event/listener/cachestats:cachestats",
        "//test/com/facebook/buck/core/rules/impl:testutil",
        "//test/com/facebook/buck/event:testutil",
        "//test/com/facebook/buck/rules:testutil",
        "//third-party/java/jackson:jackson-annotations",
        "//third-party/java/jackson:jackson-core",
        "//third-party/java/jackson:jackson-databind",
        "//third-party/java/junit:junit",
    ],
)
