// @generated
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/com/facebook/buck/logd/proto/logdservice.proto

package com.facebook.buck.logd.proto;

@javax.annotation.Generated(value="protoc", comments="annotations:CreateLogDirRequestOrBuilder.java.pb.meta")
public interface CreateLogDirRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:logd.v1.CreateLogDirRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * a buck command's uuid
   * </pre>
   *
   * <code>string buildId = 1;</code>
   */
  java.lang.String getBuildId();
  /**
   * <pre>
   * a buck command's uuid
   * </pre>
   *
   * <code>string buildId = 1;</code>
   */
  com.google.protobuf.ByteString
      getBuildIdBytes();
}
