load("//tools/build_rules:java_rules.bzl", "buck_java_library")

buck_java_library(
    name = "appendablelogrecord",
    srcs = glob(["*java"]),
    # This target is pulled in by testrunner, which needs to compile against Java 8.
    source = "8",
    target = "8",
    visibility = [
        "//src/com/facebook/buck/core/util/log:log",
        "//src/com/facebook/buck/log:",
        "//src/com/facebook/buck/testrunner:junit",
    ],
)
