UTILS_SRCS = [
    "ProjectFilesystemUtils.java",
]

java_library(
    name = "impl",
    srcs = glob(
        ["*.java"],
        exclude = UTILS_SRCS,
    ),
    tests = [
        "//test/com/facebook/buck/io/filesystem/impl:impl",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        ":utils",
        "//src/com/facebook/buck/core/exceptions:exceptions",
        "//src/com/facebook/buck/core/util/log:log",
        "//src/com/facebook/buck/edenfs:edenfs",
        "//src/com/facebook/buck/event:interfaces",
        "//src/com/facebook/buck/io:io",
        "//src/com/facebook/buck/io/file:file",
        "//src/com/facebook/buck/io/watchman:capability",
        "//src/com/facebook/buck/io/watchman:watchman",
        "//src/com/facebook/buck/io/windowsfs:windowsfs",
        "//src/com/facebook/buck/util:constants",
        "//src/com/facebook/buck/util:process_executor",
        "//src/com/facebook/buck/util:util",
        "//src/com/facebook/buck/util/config:config",
        "//src/com/facebook/buck/util/environment:platform",
        "//src/com/facebook/buck/util/sha1:sha1",
        "//src/com/facebook/buck/util/stream:stream",
        "//src/com/facebook/buck/util/versioncontrol:versioncontrol",
        "//third-party/java/guava:guava",
        "//third-party/java/jsr:jsr305",
    ],
    exported_deps = [
        "//src/com/facebook/buck/io/filesystem:filesystem",
    ],
)

java_library(
    name = "utils",
    srcs = UTILS_SRCS,
    tests = [
        "//test/com/facebook/buck/io/filesystem/impl:impl",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/core/exceptions:exceptions",
        "//src/com/facebook/buck/core/util/log:log",
        "//src/com/facebook/buck/event:interfaces",
        "//src/com/facebook/buck/io:io",
        "//src/com/facebook/buck/io/file:file",
        "//src/com/facebook/buck/io/watchman:capability",
        "//src/com/facebook/buck/io/windowsfs:windowsfs",
        "//src/com/facebook/buck/util:constants",
        "//src/com/facebook/buck/util:process_executor",
        "//src/com/facebook/buck/util:util",
        "//src/com/facebook/buck/util/config:config",
        "//src/com/facebook/buck/util/environment:platform",
        "//src/com/facebook/buck/util/sha1:sha1",
        "//src/com/facebook/buck/util/stream:stream",
        "//src/com/facebook/buck/util/versioncontrol:versioncontrol",
        "//third-party/java/guava:guava",
        "//third-party/java/jsr:jsr305",
    ],
    exported_deps = [
        "//src/com/facebook/buck/io/filesystem:filesystem",
    ],
)
