java_library(
    name = "impl",
    srcs = glob(["*.java"]),
    exported_deps = [
        "//src/com/facebook/buck/io/filesystem:filesystem",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/io:io",
        "//src/com/facebook/buck/util:exceptions",
        "//src/com/facebook/buck/util/config:config",
        "//third-party/java/guava:guava",
        "//third-party/java/jsr:jsr305",
    ],
)
