standard_java_library(
  immutable_types = [
    'AbstractConstraints',
    'AbstractExactConstraint',
    'AbstractImplication',
    'AbstractVersion',
    'AbstractVersionedAlias',
    'AbstractVersionInfo',
    'AbstractVersionUniverse',
  ],
  tests = [
    '//test/com/facebook/buck/versions:versions',
  ],
)
