load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "artifact",
    srcs = glob(["*.java"]),
    exported_deps = [
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/core/rules/analysis/action:action",
        "//src/com/facebook/buck/core/sourcepath:sourcepath",
        "//src/com/facebook/buck/core/starlark/rule/artifact:artifact",
    ],
    tests = [
        "//test/com/facebook/buck/core/artifact:artifact",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/core/model/impl:impl",
        "//src/com/facebook/buck/io/file:file",
        "//third-party/java/guava:guava",
    ],
)
