java_library(
    name = "impl",
    srcs = glob(["*.java"]),
    exported_deps = [
        "//src/com/facebook/buck/android:utils",
        "//src/com/facebook/buck/android/toolchain:toolchain",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/android:config",
        "//src/com/facebook/buck/android:helpers",
        "//src/com/facebook/buck/android:steps",
        "//src/com/facebook/buck/android/toolchain:toolchain",
        "//src/com/facebook/buck/android/toolchain/ndk:ndk",
        "//src/com/facebook/buck/config:config",
        "//src/com/facebook/buck/cxx/toolchain:toolchain",
        "//src/com/facebook/buck/io:io",
        "//src/com/facebook/buck/io/filesystem:filesystem",
        "//src/com/facebook/buck/util/environment:platform",
        "//third-party/java/guava:guava",
    ],
)
