java_library(
    name = "impl",
    srcs = glob(["*.java"]),
    exported_deps = [
        "//src/com/facebook/buck/android/toolchain/ndk:ndk",
        "//src/com/facebook/buck/toolchain:toolchain",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/android:config",
        "//src/com/facebook/buck/android:helpers",
        "//src/com/facebook/buck/android:utils",
        "//src/com/facebook/buck/util/environment:platform",
    ],
)
