load("//tools/build_rules:java_rules.bzl", "standard_java_test")

java_library(
    name = "testutil",
    srcs = glob(
        ["*.java"],
        exclude = [
            "*Test.java",
        ],
    ),
    exported_deps = [
        "//src/com/facebook/buck/util/config:config",
    ],
    visibility = ["//test/..."],
    deps = [
        "//third-party/java/guava:guava",
    ],
)

standard_java_test(
    name = "config",
    deps = [
        ":testutil",
        "//src/com/facebook/buck/core/exceptions:exceptions",
        "//src/com/facebook/buck/util:exceptions",
        "//src/com/facebook/buck/util/config:config",
        "//third-party/java/guava:guava",
        "//third-party/java/hamcrest:java-hamcrest",
        "//third-party/java/ini4j:ini4j",
        "//third-party/java/junit:junit",
    ],
)
