java_library(
  name = 'NotBuckBlockJUnit4ClassRunner',
  srcs = [ 'NotBuckBlockJUnit4ClassRunner.java', ],
  deps = [
    ':junit',
  ],
)

java_test(
  name = 'TestThatTakesTooLong',
  srcs = [ 'TestThatTakesTooLong.java', ],
  deps = [
    ':junit',
    ':NotBuckBlockJUnit4ClassRunner',
  ],
)

java_test(
  name = 'TestThatRunsForever',
  srcs = [ 'TestThatRunsForever.java', ],
  deps = [
    ':junit',
    ':NotBuckBlockJUnit4ClassRunner',
  ],
)

java_test(
  name = 'TestThatExceedsDefaultTimeoutButIsLessThanTimeoutAnnotation',
  srcs = [ 'TestThatExceedsDefaultTimeoutButIsLessThanTimeoutAnnotation.java', ],
  deps = [
    ':junit',
    ':NotBuckBlockJUnit4ClassRunner',
  ],
)

java_test(
  name = 'TestThatExceedsDefaultTimeoutButIsLessThanTimeoutRule',
  srcs = [ 'TestThatExceedsDefaultTimeoutButIsLessThanTimeoutRule.java', ],
  deps = [
    ':junit',
    ':NotBuckBlockJUnit4ClassRunner',
  ],
)

prebuilt_jar(
  name = 'junit',
  binary_jar = 'junit-4.11.jar',
  deps = [
    ':hamcrest-core',
    ':hamcrest-library',
  ],
)

prebuilt_jar(
  name = 'hamcrest-core',
  binary_jar = 'hamcrest-core-1.3.jar',
)

prebuilt_jar(
  name = 'hamcrest-library',
  binary_jar = 'hamcrest-library-1.3.jar',
)
