load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "resolver",
    srcs = [
        "SourcePathResolver.java",
    ],
    exported_deps = [
        "//src/com/facebook/buck/core/sourcepath:sourcepath",
        "//src/com/facebook/buck/io:io",
        "//src/com/facebook/buck/io/filesystem:filesystem",
        "//src/com/facebook/buck/model:model",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//third-party/java/guava:guava",
    ],
)
