java_library(
    name = "testutil",
    srcs = glob(["*.java"]),
    visibility = ["//test/..."],
    deps = [
        "//src-gen:downward-model",
        "//src/com/facebook/buck/io/namedpipes:namedpipes",
        "//third-party/java/guava:guava",
        "//third-party/java/jna:jna-platform",
        "//third-party/java/junit:junit",
    ],
)
