java_test(
    name = "integration",
    srcs = glob(["*IntegrationTest.java"]),
    autodeps = True,
    env = {
        "GOROOT": read_config("go", "root", "/usr/local/go"),
    },
    deps = [
        "//src/com/facebook/buck/util:exceptions",
        "//src/com/facebook/buck/util:process_executor",
        "//test/com/facebook/buck/go:assumptions",
        "//test/com/facebook/buck/testutil/integration:util",
        "//third-party/java/hamcrest:java-hamcrest",
        "//third-party/java/junit:junit",
    ],
)

java_test(
    name = "unit",
    srcs = glob(
        ["*Test.java"],
        excludes = ["*IntegrationTest.java"],
    ),
    autodeps = True,
    deps = [
        "//src/com/facebook/buck/go:go",
        "//src/com/facebook/buck/io:MorePaths.java",
        "//third-party/java/guava:guava",
        "//third-party/java/hamcrest:java-hamcrest",
        "//third-party/java/junit:junit",
    ],
)

java_library(
    name = "assumptions",
    srcs = [
        "GoAssumptions.java",
    ],
    autodeps = True,
    deps = [
        "//src/com/facebook/buck/go:go",
        "//src/com/facebook/buck/model:model",
        "//src/com/facebook/buck/util:exceptions",
        "//src/com/facebook/buck/util:process_executor",
        "//test/com/facebook/buck/cli:FakeBuckConfig",
        "//test/com/facebook/buck/testutil:testutil",
        "//third-party/java/guava:guava",
        "//third-party/java/junit:junit",
    ],
)
