standard_java_library(
    name = "common",
    exported_deps = [
        "//src/com/facebook/buck/io:io",
        "//src/com/facebook/buck/rules:build_rule",
        "//third-party/java/guava:guava",
    ],
    deps = ["//src/com/facebook/buck/util:exceptions"],
)
