java_library(
    name = "common",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/core/sourcepath/resolver:resolver",
        "//src/com/facebook/buck/io:io",
        "//src/com/facebook/buck/io/filesystem:filesystem",
        "//src/com/facebook/buck/rules:build_rule",
        "//src/com/facebook/buck/util:exceptions",
        "//third-party/java/guava:guava",
    ],
)
