load("//tools/build_rules:java_rules.bzl", "java_immutables_library", "java_test")

java_test(
    name = "impl",
    srcs = glob(["*Test.java"]),
    has_immutable_types = True,
    deps = [
        ":testutil",
        "//src/com/facebook/buck/core/model/targetgraph:targetgraph",
        "//src/com/facebook/buck/event:event",
        "//src/com/facebook/buck/event:interfaces",
        "//src/com/facebook/buck/jvm/java:config",
        "//src/com/facebook/buck/util/cache:cache",
        "//test/com/facebook/buck/core/model:testutil",
        "//test/com/facebook/buck/core/model/targetgraph:testutil",
        "//test/com/facebook/buck/jvm/java:testutil",
        "//test/com/facebook/buck/testutil:testutil",
        "//test/com/facebook/buck/testutil/integration:util",
        "//test/com/facebook/buck/util/timing:testutil",
        "//third-party/java/junit:junit",
    ],
)

java_library(
    name = "testutil",
    srcs = glob(
        ["*.java"],
        exclude = ["*Test.java"],
    ),
    exported_deps = [
        "//src/com/facebook/buck/core/model/targetgraph/impl:impl",
    ],
    visibility = [
        "//test/...",
    ],
    deps = [
    ],
)
