standard_java_library(
  visibility = [],  # Only visible to this build file.
)

java_binary(
  name = 'report-generator',
  blacklist = [
    '.*SF',
    '.*RSA',
  ],
  main_class = 'com.facebook.buck.jvm.java.coverage.ReportGenerator',
  visibility = [
    '//programs:bucklib',
    '//programs:bucklib-no-nailgun',
    '//src/com/facebook/buck/jvm/java:steps',
  ],
  deps = [
    ':coverage',
  ],
)
