java_library(
  name = 'coverage',
  srcs = [
    'ReportGenerator.java',
  ],
  autodeps = True,
)

java_binary(
  name = 'report-generator',
  main_class = 'com.facebook.buck.jvm.java.coverage.ReportGenerator',
  blacklist = [
    '.*SF',
    '.*RSA',
  ],
  deps = [
    ':coverage',
  ],
  visibility = [
    '//programs:bucklib',
    '//programs:bucklib-no-nailgun',
    '//src/com/facebook/buck/jvm/java:steps',
  ]
)
