java_library(
    name = "visibility",
    srcs = glob(["*.java"]),
    required_for_source_only_abi = True,
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/core/model:model",
        "//third-party/java/guava:guava",
    ],
)
