load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "options",
    srcs = glob([
        "*.java",
    ]),
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/core/model/targetgraph:targetgraph",
        "//src/com/facebook/buck/io:io",
        "//src/com/facebook/buck/io/filesystem:filesystem",
        "//src/com/facebook/buck/io/watchman:watchman",
        "//third-party/java/guava:guava",
    ],
)
