java_library(
    name = "function",
    srcs = [
        "BuckPyFunction.java",
    ],
    resources = [
        "BuckPyFunction.stg",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/core/description/arg:arg",
        "//src/com/facebook/buck/core/exceptions:exceptions",
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/core/starlark/rule/attr:attr",
        "//src/com/facebook/buck/rules/visibility:visibility",
        "//src/com/facebook/buck/skylark/function:function",
        "//src/com/facebook/buck/util:util",
        "//third-party/java/guava:guava",
        "//third-party/java/stringtemplate:stringtemplate",
    ],
    exported_deps = [
        "//src/com/facebook/buck/rules/coercer:interface",
    ],
)
