java_library(
  name = 'd',
  srcs = [
    'DBinary.java',
    'DBinaryDescription.java',
    'DBuckConfig.java',
    'DCompileBuildRule.java',
    'DCompileStep.java',
    'DDescriptionUtils.java',
    'DLibrary.java',
    'DLibraryDescription.java',
    'DTest.java',
    'DTestDescription.java',
    'DTestStep.java',
  ],
  autodeps = True,
  visibility=['PUBLIC'],
)
