load("//tools/build_rules:java_rules.bzl", "java_library_with_plugins")

java_library_with_plugins(
    name = "impl",
    srcs = glob(["*.java"]),
    exported_deps = [
        "//src/com/facebook/buck/cxx/toolchain:toolchain",
        "//src/com/facebook/buck/toolchain:toolchain",
    ],
    visibility = ["PUBLIC"],
)
