load("//tools/build_rules:java_rules.bzl", "java_test")

TEST_FILES_GLOB = ["*Test.java"]

java_test(
    name = "consistency",
    srcs = glob(TEST_FILES_GLOB),
    deps = [
        ":testutil",
        "//src-gen:thrift",
        "//src/com/facebook/buck/log/thrift:thrift",
        "//test/com/facebook/buck/testutil:testutil",
        "//test/com/facebook/buck/testutil/integration:util",
        "//third-party/java/guava:guava",
        "//third-party/java/jsr:jsr305",
        "//third-party/java/junit:junit",
        "//third-party/java/thrift:libthrift",
        "//tools/consistency_checker/src/com/facebook/buck/tools/consistency:consistency",
    ],
)

java_library(
    name = "testutil",
    srcs = glob(
        ["*.java"],
        exclude = TEST_FILES_GLOB,
    ),
    deps = [
        "//third-party/java/guava:guava",
    ],
)
