load("//tools/build_rules:java_rules.bzl", "java_test")

java_library(
    name = "testutil",
    srcs = glob(
        ["*.java"],
        exclude = [
            "*Test.java",
        ],
    ),
    visibility = [
        "//test/...",
    ],
    deps = [
        "//src/com/facebook/buck/python/toolchain/impl:impl",
        "//test/com/facebook/buck/model:testutil",
        "//test/com/facebook/buck/testutil:testutil",
        "//test/com/facebook/buck/toolchain/impl:testutil",
    ],
)

java_test(
    name = "impl",
    srcs = glob(["*Test.java"]),
    deps = [
        ":testutil",
        "//src/com/facebook/buck/io:io",
        "//src/com/facebook/buck/python/toolchain/impl:impl",
        "//test/com/facebook/buck/config:FakeBuckConfig",
        "//test/com/facebook/buck/io:testutil",
        "//test/com/facebook/buck/model:testutil",
        "//test/com/facebook/buck/testutil:testutil",
        "//test/com/facebook/buck/util:testutil",
        "//third-party/java/guava:guava",
        "//third-party/java/junit:junit",
    ],
)
