java_library(
    name = "launcher",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/log:api",
        "//src/com/facebook/buck/util/env:env",
        "//src/com/facebook/buck/util/trace/uploader/types:types",
        "//third-party/java/guava:guava",
    ],
)
