load("//tools/build_rules:java_rules.bzl", "buck_java_library")
buck_java_library(
    name = "launcher",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/core/config:config",
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/core/util/log:log",
        "//src/com/facebook/buck/jvm/java:config",
        "//src/com/facebook/buck/util/env:env",
        "//src/com/facebook/buck/util/java:java",
        "//src/com/facebook/buck/util/trace/uploader/types:types",
        "//third-party/java/guava:guava",
    ],
)
