java_library(
    name = "raw",
    srcs = glob(["*.java"]),
    exported_deps = [
        "//src/com/facebook/buck/core/graph/transformation/model:model",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/rules/visibility:visibility",
        "//third-party/java/guava:guava",
    ],
)
