load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "impl",
    srcs = glob(["*.java"]),
    exported_deps = [
        "//src/com/facebook/buck/core/model/targetgraph:targetgraph",
        "//src/com/facebook/buck/core/model/targetgraph/raw:raw",
        "//src/com/facebook/buck/core/rules/impl:impl",
        "//src/com/facebook/buck/core/util/graph:graph",
        "//src/com/facebook/buck/parser/exceptions:exceptions",
        "//src/com/facebook/buck/rules/coercer:coercer",
        "//src/com/facebook/buck/rules/visibility:visibility",
    ],
    tests = [
        "//test/com/facebook/buck/core/model/targetgraph:targetgraph",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/core/description/arg:arg",
        "//src/com/facebook/buck/core/description/attr:attr",
        "//src/com/facebook/buck/core/description/impl:impl",
        "//src/com/facebook/buck/core/util/log:log",
        "//src/com/facebook/buck/event:event",
        "//src/com/facebook/buck/json:json",
        "//src/com/facebook/buck/util:util",
        "//src/com/facebook/buck/util/hashing:hashing",
        "//third-party/java/jackson:jackson-annotations",
        "//third-party/java/jackson:jackson-databind",
    ],
)
