load("//tools/build_rules:java_rules.bzl", "standard_java_test")

standard_java_test(
    name = "skylark",
    deps = [
        "//src/com/facebook/buck/io:io",
        "//src/com/facebook/buck/io/filesystem/skylark:skylark",
        "//src/com/facebook/buck/util:util",
        "//test/com/facebook/buck/io/filesystem/impl:testutil",
        "//test/com/facebook/buck/testutil:testutil",
        "//third-party/java/bazel:skylark-lang",
        "//third-party/java/guava:guava",
        "//third-party/java/junit:junit",
    ],
)
