java_test(
  name = 'codegen',
  srcs = glob(['*.java']),
  source_under_test = [
    '//src/com/facebook/buck/codegen:codegen',
  ],
  deps = [
    '//lib:guava',
    '//lib:junit',
    '//src/com/facebook/buck/codegen:codegen',
  ],
)
