standard_java_testutil(
    name = "testutil",
)

standard_java_test(
    name = "randomizedtrial",
    deps = [
        "//src/com/facebook/buck/randomizedtrial:randomizedtrial",
        "//third-party/java/hamcrest:java-hamcrest",
        "//third-party/java/junit:junit",
    ],
)
