standard_java_test(
    name = "randomizedtrial",
    deps = [
        "//src/com/facebook/buck/randomizedtrial:randomizedtrial",
        "//third-party/java/guava:guava",
        "//third-party/java/hamcrest:java-hamcrest",
        "//third-party/java/junit:junit",
    ],
)
