java_binary(
  name = 'bootstrapper',
  deps = [
    ':bootstrapper_lib',

    # Be very careful what is added here, and leave comments justifying
    # each addition. See the comment below for more details on why.

    # The Tracing API jar must be accessible to both Buck and compiler plugins, so we put it
    # in the bootstrapper. Compiler plugins will have their own copy linked in, but the ClassLoaders
    # will end up loading this one instead when they are run inside Buck.
    '//src/com/facebook/buck/event/api:api',
  ],
  visibility = [
    '//programs:bucklib',
    '//programs:bucklib-no-nailgun',
    '//test/com/facebook/buck/cli/bootstrapper:bootstrapper',
  ],
)

java_library(
  name = 'bootstrapper_lib',
  srcs = glob(['*.java']),
  deps = [
    # Do not add dependencies. The bootstrapper is intended to keep the
    # system ClassLoader free of classes that might conflict with
    # those used by compiler plugins and annotation processors. As such,
    # it cannot depend on third-party libraries, directly or indirectly.
  ],
  visibility = [
  ],
)
