load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "toolchain",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/core/rules/analysis/context:context",
        "//src/com/facebook/buck/core/rules/providers/collect:collect",
    ],
    exported_deps = [
        "//src/com/facebook/buck/core/config:config",
        "//src/com/facebook/buck/core/exceptions:exceptions",
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/io:executable-finder",
        "//src/com/facebook/buck/io/filesystem:filesystem",
        "//src/com/facebook/buck/rules/keys/config:config",
        "//third-party/java/guava:guava",
        "//third-party/java/pf4j:pf4j",
    ],
)
