java_library(
  name = 'rules',
  srcs = glob(['*.java']),
  tests = [
    '//test/com/facebook/buck/thrift:thrift',
  ],
  autodeps = True,
  visibility = [
    '//src/com/facebook/buck/rules:types',
    '//test/com/facebook/buck/thrift:',
  ],
)
