java_library(
    name = "bser",
    srcs = glob(["*.java"]),
    tests = [
        "//test/com/facebook/buck/util/bser:bser",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/util:util",
        "//third-party/java/guava:guava",
        "//third-party/java/jsr:jsr305",
    ],
)
