PLATFORM_IMMUTABLES = [
  'AbstractAppleCxxPlatform.java',
  'AbstractApplePlatform.java',
  'AbstractAppleSdk.java',
  'AbstractAppleSdkPaths.java',
  'AbstractAppleToolchain.java',
  'AbstractFatBinaryInfo.java',
]
PLATFORM_SRCS = [
  'ApplePlatforms.java',
  'FatBinaryInfos.java',
]
GENERATOR_SRCS = [
  'CxxPlatformXcodeConfigGenerator.java',
  'ProjectGenerator.java',
  'SchemeGenerator.java',
  'WorkspaceAndProjectGenerator.java',
  'WorkspaceGenerator.java',
]
java_immutables_library(
  name = 'platform',
  srcs = PLATFORM_SRCS,
  immutable_srcs = PLATFORM_IMMUTABLES,
  autodeps = True,
  visibility = ['PUBLIC'],
)

java_immutables_library(
  name = 'generators',
  srcs = GENERATOR_SRCS,
  tests = [
    '//test/com/facebook/buck/apple:apple',
    '//test/com/facebook/buck/apple:apple_test_integration',
  ],
  autodeps = True,
  visibility = [
    'PUBLIC'
  ],
)

java_immutables_library(
  name = 'rules',
  srcs = glob(['*.java',], excludes=PLATFORM_SRCS+GENERATOR_SRCS),
  tests = [
    '//test/com/facebook/buck/apple:apple',
    '//test/com/facebook/buck/apple:apple_test_integration',
  ],
  resources = [
    'build-with-buck.st',
    'codesign.st',
    'codesign.py',
    'fix-uuid.st',
    'rn-package.st',
    'fix_uuid.py',
  ],
  autodeps = True,
  visibility = [
    'PUBLIC'
  ],
)

python_library(
  name = 'fixuuid',
  srcs = [
    'fix_uuid.py',
  ],
  deps = [],
)

python_test(
  name = 'fixuuid_test',
  srcs = ['fix_uuid_test.py'],
  resources = glob(['uuid_test_app/**/*']),
  deps = [':fixuuid'],
)
