java_library(
    name = "unixsocket",
    srcs = ["UnixDomainSocket.java"],
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/io/watchman:transport",
        "//third-party/java/junixsocket:junixsocket",
    ],
)
