load(
    "//tools/build_rules:java_rules.bzl",
    "java_test",
)

java_test(
    name = "util",
    srcs = glob([
        "*.java",
    ]),
    has_immutable_types = True,
    deps = [
        "//src/com/facebook/buck/core/exceptions:exceptions",
        "//src/com/facebook/buck/event:interfaces",
        "//src/com/facebook/buck/remoteexecution:remoteexecution",
        "//src/com/facebook/buck/remoteexecution/grpc:grpc",
        "//src/com/facebook/buck/remoteexecution/util:util",
        "//src/com/facebook/buck/util/types:types",
        "//test/com/facebook/buck/event:testutil",
        "//test/com/facebook/buck/testutil:testutil",
        "//third-party/java/easymock:easymock",
        "//third-party/java/grpc:grpc-core",
        "//third-party/java/guava:guava",
        "//third-party/java/junit:junit",
    ],
)
