// @generated
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cd/resources/proto/javacd.proto

package com.facebook.buck.cd.model.java;

@javax.annotation.Generated(value="protoc", comments="annotations:PipeliningCommandOrBuilder.java.pb.meta")
public interface PipeliningCommandOrBuilder extends
    // @@protoc_insertion_point(interface_extends:javacd.api.v1.PipeliningCommand)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.javacd.api.v1.BaseCommandParams baseCommandParams = 1;</code>
   */
  boolean hasBaseCommandParams();
  /**
   * <code>.javacd.api.v1.BaseCommandParams baseCommandParams = 1;</code>
   */
  com.facebook.buck.cd.model.java.BaseCommandParams getBaseCommandParams();
  /**
   * <code>.javacd.api.v1.BaseCommandParams baseCommandParams = 1;</code>
   */
  com.facebook.buck.cd.model.java.BaseCommandParamsOrBuilder getBaseCommandParamsOrBuilder();

  /**
   * <code>.javacd.api.v1.PipelineState pipeliningState = 2;</code>
   */
  boolean hasPipeliningState();
  /**
   * <code>.javacd.api.v1.PipelineState pipeliningState = 2;</code>
   */
  com.facebook.buck.cd.model.java.PipelineState getPipeliningState();
  /**
   * <code>.javacd.api.v1.PipelineState pipeliningState = 2;</code>
   */
  com.facebook.buck.cd.model.java.PipelineStateOrBuilder getPipeliningStateOrBuilder();

  /**
   * <code>.javacd.api.v1.BasePipeliningCommand abiCommand = 3;</code>
   */
  boolean hasAbiCommand();
  /**
   * <code>.javacd.api.v1.BasePipeliningCommand abiCommand = 3;</code>
   */
  com.facebook.buck.cd.model.java.BasePipeliningCommand getAbiCommand();
  /**
   * <code>.javacd.api.v1.BasePipeliningCommand abiCommand = 3;</code>
   */
  com.facebook.buck.cd.model.java.BasePipeliningCommandOrBuilder getAbiCommandOrBuilder();

  /**
   * <code>.javacd.api.v1.LibraryPipeliningCommand libraryCommand = 4;</code>
   */
  boolean hasLibraryCommand();
  /**
   * <code>.javacd.api.v1.LibraryPipeliningCommand libraryCommand = 4;</code>
   */
  com.facebook.buck.cd.model.java.LibraryPipeliningCommand getLibraryCommand();
  /**
   * <code>.javacd.api.v1.LibraryPipeliningCommand libraryCommand = 4;</code>
   */
  com.facebook.buck.cd.model.java.LibraryPipeliningCommandOrBuilder getLibraryCommandOrBuilder();
}
