load("//tools/build_rules:java_rules.bzl", "standard_java_test")

standard_java_test(
    name = "dotnet",
    with_test_data = True,
    deps = [
        "//src/com/facebook/buck/features/dotnet:dotnet",
        "//src/com/facebook/buck/util/environment:environment",
        "//src/com/facebook/buck/util/environment:platform",
        "//test/com/facebook/buck/testutil:testutil",
        "//test/com/facebook/buck/testutil/integration:util",
        "//third-party/java/jimfs:jimfs",
        "//third-party/java/junit:junit",
    ],
)
