java_library(
    name = "impl",
    srcs = glob(["*.java"]),
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/apple/platform_type:type",
        "//src/com/facebook/buck/apple/toolchain:toolchain",
        "//src/com/facebook/buck/model:model",
        "//src/com/facebook/buck/rules:build_rule",
        "//src/com/facebook/buck/swift/toolchain:toolchain",
        "//third-party/java/guava:guava",
    ],
)
