load("//tools/build_rules:java_rules.bzl", "buck_java_library")

buck_java_library(
    name = "testutil",
    srcs = glob(
        ["*.java"],
    ),
    visibility = [
        "//test/...",
    ],
    deps = [
        # TODO: merge these two packages
        "//test/com/facebook/buck/core/starlark/compatible:testutil",
    ],
    exported_deps = [
        "//starlark:bazel",
    ],
)
