java_library(
    name = "testutil",
    srcs = glob(
        ["*.java"],
    ),
    visibility = [
        "//test/...",
    ],
    deps = [
        "//third-party/java/bazel:bazel",
        # TODO: merge these two packages
        "//test/com/facebook/buck/core/starlark/compatible:testutil",
    ],
)
