load("//tools/build_rules:java_rules.bzl", "java_library_with_plugins")

java_library_with_plugins(
    name = "cd",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    deps = [
        "//src-gen:javacd-model",
        "//src-gen:kotlincd-model",
        "//src/com/facebook/buck/core/build/buildable/context:context",
        "//src/com/facebook/buck/core/cell/name:name",
        "//src/com/facebook/buck/core/filesystems:filesystems",
        "//src/com/facebook/buck/jvm/cd:cd",
        "//src/com/facebook/buck/jvm/core:core",
        "//src/com/facebook/buck/jvm/java:steps",
        "//src/com/facebook/buck/jvm/java:support",
        "//src/com/facebook/buck/jvm/kotlin:kotlin",
        "//src/com/facebook/buck/jvm/cd/serialization:serialization",
        "//src/com/facebook/buck/jvm/cd/serialization/java:java",
        "//src/com/facebook/buck/jvm/cd/serialization/kotlin:kotlin",
        "//src/com/facebook/buck/step/isolatedsteps:isolatedsteps",
    ],
)
