java_library(
    name = "devspeed",
    srcs = glob(["*.java"]),
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/event:event",
        "//src/com/facebook/buck/io/filesystem:filesystem",
        "//third-party/java/pf4j:pf4j",
    ],
)
