java_test(
  name = 'graph',
  srcs = glob(['*.java']),
  source_under_test = [
    '//src/com/facebook/buck/graph:graph',
  ],
  deps = [
    '//third-party/java/guava:guava',
    '//third-party/java/junit:junit',
    '//src/com/facebook/buck/graph:graph',
  ],
)
