java_test(
  name = 'graph',
  srcs = glob(['*.java']),
  source_under_test = [
    '//src/com/facebook/buck/graph:graph',
  ],
  deps = [
    '//lib:junit',
    '//src/com/facebook/buck/graph:graph',
  ],
)
