java_test(
    name = "tracing",
    srcs = glob(["*.java"]),
    autodeps = True,
    provided_deps = [
        # Tools.jar is the compiler itself, and will already be present at runtime;
        # we compile against a stub.
        "//third-party/java/jdk:compiler-tree-api",
    ],
    deps = [
        # Autodeps can't figure this out for some reason
        "//src/com/facebook/buck/jvm/java/plugin/adapter:adapter",
        "//src/com/facebook/buck/jvm/java/tracing:api",
        "//src/com/facebook/buck/jvm/java/tracing:compiler-plugin",
        "//src/com/facebook/buck/jvm/java/tracing:tracing",
        "//src/com/facebook/buck/model:model",
        "//test/com/facebook/buck/event:testutil",
        "//test/com/facebook/buck/jvm/java/testutil:testutil",
        "//test/com/facebook/buck/model:testutil",
        "//third-party/java/easymock:easymock",
        "//third-party/java/guava:guava",
        "//third-party/java/junit:junit",
    ],
)
