java_library(
  name = 'types',
  srcs = [
    'Cell.java',
    'KnownBuildRuleTypes.java',
    'KnownBuildRuleTypesFactory.java',
  ],
  tests = [
    '//test/com/facebook/buck/rules:rules',
  ],
  autodeps = True,
  visibility = [
    '//src/com/facebook/buck/cli:cli',
    '//src/com/facebook/buck/parser:parser',
    '//test/...',
  ],
)

java_library(
  name = 'rule_key',
  srcs = [
    'RuleKey.java',
  ],
  autodeps = True,
  visibility = [
    'PUBLIC',
  ],
)

BUILD_RULE_IMMUTABLES = [
  'AbstractBuildRuleType.java',
  'AbstractExopackageInfo.java',
  'AbstractExternalTestRunnerTestSpec.java',
  'AbstractLabel.java',
  'AbstractSha1HashCode.java',
  'AbstractSourceWithFlags.java',
]

# Ideally, BuildRule.java would require only a handful of other source files
# in order to compile it. Because BuildContext is referenced in the BuildRule
# interface, its dependencies are much broader than desired.
java_immutables_library(
  name = 'build_rule',
  srcs = [
    'AbstractBuildRule.java',
    'AbstractDescriptionArg.java',
    'AbstractSourcePath.java',
    'ActionGraph.java',
    'ActionGraphEvent.java',
    'AddToRuleKey.java',
    'BinaryBuildRule.java',
    'BuckPyFunction.java',
    'BuildableContext.java',
    'BuildableProperties.java',
    'BuildContext.java',
    'BuildEngine.java',
    'BuildInfo.java',
    'BuildInfoRecorder.java',
    'BuildResult.java',
    'BuildRule.java',
    'BuildRuleDependencyVisitors.java',
    'BuildRuleFactoryParams.java',
    'BuildRuleResolver.java',
    'BuildRuleParams.java',
    'BuildRules.java',
    'BuildRuleStatus.java',
    'BuildRuleSuccessType.java',
    'BuildTargetSourcePath.java',
    'CommandTool.java',
    'ConstructorArgMarshaller.java',
    'ConstructorArgMarshalException.java',
    'DefaultOnDiskBuildInfo.java',
    'Description.java',
    'ExportDependencies.java',
    'HashedFileTool.java',
    'HasPostBuildSteps.java',
    'HasRuntimeDeps.java',
    'Hint.java',
    'ImplicitDepsInferringDescription.java',
    'ImplicitInputsInferringDescription.java',
    'MetadataProvidingDescription.java',
    'NonHashableSourcePathContainer.java',
    'OnDiskBuildInfo.java',
    'ParamInfo.java',
    'ParamInfoException.java',
    'PathSourcePath.java',
    'RecordFileSha1Step.java',
    'ResourceSourcePath.java',
    'RuleKeyAppendable.java',
    'RuleKeyBuilder.java',
    'RuleKeyBuilderFactory.java',
    'SourcePath.java',
    'SourcePathResolver.java',
    'SourcePaths.java',
    'SourceRoot.java',
    'TargetGraph.java',
    'TargetGraphToActionGraph.java',
    'TargetGraphTransformer.java',
    'TargetName.java',
    'TargetNode.java',
    'TargetNodeToBuildRuleTransformer.java',
    'TargetNodes.java',
    'Tool.java',
  ],
  immutable_srcs = BUILD_RULE_IMMUTABLES,
  tests = [
    '//test/com/facebook/buck/rules/coercer:coercer',
    '//test/com/facebook/buck/rules:rules',
  ],
  autodeps = True,
  exported_deps = [
    ':rule_key',

    # Need this because TargetGraph subclasses
    # com.facebook.buck.graph.DefaultDirectedAcyclicGraph.
    '//src/com/facebook/buck/graph:graph',

    # AbstractBuildRule requires that BuildTarget be visible to subclasses.
    '//src/com/facebook/buck/model:model',

    # `Description` is a commonly implemented interface that includes a method
    # with a `throws NoSuchBuildTargetException` clause, so we export this
    # rule so that `NoSuchBuildTargetException` will be on the classpath.
    #
    # It needs to be available because a class that implements `Description` can
    # implement the method without declaring `throws NoSuchBuildTargetException`
    # which creates the implicit dependency on `NoSuchBuildTargetException` that
    # is repaired by exporting this rule.
    '//src/com/facebook/buck/parser:rule_pattern',

    # AbstractDescriptionArg uses the @SuppressFieldNotInitialized annotation,
    # it is required by all subclasses to make them build with Infer.
    '//third-party/java/infer-annotations:infer-annotations',

    # ExternalTestRunnerTestSpec implements
    # com.fasterxml.jackson.databind.JsonSerializable.
    '//third-party/java/jackson:jackson-databind',
  ],
  visibility = [
    'PUBLIC',
  ],
)

java_immutables_library(
  name = 'target_graph_hashing',
  srcs = [
    'TargetGraphHashing.java',
  ],
  autodeps = True,
  visibility = [
    'PUBLIC',
  ],
)

java_library(
  name = 'build_event',
  srcs = [
    'BuildEvent.java',
  ],
  autodeps = True,
)

java_immutables_library(
  name = 'rules',
  srcs = [
    'AbstractBuildRuleKeys.java',
    'AssociatedTargetNodePredicate.java',
    'BuildOutputInitializer.java',
    'BuildRuleEvent.java',
    'CachingBuildEngine.java',
    'DefaultBuildableContext.java',
    'ExternalTestRunnerRule.java',
    'IndividualTestEvent.java',
    'InitializableFromDisk.java',
    'InstallableApk.java',
    'Manifest.java',
    'NoopBuildRule.java',
    'NoopBuildRuleWithTests.java',
    'ProjectConfig.java',
    'ProjectConfigDescription.java',
    'RuleDepsCache.java',
    'SymlinkTree.java',
    'TargetGraphAndTargets.java',
    'TestRule.java',
    'TestRunEvent.java',
    'TestStatusMessageEvent.java',
    'TestSummaryEvent.java',
    'WriteStringTemplateRule.java',
  ],
  tests = [
    '//test/com/facebook/buck/rules:rules',
  ],
  autodeps = True,
  exported_deps = [
    ':build_event',

    # SymlinkTree implements com.facebook.buck.rules.keys.SupportsInputBasedRuleKey.
    '//src/com/facebook/buck/rules/keys:keys',
  ],
  visibility = ['PUBLIC'],
)
