java_library(
    name = "actions",
    srcs = glob(["*.java"]),
    exported_deps = [
        "//src/com/facebook/buck/core/model:model",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//third-party/java/guava:guava",
    ],
)
