java_library(
    name = "filesystem",
    srcs = glob(["*.java"]),
    tests = [
        "//test/com/facebook/buck/util/filesystem:filesystem",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/core/model/label:label",
        "//src/com/facebook/buck/core/util/log:log",
        "//third-party/java/guava:guava",
        "//third-party/java/jsr:jsr305",
    ],
    exported_deps = [
        "//src/com/facebook/buck/io/filesystem:filesystem",
        "//src/com/facebook/buck/util/function:function",
        "//src/com/facebook/buck/util/types:types",
        "//starlark:bazel",
        "//third-party/java/guava:guava",
        "//third-party/java/jackson:jackson-databind",
    ],
)
