java_library(
    name = "select",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/core/config:config",
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/core/model/platform:platform",
        "//third-party/java/bazel:bazel",
        "//third-party/java/jsr:jsr305",
    ],
    exported_deps = [
        "//src/com/facebook/buck/rules/coercer/concat:concat",
        "//src/com/facebook/buck/util/function:function",
    ],
)
