load(
    "//tools/build_rules:java_rules.bzl",
    "java_immutables_library",
)

java_immutables_library(
    name = "ndk",
    srcs = glob(["*.java"]),
    tests = [
        "//test/com/facebook/buck/android/toolchain/ndk/impl:impl",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/core/toolchain/toolprovider:toolprovider",
        "//src/com/facebook/buck/rules/args:args",
    ],
    exported_deps = [
        "//src/com/facebook/buck/core/toolchain:toolchain",
        "//src/com/facebook/buck/cxx/toolchain:toolchain",
    ],
)
