load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "ndk",
    srcs = glob(["*.java"]),
    exported_deps = [
        "//src/com/facebook/buck/core/toolchain:toolchain",
        "//src/com/facebook/buck/cxx/toolchain:toolchain",
    ],
    tests = [
        "//test/com/facebook/buck/android/toolchain/ndk/impl:impl",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/util:exceptions",
    ],
)
