load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "ndk",
    srcs = glob(["*.java"]),
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/toolchain:toolchain",
    ],
)
