load("//tools/build_rules:java_rules.bzl", "buck_java_library")

buck_java_library(
    name = "pathformat",
    srcs = glob(["*.java"]),
    visibility = [
        "PUBLIC",
    ],
    exported_deps = [
        "//src/com/facebook/buck/core/filesystems:filesystems",
    ],
)
