java_library(
    name = "pathformat",
    srcs = glob(["*.java"]),
    visibility = [
        "PUBLIC",
    ],
    exported_deps = [
        "//src/com/facebook/buck/core/filesystems:filesystems",
    ],
)
