os_constraint_detector(
    name = "os-detector",
    visibility = [
        "PUBLIC",
    ],
)

constraint_setting(
    name = "os",
    host_constraint_detector = ":os-detector",
    visibility = [
        "PUBLIC",
    ],
)

constraint_value(
    name = "linux",
    constraint_setting = ":os",
    visibility = [
        "PUBLIC",
    ],
)

constraint_value(
    name = "osx",
    constraint_setting = ":os",
    visibility = [
        "PUBLIC",
    ],
)

cpu_constraint_detector(
    name = "cpu-detector",
    visibility = [
        "PUBLIC",
    ],
)

constraint_setting(
    name = "cpu",
    host_constraint_detector = ":cpu-detector",
    visibility = [
        "PUBLIC",
    ],
)

constraint_value(
    name = "x86_64",
    constraint_setting = ":cpu",
    visibility = [
        "PUBLIC",
    ],
)

constraint_value(
    name = "aarch64",
    constraint_setting = ":cpu",
    visibility = [
        "PUBLIC",
    ],
)

constraint_value(
    name = "arm",
    constraint_setting = ":cpu",
    visibility = [
        "PUBLIC",
    ],
)
