java_test(
  name = 'javacc',
  srcs = glob(['*.java']),
  source_under_test = [
    '//third-party/java/javacc:javacc',
  ],
  deps = [
    '//third-party/java/junit:junit',
    ':simple1',
  ],
)

include_defs('//third-party/java/javacc/DEFS')

javacc_parser_library(
  name = 'simple1',
  srcs = glob(['*.jj']),
)

