load("//tools/build_rules:java_rules.bzl", "buck_java_binary")
buck_java_binary(
    name = "buck-android-support",
    deps = [
        "//android/com/facebook/buck/android/support/exopackage:exopackage",
    ],
)
