standard_java_test(
    name = "aggregation",
    deps = [
        "//src/com/facebook/buck/graph:graph",
        "//src/com/facebook/buck/ide/intellij:intellij",
        "//src/com/facebook/buck/util:util",
        "//third-party/java/guava:guava",
        "//third-party/java/junit:junit",
    ],
)
