load("//tools/build_rules:java_rules.bzl", "standard_java_test")

standard_java_test(
    name = "aggregation",
    deps = [
        "//src/com/facebook/buck/graph:graph",
        "//src/com/facebook/buck/ide/intellij:intellij",
        "//src/com/facebook/buck/util:util",
        "//test/com/facebook/buck/ide/intellij:testutil",
        "//third-party/java/guava:guava",
        "//third-party/java/junit:junit",
    ],
)
