load("//tools/build_rules:java_rules.bzl", "standard_java_test")

standard_java_test(
    name = "module",
    deps = [
        "//src/com/facebook/buck/parser/api:api",
        "//src/com/facebook/buck/parser/cache/json:json",
        "//src/com/facebook/buck/skylark/io:io",
        "//src/com/facebook/buck/util/environment:platform",
        "//third-party/java/guava:guava",
        "//third-party/java/jackson:jackson-databind",
        "//third-party/java/junit:junit",
    ],
)
