load("//tools/build_rules:java_rules.bzl", "java_library_with_plugins")

java_library_with_plugins(
    name = "impl",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/android/toolchain:toolchain",
        "//src/com/facebook/buck/core/util/log:log",
    ],
    exported_deps = [
        "//src/com/facebook/buck/core/toolchain:toolchain",
        "//src/com/facebook/buck/file/downloader:downloader",
    ],
)
