load("//tools/build_rules:java_rules.bzl", "buck_java_library")
buck_java_library(
    name = "hostname",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    deps = ["//third-party/java/jna:jna"],
)
