load(
    "//tools/build_rules:java_rules.bzl",
    "java_immutables_library",
)

java_immutables_library(
    name = "impl",
    srcs = glob(["*.java"]),
    exported_deps = [
        "//src/com/facebook/buck/core/rules/modern:modern",
        "//src/com/facebook/buck/core/toolchain/tool:tool",
    ],
    tests = [
        "//test/com/facebook/buck/core/toolchain/tool/impl:impl",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/core/rulekey:rulekey",
        "//src/com/facebook/buck/core/rules:rules",
        "//src/com/facebook/buck/core/rules/modern/annotations:annotations",
        "//src/com/facebook/buck/core/rules/tool:tool",
        "//src/com/facebook/buck/core/sourcepath/resolver:resolver",
        "//src/com/facebook/buck/rules/args:args",
        "//src/com/facebook/buck/util:util",
        "//third-party/java/guava:guava",
    ],
)
