load("//tools/build_rules:java_rules.bzl", "java_test", "standard_java_test")

standard_java_test(
    name = "impl",
    deps = [
        "//src/com/facebook/buck/io:io",
        "//src/com/facebook/buck/io/filesystem:filesystem",
        "//src/com/facebook/buck/io/watchman:watchman",
        "//src/com/facebook/buck/util:util",
        "//src/com/facebook/buck/util/cache:cache",
        "//src/com/facebook/buck/util/cache/impl:impl",
        "//src/com/facebook/buck/util/config:config",
        "//src/com/facebook/buck/util/zip:zip",
        "//test/com/facebook/buck/io/filesystem:testutil",
        "//test/com/facebook/buck/io/filesystem/impl:testutil",
        "//test/com/facebook/buck/testutil:testutil",
        "//test/com/facebook/buck/testutil/integration:util",
        "//test/com/facebook/buck/util/config:testutil",
        "//test/com/facebook/buck/util/timing:testutil",
        "//third-party/java/junit:junit",
    ],
)

java_library(
    name = "cache_benchmark_lib",
    srcs = ["CacheBenchmark.java"],
    exported_deps = [
        "//src/com/facebook/buck/io:io",
        "//src/com/facebook/buck/io/watchman:watchman",
        "//src/com/facebook/buck/util/cache:cache",
        "//src/com/facebook/buck/util/cache/impl:impl",
        "//test/com/facebook/buck/io/filesystem/impl:testutil",
        "//third-party/java/caliper:caliper",
        "//third-party/java/guava:guava",
        "//third-party/java/junit:junit",
    ],
    visibility = [
        "//test/com/facebook/buck/benchmarks/...",
    ],
)

java_test(
    name = "cache_benchmark",
    srcs = ["CacheBenchmark.java"],
    deps = [
        ":cache_benchmark_lib",
    ],
)
