java_test(
  name = 'xcconfig',
  srcs = glob(['*.java']),
  source_under_test = [
    '//src/com/facebook/buck/apple/xcode/xcconfig:xcconfig',
  ],
  deps = [
    '//third-party/java/easymock:easymock',
    '//third-party/java/guava:guava',
    '//third-party/java/junit:junit',
    '//third-party/java/hamcrest:hamcrest-core',
    '//third-party/java/hamcrest:hamcrest-library',
    '//src/com/facebook/buck/util:io',
    '//src/com/facebook/buck/util:exceptions',
    '//test/com/facebook/buck/testutil:testutil',
    '//src/com/facebook/buck/apple/xcode/xcconfig:xcconfig',
  ]
)
