load("//tools/build_rules:java_rules.bzl", "buck_java_library")
buck_java_library(
    name = "timing",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/log/views:views",
        "//third-party/java/jackson:jackson-annotations",
    ],
)
