java_library(
    name = "parameter_extractors",
    srcs = glob(["*.java"]),
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/config:config",
        "//src/com/facebook/buck/parser:parser",
        "//src/com/facebook/buck/util:process_executor",
        "//src/com/facebook/buck/util/config:config",
        "//third-party/java/guava:guava",
        "//third-party/java/jsr:jsr305",
    ],
)
