java_test(
  name = 'scala',
  srcs = glob(['*Test.java']),
  resources = glob(['testdata/**'], include_dotfiles=True),
  autodeps = True,
  # Unfortunately the scala compiler is _really_ slow.
  run_test_separately = True,
  test_rule_timeout_ms = 180000,
)
