java_test(
  name = 'scala',
  srcs = glob(['*Test.java']),
  autodeps = True,
  labels = ['long_running'],
  resources = glob(
    ['testdata/**'],
    include_dotfiles = True,
  ),
  # Unfortunately the scala compiler is _really_ slow.
  run_test_separately = True,
  test_rule_timeout_ms = 180000,
  vm_args = ['-Xmx512m'],
)
