java_test(
    name='scala',
    srcs=glob(['*Test.java']),
    resources=glob(['testdata/**'], include_dotfiles=True),
    deps=[
        '//src/com/facebook/buck/cli:cli',
        '//src/com/facebook/buck/jvm/scala:rules',
        '//src/com/facebook/buck/rules:build_rule',
        '//src/com/facebook/buck/util/environment:platform',
        '//src/com/facebook/buck/cli:config',
        '//src/com/facebook/buck/io:io',
        '//src/com/facebook/buck/util:exceptions',
        '//test/com/facebook/buck/cli:FakeBuckConfig',
        '//test/com/facebook/buck/testutil/integration:integration',
        '//third-party/java/hamcrest:hamcrest',
        '//third-party/java/guava:guava',
        '//third-party/java/junit:junit',
    ],
    # Unfortunately the scala compiler is _really_ slow.
    run_test_separately=True,
    test_rule_timeout_ms=180000,
)
