load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_library(
    name = "event",
    srcs = glob(
        ["*.java"],
    ),
    exported_deps = [
        "//src/com/facebook/buck/event:interfaces",
        "//src/com/facebook/buck/test:test",
        "//src/com/facebook/buck/test/selectors:selectors",
    ],
    tests = [
        "//test/com/facebook/buck/core/test/event:event",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//third-party/java/guava:guava",
        "//third-party/java/jackson:jackson-annotations",
    ],
)
