java_library(
    name = "impl",
    srcs = glob(["*.java"]),
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/core/model/platform/impl:impl",
        "//src/com/facebook/buck/core/rules/config:config",
        "//src/com/facebook/buck/core/rules/config/impl:impl",
        "//src/com/facebook/buck/core/rules/platform:platform",
    ],
    exported_deps = [
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/core/model/platform:platform",
        "//src/com/facebook/buck/core/model/targetgraph:targetgraph",
        "//src/com/facebook/buck/core/rules/config/registry:registry",
    ],
)
