java_library(
  name = 'adapter',
  srcs = glob(['*.java']),
  autodeps = False,  # see below
  deps = [
    # This module is loaded as a plugin into the compiler itself; don't take dependencies on Buck
    # internals or large libraries like Guava
  ],
  provided_deps = [
    # Tools.jar is the compiler itself, and will already be present at runtime;
    # we compile against a stub.
    '//third-party/java/jdk:compiler-tree-api',
  ],
  visibility = [
    '//src/com/facebook/buck/jvm/java/plugin:javac-plugin',
    '//src/com/facebook/buck/jvm/java/abi/source:source',
    '//src/com/facebook/buck/jvm/java/tracing:compiler-plugin',
    '//test/com/facebook/buck/jvm/java/plugin/adapter:adapter',
    '//test/com/facebook/buck/jvm/java/tracing:tracing',
  ]
)