java_library(
    name = "adapter",
    # We use conditional compilation to support building against both Java 8 and 10, despite
    # breaking interface changes in the JDK.
    srcs = glob(["*.java"]) + select({
        "//tools/build/config:java_8": glob(["java8/*.java"]),
        "//tools/build/config:java_10": glob(["java10/*.java"]),
    }),
    provided_deps = [
        # Tools.jar is the compiler itself, and will already be present at runtime;
        # we compile against a stub.
        "//third-party/java/jdk:compiler-tree-api",

        # api modules are included in the bootstrapper at runtime, so we don't need direct deps on them
        "//src/com/facebook/buck/jvm/java/plugin/api:api",
    ],
    visibility = [
        "//src/com/facebook/buck/jvm/java/abi/source:source",
        "//src/com/facebook/buck/jvm/java/plugin:javac-plugin",
        "//test/com/facebook/buck/jvm/java/abi/source:",
        "//test/com/facebook/buck/jvm/java/plugin/adapter:",
        "//test/com/facebook/buck/jvm/java/testutil/compiler:compiler",
        "//test/com/facebook/buck/jvm/java/tracing:tracing",
    ],
    deps = [
        # This module is loaded as a plugin into the compiler itself; don't take dependencies on Buck
        # internals or large libraries like Guava
        "//src/com/facebook/buck/jvm/java/lang/model:model",
        "//src/com/facebook/buck/util:isolated",
        "//src/com/facebook/buck/util/liteinfersupport:liteinfersupport",
    ],
)
