java_library(
  name = 'main',
  srcs = ['Main.java'],
  deps = [
    '@external//:external',
  ],
  visibility = ['PUBLIC'],
)

java_binary(
  name = 'bin',
  deps = [
    ':main',
  ],
  main_class = 'Main',
)
