python_library(
    name = "buck_result_lib",
    srcs = [
        "buck_result.py",
    ],
    base_module = "",
    visibility = [
        "PUBLIC",
    ],
)

python_library(
    name = "buck_process_lib",
    srcs = [
        "buck_process.py",
    ],
    base_module = "",
    visibility = [
        "PUBLIC",
    ],
    deps = [
        ":buck_result_lib",
    ],
)
