load("//tools/build_rules:java_rules.bzl", "buck_java_binary", "buck_java_library")
buck_java_library(
    name = "abi",
    srcs = glob(
        ["*.java"],
        exclude = [
            "ApiStubber.java",
        ],
    ) +  glob(["java11/*.java"]),
    tests = [
        "//test/com/facebook/buck/jvm/java/abi:abi",
    ],
    visibility = [
        "//src/com/facebook/buck/jvm/java:rules",
        "//src/com/facebook/buck/jvm/java:steps",
        "//src/com/facebook/buck/jvm/java:support",
        "//test/com/facebook/buck/jvm/java/abi/...",
    ],
    deps = [
        "//src-gen:javacd-model",
        "//src/com/facebook/buck/core/exceptions:exceptions",
        "//src/com/facebook/buck/event/api:api",
        "//src/com/facebook/buck/io/pathformat:pathformat",
        "//src/com/facebook/buck/jvm/java:javac-sink",
        "//src/com/facebook/buck/jvm/java/abi/kotlin:kotlin",
        "//src/com/facebook/buck/jvm/java/abi/source/api:api",
        "//src/com/facebook/buck/jvm/java/lang/model:model",
        "//src/com/facebook/buck/jvm/java/plugin/api:api",
        "//src/com/facebook/buck/util:util",
        "//src/com/facebook/buck/util/function:function",
        "//third-party/java/asm:asm",
        "//third-party/java/guava:guava",
        "//third-party/java/infer-annotations:infer-annotations",
        "//third-party/java/jsr:jsr305",
    ],
    exported_deps = [
        "//src/com/facebook/buck/util/zip:zip",
    ],
)

buck_java_binary(
    name = "api-stubber",
    main_class = "com.facebook.buck.jvm.java.abi.ApiStubber",
    deps = [
        ":lib-api-stubber",
    ],
    visibility = ["PUBLIC"],
)

buck_java_library(
    name = "lib-api-stubber",
    srcs = ["ApiStubber.java"],
    deps = [
        "//src/com/facebook/buck/core/filesystems:filesystems",
        ":abi",
    ],
)
