java_test(
    name = "headermap",
    srcs = glob(["*.java"]),
    autodeps = True,
    deps = [
        "//src/com/facebook/buck/apple/clang:headermap",
        "//src/com/facebook/buck/util/environment:platform",
        "//third-party/java/junit:junit",
    ],
)
