java_test(
  name = 'crosscell',
  srcs = glob(['*.java']),
  deps = [
    '//src/com/facebook/buck/model:model',
    '//src/com/facebook/buck/util/environment:platform',
    '//test/com/facebook/buck/testutil/integration:integration',
    '//third-party/java/hamcrest:hamcrest',
    '//third-party/java/ini4j:ini4j',
    '//third-party/java/junit:junit',
  ],
)
