load("//tools/build_rules:java_rules.bzl", "buck_java_library")

buck_java_library(
    name = "toolprovider",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/core/rules:rules",
        "//third-party/java/guava:guava",
    ],
    exported_deps = [
        "//src/com/facebook/buck/core/toolchain/tool:tool",
    ],
)
