java_test(
  name = 'plist',
  srcs = glob(['*.java']),
  source_under_test = [
    '//src/com/facebook/buck/apple/xcode/plist:plist',
  ],
  deps = [
    '//third-party/java/easymock:easymock',
    '//third-party/java/guava:guava',
    '//third-party/java/junit:junit',
    '//third-party/java/hamcrest:hamcrest-core',
    '//third-party/java/hamcrest:hamcrest-library',
    '//src/com/facebook/buck/apple/xcode/plist:plist',
  ],
)
