load("//tools/build_rules:java_rules.bzl", "java_immutables_library", "standard_java_test")

java_immutables_library(
    name = "testutil",
    srcs = glob(
        ["*.java"],
        exclude = [
            "*Test.java",
        ],
    ),
    visibility = ["//test/..."],
    deps = [
        "//src/com/facebook/buck/step/impl:impl",
        "//test/com/facebook/buck/core/cell:testutil",
        "//test/com/facebook/buck/core/rules/actions:testutil",
        "//test/com/facebook/buck/event:testutil",
        "//test/com/facebook/buck/jvm/java:fakepackagefinder",
        "//test/com/facebook/buck/util:testutil",
        "//third-party/java/guava:guava",
    ],
    exported_deps = [
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/core/rules/actions:actions",
        "//src/com/facebook/buck/step:step",
    ],
)

standard_java_test(
    name = "impl",
    deps = [
        "//src/com/facebook/buck/step/impl:impl",
        "//test/com/facebook/buck/core/cell:testutil",
        "//test/com/facebook/buck/core/model:testutil",
        "//test/com/facebook/buck/core/rules/actions:testutil",
        "//test/com/facebook/buck/event:testutil",
        "//test/com/facebook/buck/io/filesystem:testutil",
        "//test/com/facebook/buck/jvm/java:fakepackagefinder",
        "//test/com/facebook/buck/util:testutil",
        "//third-party/java/guava:guava",
        "//third-party/java/junit:junit",
    ],
)
