standard_java_test(
    name = "unit",
    deps = [
        "//src/com/facebook/buck/model:simple_types",
        "//src/com/facebook/buck/util/immutables:immutables",
        "//src/com/facebook/buck/util/unit:unit",
        "//third-party/java/guava:guava",
        "//third-party/java/immutables:immutables",
        "//third-party/java/jackson:jackson-databind",
        "//third-party/java/jsr:jsr305",
        "//third-party/java/junit:junit",
    ],
)
