java_library(
    name = "rulekey",
    srcs = [
        "AddToRuleKey.java",
        "AddsToRuleKey.java",
        "RuleKey.java",
        "RuleKeyAppendable.java",
        "RuleKeyDiagnosticsMode.java",
        "RuleKeyObjectSink.java",
    ],
    required_for_source_only_abi = True,  # TODO(jkeljo): Break out the annotations
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/log/views:views",
        "//third-party/java/guava:guava",
        "//third-party/java/jackson:jackson-annotations",
        "//third-party/java/jsr:jsr305",
    ],
)
