java_library(
  name = 'rules',
  srcs = [
    'ScalaBuckConfig.java',
    'ScalaLibraryDescription.java',
    'ScalaTestDescription.java',
    'ScalacToJarStepFactory.java',
    'ScalacStep.java',
  ],
  tests = [
    '//test/com/facebook/buck/jvm/scala:scala',
  ],
  autodeps = True,
  visibility = ['PUBLIC'],
)
