load("//tools/build_rules:java_rules.bzl", "standard_java_test")

standard_java_test(
    name = "buildtargetparser",
    deps = [
        "//src/com/facebook/buck/core/parser/buildtargetparser:buildtargetparser",
        "//test/com/facebook/buck/core/cell:testutil",
        "//test/com/facebook/buck/core/model:testutil",
        "//third-party/java/junit:junit",
        "//third-party/java/junitparams:junitparams",
    ],
)
