java_library(
    name = "testutil",
    srcs = [
        "PackagedResourceTestUtil.java",
    ],
    autodeps = True,
    resources = [
        "testdata/packaged_resource_one",
        "testdata/packaged_resource_two",
    ],
    visibility = [
        "//test/...",
    ],
)
