# This file does not use standard_java_test() because it defines a library with some nonstandard
# resources.
java_library(
  name = 'testutil',
  srcs = [
    'PackagedResourceTestUtil.java',
  ],
  resources = [
    'testdata/packaged_resource_one',
    'testdata/packaged_resource_two'
  ],
  autodeps = True,
  visibility = [
    '//test/...',
  ],
)
