ios_library(
  name = 'foolib',
  configs = {},
  srcs = [],
  frameworks = [],
  deps = [],
  visibility = ['PUBLIC']
)

xcode_project_config(
  name = 'project',
  project_name = 'fooproject',
  rules = [
    ':foolib',
  ]
)
