java_library(
    name = "impl",
    srcs = glob(
        ["*.java"],
    ),
    exported_deps = [
        "//src/com/facebook/buck/plugin:plugin",
        "//third-party/java/pf4j:pf4j",
    ],
    visibility = [
        "//src/com/facebook/buck/cli:cli",
        "//src/com/facebook/buck/rules/modern/builders/...",
        "//test/...",
    ],
)
