load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "impl",
    srcs = glob(["*.java"]),
    exported_deps = [
        "//src/com/facebook/buck/core/sourcepath/resolver:resolver",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//third-party/java/guava:guava",
    ],
)
