load("//tools/build_rules:java_rules.bzl", "buck_java_library")

buck_java_library(
    name = "strings",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/core/filesystems:filesystems",
        "//src/com/facebook/buck/io/filesystem/impl:utils",
        "//third-party/java/guava:guava",
    ],
)
