load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "packageable",
    srcs = glob(["*.java"]),
    tests = [
        "//test/com/facebook/buck/android/packageable:packageable",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/android/apkmodule:apkmodule",
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/core/rules/impl:impl",
        "//src/com/facebook/buck/core/sourcepath/resolver:resolver",
        "//src/com/facebook/buck/cxx/toolchain:toolchain",
        "//src/com/facebook/buck/cxx/toolchain/nativelink:nativelink",
        "//src/com/facebook/buck/graph:graph",
        "//src/com/facebook/buck/jvm/core:core",
        "//src/com/facebook/buck/rules/coercer:coercer",
        "//src/com/facebook/buck/util:exceptions",
        "//src/com/facebook/buck/util:util",
    ],
)
