load("//tools/build_rules:java_rules.bzl", "java_library_with_plugins")

java_library_with_plugins(
    name = "configsetting",
    srcs = glob(["*.java"]),
    exported_deps = [
        "//src/com/facebook/buck/core/rules/config:config",
        "//src/com/facebook/buck/core/select:select",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
    ],
)
