java_library(
    name = "java10",
    srcs = glob(["*.java"]),
    visibility = [
        "//src/com/facebook/buck/jvm/java/abi:abi",
    ],
    deps = [
        "//third-party/java/asm:asm",
    ],
)
