load("//tools/build_rules:java_rules.bzl", "java_immutables_library", "java_test")

java_test(
    name = "configsetting",
    srcs = glob(["*Test.java"]),
    deps = [
        "//src/com/facebook/buck/core/rules/configsetting:configsetting",
        "//test/com/facebook/buck/testutil:testutil",
        "//test/com/facebook/buck/testutil/integration:util",
        "//third-party/java/junit:junit",
    ],
)
