load("//tools/build_rules:java_rules.bzl", "standard_java_test")

standard_java_test(
    name = "transformation",
    deps = [
        "//src/com/facebook/buck/graph/transformation:transformation",
        "//src/com/facebook/buck/util/types:types",
        "//third-party/java/guava:guava",
        "//third-party/java/junit:junit",
    ],
)
