java_test(
  name = 'simulator',
  srcs = glob(['*Test.java']),
  resources = glob(['testdata/**']),
  deps = [
        '//src/com/facebook/buck/apple/simulator:simulator',
        '//src/com/facebook/buck/util:io',
        '//test/com/facebook/buck/testutil/integration:integration',
        '//test/com/facebook/buck/util:testutil',
        '//third-party/java/dd-plist:dd-plist',
        '//third-party/java/guava:guava',
        '//third-party/java/hamcrest:hamcrest',
        '//third-party/java/junit:junit',
    ],
)
