load("//tools/build_rules:java_rules.bzl", "java_test")

TEST_SRCS = glob(["*Test.java"])

java_library(
    name = "testutil",
    srcs = glob(
        ["*.java"],
        exclude = TEST_SRCS,
    ),
    required_for_source_only_abi = True,
    resources = glob(["testdata/**"]),
    visibility = [
        "//test/...",
    ],
    deps = [
        "//programs:buck",
        "//src/com/facebook/buck/io:executable-finder",
        "//src/com/facebook/buck/model:model",
        "//src/com/facebook/buck/util:constants",
        "//src/com/facebook/buck/util:process_executor",
        "//src/com/facebook/buck/util:util",
        "//src/com/facebook/buck/util/environment:platform",
        "//test/com/facebook/buck/model:testutil",
        "//test/com/facebook/buck/testutil:testutil",
        "//third-party/java/junit:junit",
    ],
)

java_test(
    name = "endtoend",
    srcs = TEST_SRCS,
    visibility = [
        "//test/...",
    ],
    deps = [
        "//src/com/facebook/buck/util:util",
        "//src/com/facebook/buck/util/environment:platform",
        "//test/com/facebook/buck/testutil:testutil",
        "//test/com/facebook/buck/testutil/endtoend:testutil",
        "//third-party/java/junit:junit",
    ],
)
