java_library(
    name = "transformation",
    srcs = glob(["*.java"]),
    tests = [
        "//test/com/facebook/buck/graph/transformation:transformation",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/log:api",
        "//src/com/facebook/buck/util:util",
        "//third-party/java/guava:guava",
    ],
)
