java_library(
    name = "utils",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    deps = ["//src/com/facebook/buck/core/filesystems:filesystems",
    "//third-party/java/guava:guava",
    "//src/com/facebook/buck/io/filesystem/impl:utils",
    "//src/com/facebook/buck/core/exceptions:exceptions",
    ],
)
