apple_bundle(
  name = 'DemoApp',
  binary = ':DemoAppBinary',
  extension = 'app',
  info_plist = 'Info.plist',
  dirs = {
    'Foo.framework': 'Frameworks',
    'Baz.appex': 'PlugIns',
    'Images': 'Resources',
    'Qux.bundle': 'Products',
  },
  files = {
    'Image.png': 'Resources',
  }
)

apple_binary(
  name = 'DemoAppBinary',
  preprocessor_flags = ['-fobjc-arc'],
  headers = glob([
    '*.h',
  ]),
  srcs = glob([
    '*.m',
  ]),
  frameworks = [
    '$SDKROOT/System/Library/Frameworks/UIKit.framework',
    '$SDKROOT/System/Library/Frameworks/Foundation.framework',
    '$SDKROOT/usr/lib/libobjc.dylib',
  ],
)
