java_library(
    name = "buildtargetparser",
    srcs = glob(["*.java"]),
    exported_deps = [
        "//src/com/facebook/buck/core/model:model",
    ],
    visibility = [
        "PUBLIC",
    ],
)
