java_library(
    name = "javacd",
    srcs = glob(["*.java"]),
    visibility = [
        "//src/com/facebook/buck/...",
    ],
    deps = [
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/jvm/java:steps",
        "//src/com/facebook/buck/jvm/java:support",
        "//src/com/facebook/buck/jvm/java/abi/source/api:api",
        "//src/com/facebook/buck/jvm/java/stepsbuilder:stepsbuilder",
        "//src/com/facebook/buck/jvm/java/stepsbuilder/impl:impl",
        "//third-party/java/guava:guava",
    ],
)
