load("//tools/build_rules:java_rules.bzl", "standard_java_test")

standard_java_test(
    name = "coercer",
    has_immutable_types = True,
    deps = [
        "//src/com/facebook/buck/core/description/arg:arg",
        "//src/com/facebook/buck/core/starlark/coercer:coercer",
        "//src/com/facebook/buck/core/starlark/rule:rule",
        "//src/com/facebook/buck/core/starlark/rule/attr:attr",
        "//src/com/facebook/buck/rules/coercer:coercer",
        "//test/com/facebook/buck/core/cell:testutil",
        "//test/com/facebook/buck/core/model:testutil",
        "//test/com/facebook/buck/io/filesystem:testutil",
        "//test/com/facebook/buck/skylark/function:testutil",
        "//test/com/facebook/buck/testutil:testutil",
        "//third-party/java/bazel:bazel",
        "//third-party/java/junit:junit",
    ],
)
