load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

TRANSPORT_SRCS = ["Transport.java"]

CAPABILITY_SRCS = ["Capability.java"]

WATCHMAN_SRCS = glob(
    ["*.java"],
    exclude = TRANSPORT_SRCS + CAPABILITY_SRCS,
)

java_library(
    name = "transport",
    srcs = TRANSPORT_SRCS,
    visibility = [
        "PUBLIC",
    ],
)

java_library(
    name = "capability",
    srcs = CAPABILITY_SRCS,
    visibility = ["PUBLIC"],
)

java_immutables_library(
    name = "watchman",
    srcs = WATCHMAN_SRCS,
    visibility = [
        "PUBLIC",
    ],
    deps = [
        ":capability",
        ":transport",
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/core/util/log:log",
        "//src/com/facebook/buck/event:event",
        "//src/com/facebook/buck/event:interfaces",
        "//src/com/facebook/buck/event/external:external_lib",
        "//src/com/facebook/buck/io:executable-finder",
        "//src/com/facebook/buck/io:io",
        "//src/com/facebook/buck/io/file:file",
        "//src/com/facebook/buck/io/filesystem:filesystem",
        "//src/com/facebook/buck/io/unixsocket:unixsocket",
        "//src/com/facebook/buck/io/windowspipe:windowspipe",
        "//src/com/facebook/buck/util:process_executor",
        "//src/com/facebook/buck/util:util",
        "//src/com/facebook/buck/util/bser:bser",
        "//src/com/facebook/buck/util/concurrent:concurrent",
        "//src/com/facebook/buck/util/environment:platform",
        "//src/com/facebook/buck/util/timing:timing",
    ],
)
