load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

TRANSPORT_SRCS = [
    "Transport.java",
]

java_library(
    name = "transport",
    srcs = TRANSPORT_SRCS,
    visibility = [
        "PUBLIC",
    ],
)

WATCHMAN_SRCS = [
    "AbstractWatchmanDiagnostic.java",
    "AbstractProjectWatch.java",
    "AbstractWatchmanQuery.java",
    "Watchman.java",
    "WatchmanClient.java",
    "WatchmanCursor.java",
    "WatchmanDiagnosticEvent.java",
    "WatchmanDiagnosticEventListener.java",
    "WatchmanEvent.java",
    "WatchmanFactory.java",
    "WatchmanTransportClient.java",
    "WatchmanWatcher.java",
    "WatchmanWatcherException.java",
]

java_immutables_library(
    name = "watchman",
    srcs = WATCHMAN_SRCS,
    visibility = [
        "PUBLIC",
    ],
    deps = [
        ":transport",
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/event:event",
        "//src/com/facebook/buck/event:interfaces",
        "//src/com/facebook/buck/event/external:external_lib",
        "//src/com/facebook/buck/io:executable-finder",
        "//src/com/facebook/buck/io:io",
        "//src/com/facebook/buck/io/file:file",
        "//src/com/facebook/buck/io/filesystem:filesystem",
        "//src/com/facebook/buck/io/unixsocket:unixsocket",
        "//src/com/facebook/buck/io/windowspipe:windowspipe",
        "//src/com/facebook/buck/log:api",
        "//src/com/facebook/buck/util:exceptions",
        "//src/com/facebook/buck/util:process_executor",
        "//src/com/facebook/buck/util:util",
        "//src/com/facebook/buck/util/bser:bser",
        "//src/com/facebook/buck/util/concurrent:concurrent",
        "//src/com/facebook/buck/util/environment:platform",
        "//src/com/facebook/buck/util/timing:timing",
    ],
)
