load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "provider",
    srcs = glob(
        ["*.java"],
    ),
    exported_deps = [
        "//src/com/facebook/buck/core/sourcepath/resolver:resolver",
        "//src/com/facebook/buck/io/filesystem:filesystem",
        "//src/com/facebook/buck/model:model",
    ],
    tests = [
        "//test/com/facebook/buck/core/rules/provider:provider",
    ],
    visibility = [
        "PUBLIC",
    ],
)
