java_library(
    name = "trace",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/io:BuckPaths",
        "//src/com/facebook/buck/io:io",
        "//src/com/facebook/buck/log:api",
        "//src/com/facebook/buck/util:exceptions",
        "//src/com/facebook/buck/util:object_mapper",
        "//third-party/java/guava:guava",
        "//third-party/java/jackson:jackson-core",
        "//third-party/java/jackson:jackson-databind",
    ],
)
