java_library(
    name = "names",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    deps = [
        "//third-party/java/jsr:jsr305",
    ],
    exported_deps = [
        "//src/com/facebook/buck/core/model/label:label",
        "//src/com/facebook/buck/util/types:types",
        "//starlark:bazel",
        "//third-party/java/guava:guava",
    ],
)
