load("//tools/build_rules:java_rules.bzl", "standard_java_test")

standard_java_test(
    name = "config",
    with_test_data = True,
    deps = [
        "//src/com/facebook/buck/parser/exceptions:exceptions",
        "//src/com/facebook/buck/support/cli/config:config",
        "//src/com/facebook/buck/util/json:json",
        "//test/com/facebook/buck/core/config:testutil",
        "//test/com/facebook/buck/testutil:testutil",
        "//test/com/facebook/buck/testutil/integration:util",
        "//third-party/java/junit:junit",
        "//third-party/java/junitparams:junitparams",
    ],
)
