load("//tools/build_rules:java_rules.bzl", "java_test")

java_test(
    name = "config",
    srcs = glob(["*Test.java"]),
    deps = [
        "//src/com/facebook/buck/parser/exceptions:exceptions",
        "//src/com/facebook/buck/support/cli/config:config",
        "//test/com/facebook/buck/core/config:testutil",
        "//test/com/facebook/buck/testutil:testutil",
        "//third-party/java/junit:junit",
    ],
)
