java_library(
    name = "factory",
    srcs = glob(["*.java"]),
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/util/randomizedtrial:randomizedtrial",
    ],
)
