java_library(
    name = "classhash",
    srcs = [
        "HasJavaClassHashes.java",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/rules:build_rule",
        "//third-party/java/guava:guava",
    ],
)

java_library(
    name = "packagefinder",
    srcs = [
        "JavaPackageFinder.java",
    ],
    visibility = ["PUBLIC"],
    deps = ["//src/com/facebook/buck/model:model"],
)
