java_library(
    name = "core",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/core/model/impl:impl",
        "//src/com/facebook/buck/core/rules/impl:impl",
        "//src/com/facebook/buck/core/sourcepath/resolver:resolver",
        "//src/com/facebook/buck/util:util",
        "//src/com/facebook/buck/util/unarchive:unarchive",
        "//third-party/java/guava:guava",
        "//third-party/java/infer-annotations:infer-annotations",
        "//third-party/java/jsr:jsr305",
    ],
    exported_deps = [
        ":packagefinder",
    ],
)

java_library(
    name = "packagefinder",
    srcs = [
        "JavaPackageFinder.java",
    ],
    visibility = [
        "//src/com/facebook/buck/core/build/context:context",
        "//src/com/facebook/buck/core/build/execution/context:context",
        "//src/com/facebook/buck/rules/modern/builders/...",
    ],
    deps = ["//src/com/facebook/buck/core/model:model"],
)
