java_test(
  name = 'cache',
  srcs = glob(['*.java']),
  deps = [
    '//third-party/java/guava:guava',
    '//third-party/java/hamcrest:hamcrest-core',
    '//third-party/java/hamcrest:hamcrest-library',
    '//third-party/java/junit:junit',
    '//test/com/facebook/buck/testutil/integration:integration',
  ],
)
