java_library(
    name = "immutables",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    deps = [
        "//third-party/java/immutables:immutables",
        "//third-party/java/jackson:jackson-databind",
    ],
)
