load("//tools/build_rules:java_rules.bzl", "standard_java_test")

standard_java_test(
    name = "macho",
    with_test_data = True,
    deps = [
        "//src/com/facebook/buck/cxx/toolchain/objectfile:objectfile",
        "//third-party/java/guava:guava",
        "//third-party/java/hamcrest:java-hamcrest",
        "//third-party/java/immutables:immutables",
        "//third-party/java/jsr:jsr305",
        "//third-party/java/junit:junit",
    ],
)
