java_test(
  name = 'geometry',
  srcs = ['EarthIsFlatTest.java'],
  labels = [
    'unscientific',
    'not-herecy',
    'testy',
    'earthy'
  ],
  deps = [ '//lib:junit' ],
)

java_test(
  name = 'orientation',
  srcs = ['PhotonsTest.java'],
  labels = [
    'scientific',
    'testy',
    'lighty'
  ],
  deps = [ '//lib:junit' ],
)
