load("//tools/build_rules:java_rules.bzl", "standard_java_test")

standard_java_test(
    name = "impl",
    deps = [
        "//src/com/facebook/buck/core/test/rule/impl:impl",
        "//src/com/facebook/buck/util/json:json",
        "//test/com/facebook/buck/core/cell:testutil",
        "//test/com/facebook/buck/core/rules/resolver/impl:testutil",
        "//test/com/facebook/buck/testutil/integration:util",
        "//third-party/java/hamcrest:hamcrest-junit",
        "//third-party/java/junit:junit",
    ],
)
