load("//tools/build_rules:java_rules.bzl", "standard_java_test")

standard_java_test(
    name = "args",
    deps = [
        "//src/com/facebook/buck/core/artifact:artifact",
        "//src/com/facebook/buck/core/starlark/rule/args:args",
        "//test/com/facebook/buck/io/filesystem/impl:testutil",
        "//third-party/java/bazel:bazel",
        "//third-party/java/guava:guava",
        "//third-party/java/junit:junit",
    ],
)
