load("//tools/build_rules:java_rules.bzl", "buck_java_library")
buck_java_library(
    name = "handlers",
    srcs = glob(["*.java"]),
    visibility = [
        "//src/com/facebook/buck/downwardapi/processexecutor/...",
        "//src/com/facebook/buck/util:process_executor",
        "//src/com/facebook/buck/workertool/impl:impl",
        "//test/com/facebook/buck/downwardapi/processexecutor/...",
    ],
    deps = ["//src/com/facebook/buck/downwardapi/processexecutor/context:context"],
    exported_deps = ["//third-party/java/protobuf:protobuf"],
)
