java_library(
    name = "handlers",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/core/util/log:log",
        "//src/com/facebook/buck/downwardapi/processexecutor:utils",
        "//src/com/facebook/buck/event:event",
        "//src/com/facebook/buck/event/chrome_trace:chrome_trace",
        "//src/com/facebook/buck/step:step",
    ],
    exported_deps = [
        "//src-gen:downward-model",
    ],
)
