java_library(
    name = "impl",
    srcs = glob(["*.java"]),
    exported_deps = [
        "//src/com/facebook/buck/core/description:description",
        "//src/com/facebook/buck/core/model:model",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/core/model/impl:impl",
        "//third-party/java/guava:guava",
    ],
)
