java_test(
  name = 'hash',
  srcs = glob(['*.java']),
  source_under_test = [
    '//src/com/facebook/buck/util/hash:hash',
  ],
  deps = [
    '//lib:guava',
    '//lib:junit',
    '//src/com/facebook/buck/util/hash:hash',
  ],
)
