load("//tools/build_rules:java_rules.bzl", "buck_java_library")
buck_java_library(
    name = "string",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/core/util/log:log",
        "//src/com/facebook/buck/util/types:types",
        "//third-party/java/guava:guava",
    ],
)
