java_library(
    name = "string",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/util/types:types",
        "//third-party/java/guava:guava",
    ],
)
