java_library(
    name = "chrome_trace",
    srcs = glob(["*.java"]),
    tests = [
        "//test/com/facebook/buck/event/chrome_trace:chrome_trace",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/artifact_cache/config:config",
        "//src/com/facebook/buck/config:config",
        "//src/com/facebook/buck/event:event",
        "//src/com/facebook/buck/util:util",
        "//src/com/facebook/buck/util/environment:environment",
        "//third-party/java/jackson:jackson-annotations",
        "//third-party/java/jackson:jackson-databind",
    ],
)
