load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "linkgroup",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/core/rulekey:rulekey",
    ],
)
