load(
    "//tools/build_rules:java_rules.bzl",
    "java_test",
)

java_library(
    name = "testutil",
    srcs = glob(
        ["*.java"],
        exclude = ["*Test.java"],
    ),
    visibility = [
        "//test/...",
    ],
    deps = [
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/core/rules/actions:actions",
        "//third-party/java/guava:guava",
    ],
)
