load("//tools/build_rules:java_rules.bzl", "java_test")

java_test(
    name = "remoteexecution",
    srcs = glob([
        "*.java",
    ]),
    has_immutable_types = True,
    deps = [
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/event:interfaces",
        "//src/com/facebook/buck/event/listener/interfaces:interfaces",
        "//src/com/facebook/buck/remoteexecution:remoteexecution",
        "//src/com/facebook/buck/remoteexecution/event:event",
        "//src/com/facebook/buck/remoteexecution/event/listener:listener",
        "//src/com/facebook/buck/util:util",
        "//third-party/java/junit:junit",
    ],
)
