load("//tools/build_rules:java_rules.bzl", "java_test")

java_library(
    name = "testutil",
    srcs = glob(
        ["*.java"],
        exclude = [
            "*Test.java",
        ],
    ),
    visibility = ["//test/..."],
    deps = [
        "//src/com/facebook/buck/remoteexecution/event:event",
        "//src/com/facebook/buck/util:util",
    ],
)

java_test(
    name = "listener",
    srcs = glob([
        "RemoteExecutionConsoleLineProviderTest.java",
    ]),
    has_immutable_types = True,
    deps = [
        ":testutil",
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/event:interfaces",
        "//src/com/facebook/buck/event/listener/interfaces:interfaces",
        "//src/com/facebook/buck/remoteexecution:remoteexecution",
        "//src/com/facebook/buck/remoteexecution/config:config",
        "//src/com/facebook/buck/remoteexecution/event:event",
        "//src/com/facebook/buck/remoteexecution/event/listener:listener",
        "//src/com/facebook/buck/util:util",
        "//test/com/facebook/buck/core/config:testutil",
        "//third-party/java/junit:junit",
    ],
)
