load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "cache",
    srcs = glob([
        "*.java",
    ]),
    tests = [
        "//test/com/facebook/buck/parser/cache/impl:cache",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src-gen:thrift",
        "//src/com/facebook/buck/core/config:config",
        "//src/com/facebook/buck/core/exceptions:exceptions",
        "//src/com/facebook/buck/core/util/immutables:immutables",
        "//src/com/facebook/buck/core/util/log:log",
        "//src/com/facebook/buck/counters:counters",
        "//src/com/facebook/buck/io:io",
        "//src/com/facebook/buck/io/filesystem:filesystem",
        "//src/com/facebook/buck/manifestservice:manifestservice",
        "//src/com/facebook/buck/parser/cache:cache",
        "//src/com/facebook/buck/parser/cache/json:json",
        "//src/com/facebook/buck/parser/exceptions:exceptions",
        "//src/com/facebook/buck/util:util",
        "//src/com/facebook/buck/util/cache:cache",
        "//src/com/facebook/buck/util/config:config",
        "//src/com/facebook/buck/util/environment:platform",
        "//src/com/facebook/buck/util/hashing:hashing",
        "//third-party/java/guava:guava",
    ],
)
