java_library(
    name = "monitoring",
    srcs = glob(["*.java"]),
    tests = ["//test/com/facebook/buck/util/monitoring:monitoring"],
    visibility = [
        "//src/com/facebook/buck/cli:cli",
        "//src/com/facebook/buck/jvm/java/stepsbuilder/javacd/main:main_lib",
        "//test/com/facebook/buck/...",
    ],
    deps = [
        "//src/com/facebook/buck/event:interfaces",
        "//third-party/java/guava:guava",
    ],
)
