kotlin_test(
    name = "service",
    srcs = glob(["*Test.kt"]),
    friend_paths = [
        "//src/com/facebook/buck/multitenant/service:service",
    ],
    resources = glob(["*.json"]),
    deps = [
        "//src/com/facebook/buck/core/cell/impl:impl",
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/core/model/targetgraph/raw:raw",
        "//src/com/facebook/buck/core/parser/buildtargetparser:buildtargetparser",
        "//src/com/facebook/buck/core/parser/buildtargetpattern:buildtargetpattern",
        "//src/com/facebook/buck/multitenant/fs:fs",
        "//src/com/facebook/buck/multitenant/importer:RuleTypeFactory",
        "//src/com/facebook/buck/multitenant/importer:importer",
        "//src/com/facebook/buck/multitenant/service:service",
        "//third-party/java/guava:guava",
        "//third-party/java/junit:junit",
        "//third-party/java/vavr:vavr",
    ],
)
