kotlin_library(
    name = "testutil",
    srcs = glob(
        ["*.kt"],
        exclude = ["*Test.kt"],
    ),
    friend_paths = [
        "//src/com/facebook/buck/multitenant/service:service",
    ],
    visibility = [
        "//test/com/facebook/buck/multitenant/...",
    ],
    deps = [
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/core/model/targetgraph:targetgraph",
        "//src/com/facebook/buck/core/model/targetgraph/raw:raw",
        "//src/com/facebook/buck/multitenant/service:service",
        "//src/com/facebook/buck/util/json:json",
        "//test/com/facebook/buck/core/model:testutil",
        "//third-party/java/guava:guava",
        "//third-party/java/jackson:jackson-core",
        "//third-party/java/jackson:jackson-databind",
    ],
)

kotlin_test(
    name = "service",
    srcs = glob(["*Test.kt"]),
    friend_paths = [
        ":testutil",
        "//src/com/facebook/buck/multitenant/service:service",
    ],
    resources = glob(["*.json"]),
    deps = [
        ":testutil",
        "//src/com/facebook/buck/core/cell/impl:impl",
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/core/parser/buildtargetparser:buildtargetparser",
        "//src/com/facebook/buck/multitenant/service:service",
        "//test/com/facebook/buck/core/model:testutil",
        "//third-party/java/guava:guava",
        "//third-party/java/junit:junit",
    ],
)
