load("//tools/build_rules:java_rules.bzl", "buck_java_library")
buck_java_library(
    name = "cache",
    srcs = glob(["*.java"]),
    visibility = [
        "PUBLIC",
    ],
    exported_deps = [
        "//src/com/facebook/buck/core/graph/transformation:transformation",
        "//src/com/facebook/buck/core/model/targetgraph:targetgraph",
        "//src/com/facebook/buck/core/model/targetgraph/raw:raw",
        "//src/com/facebook/buck/core/rules/actions:actions",
    ],
)
