java_library(
    name = "impl",
    srcs = glob(
        ["*.java"],
    ),
    exported_deps = [
        "//src/com/facebook/buck/module:module",
    ],
    tests = [
        "//test/com/facebook/buck/module/impl/jarwithouthash:moduleclass-test",
        "//test/com/facebook/buck/module/impl/moduleclass:moduleclass-test",
        "//test/com/facebook/buck/module/impl/nonmoduleclass:nonmoduleclass-test",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//third-party/java/guava:guava",
    ],
)
