java_library(
    name = "impl",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/io:io",
        "//src/com/facebook/buck/io/watchman:watchman",
        "//src/com/facebook/buck/skylark/io:io",
        "//src/com/facebook/buck/util:util",
        "//third-party/java/bazel:skylark-lang",
        "//third-party/java/guava:guava",
        "//third-party/java/jsr:jsr305",
    ],
)
