java_library(
    name = "skylark",
    srcs = ["Glob.java"],
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/util:util",
        "//third-party/java/bazel:skylark-lang",
        "//third-party/java/guava:guava",
    ],
)
