java_test(
  name = 'file',
  srcs = glob(['*.java']),
  deps = [
    '//lib:easymock',
    '//lib:junit',
    '//lib:guava',
    '//src/com/facebook/buck/event:event',
    '//src/com/facebook/buck/file:downloader',
    '//src/com/facebook/buck/util:exceptions',
    '//test/com/facebook/buck/event:testutil',
    '//third-party/java/jetty:jetty',
  ],
)
