MATCHERS_SRCS = [
  'PathDoesNotExistOnProjectFilesystem.java',
  'PathExistsOnProjectFilesystem.java',
  'ProjectFilesystemMatchers.java',
]

java_library(
  name = 'matchers',
  srcs = MATCHERS_SRCS,
  deps = [
    '//src/com/facebook/buck/io:io',
    '//third-party/java/hamcrest:hamcrest',
  ],
  visibility = [
    '//test/...',
  ]
)

java_test(
  name = 'file',
  srcs = glob(['*.java'], excludes = MATCHERS_SRCS),
  deps = [
    '//src/com/facebook/buck/cli:cli',
    '//src/com/facebook/buck/cli:config',
    '//src/com/facebook/buck/event:event',
    '//src/com/facebook/buck/file:downloader',
    '//src/com/facebook/buck/file:file',
    '//src/com/facebook/buck/io:io',
    '//src/com/facebook/buck/model:model',
    '//src/com/facebook/buck/parser:rule_pattern',
    '//src/com/facebook/buck/rules:build_rule',
    '//src/com/facebook/buck/rules:rules',
    '//src/com/facebook/buck/step:step',
    '//src/com/facebook/buck/util:exceptions',
    '//test/com/facebook/buck/cli:FakeBuckConfig',
    '//test/com/facebook/buck/event:testutil',
    '//test/com/facebook/buck/model:BuildTargetFactory',
    '//test/com/facebook/buck/rules:testutil',
    '//test/com/facebook/buck/step:testutil',
    '//test/com/facebook/buck/testutil/integration:integration',
    '//test/com/facebook/buck/testutil:testutil',
    '//third-party/java/easymock:easymock',
    '//third-party/java/hamcrest:hamcrest',
    '//third-party/java/immutables:processor',
    '//third-party/java/jetty:jetty',
    '//third-party/java/jimfs:jimfs',
    '//third-party/java/jsr:jsr305',
    '//third-party/java/junit:junit',
    '//third-party/java/guava:guava',
  ],
)
