java_immutables_library(
    name = "testutil",
    srcs = [
        "AbstractFakeExecutionEnvironment.java",
    ],
    visibility = [
        "//test/...",
    ],
    deps = [
        "//src/com/facebook/buck/util/environment:environment",
        "//src/com/facebook/buck/util/environment:platform",
        "//third-party/java/guava:guava",
        "//third-party/java/jackson:jackson-databind",
    ],
)

java_test(
    name = "environment",
    srcs = glob(["*Test.java"]),
    deps = [
        "//src/com/facebook/buck/util/environment:environment",
        "//third-party/java/guava:guava",
        "//third-party/java/jsr:jsr305",
        "//third-party/java/junit:junit",
    ],
)
