STANDARD_TEST_SRCS = [
  '*Test.java',
]

java_test(
  name = 'environment',
  srcs = glob(STANDARD_TEST_SRCS),
  deps = [
    '//src/com/facebook/buck/util/environment:environment',
    '//src/com/facebook/buck/util/environment:env-filter',
    '//src/com/facebook/buck/util/environment:platform',
    '//src/com/facebook/buck/util:io',
    '//test/com/facebook/buck/util:testutil',
    '//third-party/java/guava:guava',
    '//third-party/java/hamcrest:hamcrest',
    '//third-party/java/junit:junit',
  ],
)
