java_immutables_library(
    name = "testutil",
    srcs = [
        "AbstractFakeExecutionEnvironment.java",
    ],
    autodeps = True,
    immutable_types = [
        "FakeExecutionEnvironment",
    ],
    visibility = [
        "//test/...",
    ],
)

java_test(
    name = "environment",
    srcs = glob(["*Test.java"]),
    autodeps = True,
)
