java_test(
  name = 'debug',
  srcs = glob(['*.java']),
  source_under_test = [
    '//src/com/facebook/buck/debug:debug',
  ],
  deps = [
    '//lib:easymock',
    '//lib:guava',
    '//lib:junit',
    '//src/com/facebook/buck/debug:debug',
  ],
)
