RULES_IMMUTABLES = [
  'AbstractOCamlBuildContext.java',
  'AbstractOCamlGeneratedBuildRules.java',
]
java_immutables_library(
  name = 'rules',
  srcs = glob(['*.java'], excludes = RULES_IMMUTABLES),
  immutable_srcs = RULES_IMMUTABLES,
  tests = [
    '//test/com/facebook/buck/ocaml:ocaml',
  ],
  autodeps = True,
  visibility = [
    'PUBLIC'
  ],
)
