standard_java_library(
    name = "ocaml",
    immutable_types = [
        "OcamlBuildContext",
        "OcamlGeneratedBuildRules",
    ],
    tests = [
        "//test/com/facebook/buck/ocaml:ocaml",
    ],
)
