java_immutables_library(
  name = 'rules',
  srcs = glob(['*.java']),
  immutable_types = [
    'OCamlBuildContext',
    'OCamlGeneratedBuildRules',
  ],
  tests = [
    '//test/com/facebook/buck/ocaml:ocaml',
  ],
  autodeps = True,
  visibility = [
    'PUBLIC'
  ],
)
