java_library(
  name = 'testutil',
  srcs = [
    'FakeBuildRule.java',
    'FakeJavaLibraryRule.java',
    'FakeTestRule.java',
    'RetainOrderComparator.java',
  ],
  deps = [
    '//lib:guava',
    '//lib:jsr305',
    '//src/com/facebook/buck/model:model',
    '//src/com/facebook/buck/parser:parser',
    '//src/com/facebook/buck/rules:rules',
    '//src/com/facebook/buck/step:step',
  ],
  visibility = [
    '//test/com/facebook/buck/parser:parser',
    '//test/com/facebook/buck/cli:cli',
  ],
)

java_test(
  name = 'rules',
  srcs = glob(['*Test.java']),
  source_under_test = [
    '//src/com/facebook/buck/rules:rules',
  ],
  deps = [
    '//lib:easymock',
    '//lib:guava',
    '//lib:junit',
    '//src/com/facebook/buck/android:android',
    '//src/com/facebook/buck/graph:graph',
    '//src/com/facebook/buck/java:java',
    '//src/com/facebook/buck/model:model',
    '//src/com/facebook/buck/parser:core',
    '//src/com/facebook/buck/rules:rules',
    '//src/com/facebook/buck/shell:shell',
    '//src/com/facebook/buck/step:step',
    '//src/com/facebook/buck/step/fs:fs',
    '//src/com/facebook/buck/util:exceptions',
    '//src/com/facebook/buck/util:io',
    '//src/com/facebook/buck/util:util',
    '//test/com/facebook/buck/model:BuildTargetFactory',
    '//test/com/facebook/buck/parser:NonCheckingBuildRuleFactoryParams',
    '//test/com/facebook/buck/testutil:testutil',
    ':testutil',
  ],
)
