java_library(
  name = 'testutil',
  srcs = [
    'FakeBuildRule.java',
    'FakeTestRule.java',
    'RetainOrderComparator.java',
  ],
  deps = [
    '//lib:guava',
    '//lib:jsr305',
    '//src/com/facebook/buck/model:model',
    '//src/com/facebook/buck/rules:rules',
    '//src/com/facebook/buck/rules:test',
    '//src/com/facebook/buck/step:step',
  ],
  visibility = [
    '//test/...',
  ],
)

java_test(
  name = 'rules',
  srcs = glob(['*Test.java']),
  source_under_test = [
    '//src/com/facebook/buck/rules:rules',
  ],
  deps = [
    '//lib:easymock',
    '//lib:guava',
    '//lib:junit',
    '//src/com/facebook/buck/graph:graph',
    '//src/com/facebook/buck/java:rules',
    '//src/com/facebook/buck/model:model',
    '//src/com/facebook/buck/parser:parser',
    '//src/com/facebook/buck/rules:rules',
    '//src/com/facebook/buck/rules:test',
    '//src/com/facebook/buck/shell:rules',
    '//src/com/facebook/buck/step:step',
    '//src/com/facebook/buck/util:constants',
    '//src/com/facebook/buck/util:exceptions',
    '//src/com/facebook/buck/util:io',
    '//src/com/facebook/buck/util:util',
    '//test/com/facebook/buck/model:BuildTargetFactory',
    '//test/com/facebook/buck/java:fakes',
    ':testutil',
  ],
)
