java_test(
  name = 'collect',
  srcs = glob(['*.java']),
  source_under_test = [
    '//src/com/facebook/buck/util/collect:collect',
  ],
  deps = [
    '//lib:junit',
    '//src/com/facebook/buck/util/collect:collect',
  ],
)
