load("//tools/build_rules:java_rules.bzl", "standard_java_test")

standard_java_test(
    name = "nio",
    deps = [
        "//src/com/facebook/buck/util:util",
        "//src/com/facebook/buck/util/nio:nio",
        "//test/com/facebook/buck/testutil:testutil",
        "//third-party/java/junit:junit",
    ],
)
