CACHE_HANDLER_SRCS = [
  'ArtifactCacheHandler.java',
]

UTIL_SRCS = [
  'Responses.java',
]

java_library(
  name = 'cache_handler',
  srcs = CACHE_HANDLER_SRCS,
  autodeps = True,
  tests = [
    '//test/com/facebook/buck/httpserver:httpserver_cache_integration_test',
  ],
)

java_library(
  name = 'httpserver',
  srcs = glob(
    ['*.java'],
    excludes = CACHE_HANDLER_SRCS + UTIL_SRCS,
  ),
  autodeps = True,
  resources = glob(['*.soy']),
  tests = [
    '//test/com/facebook/buck/httpserver:httpserver',
    '//test/com/facebook/buck/httpserver:httpserver_cache_integration_test',
  ],
  visibility = [
    '//src/com/facebook/buck/cli:cli',
    '//src/com/facebook/buck/event/listener:listener',
    '//test/com/facebook/buck/cli:',
    '//test/com/facebook/buck/event/listener:',
    '//test/com/facebook/buck/httpserver:',
  ],
)

java_library(
  name = 'util',
  srcs = UTIL_SRCS,
  autodeps = True,
  tests = [
    '//test/com/facebook/buck/httpserver:httpserver',
  ],
  visibility = [
    '//test/...',
  ],
)
