CACHE_HANDLER_SRCS = [
  'ArtifactCacheHandler.java',
]
UTIL_SRCS = [
  'Responses.java',
]

java_library(
  name = 'cache_handler',
  srcs = CACHE_HANDLER_SRCS,
  tests = [
    '//test/com/facebook/buck/httpserver:httpserver_cache_integration_test',
  ],
  autodeps = True,
)

java_library(
  name = 'httpserver',
  srcs = glob(['*.java'], excludes=CACHE_HANDLER_SRCS + UTIL_SRCS),
  tests = [
    '//test/com/facebook/buck/httpserver:httpserver',
    '//test/com/facebook/buck/httpserver:httpserver_cache_integration_test',
  ],
  autodeps = True,
  resources = glob(['*.soy']),
  visibility = [
    '//src/com/facebook/buck/cli:cli',
    '//src/com/facebook/buck/event/listener:listener',
    '//test/com/facebook/buck/cli:',
    '//test/com/facebook/buck/httpserver:',
    '//test/com/facebook/buck/event/listener:',
  ],
)

java_library(
  name = 'util',
  srcs = UTIL_SRCS,
  tests = [
    '//test/com/facebook/buck/httpserver:httpserver',
  ],
  autodeps = True,
  visibility = [
    '//test/...',
  ],
)
