load("//:DEFS", "standard_java_test")

standard_java_test(
    name = "function",
    deps = [
        "//src/com/facebook/buck/skylark/function:function",
        "//src/com/facebook/buck/skylark/io:io",
        "//src/com/facebook/buck/skylark/io/impl:impl",
        "//src/com/facebook/buck/skylark/packages:packages",
        "//third-party/java/bazel:skylark-lang",
        "//third-party/java/guava:guava",
        "//third-party/java/hamcrest:java-hamcrest",
        "//third-party/java/junit:junit",
    ],
)
