load("//tools/build_rules:java_rules.bzl", "buck_java_library")

buck_java_library(
    name = "filter",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/core/exceptions:exceptions",
        "//src/com/facebook/buck/io/filesystem:filesystem",
        "//src/com/facebook/buck/util/string:string",
        "//third-party/java/guava:guava",
        "//third-party/java/jsr:jsr305",
    ],
)
