load("//tools/build_rules:java_rules.bzl", "buck_java_binary", "buck_java_library")

buck_java_library(
    name = "filter",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/core/exceptions:exceptions",
        "//src/com/facebook/buck/core/filesystems:filesystems",
        "//src/com/facebook/buck/io/filesystem/impl:utils",
        "//src/com/facebook/buck/io/pathformat:pathformat",
        "//src/com/facebook/buck/util/string:string",
        "//third-party/java/args4j:args4j",
        "//third-party/java/guava:guava",
        "//third-party/java/jsr:jsr305",
    ],
)

buck_java_binary(
    name = "filter_resources_binary",
    main_class = "com.facebook.buck.android.resources.filter.FilterResourcesExecutableMain",
    visibility = [
        "PUBLIC",
    ],
    deps = [
        ":filter",
    ],
)
