java_library(
  name = 'parcelable',
  srcs = glob(['*.java']),
  deps = [
    '//lib:guava',
    '//lib:jsr305',
    '//src/com/facebook/buck/util:util',
  ],
  visibility = [
    '//src/com/facebook/buck/android:android',
    '//test/com/facebook/buck/parcelable:parcelable',
  ],
)
