java_library(
    name = "thrift",
    srcs = glob(["**/*.java"]),
    exported_deps = [
        "//third-party/java/thrift:libthrift",
    ],
    abi_generation_mode = "source",
    # Thrift generated code has a dependency on javax.annotation.Generated.
    # In Java 10, we have to add an explicit module dependency to access this.
    extra_arguments = select({
        "DEFAULT": [],
        "//tools/build/config:java_10": ["--add-modules", "java.xml.ws.annotation"],
    }),
    visibility = ["PUBLIC"],
    deps = [
        # This dep is looked up at runtime by reflection.
        "//third-party/java/slf4j:slf4j",
        "//third-party/java/slf4j:slf4j-api",
        "//third-party/java/fbthrift:fbthrift",
    ],
)
