java_library(
    name = "thrift",
    srcs = glob(["**/*.java"]),
    exported_deps = [
        "//third-party/java/thrift:libthrift",
    ],
    visibility = ["PUBLIC"],
    deps = ["//third-party/java/slf4j:slf4j-api"],
)
