java_test(
  name = 'aapt',
  srcs = glob(['*Test.java']),
  deps = [
    '//src/com/facebook/buck/android/aapt:aapt',
    '//src/com/facebook/buck/event:event',
    '//src/com/facebook/buck/io:io',
    '//src/com/facebook/buck/model:model',
    '//src/com/facebook/buck/step:step',
    '//test/com/facebook/buck/testutil:testutil',
    '//test/com/facebook/buck/timing:testutil',
    '//third-party/java/guava:guava',
    '//third-party/java/hamcrest:hamcrest',
    '//third-party/java/junit:junit',
  ],
  source_under_test = [
    '//src/com/facebook/buck/android/aapt:aapt',
  ],
)
