load("//tools/build_rules:java_rules.bzl", "standard_java_test")

standard_java_test(
    name = "collect",
    with_test_data = True,
    deps = [
        "//src/com/facebook/buck/util/zip/collect:collect",
        "//test/com/facebook/buck/io/filesystem:testutil",
        "//test/com/facebook/buck/testutil:testutil",
        "//test/com/facebook/buck/testutil/integration:util",
        "//third-party/java/guava:guava",
        "//third-party/java/junit:junit",
    ],
)
