java_library(
    name = "tool",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/core/rulekey:rulekey",
        "//src/com/facebook/buck/core/sourcepath/resolver:resolver",
        "//third-party/java/guava:guava",
    ],
)
