load("//tools/build_rules:java_rules.bzl", "buck_java_library")

buck_java_library(
    name = "tool",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    exported_deps = [
        "//src/com/facebook/buck/core/rulekey:rulekey",
        "//src/com/facebook/buck/core/sourcepath/resolver:resolver",
        "//third-party/java/guava:guava",
    ],
)
