java_test(
  name = 'classes',
  srcs = glob(['*.java']),
  source_under_test = [
    '//src/com/facebook/buck/java/classes:classes',
  ],
  deps = [
    '//lib:guava',
    '//lib:junit',
    '//src/com/facebook/buck/java/classes:classes',
    '//src/com/facebook/buck/util:io',
  ],
)
