java_test(
  name = 'classes',
  srcs = glob(['*.java']),
  source_under_test = [
    '//src/com/facebook/buck/java/classes:classes',
  ],
  deps = [
    '//src/com/facebook/buck/java/classes:classes',
    '//src/com/facebook/buck/io:io',
    '//third-party/java/guava:guava',
    '//third-party/java/junit:junit',
  ],
)
