load(
    "//tools/build_rules:java_rules.bzl",
    "java_test",
)

java_library(
    name = "testutil",
    srcs = glob(
        ["*.java"],
        exclude = [
            "*Test.java",
        ],
    ),
    visibility = [
        "//test/...",
    ],
    deps = [
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/core/rules:rules",
        "//src/com/facebook/buck/rules/modern:modern",
        "//third-party/java/guava:guava",
    ],
)

java_test(
    name = "modern",
    srcs = glob(
        ["*Test.java"],
        exclude = [
            "NonStaticInnerClassBanTest.java",
        ],
    ),
    has_immutable_types = True,
    deps = [
        ":testutil",
        "//src/com/facebook/buck/cli:cli",
        "//src/com/facebook/buck/core/description/arg:arg",
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/core/rules:rules",
        "//src/com/facebook/buck/core/rules/knowntypes:knowntypes",
        "//src/com/facebook/buck/core/util/immutables:immutables",
        "//src/com/facebook/buck/io:io",
        "//src/com/facebook/buck/io/file:file",
        "//src/com/facebook/buck/remoteexecution/config:config",
        "//src/com/facebook/buck/remoteexecution/grpc/server:server",
        "//src/com/facebook/buck/rules/keys:keys",
        "//src/com/facebook/buck/rules/modern:modern",
        "//src/com/facebook/buck/rules/modern/config:config",
        "//src/com/facebook/buck/step:step",
        "//src/com/facebook/buck/step/fs:fs",
        "//src/com/facebook/buck/util:util",
        "//src/com/facebook/buck/util/console:console",
        "//src/com/facebook/buck/util/env:env",
        "//test/com/facebook/buck/core/build/buildable/context:testutil",
        "//test/com/facebook/buck/core/build/context:testutil",
        "//test/com/facebook/buck/core/model:testutil",
        "//test/com/facebook/buck/core/rules/resolver/impl:testutil",
        "//test/com/facebook/buck/io/file:testutil",
        "//test/com/facebook/buck/io/filesystem:testutil",
        "//test/com/facebook/buck/io/filesystem/impl:testutil",
        "//test/com/facebook/buck/step:testutil",
        "//test/com/facebook/buck/testutil:testutil",
        "//test/com/facebook/buck/testutil/integration:util",
        "//third-party/java/guava:guava",
        "//third-party/java/junit:junit",
    ],
)

# The subclass_exclusion test iterates over every class on the classpath and asserts that there are
# no classes deriving from a set of banned classes while also being non-static and nested. For this
# to work, this rule depends on as much Buck code as possible to ensure that classes for these
# rules are on the classpath when running the test.
#
# Important to note is that only classes in the "deps" list will be checked!
java_test(
    name = "subclass_exclusion",
    srcs = ["NonStaticInnerClassBanTest.java"],
    deps = [
        "//src/com/facebook/buck/android:rules",
        "//src/com/facebook/buck/apple:apple",
        "//src/com/facebook/buck/core/toolchain/tool:tool",
        "//src/com/facebook/buck/cxx:rules",
        "//src/com/facebook/buck/features/apple/common:common",
        "//src/com/facebook/buck/features/d:d",
        "//src/com/facebook/buck/features/dotnet:dotnet",
        "//src/com/facebook/buck/features/filebundler:filebundler",
        "//src/com/facebook/buck/features/filegroup:filegroup",
        "//src/com/facebook/buck/features/go:go",
        "//src/com/facebook/buck/features/gwt:gwt",
        "//src/com/facebook/buck/features/halide:halide",
        "//src/com/facebook/buck/features/haskell:haskell",
        "//src/com/facebook/buck/features/js:js",
        "//src/com/facebook/buck/features/lua:lua",
        "//src/com/facebook/buck/features/ocaml:ocaml",
        "//src/com/facebook/buck/features/python:python",
        "//src/com/facebook/buck/features/rust:rust",
        "//src/com/facebook/buck/features/zip/rules:rules",
        "//src/com/facebook/buck/file:file",
        "//src/com/facebook/buck/jvm/java/rules:rules",
        "//src/com/facebook/buck/jvm/kotlin:kotlin",
        "//src/com/facebook/buck/rules/args:args",
        "//src/com/facebook/buck/shell:rules",
        "//src/com/facebook/buck/swift:swift",
        "//src/com/facebook/buck/testrunner:testng",
        "//third-party/java/guava:guava",
        "//third-party/java/junit:junit",
    ],
)
