load(
    "//tools/build_rules:java_rules.bzl",
    "java_test",
)

java_library(
    name = "testutil",
    srcs = glob(
        ["*.java"],
        exclude = [
            "*Test.java",
        ],
    ),
    visibility = [
        "//test/...",
    ],
    deps = [
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/core/rules:rules",
        "//src/com/facebook/buck/rules/modern:modern",
        "//third-party/java/guava:guava",
    ],
)

java_test(
    name = "modern",
    srcs = glob(["*Test.java"]),
    has_immutable_types = True,
    deps = [
        ":testutil",
        "//src/com/facebook/buck/cli:cli",
        "//src/com/facebook/buck/core/description/arg:arg",
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/core/rules:rules",
        "//src/com/facebook/buck/core/rules/knowntypes:knowntypes",
        "//src/com/facebook/buck/core/util/immutables:immutables",
        "//src/com/facebook/buck/io:io",
        "//src/com/facebook/buck/io/file:file",
        "//src/com/facebook/buck/remoteexecution/config:config",
        "//src/com/facebook/buck/remoteexecution/grpc/server:server",
        "//src/com/facebook/buck/rules/keys:keys",
        "//src/com/facebook/buck/rules/modern:modern",
        "//src/com/facebook/buck/rules/modern/config:config",
        "//src/com/facebook/buck/step:step",
        "//src/com/facebook/buck/step/fs:fs",
        "//src/com/facebook/buck/util:util",
        "//src/com/facebook/buck/util/env:env",
        "//test/com/facebook/buck/core/build/buildable/context:testutil",
        "//test/com/facebook/buck/core/model:testutil",
        "//test/com/facebook/buck/core/rules/resolver/impl:testutil",
        "//test/com/facebook/buck/io/file:testutil",
        "//test/com/facebook/buck/io/filesystem:testutil",
        "//test/com/facebook/buck/io/filesystem/impl:testutil",
        "//test/com/facebook/buck/step:testutil",
        "//test/com/facebook/buck/testutil:testutil",
        "//test/com/facebook/buck/testutil/integration:util",
        "//third-party/java/guava:guava",
        "//third-party/java/junit:junit",
    ],
)
