java_immutables_library(
    name = "bsd",
    srcs = glob(["*.java"]),
    tests = [
        "//test/com/facebook/buck/bsd:bsd",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/charset:charset",
        "//src/com/facebook/buck/util:exceptions",
    ],
)
