standard_java_library(
    name = "bsd",
    immutable_types = [
        "UnixArchiveEntry",
    ],
    tests = [
        "//test/com/facebook/buck/bsd:bsd",
    ],
    deps = [
        "//src/com/facebook/buck/charset:charset",
        "//src/com/facebook/buck/util:exceptions",
        "//src/com/facebook/buck/util/immutables:immutables",
        "//third-party/java/guava:guava",
        "//third-party/java/immutables:immutables",
        "//third-party/java/jsr:jsr305",
    ],
)
