load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

TRANSPORT_SRCS = [
    "Transport.java",
]

java_library(
    name = "transport",
    srcs = TRANSPORT_SRCS,
    visibility = [
        "PUBLIC",
    ],
)

WATCHMAN_SRCS = [
    "AbstractWatchmanQuery.java",
    "Watchman.java",
    "WatchmanClient.java",
    "WatchmanDiagnosticEvent.java",
    "WatchmanDiagnosticEventListener.java",
    "WatchmanEvent.java",
    "WatchmanFactory.java",
    "WatchmanTransportClient.java",
    "WatchmanWatcher.java",
    "WatchmanWatcherException.java",
]

java_immutables_library(
    name = "watchman",
    srcs = WATCHMAN_SRCS,
    visibility = [
        "PUBLIC",
    ],
    deps = [
        ":executable-finder",
        ":io",
        ":transport",
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/event:event",
        "//src/com/facebook/buck/event:interfaces",
        "//src/com/facebook/buck/event/external:external_lib",
        "//src/com/facebook/buck/io/file:file",
        "//src/com/facebook/buck/io/filesystem:filesystem",
        "//src/com/facebook/buck/io/unixsocket:unixsocket",
        "//src/com/facebook/buck/io/windowspipe:windowspipe",
        "//src/com/facebook/buck/log:api",
        "//src/com/facebook/buck/util:exceptions",
        "//src/com/facebook/buck/util:process_executor",
        "//src/com/facebook/buck/util:util",
        "//src/com/facebook/buck/util/bser:bser",
        "//src/com/facebook/buck/util/concurrent:concurrent",
        "//src/com/facebook/buck/util/environment:platform",
        "//src/com/facebook/buck/util/timing:timing",
    ],
)

FINDER_SRCS = [
    "ExecutableFinder.java",
]

java_library(
    name = "executable-finder",
    srcs = FINDER_SRCS,
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/core/exceptions:exceptions",
        "//src/com/facebook/buck/io/file:file",
        "//src/com/facebook/buck/log:api",
        "//src/com/facebook/buck/util:exceptions",
        "//src/com/facebook/buck/util:util",
        "//src/com/facebook/buck/util/environment:platform",
        "//third-party/java/guava:guava",
        "//third-party/java/jsr:jsr305",
    ],
)

java_immutables_library(
    name = "io",
    srcs = glob(
        ["*.java"],
        exclude = (
            FINDER_SRCS +
            WATCHMAN_SRCS +
            TRANSPORT_SRCS
        ),
    ),
    tests = [
        "//test/com/facebook/buck/io:io",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/event:interfaces",
        "//src/com/facebook/buck/io/file:file",
        "//src/com/facebook/buck/io/filesystem:filesystem",
        "//src/com/facebook/buck/io/windowsfs:windowsfs",
        "//src/com/facebook/buck/log:api",
        "//src/com/facebook/buck/util:constants",
        "//src/com/facebook/buck/util:exceptions",
        "//src/com/facebook/buck/util/concurrent:concurrent",
        "//src/com/facebook/buck/util/config:config",
        "//src/com/facebook/buck/util/environment:platform",
        "//src/com/facebook/buck/util/sha1:sha1",
    ],
)
