load("//:DEFS", "java_immutables_library")

java_immutables_library(
    name = "resources",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/config:config",
        "//src/com/facebook/buck/util/concurrent:concurrent",
    ],
)
