standard_java_library(
  tests = [
    '//test/com/facebook/buck/util/network:network',
    '//test/com/facebook/buck/util:util',
  ],
  visibility = [
    '//src/com/facebook/buck/cli:cli',
    '//src/com/facebook/buck/cli:config',
    '//src/com/facebook/buck/event/listener:listener',
    '//src/com/facebook/buck/rules:rules',
    '//src/com/facebook/buck/util:util',
    '//src/com/facebook/buck/util/environment:environment',
    '//test/com/facebook/buck/util:util',
    '//test/com/facebook/buck/event/listener:listener',
    '//test/com/facebook/buck/util/network/...',
  ],
)
