load("//tools/build_rules:java_rules.bzl", "standard_java_test")

java_library(
    name = "testutil",
    srcs = glob(
        ["*.java"],
        exclude = [
            "*Test.java",
        ],
    ),
    visibility = ["//test/..."],
    deps = [
        "//src/com/facebook/buck/core/model/impl:impl",
        "//src/com/facebook/buck/core/parser/buildtargetparser:buildtargetparser",
        "//src/com/facebook/buck/support/cli/args:args",
        "//src/com/facebook/buck/util:util",
        "//src/com/facebook/buck/util/stream:stream",
        "//test/com/facebook/buck/io/filesystem/impl:testutil",
        "//third-party/java/jsr:jsr305",
    ],
    exported_deps = [
        "//src/com/facebook/buck/core/model/impl:impl",
    ],
)

standard_java_test(
    name = "model",
    deps = [
        ":testutil",
        "//src/com/facebook/buck/core/model:model",
        "//test/com/facebook/buck/io/filesystem/impl:testutil",
        "//third-party/java/guava:guava",
        "//third-party/java/junit:junit",
    ],
)
