TYPES_SRCS = [
    "AbstractClasspathMacro.java",
    "AbstractExecutableMacro.java",
    "AbstractLocationMacro.java",
    "AbstractMavenCoordinatesMacro.java",
    "AbstractQueryOutputsMacro.java",
    "AbstractQueryTargetsMacro.java",
    "AbstractStringWithMacros.java",
    "BuildTargetMacro.java",
    "Macro.java",
    "QueryMacro.java",
]

java_immutables_library(
    name = "types",
    srcs = TYPES_SRCS,
    autodeps = True,
    immutable_types = [
        "ClasspathMacro",
        "ExecutableMacro",
        "LocationMacro",
        "MavenCoordinatesMacro",
        "QueryTargetsMacros",
        "QueryOutputsMacros",
        "StringWithMacros",
    ],
    visibility = ["PUBLIC"],
)

standard_java_library(
    srcs = glob(
        ["*.java"],
        excludes = TYPES_SRCS,
    ),
    immutable_types = [
        "MacroMatchResult",
    ],
    tests = [
        "//test/com/facebook/buck/rules/macros:macros",
    ],
)
