load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "graphbuilder",
    srcs = glob(["*.java"]),
    exported_deps = [
        "//src/com/facebook/buck/core/cell/resolver:resolver",
        "//src/com/facebook/buck/core/rules/provider:provider",
        "//src/com/facebook/buck/rules:build_rule",
    ],
    tests = [
        "//test/com/facebook/buck/core/rules/graphbuilder:graphbuilder",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/core/graph/transformation:transformation",
        "//third-party/java/guava:guava",
    ],
)
