java_library(
    name = "arg",
    srcs = glob(["*.java"]),
    exported_deps = [
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/core/sourcepath:sourcepath",
        "//src/com/facebook/buck/rules/query:types",
        "//third-party/java/guava:guava",
        "//third-party/java/immutables:immutables",
        "//third-party/java/infer-annotations:infer-annotations",
    ],
    required_for_source_only_abi = True,
    visibility = ["PUBLIC"],
)
