load("//tools/build_rules:java_rules.bzl", "buck_java_library")

buck_java_library(
    name = "testutil",
    srcs = glob(
        ["*.java"],
        exclude = ["*Test.java"],
    ),
    visibility = [
        "//test/...",
    ],
    deps = [
    ],
    exported_deps = [
        "//src/com/facebook/buck/parser/api:api",
        "//third-party/java/guava:guava",
    ],
)
