java_library(
    name = "testutil",
    srcs = glob(
        ["*.java"],
        exclude = ["*Test.java"],
    ),
    exported_deps = [
        "//src/com/facebook/buck/parser/api:api",
        "//third-party/java/guava:guava",
    ],
    visibility = [
        "//test/...",
    ],
    deps = [
    ],
)
