java_library(
    name = "compiler",
    srcs = glob(["*.java"]),
    provided_deps = [
        # Tools.jar is the compiler itself, and will already be present at runtime;
        # we compile against a stub.
        "//third-party/java/jdk:compiler-tree-api",
    ],
    visibility = [
        "//test/com/facebook/buck/jvm/java/...",
    ],
    deps = [
        "//src/com/facebook/buck/io:MorePaths.java",
        "//src/com/facebook/buck/jvm/java/abi/source:source",
        "//src/com/facebook/buck/jvm/java/plugin/adapter:adapter",
        "//src/com/facebook/buck/util/function:function",
        "//src/com/facebook/buck/zip:stream",
        "//third-party/java/asm:asm",
        "//third-party/java/guava:guava",
        "//third-party/java/hamcrest:java-hamcrest",
        "//third-party/java/junit:junit",
    ],
)
