java_library(
    name = "compiler",
    srcs = glob(["*.java"]),
    provided_deps = [
        # Tools.jar is the compiler itself, and will already be present at runtime;
        # we compile against a stub.
        "//third-party/java/jdk:compiler-tree-api",
    ],
    visibility = [
        "//test/com/facebook/buck/jvm/...",
    ],
    deps = [
        "//src/com/facebook/buck/io/file:file",
        "//src/com/facebook/buck/io/pathformat:pathformat",
        "//src/com/facebook/buck/jvm/java/abi/source:source",
        "//src/com/facebook/buck/jvm/java/abi/source/api:api",
        "//src/com/facebook/buck/jvm/java/javax:javax",
        "//src/com/facebook/buck/jvm/java/lang/model:model",
        "//src/com/facebook/buck/jvm/java/plugin/adapter:adapter",
        "//src/com/facebook/buck/jvm/java/version:version",
        "//src/com/facebook/buck/util:util",
        "//src/com/facebook/buck/util/function:function",
        "//src/com/facebook/buck/util/zip:zip",
        "//third-party/java/asm:asm",
        "//third-party/java/guava:guava",
        "//third-party/java/hamcrest:java-hamcrest",
        "//third-party/java/junit:junit",
    ],
)
