java_immutables_library(
  name = 'intellij',
  srcs = glob(['*.java']),
  resources = [
    'ij-library.st',
    'ij-module.st',
    'ij-module-index.st',
  ],
  autodeps = True,
  visibility = [
    '//src/com/facebook/buck/cli:cli',
    '//test/...',
  ],
)
