load("//tools/build_rules:java_rules.bzl", "buck_java_library")

buck_java_library(
    name = "resources",
    srcs = [
    ],
    resources = [
        "META-INF/annotations/org.immutables.value.immutable",
    ],
    resources_root = ".",
    visibility = [
        "PUBLIC",
    ],
)
