load("//tools/build_rules:java_rules.bzl", "buck_java_library")

buck_java_library(
    name = "testutil",
    srcs = glob(
        ["*.java"],
        exclude = [
            "*Test.java",
        ],
    ),
    visibility = ["//test/..."],
    deps = [
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/core/module/impl:impl",
        "//src/com/facebook/buck/rules/keys/config/impl:impl",
    ],
    exported_deps = [
        "//src/com/facebook/buck/rules/keys/config:config",
    ],
)
