load("//tools/build_rules:java_rules.bzl", "standard_java_test")

java_library(
    name = "testutil",
    srcs = glob(
        ["*.java"],
        exclude = [
            "*Test.java",
        ],
    ),
    exported_deps = [
        "//src/com/facebook/buck/rules/keys/config:config",
    ],
    visibility = ["//test/..."],
    deps = [
        "//src/com/facebook/buck/model:model",
        "//src/com/facebook/buck/module/impl:impl",
    ],
)
