load("//tools/build_rules:java_rules.bzl", "buck_java_library")
buck_java_library(
    name = "nio",
    srcs = glob(["*.java"]),
    tests = [
        "//test/com/facebook/buck/util/nio:nio",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/jvm/java/version/utils:utils",
        "//src/com/facebook/buck/util:util",
    ],
)
