load("//tools/build_rules:java_rules.bzl", "java_immutables_library", "java_test")

java_test(
    name = "cell",
    srcs = glob(["*Test.java"]),
    has_immutable_types = True,
    deps = [
        ":testutil",
        "//test/com/facebook/buck/core/model:testutil",
        "//test/com/facebook/buck/io/filesystem:testutil",
        "//test/com/facebook/buck/util/config:testutil",
        "//third-party/java/jimfs:jimfs",
        "//third-party/java/junit:junit",
    ],
)

java_library(
    name = "testutil",
    srcs = glob(
        ["*.java"],
        exclude = ["*Test.java"],
    ),
    exported_deps = [
        "//src/com/facebook/buck/core/cell/impl:impl",
        "//src/com/facebook/buck/core/module:module",
        "//src/com/facebook/buck/core/plugin/impl:impl",
        "//src/com/facebook/buck/core/toolchain/impl:impl",
        "//src/com/facebook/buck/io/filesystem/impl:impl",
        "//test/com/facebook/buck/core/config:FakeBuckConfig",
        "//test/com/facebook/buck/core/module:testutil",
        "//test/com/facebook/buck/testutil:testutil",
        "//third-party/java/guava:guava",
        "//third-party/java/jsr:jsr305",
    ],
    visibility = [
        "//test/...",
    ],
)
