load("//tools/build_rules:java_rules.bzl", "java_test")

java_test(
    name = "util",
    srcs = glob(["*.java"]),
    deps = [
        "//src/com/facebook/buck/android/agent/util:util",
        "//src/com/facebook/buck/android/agent:manifest-as-resource",
        "//src/com/facebook/buck/android:utils",
        "//test/com/facebook/buck/testutil/integration:util",
        "//third-party/java/guava:guava",
        "//third-party/java/junit:junit",
    ],
)
