java_test(
  name = 'util',
  srcs = glob(['*.java']),
  deps = [
    '//third-party/java/guava:guava',
    '//third-party/java/junit:junit',
    '//src/com/facebook/buck/android/agent:manifest-as-resource',
    '//src/com/facebook/buck/android/agent/util:util',
    '//src/com/facebook/buck/util:util',
    '//test/com/facebook/buck/testutil/integration:integration',
  ],
  source_under_test = [
    '//src/com/facebook/buck/android/agent/util:util',
  ],
)

