java_library(
  name = 'xcspec',
  srcs = glob(['*.java']),
  tests = [
    '//test/com/facebook/buck/apple/xcode/xcspec:xcspec',
  ],
  deps = [
    '//third-party/java/jsr:jsr305',
    '//third-party/java/guava:guava',
    '//third-party/java/dd-plist:dd-plist',
  ],
  visibility = ['PUBLIC'],
)
