java_library(
    name = "xcspec",
    srcs = glob(["*.java"]),
    tests = [
        "//test/com/facebook/buck/apple/xcode/xcspec:xcspec",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//third-party/java/dd-plist:dd-plist",
        "//third-party/java/guava:guava",
    ],
)
