load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "impl",
    srcs = glob(["*.java"]),
    exported_deps = [
        "//src/com/facebook/buck/core/rules/providers:providers",
        "//src/com/facebook/buck/core/rules/providers/annotations:annotations",
        "//src/com/facebook/buck/core/starlark/compatible:compatible",
    ],
    tests = [
        "//test/com/facebook/buck/core/rules/providers/impl:impl",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//third-party/java/guava:guava",
        "//third-party/java/jsr:jsr305",
    ],
)
