java_library(
    name = "impl",
    srcs = glob(["*.java"]),
    exported_deps = [
        "//src/com/facebook/buck/core/rules/providers:providers",
    ],
    tests = [
        "//test/com/facebook/buck/core/rules/providers/impl:impl",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//third-party/java/guava:guava",
        "//third-party/java/jsr:jsr305",
    ],
)
