EMPTY_CONFIGS = {
  'Debug': (
    '',
    {},
    '',
    {},
  ),
  'Release': (
    '',
    {},
    '',
    {},
  ),
}

ios_library(
  name = 'Dep2',
  configs = EMPTY_CONFIGS,
  srcs = [],
  frameworks = [],
  deps = [],
  visibility = ['PUBLIC'],
)

ios_test(
  name = 'Dep2Tests',
  configs = EMPTY_CONFIGS,
  srcs = [],
  frameworks = [],
  deps = [
    ':Dep2',
  ],
  source_under_test = [
    ':Dep2',
  ],
)

xcode_project_config(
  name = 'project',
  project_name = 'Libraries',
  rules = [
    ':Dep2',
    ':Dep2Tests',
  ],
)
