java_library(
  name = 'config',
  srcs = [
    'ParserConfig.java',
  ],
  autodeps = True,
  visibility = [
    'PUBLIC',
  ],
)

java_immutables_library(
  name = 'parser',
  srcs = [
    'AbstractBuildFileSpec.java',
    'AbstractBuildTargetSpec.java',
    'AbstractTargetNodePredicateSpec.java',
    'BuildTargetPatternTargetNodeParser.java',
    'ConcurrentMapCache.java',
    'DaemonicParserState.java',
    'MissingBuildFileException.java',
    'ParseEvent.java',
    'ParsePipeline.java',
    'Parser.java',
    'PerBuildState.java',
    'ProjectBuildFileParserPool.java',
    'TargetNodeListener.java',
    'TargetNodeSpec.java',
    'UnexpectedFlavorException.java',
  ],
  immutable_types = [
    'BuildFileSpec',
    'BuildTargetSpec',
    'TargetNodePredicateSpec',
  ],
  tests = [
    '//test/com/facebook/buck/parser:integration',
    '//test/com/facebook/buck/parser:parser',
    '//test/com/facebook/buck/parser:unit',
  ],
  autodeps = True,
  visibility = [
    'PUBLIC',
  ],
)

java_library(
  name = 'rule_pattern',
  srcs = [
    'BuildTargetParser.java',
    'BuildTargetParseException.java',
    'BuildTargetPatternParser.java',
    'NoSuchBuildTargetException.java',
  ],
  tests = [
    '//test/com/facebook/buck/parser:integration',
    '//test/com/facebook/buck/parser:parser',
    '//test/com/facebook/buck/parser:unit',
  ],
  autodeps = True,
  visibility = [
    'PUBLIC',
  ],
)
