java_test(
    name = "model",
    srcs = glob(
        ["*Test.java"],
    ),
    deps = [
        "//src/com/facebook/buck/core/graph/transformation/model:model",
        "//test/com/facebook/buck/core/graph/transformation/impl:testutil",
        "//third-party/java/guava:guava",
        "//third-party/java/junit:junit",
    ],
)
