cxx_library(
  name = 'lib',
  headers = [
    'lib.h',
  ],
  srcs = [
    'lib.cpp',
  ],
  visibility = [
    'PUBLIC',
  ],
)

cxx_library(
  name = 'foo1',
  srcs = [
    'foo.cpp',
  ],
  deps = [
    ':bar',
  ],
  visibility = [
    'PUBLIC',
  ],
)

cxx_library(
  name = 'foo2',
  srcs = [
    'foo.cpp',
  ],
  deps = [
    ':bar',
  ],
  visibility = [
    'PUBLIC',
  ],
)

cxx_library(
  name = 'bar',
  force_static = True,
  exported_headers = [
    'bar.h',
  ],
  srcs = [
    'bar.cpp',
  ],
  visibility = [
    'PUBLIC',
  ],
)

cxx_library(
  name = 'headeronly',
  exported_headers = [
    'bar.h',
  ],
  visibility = [ 'PUBLIC' ],
)

cxx_library(
  name = 'x86-only',
  srcs = ['x86-only.c'],
  supported_platforms_regex = "^android-x86$",
  visibility = [
    'PUBLIC'
  ],
)
