genrule(
  name = 'generate_bnf',
  out = '.',
  cmd = '$(exe //third-party/java/grammar-kit:grammar-kit) $OUT ' \
    'src/com/facebook/buck/intellij/plugin/lang/Buck.bnf $OUT',
  srcs = [
    'src/com/facebook/buck/intellij/plugin/lang/Buck.bnf',
  ],
)

genrule(
  name = 'generate_flex',
  out = '.',
  cmd = '$(exe //third-party/java/grammar-kit:jflex) -sliceandcharat -skel ' \
  'resources/idea-flex.skeleton -d $OUT src/com/facebook/buck/intellij/plugin/lang/Buck.flex',
  srcs = [
    'resources/idea-flex.skeleton',
    'src/com/facebook/buck/intellij/plugin/lang/Buck.flex',
  ],
)

zip_file(
  name = 'generate_zip',
  out = 'generated_bnf.src.zip',
  srcs = [
    ':generate_bnf',
    ':generate_flex',
  ]
)

java_library(
  name = 'bundle_generated_lib',
  provided_deps = [
    '//third-party/java/intellij:intellij-plugin-sdk',
  ],
  srcs = [
    ':generate_zip',
    'src/com/facebook/buck/intellij/plugin/file/BuckFileType.java',
    'src/com/facebook/buck/intellij/plugin/lang/psi/BuckElementType.java',
    'src/com/facebook/buck/intellij/plugin/lang/psi/BuckPsiUtils.java',
    'src/com/facebook/buck/intellij/plugin/lang/psi/BuckTokenType.java',
    'src/com/facebook/buck/intellij/plugin/lang/BuckLanguage.java',
    'src/icons/BuckIcons.java',
  ],
)

java_library(
  name = 'ideabuck-lib',
  srcs = glob([
      'src/**/*.java',
    ],
    excludes = [
      'src/com/facebook/buck/intellij/plugin/file/BuckFileType.java',
      'src/com/facebook/buck/intellij/plugin/lang/psi/*.java',
      'src/com/facebook/buck/intellij/plugin/lang/BuckLanguage.java',
      'src/icons/*.java',
    ]
  ),
  source = '1.6',
  target = '1.6',
  provided_deps = [
    '//third-party/java/intellij:intellij-plugin-sdk',
  ],
  deps = [
    ':bundle_generated_lib',
    '//src/com/facebook/buck/event/external:external_lib',
    '//src/com/facebook/buck/io:executable-finder',
    '//third-party/java/gson:gson',
    '//third-party/java/guava:guava',
    '//third-party/java/jackson:jackson-databind',
    '//third-party/java/jackson:jackson-annotations',
    '//third-party/java/jackson-datatype-guava:jackson-datatype-guava',
    '//third-party/java/jackson:jackson-mrbean',
    '//third-party/java/jetty:jetty',
    '//third-party/java/ddmlib:ddmlib',
  ],
)

java_library(
  name = 'resources',
  srcs = [],
  resources = glob([
      '**/*.png',
  ]),
  resources_root = 'resources/',
  visibility = [
    'PUBLIC',
  ],
)

java_binary(
  name = 'ideabuck',
  meta_inf_directory = 'META-INF',
  deps = [
    ':ideabuck-lib',
    ':resources',
  ],
)
