java_library(
    name = "events",
    srcs = glob([
        "*.java",
    ]),
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/event:interfaces",
        "//src/com/facebook/buck/event/external:external_lib",
        "//src/com/facebook/buck/parser/api:api",
        "//src/com/facebook/buck/parser/exceptions:exceptions",
        "//third-party/java/guava:guava",
    ],
)
