load("//tools/build_rules:java_rules.bzl", "standard_java_test")

standard_java_test(
    name = "firstorder",
    required_for_source_only_abi = True,
    deps = [
        "//src/com/facebook/buck/android/dalvik/firstorder:firstorder",
        "//src/com/facebook/buck/util:util",
        "//src/com/facebook/buck/util/immutables:immutables",
        "//third-party/java/asm:asm",
        "//third-party/java/guava:guava",
        "//third-party/java/immutables:immutables",
        "//third-party/java/jackson:jackson-databind",
        "//third-party/java/jsr:jsr305",
        "//third-party/java/junit:junit",
    ],
)
