load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "attr",
    srcs = glob(
        ["*.java"],
    ),
    visibility = ["PUBLIC"],
    deps = [
        "//third-party/java/guava:guava",
    ],
    exported_deps = [
        "//src/com/facebook/buck/core/cell:cell",
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/core/rules/actions:actions",
        "//src/com/facebook/buck/core/rules/analysis:analysis",
        "//src/com/facebook/buck/core/rules/providers/collect:collect",
        "//src/com/facebook/buck/io/filesystem:filesystem",
        "//src/com/facebook/buck/rules/coercer:interface",
        "//third-party/java/bazel:bazel",
    ],
)
