load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "attr",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/rules/coercer:coercer",
        "//third-party/java/bazel:bazel",
        "//third-party/java/guava:guava",
    ],
)
