java_library(
    name = "workertool",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    deps = [
        "//src-gen:worker-tool-model",
        "//src/com/facebook/buck/core/util/log:log",
        "//src/com/facebook/buck/downwardapi/namedpipes:namedpipes",
        "//src/com/facebook/buck/downwardapi/processexecutor:processexecutor",
        "//src/com/facebook/buck/downwardapi/protocol:protocol",
        "//src/com/facebook/buck/io/namedpipes:namedpipes",
        "//src/com/facebook/buck/util:process_executor",
        "//src/com/facebook/buck/util/environment:environment",
        "//src/com/facebook/buck/workertool/utils:utils",
        "//third-party/java/guava:guava",
    ],
)
