load("//tools/build_rules:java_rules.bzl", "buck_java_library")
buck_java_library(
    name = "workertool",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    deps = [
        "//src-gen:downward-model",
        "//src/com/facebook/buck/event:interfaces",
        "//src/com/facebook/buck/worker:worker_pool",
        "//third-party/java/guava:guava",
    ],
)
