load("//tools/build_rules:java_rules.bzl", "standard_java_test")

standard_java_test(
    name = "rule",
    deps = [
        "//src/com/facebook/buck/core/cell:cell",
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/core/starlark/coercer:coercer",
        "//src/com/facebook/buck/core/starlark/rule:rule",
        "//src/com/facebook/buck/core/starlark/rule/attr:attr",
        "//src/com/facebook/buck/core/starlark/rule/attr/impl:impl",
        "//src/com/facebook/buck/rules/coercer:interface",
        "//src/com/facebook/buck/skylark/function:function",
        "//src/com/facebook/buck/skylark/io:io",
        "//src/com/facebook/buck/skylark/packages:packages",
        "//src/com/facebook/buck/skylark/parser/context:context",
        "//test/com/facebook/buck/core/cell:testutil",
        "//test/com/facebook/buck/skylark/function:testutil",
        "//third-party/java/bazel:bazel",
        "//third-party/java/guava:guava",
        "//third-party/java/jsr:jsr305",
        "//third-party/java/junit:junit",
    ],
)
