load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "api",
    srcs = glob([
        "*.java",
    ]),
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/core/exceptions:exceptions",
        "//src/com/facebook/buck/parser/exceptions:exceptions",
        "//src/com/facebook/buck/skylark/io:io",
        "//third-party/java/guava:guava",
    ],
)
