java_library(
    name = "api",
    srcs = glob([
        "*.java",
    ]),
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/core/exceptions:exceptions",
        "//src/com/facebook/buck/parser/exceptions:exceptions",
        "//third-party/java/guava:guava",
    ],
)
