java_library(
    name = "downloader",
    srcs = [
        "AuthAwareDownloader.java",
        "DownloadEvent.java",
        "DownloadProgressEvent.java",
        "Downloader.java",
        "ExplodingDownloader.java",
        "HttpDownloader.java",
        "MavenUrlDecoder.java",
        "OnDiskMavenDownloader.java",
        "RemoteMavenDownloader.java",
        "RetryingDownloader.java",
        "StackedDownloader.java",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/cli:config",
        "//src/com/facebook/buck/event:interfaces",
        "//src/com/facebook/buck/event/external:external_lib",
        "//src/com/facebook/buck/log:api",
        "//src/com/facebook/buck/util:exceptions",
        "//third-party/java/guava:guava",
    ],
)

java_immutables_library(
    name = "file",
    srcs = [
        "DownloadStep.java",
        "RemoteFile.java",
        "RemoteFileBinary.java",
        "RemoteFileDescription.java",
    ],
    visibility = [
        "//src/com/facebook/buck/cli:cli",
        "//src/com/facebook/buck/rules:types",
        "//test/com/facebook/buck/file:",
        "//test/com/facebook/buck/maven:maven",
    ],
    deps = [
        ":downloader",
        "//src/com/facebook/buck/event:event",
        "//src/com/facebook/buck/event:interfaces",
        "//src/com/facebook/buck/event/external:external_lib",
        "//src/com/facebook/buck/io:io",
        "//src/com/facebook/buck/model:model",
        "//src/com/facebook/buck/parser:rule_pattern",
        "//src/com/facebook/buck/rules:build_rule",
        "//src/com/facebook/buck/rules:command_tool",
        "//src/com/facebook/buck/rules:interfaces",
        "//src/com/facebook/buck/rules:source_path",
        "//src/com/facebook/buck/rules/args:args",
        "//src/com/facebook/buck/step:step",
        "//src/com/facebook/buck/step/fs:fs",
        "//src/com/facebook/buck/util:exceptions",
        "//src/com/facebook/buck/util:process_executor",
        "//src/com/facebook/buck/zip:steps",
        "//third-party/java/guava:guava",
        "//third-party/java/infer-annotations:infer-annotations",
    ],
)

java_library(
    name = "rules",
    srcs = [
        "WriteFile.java",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/io:io",
        "//src/com/facebook/buck/model:model",
        "//src/com/facebook/buck/rules:build_rule",
        "//src/com/facebook/buck/rules:source_path",
        "//src/com/facebook/buck/step:step",
        "//src/com/facebook/buck/step/fs:fs",
        "//third-party/java/guava:guava",
    ],
)
