load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "impl",
    srcs = glob(
        ["*.java"],
    ),
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/core/artifact/converter:converter",
        "//src/com/facebook/buck/core/sourcepath/resolver/impl:impl",
        "//src/com/facebook/buck/io/file:file",
        "//src/com/facebook/buck/step/fs:fs",
        "//src/com/facebook/buck/step/impl:impl",
        "//src/com/facebook/buck/util:util",
        "//src/com/facebook/buck/util/stream:stream",
        "//third-party/java/guava:guava",
    ],
    exported_deps = [
        "//src/com/facebook/buck/core/description:description",
        "//src/com/facebook/buck/core/rules:rules",
        "//src/com/facebook/buck/core/rules/attr:attr",
    ],
)
