load("//tools/build_rules:java_rules.bzl", "java_library_with_plugins")

java_library_with_plugins(
    name = "platform",
    srcs = glob(["*.java"]),
    tests = [
        "//src/com/facebook/buck/core/rules/platform:platform",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/core/model/impl:impl",
        "//src/com/facebook/buck/core/model/platform/impl:impl",
    ],
    exported_deps = [
        "//src/com/facebook/buck/core/model/platform:platform",
        "//src/com/facebook/buck/core/rules/attr:attr",
        "//src/com/facebook/buck/core/rules/config:config",
    ],
)
