load("//tools/build_rules:java_rules.bzl", "standard_java_test")

standard_java_test(
    name = "android",
    deps = [
        "//src-gen:buildable-command-model",
        "//src/com/facebook/buck/external/model:model",
        "//src/com/facebook/buck/externalactions/android:android_external_actions",
        "//src/com/facebook/buck/step/isolatedsteps:isolatedsteps",
        "//src/com/facebook/buck/step/isolatedsteps/android:android_steps",
        "//src/com/facebook/buck/step/isolatedsteps/common:common",
        "//src/com/facebook/buck/util/json:json",
        "//test/com/facebook/buck/io/filesystem/impl:testutil",
        "//test/com/facebook/buck/step:testutil",
        "//third-party/java/guava:guava",
        "//third-party/java/junit:junit",
    ],
)
