load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "args",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    exported_deps = [
        "//src/com/facebook/buck/core/artifact:artifact",
    ],
)
