java_library(
    name = "context",
    srcs = glob(["*.java"]),
    visibility = [
        "//src/com/facebook/buck/downwardapi/processexecutor/...",
        "//src/com/facebook/buck/util:process_executor",
        "//src/com/facebook/buck/workertool/impl:impl",
        "//test/com/facebook/buck/downwardapi/processexecutor/...",
    ],
    deps = [
        "//src/com/facebook/buck/event:interfaces",
        "//src/com/facebook/buck/util:util",
        "//src/com/facebook/buck/util/timing:timing",
    ],
)
