load("//tools/build_rules:java_rules.bzl", "buck_java_library")
buck_java_library(
    name = "context",
    srcs = glob(["*.java"]),
    tests = ["//test/com/facebook/buck/downwardapi/processexecutor/context:context"],
    visibility = [
        "//src/com/facebook/buck/downwardapi/processexecutor/...",
        "//src/com/facebook/buck/util:process_executor",
        "//src/com/facebook/buck/workertool/impl:impl",
        "//test/com/facebook/buck/downwardapi/processexecutor/...",
    ],
    deps = [
        "//src/com/facebook/buck/core/util/log:log",
        "//src/com/facebook/buck/event:interfaces",
        "//src/com/facebook/buck/util/timing:timing",
        "//third-party/java/jsr:jsr305",
    ],
)
