java_library(
    name = "impl",
    srcs = glob(["*.java"]),
    exported_deps = [
        "//src/com/facebook/buck/core/rules/type:type",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/util:util",
    ],
)
