load("//tools/build_rules:java_rules.bzl", "java_test")

java_test(
    name = "impl",
    srcs = glob(
        ["*Test.java"],
    ),
    has_immutable_types = True,
    deps = [
        "//src/com/facebook/buck/core/rules/providers/collect/impl:impl",
        "//src/com/facebook/buck/core/rules/providers/impl:impl",
        "//src/com/facebook/buck/core/rules/providers/lib:lib",
        "//src/com/facebook/buck/parser:parser",
        "//src/com/facebook/buck/skylark/function:function",
        "//test/com/facebook/buck/core/model:testutil",
        "//test/com/facebook/buck/core/rules/analysis/impl:testutil",
        "//test/com/facebook/buck/core/starlark/compatible:testutil",
        "//third-party/java/guava:guava",
        "//third-party/java/junit:junit",
    ],
)
