EMPTY_CONFIGS = {
  'Debug': {},
  'Release': {},
}

apple_binary(
  name = 'TestAppBinary',
  configs = EMPTY_CONFIGS,
)

apple_test(
  name = 'TestAppTests',
  extension = 'octest',
  configs = EMPTY_CONFIGS,
  info_plist = 'Test.plist',
)

xcode_workspace_config(
  name = 'workspace',
  src_target = ':TestAppBinary',
  extra_tests = [':TestAppTests'],
)
