load("//tools/build_rules:java_rules.bzl", "java_library_with_plugins")

java_library_with_plugins(
    name = "impl",
    srcs = glob(["*.java"]),
    exported_deps = [
        "//src/com/facebook/buck/features/python:python",
        "//src/com/facebook/buck/features/python/toolchain:toolchain",
    ],
    exported_provided_deps = [
        "//src/com/facebook/buck/util:process_executor",
    ],
    provided_deps = [
        "//src/com/facebook/buck/core/toolchain/tool/impl:impl",
        "//src/com/facebook/buck/rules:rules",
        "//src/com/facebook/buck/rules/args:args",
        "//src/com/facebook/buck/rules/keys:keys",
        "//src/com/facebook/buck/util:exceptions",
    ],
    tests = [
        "//test/com/facebook/buck/features/python/toolchain/impl:impl",
    ],
    visibility = ["PUBLIC"],
)
