load("//tools/build_rules:java_rules.bzl", "standard_java_test")

java_library(
    name = "test_extension",
    srcs = [
        "TestExtension.java",
    ],
    visibility = [
        "//test/com/facebook/buck/core/module/impl/...",
    ],
    deps = [
        "//third-party/java/pf4j:pf4j",
    ],
)

standard_java_test(
    name = "impl",
    deps = [
        "//src/com/facebook/buck/core/module/impl:impl",
        "//third-party/java/junit:junit",
    ],
)

export_file(
    name = "test_app.py",
    visibility = [
        "//test/com/facebook/buck/core/module/impl/...",
    ],
)
