load("//tools/build_rules:java_rules.bzl", "standard_java_test")

java_library(
    name = "testutil",
    srcs = glob(
        ["*.java"],
        exclude = ["*Test.java"],
    ),
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/io/filesystem/skylark:skylark",
        "//src/com/facebook/buck/rules/coercer:coercer",
        "//src/com/facebook/buck/skylark/function:function",
        "//src/com/facebook/buck/skylark/io/impl:impl",
        "//test/com/facebook/buck/core/rules/knowntypes:testutil",
        "//test/com/facebook/buck/event:testutil",
    ],
    exported_deps = [
        "//src/com/facebook/buck/parser:parser",
        "//src/com/facebook/buck/parser/options:options",
        "//src/com/facebook/buck/skylark/function:function",
        "//src/com/facebook/buck/skylark/parser:parser",
    ],
)

standard_java_test(
    name = "parser",
    deps = [
        ":testutil",
        "//src/com/facebook/buck/features/dotnet:dotnet",
        "//src/com/facebook/buck/io/file:file",
        "//src/com/facebook/buck/io/filesystem/skylark:skylark",
        "//src/com/facebook/buck/jvm/java/rules:rules",
        "//src/com/facebook/buck/rules/coercer:coercer",
        "//src/com/facebook/buck/skylark/function:function",
        "//src/com/facebook/buck/skylark/io/impl:impl",
        "//test/com/facebook/buck/core/cell:testutil",
        "//test/com/facebook/buck/core/rules/knowntypes:testutil",
        "//test/com/facebook/buck/core/toolchain/impl:testutil",
        "//test/com/facebook/buck/event:testutil",
        "//test/com/facebook/buck/sandbox:testutil",
        "//test/com/facebook/buck/testutil/integration:util",
        "//third-party/java/guava:guava",
        "//third-party/java/junit:junit",
    ],
)
