java_library(
    name = "impl",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/core/config:config",
        "//src/com/facebook/buck/sandbox:sandbox",
        "//src/com/facebook/buck/sandbox/darwin:darwin",
        "//src/com/facebook/buck/util:util",
        "//src/com/facebook/buck/util/environment:platform",
    ],
)
