load("//tools/build_rules:java_rules.bzl", "buck_java_library")
buck_java_library(
    name = "downloader",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    deps = [
    ],
    exported_deps = [
        "//src/com/facebook/buck/core/toolchain:toolchain",
        "//src/com/facebook/buck/event:interfaces",
    ],
)
