java_library(
    name = "factory",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/event:interfaces",
        "//src/com/facebook/buck/remoteexecution/config:config",
        "//src/com/facebook/buck/remoteexecution/grpc:grpc",
        "//src/com/facebook/buck/remoteexecution/thrift:thrift",
        "//src/com/facebook/buck/remoteexecution/util:util",
        "//src/com/facebook/buck/rules/modern/config:config",
    ],
)
