load("//tools/build_rules:java_rules.bzl", "buck_java_library")
buck_java_library(
    name = "factory",
    srcs = glob(["*.java"]),
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/core/exceptions:exceptions",
        "//src/com/facebook/buck/event:interfaces",
        "//src/com/facebook/buck/log:log",
        "//src/com/facebook/buck/remoteexecution/config:config",
        "//src/com/facebook/buck/remoteexecution/grpc:grpc",
        "//src/com/facebook/buck/remoteexecution/util:util",
        "//src/com/facebook/buck/rules/modern/config:config",
    ],
)
