load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "analysis",
    srcs = glob(["*.java"]),
    exported_deps = [
        "//src/com/facebook/buck/core/graph/transformation:transformation",
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/core/rules/actions:actions",
        "//src/com/facebook/buck/core/rules/providers:providers",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//third-party/java/guava:guava",
    ],
)
