java_library(
    name = "apk",
    srcs = glob(["*.java"]),
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/core/exceptions:exceptions",
        "//third-party/java/aosp:aosp",
        "//third-party/java/android:sdklib",
        "//third-party/java/guava:guava",
    ],
)

java_binary(
    name = "apk_builder_binary",
    main_class = "com.facebook.buck.android.apk.ApkBuilderExecutableMain",
    deps = [
        ":apk",
    ],
)
