load("//tools/build_rules:java_rules.bzl", "java_test")

java_test(
    name = "config",
    srcs = glob(["*.java"]),
    target = "1.8",
    deps = [
        "//third-party/java/easymock:easymock",
        "//third-party/java/guava:guava",
        "//third-party/java/guava:guava-testlib",
        "//third-party/java/intellij:intellij-plugin-sdk",
        "//third-party/java/junit:junit",
        "//tools/ideabuck:ideabuck-lib",
    ],
)
