apple_test(
    name='foo',
    extension='xctest',
    srcs = ['Foo.m'],
    info_plist = 'Test.plist',
    frameworks = [
        '$PLATFORM_DIR/Developer/Library/Frameworks/XCTest.framework',
        '$SDKROOT/System/Library/Frameworks/Foundation.framework',
    ]
)
