TYPE_COERCER_SRCS = [
  'CoerceFailedException.java',
  'TypeCoercer.java',
  'TypeCoercerFactory.java',
]

TYPES_SRCS = [
  'AbstractBuildConfigFields.java',
  'AbstractFrameworkPath.java',
  'AbstractManifestEntries.java',
  'AbstractOcamlSource.java',
  'AbstractSourceList.java',
  'AbstractSourceWithFlagsList.java',
]

java_immutables_library(
  name = 'types',
  srcs = TYPES_SRCS,
  immutable_types = [
    'BuildConfigFields',
    'FrameworkPath',
    'ManifestEntries',
    'OcamlSource',
    'SourceList',
    'SourceWithFlagsList',
  ],
  autodeps = True,
  visibility = ['PUBLIC'],
)

java_library(
  name = 'type_coercer',
  srcs = TYPE_COERCER_SRCS,
  autodeps = True,
  visibility = ['PUBLIC'],
)

java_library(
  name = 'coercer',
  srcs = glob(['*.java'], excludes = TYPE_COERCER_SRCS + TYPES_SRCS),
  autodeps = True,
  visibility = ['PUBLIC'],
)
