TYPES_SRCS = [
  'CoerceFailedException.java',
  'TypeCoercer.java',
  'TypeCoercerFactory.java',
]

java_library(
  name = 'types',
  srcs = TYPES_SRCS,
  autodeps = True,
  visibility = ['PUBLIC'],
)

java_immutables_library(
  name = 'coercer',
  srcs = glob(['*.java'], excludes = TYPES_SRCS),
  immutable_types = [
    'BuildConfigFields',
    'FrameworkPath',
    'ManifestEntries',
    'OCamlSource',
    'SourceList',
    'SourceWithFlagsList',
  ],
  autodeps = True,
  visibility = ['PUBLIC'],
)
