kotlin_library(
    name = "testutil",
    srcs = glob(
        ["*.kt"],
        exclude = ["*Test.kt"],
    ),
    deps = [
        "//src/com/facebook/buck/core/sourcepath:types",
    ],
)

kotlin_test(
    name = "query",
    srcs = glob(["*Test.kt"]),
    friend_paths = [
        "//src/com/facebook/buck/multitenant/query:query",
    ],
    resources = glob(["*.json"]),
    deps = [
        ":testutil",
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/core/model/targetgraph/raw:raw",
        "//src/com/facebook/buck/core/sourcepath:types",
        "//src/com/facebook/buck/multitenant/fs:fs",
        "//src/com/facebook/buck/multitenant/importer:RuleTypeFactory",
        "//src/com/facebook/buck/multitenant/importer:importer",
        "//src/com/facebook/buck/multitenant/query:query",
        "//src/com/facebook/buck/multitenant/service:service",
        "//src/com/facebook/buck/query:query",
        "//third-party/java/guava:guava",
        "//third-party/java/junit:junit",
    ],
)
