# These are separate from the rest of the tests so we can run
# them separately, avoiding the 20 second timeout in the iOS simulator.
STANDARD_TEST_SRCS = [
    "*Test.java",
]

STANDARD_INTEGRATION_TEST_SRCS = [
    "*IntegrationTest.java",
]

java_test(
    name = "unit",
    srcs = glob(
        STANDARD_TEST_SRCS,
        excludes = STANDARD_INTEGRATION_TEST_SRCS,
    ),
    autodeps = True,
    deps = [
        "//src/com/facebook/buck/cxx:rules",
        "//src/com/facebook/buck/model:model",
        "//src/com/facebook/buck/rules:build_rule",
        "//src/com/facebook/buck/swift:swift",
        "//test/com/facebook/buck/apple:testutil",
        "//test/com/facebook/buck/cli:FakeBuckConfig",
        "//test/com/facebook/buck/model:testutil",
        "//test/com/facebook/buck/rules:testutil",
        "//third-party/java/guava:guava",
        "//third-party/java/hamcrest:java-hamcrest",
        "//third-party/java/junit:junit",
    ],
)

java_test(
    name = "integration",
    srcs = glob(STANDARD_INTEGRATION_TEST_SRCS),
    autodeps = True,
    labels = ["long_running"],
    resources = glob(["testdata/**"]),
    run_test_separately = True,
    deps = [
        "//src/com/facebook/buck/apple:platform",
        "//src/com/facebook/buck/apple:rules",
        "//src/com/facebook/buck/cxx:rules",
        "//src/com/facebook/buck/io:io",
        "//src/com/facebook/buck/model:model",
        "//src/com/facebook/buck/parser:rule_pattern",
        "//src/com/facebook/buck/rules:build_rule",
        "//src/com/facebook/buck/rules/args:args",
        "//src/com/facebook/buck/swift:platform",
        "//src/com/facebook/buck/swift:swift",
        "//src/com/facebook/buck/util/environment:platform",
        "//test/com/facebook/buck/apple:testutil",
        "//test/com/facebook/buck/cxx:testutil",
        "//test/com/facebook/buck/model:testutil",
        "//test/com/facebook/buck/rules:testutil",
        "//test/com/facebook/buck/testutil:testutil",
        "//test/com/facebook/buck/testutil/integration:util",
        "//third-party/java/guava:guava",
        "//third-party/java/hamcrest:java-hamcrest",
        "//third-party/java/junit:junit",
    ],
)
