# These are separate from the rest of the tests so we can run
# them separately, avoiding the 20 second timeout in the iOS simulator.
java_test(
  name = 'swift_test_integration',
  run_test_separately = True,
  srcs = glob(['*IntegrationTest.java']),
  resources = glob(['testdata/**']),
  deps = [
    '//src/com/facebook/buck/apple:platform',
    '//src/com/facebook/buck/apple:rules',
    '//src/com/facebook/buck/swift:rules',
    '//src/com/facebook/buck/model:model',
    '//src/com/facebook/buck/util:constants',
    '//src/com/facebook/buck/util:exceptions',
    '//src/com/facebook/buck/util:io',
    '//src/com/facebook/buck/util/environment:platform',
    '//test/com/facebook/buck/apple:testutil',
    '//test/com/facebook/buck/model:BuildTargetFactory',
    '//test/com/facebook/buck/testutil:testutil',
    '//test/com/facebook/buck/testutil/integration:integration',
    '//third-party/java/guava:guava',
    '//third-party/java/hamcrest:hamcrest',
    '//third-party/java/infer-annotations:infer-annotations',
    '//third-party/java/jackson:jackson',
    '//third-party/java/jsr:jsr305',
    '//third-party/java/junit:junit',
  ]
)
