load("//tools/build_rules:java_rules.bzl", "standard_java_test")

standard_java_test(
    name = "isolated",
    deps = [
        "//src-gen:downward-model",
        "//src/com/facebook/buck/core/util/log:log",
        "//src/com/facebook/buck/downwardapi/protocol:protocol",
        "//src/com/facebook/buck/downwardapi/utils:utils",
        "//src/com/facebook/buck/event:event",
        "//src/com/facebook/buck/event/isolated:isolated",
        "//test/com/facebook/buck/downwardapi/testutil:testutil",
        "//test/com/facebook/buck/event:testutil",
        "//test/com/facebook/buck/testutil:testutil",
        "//test/com/facebook/buck/testutil/integration:util",
        "//test/com/facebook/buck/util/timing:testutil",
        "//third-party/java/junit:junit",
    ],
)
