load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "toolchain",
    srcs = glob(["*.java"]),
    exported_deps = [
        "//src/com/facebook/buck/android/toolchain/ndk:ndk",
        "//src/com/facebook/buck/cxx/toolchain:toolchain",
        "//src/com/facebook/buck/toolchain:toolchain",
    ],
    tests = [
        "//test/com/facebook/buck/android/toolchain/impl:impl",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/core/rules/impl:impl",
        "//third-party/java/guava:guava",
    ],
)
