java_immutables_library(
    name = "toolchain",
    srcs = glob(["*.java"]),
    exported_deps = [
        "//src/com/facebook/buck/toolchain:toolchain",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/cxx/toolchain:toolchain",
        "//src/com/facebook/buck/rules:build_rule",
        "//third-party/java/guava:guava",
    ],
)
