load("//tools/build_rules:java_rules.bzl", "java_library_with_plugins")

java_library_with_plugins(
    name = "moduleinfo",
    srcs = glob(
        ["*.java"],
        exclude = [
            "LookupTool.java",
            "UpdateBinaryIndexFromIMLListTool.java",
        ],
    ),
    provided_deps = ["//third-party/java/guava:guava"],
    source = "8",
    target = "8",
    tests = [
        "//test/com/facebook/buck/features/project/intellij/moduleinfo:moduleinfo",
    ],
    visibility = ["PUBLIC"],
)

java_library_with_plugins(
    name = "lookuptool-lib",
    srcs = ["LookupTool.java"],
    deps = [
        ":moduleinfo",
    ],
)

java_binary(
    name = "lookuptool",
    main_class = "com.facebook.buck.features.project.intellij.moduleinfo.LookupTool",
    deps = [
        ":lookuptool-lib",
        "//third-party/java/guava:guava",
    ],
)

java_library_with_plugins(
    name = "updatetool-lib",
    srcs = ["UpdateTool.java"],
    deps = [
        ":moduleinfo",
    ],
)

java_binary(
    name = "updatetool",
    main_class = "com.facebook.buck.features.project.intellij.moduleinfo.UpdateTool",
    deps = [
        ":updatetool-lib",
        "//third-party/java/guava:guava",
    ],
)
