java_binary(
  name = 'bin-fat',
  main_class = 'Lib',
  deps = [
    ':lib',
  ],
)

java_library(
  name = 'lib',
  srcs = [
    'Lib.java',
  ],
  deps = [
    ':native',
  ],
)

cxx_library(
  name = 'native',
  srcs = [
    'Native.cpp',
  ],
  deps = [
    ':dep',
  ],
)

cxx_library(
  name = 'dep',
  srcs = [
    'Dep.cpp',
  ],
  exported_headers = [
    'Dep.h',
  ],
)

java_binary(
  name = 'bin-output',
  main_class = 'LibOutput',
  deps = [
    ':lib-output',
  ],
)

java_library(
  name = 'lib-output',
  srcs = [
    'LibOutput.java',
  ],
)

java_binary(
  name = 'bin-exit-code',
  main_class = 'LibExitCode',
  deps = [
    ':lib-exit-code',
  ],
)

java_library(
  name = 'lib-exit-code',
  srcs = [
    'LibExitCode.java',
  ],
)
