load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "impl",
    srcs = glob(["*.java"]),
    exported_deps = [
        "//src/com/facebook/buck/core/graph/transformation:transformation",
        "//src/com/facebook/buck/core/model/targetgraph:targetgraph",
        "//src/com/facebook/buck/core/model/targetgraph/raw:raw",
        "//src/com/facebook/buck/core/rules/analysis:analysis",
        "//src/com/facebook/buck/core/rules/analysis/cache:cache",
        "//src/com/facebook/buck/core/rules/analysis/computation:computation",
    ],
    tests = [
        "//test/com/facebook/buck/core/rules/analysis/impl:impl",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/core/graph/transformation/executor:executor",
        "//third-party/java/guava:guava",
    ],
)
