java_library(
    name = "testutil",
    srcs = glob(
        ["*.java"],
        excludes = ["*Test.java"],
    ),
    visibility = ["//test/..."],
    deps = [
        "//src-gen:thrift",
        "//src/com/facebook/buck/distributed:common",
        "//src/com/facebook/buck/distributed:distributed",
        "//src/com/facebook/buck/distributed/build_client:build_client",
        "//src/com/facebook/buck/distributed/build_slave:build_slave",
        "//src/com/facebook/buck/io:io",
        "//test/com/facebook/buck/testutil:testutil",
        "//third-party/java/guava:guava",
    ],
)
