standard_java_library(
    name = "hashing",
    tests = [
        "//test/com/facebook/buck/hashing:hashing",
    ],
    deps = [
        "//src/com/facebook/buck/io:MorePaths.java",
        "//src/com/facebook/buck/io:io",
        "//third-party/java/guava:guava",
    ],
)
