java_library(
    name = "hashing",
    srcs = glob(["*.java"]),
    tests = [
        "//test/com/facebook/buck/hashing:hashing",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/io:io",
        "//src/com/facebook/buck/io:more-paths",
        "//third-party/java/guava:guava",
    ],
)
