java_library(
  name = 'hashing',
  srcs = glob(['*.java']),
  tests = [
    '//test/com/facebook/buck/hashing:hashing',
  ],
  deps = [
    '//third-party/java/guava:guava',
    '//src/com/facebook/buck/io:io',
  ],
  visibility = [
    'PUBLIC',
  ],
)
