load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "knowntypes",
    srcs = glob(["*.java"]),
    exported_deps = [
        "//src/com/facebook/buck/core/cell:cell",
        "//src/com/facebook/buck/core/model/targetgraph:targetgraph",
        "//src/com/facebook/buck/core/rules/config:config",
    ],
    tests = [
        "//test/com/facebook/buck/core/rules/knowntypes:knowntypes",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/core/description/impl:impl",
    ],
)
