standard_java_library(
    name = "memory",
    deps = [
        "//src/com/facebook/buck/log:api",
        "//src/com/facebook/buck/log:log",
        "//src/com/facebook/buck/util:object_mapper",
        "//src/com/facebook/buck/util/network:network",
        "//third-party/java/guava:guava",
        "//third-party/java/jackson:jackson-databind",
    ],
)
