java_library(
    name = "memory",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/log:api",
        "//src/com/facebook/buck/log:log",
        "//src/com/facebook/buck/slb:slb",
        "//src/com/facebook/buck/util:util",
        "//src/com/facebook/buck/util/network:network",
        "//third-party/java/guava:guava",
        "//third-party/java/jackson:jackson-databind",
    ],
)
