java_library(
    name = "impl",
    srcs = glob(
        ["*.java"],
    ),
    exported_deps = [
        "//src/com/facebook/buck/core/cell:cell",
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/core/rules/impl:impl",
        "//src/com/facebook/buck/core/rules/transformer:transformer",
        "//src/com/facebook/buck/util/types:types",
    ],
    tests = [
        "//test/com/facebook/buck/core/rules/resolver/impl:impl",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/core/rules:rules",
        "//src/com/facebook/buck/util:util",
        "//src/com/facebook/buck/util/concurrent:concurrent",
        "//src/com/facebook/buck/util/types:types",
        "//src/com/facebook/buck/versions:types",
        "//third-party/java/jsr:jsr305",
    ],
)
