java_library(
  name = 'rules',
  srcs = [
    'GroovyBuckConfig.java',
    'GroovyLibraryDescription.java',
    'GroovycToJarStepFactory.java',
    'GroovyTestDescription.java',
    'GroovycStep.java',
  ],
  tests = [
    '//test/com/facebook/buck/jvm/groovy:groovy',
  ],
  autodeps = True,
  visibility = ['PUBLIC'],
)
