java_library(
    name = "types",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    deps = [
        "//third-party/java/guava:guava",
        "//third-party/java/jackson:jackson-annotations",
        "//third-party/java/jsr:jsr305",
    ],
)
