java_library(
    name = "randomizedtrial",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/core/util/log:log",
        "//src/com/facebook/buck/util:util",
        "//third-party/java/guava:guava",
    ],
)
