java_immutables_library(
  name = 'autosparse',
  srcs = glob(['*.java']),
  autodeps = True,
  immutable_types = [
    'ManifestInfo',
  ],
  tests = [
    '//test/com/facebook/buck/util/autosparse:autosparse',
  ],
  visibility = [
    'PUBLIC',
  ],
)
