CONFIG_SRCS = [
    "AbstractAutoSparseConfig.java",
]

java_immutables_library(
    name = "autosparse_config",
    srcs = CONFIG_SRCS,
    autodeps = True,
    exported_deps = [
        "//src/com/facebook/buck/config:config",
        "//src/com/facebook/buck/util/immutables:immutables",
    ],
    immutable_types = [
        "AutoSparseConfig",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//third-party/java/guava:guava",
        "//third-party/java/immutables:immutables",
    ],
)

java_immutables_library(
    name = "autosparse",
    srcs = glob(
        ["*.java"],
        excludes = CONFIG_SRCS,
    ),
    autodeps = True,
    exported_deps = [
        "//src/com/facebook/buck/event:interfaces",
        "//src/com/facebook/buck/io:ProjectFilesystemDelegate",
        "//src/com/facebook/buck/util/autosparse:autosparse_config",
        "//src/com/facebook/buck/util/immutables:immutables",
        "//src/com/facebook/buck/util/sha1:sha1",
        "//src/com/facebook/buck/util/versioncontrol:versioncontrol_hg",
        "//third-party/java/guava:guava",
        "//third-party/java/jsr:jsr305",
    ],
    immutable_types = [
        "ManifestInfo",
    ],
    tests = [
        "//test/com/facebook/buck/util/autosparse:autosparse",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/io:DefaultProjectFilesystemDelegate",
        "//src/com/facebook/buck/log:api",
        "//src/com/facebook/buck/log/views:views",
        "//src/com/facebook/buck/util:exceptions",
        "//src/com/facebook/buck/util/versioncontrol:versioncontrol",
        "//third-party/java/immutables:immutables",
        "//third-party/java/jackson:jackson-annotations",
    ],
)
