java_test(
  name = 'parser',
  srcs = glob(['*Test.java']),
  source_under_test = [
    '//src/com/facebook/buck/parser:parser',
    '//src/com/facebook/buck/parser:support',
  ],
  deps = [
    ':NonCheckingBuildRuleFactoryParams',
    '//lib:easymock',
    '//lib:guava',
    '//lib:junit',
    '//lib:jyson',
    '//lib:jython',
    '//src/com/facebook/buck/event:event',
    '//src/com/facebook/buck/graph:graph',
    '//src/com/facebook/buck/java:rules',
    '//src/com/facebook/buck/json:json',
    '//src/com/facebook/buck/model:model',
    '//src/com/facebook/buck/parser:support',
    '//src/com/facebook/buck/parser:parser',
    '//src/com/facebook/buck/parser:events',
    '//src/com/facebook/buck/parser:project',
    '//src/com/facebook/buck/rules:rules',
    '//src/com/facebook/buck/rules:types',
    '//src/com/facebook/buck/util:constants',
    '//src/com/facebook/buck/util:exceptions',
    '//src/com/facebook/buck/util:io',
    '//src/com/facebook/buck/util:util',
    '//test/com/facebook/buck/model:BuildTargetFactory',
    '//test/com/facebook/buck/event:testutil',
    '//test/com/facebook/buck/rules:testutil',
    '//test/com/facebook/buck/testutil:testutil',
    '//test/com/facebook/buck/timing:testutil',
  ],
)

java_library(
  name = 'PartialGraphFactory',
  srcs = [
    'PartialGraphFactory.java',
  ],
  deps = [
    '//lib:guava',
    '//src/com/facebook/buck/graph:graph',
    '//src/com/facebook/buck/model:model',
    '//src/com/facebook/buck/parser:parser',
    '//src/com/facebook/buck/rules:rules',
  ],
  visibility = [
    '//test/com/facebook/buck/cli:cli',
    '//test/com/facebook/buck/command:command',
  ],
)

java_library(
  name = 'NonCheckingBuildRuleFactoryParams',
  srcs = [
    'NonCheckingBuildRuleFactoryParams.java',
  ],
  deps = [
    '//lib:guava',
    '//src/com/facebook/buck/model:model',
    '//src/com/facebook/buck/parser:support',
    '//src/com/facebook/buck/rules:rules',
    '//src/com/facebook/buck/util:io',
    '//src/com/facebook/buck/util:util',
    '//test/com/facebook/buck/testutil:testutil',
  ],
  visibility = [
    '//test/...',
  ],
)
