# This test is huge, so we run it by itself.
PARSER_TEST_SRCS = [
  'ParserTest.java',
]
java_test(
  name = 'parser',
  srcs = PARSER_TEST_SRCS,
  autodeps = True,
)

java_test(
  name = 'unit',
  srcs = glob(
    ['*Test.java'],
    excludes=PARSER_TEST_SRCS + ['*IntegrationTest.java']),
  autodeps = True,
)

java_test(
  name = 'integration',
  srcs = glob(['*IntegrationTest.java']),
  resources = glob(['testdata/**'], include_dotfiles=True),
  autodeps = True,
)

java_test(
  name = 'benchmark_correctness',
  autodeps = True,
)

java_library(
  name = 'benchmarks',
  srcs = glob(['*Benchmark.java']),
  autodeps = True,
  visibility = [
    '//test/com/facebook/buck/benchmarks/...',
  ],
)
