java_test(
  name = 'parser',
  srcs = glob(['*Test.java']),
  source_under_test = [
    '//src/com/facebook/buck/parser:parser',
  ],
  deps = [
    ':NonCheckingBuildRuleFactoryParams',
    '//lib:easymock',
    '//lib:junit',
    '//lib:jyson',
    '//lib:jython',
    '//src/com/facebook/buck/parser:parser',
    '//test/com/facebook/buck/model:BuildTargetFactory',
    '//test/com/facebook/buck/rules:testutil',
  ],
)

java_library(
  name = 'PartialGraphFactory',
  srcs = [
    'PartialGraphFactory.java',
  ],
  deps = [
    '//src/com/facebook/buck/parser:parser',
  ],
  visibility = [
    '//test/com/facebook/buck/cli:cli',
    '//test/com/facebook/buck/command:command',
  ],
)

java_library(
  name = 'NonCheckingBuildRuleFactoryParams',
  srcs = [
    'NonCheckingBuildRuleFactoryParams.java',
  ],
  deps = [
    '//src/com/facebook/buck/parser:parser',
  ],
  visibility = [
    '//test/com/facebook/buck/rules:rules',
  ],
)
