standard_java_testutil(
    name = "testutil",
)

standard_java_test(
    name = "log",
    deps = [
        "//src/com/facebook/buck/io:io",
        "//src/com/facebook/buck/log:log",
        "//test/com/facebook/buck/testutil:testutil",
        "//test/com/facebook/buck/testutil/integration:util",
        "//third-party/java/easymock:easymock",
        "//third-party/java/hamcrest:java-hamcrest",
        "//third-party/java/junit:junit",
    ],
)

python_test(
    name = "log_rotation_integration_test",
    srcs = ["test_log_rotation.py"],
    deps = [
        "//test/com/facebook/buck/testutil/integration:integration-py",
    ],
)
