load("//tools/build_rules:java_rules.bzl",  "buck_java_library")

buck_java_library(
    name = "options_handler",
    srcs = glob(["*.java"]),
    exported_deps = ["//third-party/java/args4j:args4j"],
    visibility = [
        "PUBLIC",
    ],
)

