java_library(
  name = 'testutil',
  srcs = [
    'FakeStep.java',
    'TestExecutionContext.java',
  ],
  deps = [
    '//src/com/facebook/buck/event:event',
    '//src/com/facebook/buck/io:io',
    '//src/com/facebook/buck/model:model',
    '//src/com/facebook/buck/step:step',
    '//src/com/facebook/buck/util:io',
    '//src/com/facebook/buck/util:util',
    '//src/com/facebook/buck/util/environment:platform',
    '//test/com/facebook/buck/event:testutil',
    '//test/com/facebook/buck/java:fakepackagefinder',
    '//test/com/facebook/buck/testutil:testutil',
    '//third-party/java/guava:guava',
    '//third-party/java/jackson:jackson',
  ],
  visibility = [
    '//test/...',
  ],
)


java_test(
  name = 'step',
  srcs = glob(['*Test.java']),
  source_under_test = [
    '//src/com/facebook/buck/step:step',
  ],
  deps = [
    ':testutil',
    '//src/com/facebook/buck/event:event',
    '//src/com/facebook/buck/io:io',
    '//src/com/facebook/buck/model:model',
    '//src/com/facebook/buck/step:step',
    '//src/com/facebook/buck/util:io',
    '//src/com/facebook/buck/util:util',
    '//src/com/facebook/buck/util/concurrent:concurrent',
    '//src/com/facebook/buck/util/environment:platform',
    '//test/com/facebook/buck/event:testutil',
    '//test/com/facebook/buck/testutil:testutil',
    '//test/com/facebook/buck/timing:testutil',
    '//third-party/java/easymock:easymock',
    '//third-party/java/guava:guava',
    '//third-party/java/junit:junit',
  ],
)
