EMPTY_CONFIGS = {
  'Debug': {},
  'Release': {},
}

apple_library(
  name = 'Dep3',
  configs = EMPTY_CONFIGS,
  srcs = [],
  frameworks = [],
  deps = [],
  tests = [':Dep3Tests'],
  visibility = ['PUBLIC'],
)

apple_test(
  name = 'Dep3Tests',
  extension = 'octest',
  configs = EMPTY_CONFIGS,
  srcs = [],
  frameworks = [],
  deps = [
    ':Dep3',
  ],
)
