EMPTY_CONFIGS = {
  'Debug': {},
  'Release': {},
}

apple_library(
  name = 'Dep3',
  configs = EMPTY_CONFIGS,
  srcs = [],
  frameworks = [],
  deps = [],
  visibility = ['PUBLIC'],
)

apple_test(
  name = 'Dep3Tests',
  source_under_test = [
    ':Dep3',
  ],
  extension = 'octest',
  configs = EMPTY_CONFIGS,
  srcs = [],
  frameworks = [],
  deps = [
    ':Dep3',
  ],
)

xcode_project_config(
  name = 'project',
  project_name = 'Libraries',
  rules = [
    ':Dep3',
    ':Dep3Tests',
  ],
)
