kotlin_library(
    name = "service",
    srcs = glob(["*.kt"]),
    tests = [
        "//test/com/facebook/buck/multitenant/service:service",
    ],
    visibility = [
        "//src/com/facebook/buck/multitenant/...",
        "//test/com/facebook/buck/multitenant/...",
    ],
    deps = [
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/core/model/targetgraph/raw:raw",
        "//src/com/facebook/buck/multitenant/collect:collect",
        "//src/com/facebook/buck/multitenant/fs:fs",
        "//third-party/java/guava:guava",
    ],
)
