// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: downward_api.proto

package com.facebook.buck.downward.model;

@javax.annotation.Generated(value="protoc", comments="annotations:EndEventOrBuilder.java.pb.meta")
public interface EndEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:downward.api.v1.EndEvent)
    com.google.protobuf.MessageOrBuilder {
}
