// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/com/facebook/buck/downwardapi/resources/proto/downward_api.proto

package com.facebook.buck.downward.model;

/**
 * Protobuf type {@code downward.api.v1.EventTypeMessage}
 */
@javax.annotation.Generated(value="protoc", comments="annotations:EventTypeMessage.java.pb.meta")
public  final class EventTypeMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:downward.api.v1.EventTypeMessage)
    EventTypeMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EventTypeMessage.newBuilder() to construct.
  private EventTypeMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EventTypeMessage() {
    eventType_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private EventTypeMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            eventType_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.facebook.buck.downward.model.DownwardAPIProto.internal_static_downward_api_v1_EventTypeMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.facebook.buck.downward.model.DownwardAPIProto.internal_static_downward_api_v1_EventTypeMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.facebook.buck.downward.model.EventTypeMessage.class, com.facebook.buck.downward.model.EventTypeMessage.Builder.class);
  }

  /**
   * Protobuf enum {@code downward.api.v1.EventTypeMessage.EventType}
   */
  public enum EventType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN = 0;</code>
     */
    UNKNOWN(0),
    /**
     * <code>CONSOLE_EVENT = 1;</code>
     */
    CONSOLE_EVENT(1),
    /**
     * <code>LOG_EVENT = 2;</code>
     */
    LOG_EVENT(2),
    /**
     * <code>CHROME_TRACE_EVENT = 3;</code>
     */
    CHROME_TRACE_EVENT(3),
    /**
     * <code>STEP_EVENT = 4;</code>
     */
    STEP_EVENT(4),
    /**
     * <code>END_EVENT = 100;</code>
     */
    END_EVENT(100),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNKNOWN = 0;</code>
     */
    public static final int UNKNOWN_VALUE = 0;
    /**
     * <code>CONSOLE_EVENT = 1;</code>
     */
    public static final int CONSOLE_EVENT_VALUE = 1;
    /**
     * <code>LOG_EVENT = 2;</code>
     */
    public static final int LOG_EVENT_VALUE = 2;
    /**
     * <code>CHROME_TRACE_EVENT = 3;</code>
     */
    public static final int CHROME_TRACE_EVENT_VALUE = 3;
    /**
     * <code>STEP_EVENT = 4;</code>
     */
    public static final int STEP_EVENT_VALUE = 4;
    /**
     * <code>END_EVENT = 100;</code>
     */
    public static final int END_EVENT_VALUE = 100;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EventType valueOf(int value) {
      return forNumber(value);
    }

    public static EventType forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN;
        case 1: return CONSOLE_EVENT;
        case 2: return LOG_EVENT;
        case 3: return CHROME_TRACE_EVENT;
        case 4: return STEP_EVENT;
        case 100: return END_EVENT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EventType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EventType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EventType>() {
            public EventType findValueByNumber(int number) {
              return EventType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.facebook.buck.downward.model.EventTypeMessage.getDescriptor().getEnumTypes().get(0);
    }

    private static final EventType[] VALUES = values();

    public static EventType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private EventType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:downward.api.v1.EventTypeMessage.EventType)
  }

  public static final int EVENT_TYPE_FIELD_NUMBER = 1;
  private int eventType_;
  /**
   * <code>.downward.api.v1.EventTypeMessage.EventType event_type = 1;</code>
   */
  public int getEventTypeValue() {
    return eventType_;
  }
  /**
   * <code>.downward.api.v1.EventTypeMessage.EventType event_type = 1;</code>
   */
  public com.facebook.buck.downward.model.EventTypeMessage.EventType getEventType() {
    @SuppressWarnings("deprecation")
    com.facebook.buck.downward.model.EventTypeMessage.EventType result = com.facebook.buck.downward.model.EventTypeMessage.EventType.valueOf(eventType_);
    return result == null ? com.facebook.buck.downward.model.EventTypeMessage.EventType.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (eventType_ != com.facebook.buck.downward.model.EventTypeMessage.EventType.UNKNOWN.getNumber()) {
      output.writeEnum(1, eventType_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (eventType_ != com.facebook.buck.downward.model.EventTypeMessage.EventType.UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, eventType_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.facebook.buck.downward.model.EventTypeMessage)) {
      return super.equals(obj);
    }
    com.facebook.buck.downward.model.EventTypeMessage other = (com.facebook.buck.downward.model.EventTypeMessage) obj;

    if (eventType_ != other.eventType_) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + EVENT_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + eventType_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.facebook.buck.downward.model.EventTypeMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.facebook.buck.downward.model.EventTypeMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.facebook.buck.downward.model.EventTypeMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.facebook.buck.downward.model.EventTypeMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.facebook.buck.downward.model.EventTypeMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.facebook.buck.downward.model.EventTypeMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.facebook.buck.downward.model.EventTypeMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.facebook.buck.downward.model.EventTypeMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.facebook.buck.downward.model.EventTypeMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.facebook.buck.downward.model.EventTypeMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.facebook.buck.downward.model.EventTypeMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.facebook.buck.downward.model.EventTypeMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.facebook.buck.downward.model.EventTypeMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code downward.api.v1.EventTypeMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:downward.api.v1.EventTypeMessage)
      com.facebook.buck.downward.model.EventTypeMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.facebook.buck.downward.model.DownwardAPIProto.internal_static_downward_api_v1_EventTypeMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.facebook.buck.downward.model.DownwardAPIProto.internal_static_downward_api_v1_EventTypeMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.facebook.buck.downward.model.EventTypeMessage.class, com.facebook.buck.downward.model.EventTypeMessage.Builder.class);
    }

    // Construct using com.facebook.buck.downward.model.EventTypeMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      eventType_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.facebook.buck.downward.model.DownwardAPIProto.internal_static_downward_api_v1_EventTypeMessage_descriptor;
    }

    @java.lang.Override
    public com.facebook.buck.downward.model.EventTypeMessage getDefaultInstanceForType() {
      return com.facebook.buck.downward.model.EventTypeMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.facebook.buck.downward.model.EventTypeMessage build() {
      com.facebook.buck.downward.model.EventTypeMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.facebook.buck.downward.model.EventTypeMessage buildPartial() {
      com.facebook.buck.downward.model.EventTypeMessage result = new com.facebook.buck.downward.model.EventTypeMessage(this);
      result.eventType_ = eventType_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.facebook.buck.downward.model.EventTypeMessage) {
        return mergeFrom((com.facebook.buck.downward.model.EventTypeMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.facebook.buck.downward.model.EventTypeMessage other) {
      if (other == com.facebook.buck.downward.model.EventTypeMessage.getDefaultInstance()) return this;
      if (other.eventType_ != 0) {
        setEventTypeValue(other.getEventTypeValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.facebook.buck.downward.model.EventTypeMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.facebook.buck.downward.model.EventTypeMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int eventType_ = 0;
    /**
     * <code>.downward.api.v1.EventTypeMessage.EventType event_type = 1;</code>
     */
    public int getEventTypeValue() {
      return eventType_;
    }
    /**
     * <code>.downward.api.v1.EventTypeMessage.EventType event_type = 1;</code>
     */
    public Builder setEventTypeValue(int value) {
      eventType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.downward.api.v1.EventTypeMessage.EventType event_type = 1;</code>
     */
    public com.facebook.buck.downward.model.EventTypeMessage.EventType getEventType() {
      @SuppressWarnings("deprecation")
      com.facebook.buck.downward.model.EventTypeMessage.EventType result = com.facebook.buck.downward.model.EventTypeMessage.EventType.valueOf(eventType_);
      return result == null ? com.facebook.buck.downward.model.EventTypeMessage.EventType.UNRECOGNIZED : result;
    }
    /**
     * <code>.downward.api.v1.EventTypeMessage.EventType event_type = 1;</code>
     */
    public Builder setEventType(com.facebook.buck.downward.model.EventTypeMessage.EventType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      eventType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.downward.api.v1.EventTypeMessage.EventType event_type = 1;</code>
     */
    public Builder clearEventType() {
      
      eventType_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:downward.api.v1.EventTypeMessage)
  }

  // @@protoc_insertion_point(class_scope:downward.api.v1.EventTypeMessage)
  private static final com.facebook.buck.downward.model.EventTypeMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.facebook.buck.downward.model.EventTypeMessage();
  }

  public static com.facebook.buck.downward.model.EventTypeMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EventTypeMessage>
      PARSER = new com.google.protobuf.AbstractParser<EventTypeMessage>() {
    @java.lang.Override
    public EventTypeMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new EventTypeMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<EventTypeMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EventTypeMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.facebook.buck.downward.model.EventTypeMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

