java_library(
    name = "label",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    deps = [
        "//third-party/java/bazel:bazel",
        "//third-party/java/guava:guava",
        "//third-party/java/jsr:jsr305",
    ],
)
