java_library(
    name = "label",
    srcs = glob(["*.java"]),
    plugins = [
        "//starlark:starlark-annot-processor",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/core/cell/name:name",
        "//starlark:bazel",
        "//third-party/java/guava:guava",
        "//third-party/java/jsr:jsr305",
    ],
)
