java_library(
    name = "pipeline",
    srcs = glob(["*.java"]),
    exported_deps = [
        "//src/com/facebook/buck/core/build/engine:engine",
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/core/rules/impl:impl",
        "//src/com/facebook/buck/step:step",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//third-party/java/jsr:jsr305",
    ],
)
