load("//tools/build_rules:java_rules.bzl", "buck_java_library")
buck_java_library(
    name = "select",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    deps = [
        "//starlark:bazel",
        "//third-party/java/guava:guava",
    ],
)
