TEST_SRCS = glob(["*Test.java"])

java_test(
    name = "integration",
    srcs = TEST_SRCS,
    autodeps = True,
    visibility = [
        "//test/...",
    ],
    deps = [
        "//test/com/facebook/buck/testutil/integration:util",
        "//third-party/java/guava:guava",
        "//third-party/java/junit:junit",
    ],
)

java_library(
    name = "util",
    srcs = glob(
        ["*.java"],
        excludes = TEST_SRCS,
    ),
    autodeps = True,
    exported_deps = [
        "//src/com/facebook/buck/io:BuckPaths",
        "//src/com/facebook/buck/model:model",
        "//src/com/facebook/buck/rules:build_rule",
        "//src/com/facebook/buck/rules:types",
        "//src/com/facebook/buck/util/sha1:sha1",
        "//src/com/facebook/buck/util:process_executor",
        "//third-party/java/guava:guava",
        # This is due to the bug mentioned above.
        "//third-party/java/jetty:jetty",
        "//third-party/java/jsr:jsr305",
        "//third-party/java/junit:junit",
        "//third-party/java/nailgun:nailgun",
    ],
    visibility = [
        "//test/...",
    ],
    deps = [
        "//src/com/facebook/buck/android:utils",
        "//src/com/facebook/buck/apple:platform",
        "//src/com/facebook/buck/apple:rules",
        "//src/com/facebook/buck/apple/device:device",
        "//src/com/facebook/buck/artifact_cache:artifact_cache",
        "//src/com/facebook/buck/cli:cli",
        "//src/com/facebook/buck/cli:config",
        "//src/com/facebook/buck/config:config",
        "//src/com/facebook/buck/io:MorePaths.java",
        "//src/com/facebook/buck/io:executable-finder",
        "//src/com/facebook/buck/io:io",
        "//src/com/facebook/buck/io:watchman",
        "//src/com/facebook/buck/log:api",
        "//src/com/facebook/buck/model:build_id",
        "//src/com/facebook/buck/rules:default_cell_path_resolver",
        "//src/com/facebook/buck/util:constants",
        "//src/com/facebook/buck/util:util",
        "//src/com/facebook/buck/util:watchman",
        "//src/com/facebook/buck/util/environment:environment",
        "//src/com/facebook/buck/util/environment:platform",
        "//src/com/facebook/buck/util/trace:trace",
        "//test/com/facebook/buck/jvm/java:javac-env",
        "//test/com/facebook/buck/model:testutil",
        "//test/com/facebook/buck/testutil:testutil",
        "//third-party/java/dd-plist:dd-plist",
        "//third-party/java/gson:gson",
        "//third-party/java/hamcrest:java-hamcrest",
        "//third-party/java/ini4j:ini4j",
    ],
)

python_library(
    name = "integration-py",
    srcs = glob(["*.py"]),
    base_module = "",
    visibility = [
        "//scripts/...",
        "//test/...",
    ],
)
