# TODO(bolinfest): Replace this with standard_java_test() once `buck autodeps` is
# fixed to automatically infer the export of '//third-party/java/jetty:jetty'.

java_library(
  name = 'integration',
  srcs = glob(['*.java']),
  autodeps = True,
  exported_deps = [
    # This is due to the bug mentioned above.
    '//third-party/java/jetty:jetty',
  ],
  visibility = [
    '//test/...',
  ],
)

python_library(
  name = 'integration-py',
  base_module = '',
  srcs = glob(['*.py']),
  visibility = [
    '//test/...',
    '//scripts/...',
  ],
)
