java_library(
  name = 'integration',
  srcs = glob(['*.java']),
  deps = [
    '//src/com/facebook/buck/cli:cli',
    '//src/com/facebook/buck/util:constants',
    '//src/com/facebook/buck/util:io',
    '//lib:guava',
    '//lib:jsr305',
    '//lib:junit',

    # Although this library does not use Jython directly, it must be on the classpath so that
    # new ScriptEngineManager().getEngineByName("python") will not return null.
    '//lib:jyson',
    '//lib:jython',
  ],
  visibility = [
    'PUBLIC',
  ],
)
