java_library(
    name = "compatible",
    srcs = glob(["*.java"]),
    exported_deps = [
        "//third-party/java/bazel:bazel",
    ],
    tests = [
        "//test/com/facebook/buck/core/starlark/compatible:compatible",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//third-party/java/guava:guava",
        "//third-party/java/jsr:jsr305",
    ],
)
