java_library(
    name = "compatible",
    srcs = glob(["*.java"]),
    # Work around bug P129476630
    abi_generation_mode = "class",
    tests = [
        "//test/com/facebook/buck/core/starlark/compatible:compatible",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//third-party/java/guava:guava",
        "//third-party/java/jsr:jsr305",
    ],
    exported_deps = [
        "//src/com/facebook/buck/rules/param:param",
        "//third-party/java/bazel:bazel",
    ],
)
