standard_java_test(
    name = "firstorder",
    deps = [
        "//src/com/facebook/buck/dalvik/firstorder:firstorder",
        "//src/com/facebook/buck/model:simple_types",
        "//src/com/facebook/buck/util:util",
        "//src/com/facebook/buck/util/immutables:immutables",
        "//third-party/java/asm:asm",
        "//third-party/java/guava:guava",
        "//third-party/java/immutables:immutables",
        "//third-party/java/jackson:jackson-databind",
        "//third-party/java/jsr:jsr305",
        "//third-party/java/junit:junit",
    ],
)
