java_test(
  name = 'rules',
  srcs = glob(['*Test.java']),
  source_under_test = [
    '//src/com/facebook/buck/apple:rules',
  ],
  deps = [
    '//lib:hamcrest-core',
    '//lib:hamcrest-library',
    '//lib:guava',
    '//lib:junit',
    '//src/com/facebook/buck/apple:rules',
    '//src/com/facebook/buck/graph:graph',
    '//src/com/facebook/buck/model:model',
    '//src/com/facebook/buck/parser:rule_pattern',
    '//src/com/facebook/buck/rules:build_rule',
    '//src/com/facebook/buck/rules:rules',
    '//src/com/facebook/buck/step:step',
    '//src/com/facebook/buck/step/fs:fs',
    '//src/com/facebook/buck/util:io',
    '//test/com/facebook/buck/model:BuildTargetFactory',
    '//test/com/facebook/buck/rules:testutil',
    '//test/com/facebook/buck/step:testutil',
    '//test/com/facebook/buck/testutil:testutil',
    '//test/com/facebook/buck/util:testutil',
  ]
)
