load("//tools/build_rules:java_rules.bzl", "standard_java_test")

standard_java_test(
    name = "namedpipes",
    deps = [
        "//src/com/facebook/buck/downwardapi/namedpipes:namedpipes",
        "//src/com/facebook/buck/downwardapi/protocol:protocol",
        "//src/com/facebook/buck/io/namedpipes:namedpipes",
        "//test/com/facebook/buck/testutil:testutil",
        "//third-party/java/junit:junit",
    ],
)
