java_immutables_library(
  name = 'simulate',
  srcs = glob(['*.java']),
  immutable_types = [
    'SimulateReport',
    'SingleRunReport',
  ],
  autodeps = True,
  visibility = [
    'PUBLIC',
  ],
)
