java_library(
  name = 'runner',
  srcs = glob(['*.java']),
  deps = [
    # DO NOT ADD ANY DEPS.
  ],
  visibility = [
    '//src/com/facebook/buck/java:steps',
    '//src/com/facebook/buck/junit:junit',
    '//test/com/facebook/buck/java:java',
    '//test/com/facebook/buck/java/runner:runner',
  ],
)
