load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "impl",
    srcs = glob(["*.java"]),
    tests = [
        "//test/com/facebook/buck/core/rules/providers/collect/impl:impl",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/core/rules/providers/lib:lib",
        "//third-party/java/guava:guava",
        "//third-party/java/jsr:jsr305",
    ],
    exported_deps = [
        "//src/com/facebook/buck/core/rules/providers:providers",
        "//src/com/facebook/buck/core/rules/providers/collect:collect",
        "//src/com/facebook/buck/core/starlark/compatible:compatible",
    ],
)
