load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "schedule",
    srcs = [
        "AbstractRuleScheduleInfo.java",
        "OverrideScheduleRule.java",
    ],
    exported_deps = [
        "//src/com/facebook/buck/core/rules/impl:impl",
    ],
    visibility = [
        "PUBLIC",
    ],
)
