java_test(
    name = "collector_test",
    srcs = ["SoyTemplateSkylarkSignatureRendererTest.java"],
    resources = [
        "//tools/documentation_generator/test/com/facebook/buck/tools/documentation/generator/skylark/rendering/data:expected_dummy_function.soy",
        "//tools/documentation_generator/test/com/facebook/buck/tools/documentation/generator/skylark/rendering/data:expected_dummy_function_with_braces_inside.soy",
        "//tools/documentation_generator/test/com/facebook/buck/tools/documentation/generator/skylark/rendering/data:expected_dummy_function_with_kwargs.soy",
        "//tools/documentation_generator/test/com/facebook/buck/tools/documentation/generator/skylark/rendering/data:expected_dummy_function_without_args.soy",
        "//tools/documentation_generator/test/com/facebook/buck/tools/documentation/generator/skylark/rendering/data:expected_dummy_toc.soy",
    ],
    deps = [
        "//src/com/facebook/buck/util/environment:platform",
        "//third-party/java/bazel:bazel",
        "//third-party/java/junit:junit",
        "//tools/documentation_generator/src/com/facebook/buck/tools/documentation/generator/skylark/rendering:rendering",
    ],
)
