load("//tools/build_rules:java_rules.bzl", "java_test")

java_test(
    name = "manifest",
    srcs = glob(["*Test.java"]),
    deps = [
        "//src/com/facebook/buck/android/manifest:manifest",
        "//third-party/java/guava:guava",
        "//third-party/java/junit:junit",
    ],
)
