load("//tools/build_rules:java_rules.bzl", "java_immutables_library", "standard_java_test")

standard_java_test(
    name = "unit",
    deps = [
        ":testutil",
        "//src/com/facebook/buck/core/util/log:log",
        "//src/com/facebook/buck/io/namedpipes:namedpipes",
        "//src/com/facebook/buck/util:util",
        "//src/com/facebook/buck/util/environment:platform",
        "//third-party/java/junit:junit",
    ],
)

java_immutables_library(
    name = "testutil",
    srcs = glob(
        ["*.java"],
        exclude = ["*Test.java"],
    ),
    visibility = ["//test/..."],
    exported_deps = ["//src/com/facebook/buck/util/json:json"],
)
