java_test(
  name = 'gwt',
  srcs = glob(['*Test.java']),
  deps = [
    '//test/com/facebook/buck/testutil/integration:integration',
    '//third-party/java/junit:junit',
  ],
  # GwtBinaryIntegrationTest tends to time out when run in parallel
  # on underpowered systems. Run it separately in serial at the end
  # of the test run.
  run_test_separately = True,
  # Constraint the heap so it doesn't balloon and OOM.
  vm_args = [ '-Xmx256m' ],
)
