genrule(
    name = "manifest",
    srcs = [
        "AndroidManifest-template.xml",
    ],
    out = "AndroidManifest.xml",
    bash = "VERSION=`sed -ne '/AGENT_VERSION_CODE/s/[^0-9]//gp' < " +
           "$(location //src/com/facebook/buck/android/agent/util:util_src)` && " +
           "sed s/{version}/$VERSION/g < $SRCDIR/AndroidManifest-template.xml > $OUT",
)

android_binary(
    name = "agent",
    keystore = ":debug_keystore",
    manifest = ":manifest",
    deps = [
        "//android/com/facebook/buck/android/agent/native:native",
        "//src/com/facebook/buck/android/agent:agent",
    ],
)

keystore(
    name = "debug_keystore",
    properties = "debug.keystore.properties",
    store = "debug.keystore",
)
