load("//tools/build_rules:java_rules.bzl", "buck_java_library", "buck_java_binary")

MERGE_ANDROID_RESOURCES_SRCS = ["MergeAndroidResources.java", "MergeAndroidResourcesExecutableMain.java"]
MERGE_ASSETS_SRCS = ["MergeAssetsUtils.java", "MergeAssetsExecutableMain.java"]
MERGE_THIRD_PARTY_JAR_RESOURCES_SRCS = ["MergeThirdPartyJarResourcesUtils.java"]

buck_java_library(
    name = "resources",
    srcs = glob(["*.java"], exclude = MERGE_ANDROID_RESOURCES_SRCS + MERGE_ASSETS_SRCS + MERGE_THIRD_PARTY_JAR_RESOURCES_SRCS),
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/io:io",
        "//src/com/facebook/buck/io/file:file",
        "//src/com/facebook/buck/io/filesystem/impl:impl",
        "//src/com/facebook/buck/io/filesystem/impl:utils",
        "//src/com/facebook/buck/util:util",
        "//src/com/facebook/buck/util/stream:stream",
        "//src/com/facebook/buck/util/zip:zip",
        "//third-party/java/guava:guava",
        "//third-party/java/jsr:jsr305",
    ],
)

buck_java_library(
    name = "merge_android_resources",
    srcs = MERGE_ANDROID_RESOURCES_SRCS,
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/android/aapt:r_dot_txt",
        "//src/com/facebook/buck/util:util",
        "//src/com/facebook/buck/util/json:json",
        "//src/com/facebook/buck/core/util/log:log",
        "//third-party/java/args4j:args4j",
        "//third-party/java/guava:guava",
    ],
)

buck_java_binary(
    name = "merge_android_resources_binary",
    main_class = "com.facebook.buck.android.resources.MergeAndroidResourcesExecutableMain",
    visibility = [
        "PUBLIC",
    ],
    deps = [
        ":merge_android_resources",
    ],
)

buck_java_library(
    name = "merge_assets",
    srcs = MERGE_ASSETS_SRCS,
    visibility = ["PUBLIC"],
    deps = [
        ":resources",
        "//src/com/facebook/buck/io/filesystem/impl:utils",
        "//third-party/java/args4j:args4j",
        "//third-party/java/guava:guava",
    ],
    java_version = "11",
)

buck_java_binary(
    name = "merge_assets_binary",
    main_class = "com.facebook.buck.android.resources.MergeAssetsExecutableMain",
    visibility = [
        "PUBLIC",
    ],
    deps = [
        ":merge_assets",
    ],
)

buck_java_library(
    name = "merge_third_party_jar_resources",
    srcs = MERGE_THIRD_PARTY_JAR_RESOURCES_SRCS,
    visibility = ["PUBLIC"],
    deps = [
        ":resources",
        "//src/com/facebook/buck/core/filesystems:filesystems",
        "//src/com/facebook/buck/io/filesystem/impl:utils",
        "//third-party/java/guava:guava",
    ],
    java_version = "11",
)
