load("//tools/build_rules:java_rules.bzl", "buck_java_library")
buck_java_library(
    name = "filesystems",
    srcs = glob(["*.java"]),
    tests = ["//test/com/facebook/buck/core/filesystems:filesystems"],
    visibility = [
        "//programs:",
        "//src/com/facebook/buck/...",
        "//test/...",
    ],
    deps = [
        # Do NOT add deps here. This library is loaded into the JVM bootstrap classloader in Java 9+.
    ],
)
