java_library(
  name = 'fixtures',
  srcs = [
    'MockingDSL.java',
    'VacationFixture.java',
  ],
  deps = [
    '//lib:easymock',
    '//lib:guava',
    '//lib:junit',
    '//src/com/facebook/buck/model:model',
    '//src/com/facebook/buck/rules:build_rule',
    '//src/com/facebook/buck/rules:rules',
    '//src/com/facebook/buck/test:test',
    '//test/com/facebook/buck/testutil/integration:integration',
  ],
)

java_test(
  name = 'resultgroups',
  srcs = [
    'MockedMealTest.java',
    'VacationIntegrationTest.java',
  ],
  source_under_test = ['//src/com/facebook/buck/test/resultgroups:resultgroups'],
  deps = [
    ':fixtures',
    '//lib:easymock',
    '//lib:guava',
    '//lib:hamcrest-core',
    '//lib:hamcrest-library',
    '//lib:junit',
    '//src/com/facebook/buck/model:model',
    '//src/com/facebook/buck/rules:build_rule',
    '//src/com/facebook/buck/rules:rules',
    '//src/com/facebook/buck/test/resultgroups:resultgroups',
    '//src/com/facebook/buck/test:test',
    '//test/com/facebook/buck/testutil/integration:integration',
  ],
  visibility = ['PUBLIC'],
)
