load("//tools/build_rules:java_rules.bzl", "java_test")

java_test(
    name = "impl",
    srcs = glob(["*Test.java"]),
    deps = [
        "//src/com/facebook/buck/core/model/platform/impl:impl",
        "//test/com/facebook/buck/core/model:testutil",
        "//test/com/facebook/buck/testutil:testutil",
        "//test/com/facebook/buck/testutil/integration:util",
        "//third-party/java/junit:junit",
    ],
)
