load("//tools/build_rules:java_rules.bzl", "standard_java_test")

standard_java_test(
    name = "skylark",
    deps = [
        "//test/com/facebook/buck/core/starlark/testutil:testutil",
        "//third-party/java/guava:guava",
        "//third-party/java/junit:junit",
    ],
)
