load("//tools/build_rules:java_rules.bzl", "standard_java_test")

standard_java_test(
    name = "files",
    deps = [
        "//src/com/facebook/buck/core/files:files",
        "//src/com/facebook/buck/io/watchman:watchman",
        "//test/com/facebook/buck/core/graph/transformation:testutil",
        "//test/com/facebook/buck/io/filesystem:testutil",
        "//test/com/facebook/buck/testutil:testutil",
        "//third-party/java/guava:guava",
        "//third-party/java/junit:junit",
        "//third-party/java/junitparams:junitparams",
    ],
)
