load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "impl",
    srcs = glob(["*.java"]),
    visibility = [
        "//src/com/facebook/buck/cli:cli",
        "//test/...",
    ],
    deps = [
        "//src/com/facebook/buck/config:config",
        "//src/com/facebook/buck/rules/keys:keys",
    ],
)
