load("//tools/build_rules:java_rules.bzl", "buck_java_library")
buck_java_library(
    name = "artifact",
    srcs = glob(
        ["*.java"],
    ),
    plugins = [
        "//starlark:starlark-annot-processor",
    ],
    visibility = ["PUBLIC"],
    exported_deps = [
        "//starlark:bazel",
    ],
)
