java_library(
    name = "artifact",
    srcs = glob(
        ["*.java"],
    ),
    exported_deps = [
        "//third-party/java/bazel:bazel",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//third-party/java/guava:guava",
    ],
)
