java_library(
    name = "impl",
    srcs = glob(["*.java"]),
    visibility = [
        "//src/com/facebook/buck/...",
    ],
    deps = [
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/core/model/impl:impl",
        "//src/com/facebook/buck/core/rules/common:common",
        "//src/com/facebook/buck/jvm/java:steps",
        "//src/com/facebook/buck/jvm/java:support",
        "//src/com/facebook/buck/jvm/java/stepsbuilder:stepsbuilder",
        "//src/com/facebook/buck/step/isolatedsteps:isolatedsteps",
        "//src/com/facebook/buck/step/isolatedsteps/java:java",
        "//third-party/java/guava:guava",
    ],
)
