load(
    "//tools/build_rules:java_rules.bzl",
    "java_immutables_library",
)

java_immutables_library(
    name = "stampede",
    srcs = glob(["*.java"]),
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/core/build/event:event",
        "//src/com/facebook/buck/distributed:common",
        "//src/com/facebook/buck/distributed/build_client:build_client",
        "//src/com/facebook/buck/distributed/build_slave:build_slave",
        "//src/com/facebook/buck/event:interfaces",
        "//src/com/facebook/buck/event/external:external_lib",
        "//src/com/facebook/buck/event/listener/stats/cache:cache",
        "//src/com/facebook/buck/event/listener/util:util",
        "//third-party/java/guava:guava",
    ],
)
