load("//tools/build_rules:java_rules.bzl", "java_test")

java_test(
    name = "impl",
    srcs = glob(
        ["*Test.java"],
    ),
    resources = glob(
        ["testdata/**"],
    ),
    deps = [
        ":testutil",
        "//src/com/facebook/buck/android:config",
        "//src/com/facebook/buck/android:helpers",
        "//src/com/facebook/buck/android:utils",
        "//src/com/facebook/buck/android/toolchain/impl:impl",
        "//src/com/facebook/buck/android/toolchain/ndk/impl:impl",
        "//src/com/facebook/buck/core/sourcepath/resolver/impl:impl",
        "//src/com/facebook/buck/cxx:rules",
        "//src/com/facebook/buck/cxx/toolchain/impl:impl",
        "//src/com/facebook/buck/io:executable-finder",
        "//src/com/facebook/buck/io/file:file",
        "//src/com/facebook/buck/parser/exceptions:exceptions",
        "//src/com/facebook/buck/plugin/impl:impl",
        "//src/com/facebook/buck/rules/args:args",
        "//src/com/facebook/buck/toolchain/impl:impl",
        "//test/com/facebook/buck/android:testutil",
        "//test/com/facebook/buck/android:utils",
        "//test/com/facebook/buck/config:FakeBuckConfig",
        "//test/com/facebook/buck/core/cell:testutil",
        "//test/com/facebook/buck/core/rules/resolver/impl:testutil",
        "//test/com/facebook/buck/cxx/toolchain:testutil",
        "//test/com/facebook/buck/io:testutil",
        "//test/com/facebook/buck/io/filesystem:testutil",
        "//test/com/facebook/buck/model:testutil",
        "//test/com/facebook/buck/rules:testutil",
        "//test/com/facebook/buck/rules/keys:testutil",
        "//test/com/facebook/buck/rules/keys/config:testutil",
        "//test/com/facebook/buck/testutil:testutil",
        "//test/com/facebook/buck/testutil/integration:util",
        "//test/com/facebook/buck/toolchain/impl:testutil",
        "//third-party/java/junit:junit",
    ],
)

java_library(
    name = "testutil",
    srcs = glob(
        ["*.java"],
        exclude = ["*Test.java"],
    ),
    exported_deps = [
        "//src/com/facebook/buck/android/toolchain/ndk:ndk",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/android:config",
        "//src/com/facebook/buck/android:helpers",
        "//src/com/facebook/buck/android:rules",
        "//src/com/facebook/buck/android:steps",
        "//src/com/facebook/buck/android:utils",
        "//src/com/facebook/buck/android/toolchain/ndk/impl:impl",
        "//test/com/facebook/buck/config:FakeBuckConfig",
        "//test/com/facebook/buck/cxx/toolchain:testutil",
        "//test/com/facebook/buck/rules/keys/config:testutil",
        "//test/com/facebook/buck/testutil:testutil",
        "//test/com/facebook/buck/testutil/integration:util",
        "//test/com/facebook/buck/toolchain/impl:testutil",
        "//third-party/java/junit:junit",
        "//third-party/java/xz-java-1.5:xz",
    ],
)
