load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "action",
    srcs = glob(["*.java"]),
    exported_deps = [
        "//src/com/facebook/buck/core/model:model",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/core/starlark/coercer:coercer",
        "//third-party/java/guava:guava",
    ],
)
