STANDARD_TEST_SRCS = [
  '*Test.java',
]

java_library(
  name = 'testutil',
  srcs = glob(['*.java'], excludes=STANDARD_TEST_SRCS),
  deps = [
    '//src/com/facebook/buck/util/network:network',
    '//third-party/java/guava:guava',
    '//third-party/java/jsr:jsr305',
  ],
  visibility = [
    '//test/...'
  ],
)

java_test(
  name = 'network',
  srcs = glob(STANDARD_TEST_SRCS),
  deps = [
    '//src/com/facebook/buck/util:io',
    '//src/com/facebook/buck/util:util',
    '//src/com/facebook/buck/util/network:network',
    '//src/com/facebook/buck/util:object_mapper',
    '//test/com/facebook/buck/testutil:testutil',
    '//third-party/java/guava:guava',
    '//third-party/java/hamcrest:hamcrest',
    '//third-party/java/jackson:jackson-annotations',
    '//third-party/java/jackson:jackson-databind',
    '//third-party/java/junit:junit',
  ],
)
