java_library(
    name = "selectors",
    srcs = glob(["*.java"]),
    required_for_source_only_abi = True,
    # This target is pulled in by testrunner, which needs to compile against Java 8.
    source = "8",
    target = "8",
    tests = [
        "//test/com/facebook/buck/test/selectors:selectors",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [],  # This list is to remain empty. See src/com/facebook/buck/testrunner/BUCK.
)
