java_library(
  name = 'selectors',
  srcs = glob(['*.java']),
  deps = [
    # IMPORTANT! This list is to remain empty. See src/com/facebook/buck/junit/BUCK.
  ],
  visibility = [
    '//src/com/facebook/buck/apple:rules',
    '//src/com/facebook/buck/cli:cli',
    '//src/com/facebook/buck/d:d',
    '//src/com/facebook/buck/event/listener:listener',
    '//src/com/facebook/buck/java:steps',
    '//src/com/facebook/buck/java:rules',
    '//src/com/facebook/buck/junit:base',
    '//src/com/facebook/buck/rules:rules',
    '//src/com/facebook/buck/shell:rules',
    '//src/com/facebook/buck/python:rules',
    '//src/com/facebook/buck/cxx:rules',
    '//test/com/facebook/buck/cxx:cxx',
    '//test/com/facebook/buck/event:event',
    '//test/com/facebook/buck/event/listener:listener',
    '//test/com/facebook/buck/java:java',
    '//test/com/facebook/buck/rules:rules',
    '//test/com/facebook/buck/rules:testutil',
    '//test/com/facebook/buck/test/selectors:selectors',
  ],
)
