java_library(
  name = 'selectors',
  srcs = glob(['*.java']),
  tests = [
    '//test/com/facebook/buck/test/selectors:selectors',
  ],
  autodeps = False, # This list is to remain empty. See src/com/facebook/buck/testruner/BUCK.
  visibility = [
    'PUBLIC',
  ],
)
