java_test(
    name = 'bser',
    srcs = glob(['*Test.java']),
    deps = [
        '//third-party/java/guava:guava',
        '//third-party/java/hamcrest:hamcrest',
        '//third-party/java/junit:junit',
        '//src/com/facebook/buck/bser:bser',
    ],
)
