load("//tools/build_rules:java_rules.bzl", "buck_java_library")

buck_java_library(
    name = "testutil",
    srcs = glob(
        ["*.java"],
        exclude = ["*Test.java"],
    ),
    visibility = ["//test/..."],
    deps = [
        "//third-party/java/guava:guava",
        "//third-party/java/junit:junit",
    ],
    exported_deps = [
        "//src/com/facebook/buck/core/rules:rules",
    ],
)
