load("//tools/build_rules:java_rules.bzl", "buck_java_library")
buck_java_library(
    name = "factory",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/core/model/impl:impl",
    ],
    exported_deps = [
        "//src/com/facebook/buck/core/cell:cell",
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/core/parser/buildtargetparser:buildtargetparser",
    ],
)
