# Code shared between the agent and the host.
java_library(
  name = 'util',
  source = '6',
  target = '6',
  srcs = glob(['*.java']),
  deps = [
    # Do not add other deps here.  The agent should remain very small.
  ],
  visibility = [
    '//src/com/facebook/buck/android:helpers',
    '//src/com/facebook/buck/android/agent:agent-lib',
    '//test/com/facebook/buck/android/agent/util:util',
  ],
)
