load("//tools/build_rules:file_alias.bzl", "file_alias")

# Code shared between the agent and the host.
java_library(
    name = "util",
    srcs = glob(["*.java"]),
    source = "6",
    target = "6",
    tests = [
        "//test/com/facebook/buck/android/agent/util:util",
    ],
    visibility = [
        "//src/com/facebook/buck/android:helpers",
        "//src/com/facebook/buck/android/agent:agent",
        "//test/com/facebook/buck/android:integration1",
        "//test/com/facebook/buck/android:integration2",
        "//test/com/facebook/buck/android/...",
        "//test/com/facebook/buck/android/agent/util:util",
    ],
    deps = [
        # Do not add other deps here.  The agent should remain very small.
    ],
)

file_alias(
    name = "util_src",
    source = "AgentUtil.java",
    visibility = [
        "//android/com/facebook/buck/android/agent/...",
    ],
)
