standard_java_test(
    name = "config",
    deps = [
        "//src/com/facebook/buck/config:config",
        "//src/com/facebook/buck/rules:relative_cell_name",
        "//src/com/facebook/buck/util/config:config",
        "//third-party/java/guava:guava",
        "//third-party/java/junit:junit",
    ],
)
