java_library(
    name = "namedpipes",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    deps = [
        "//src-gen:downward-model",
        "//src/com/facebook/buck/downwardapi/protocol:protocol",
        "//src/com/facebook/buck/io/namedpipes:namedpipes",
        "//third-party/java/jsr:jsr305",
    ],
)
