standard_java_testutil(
    name = "testutil",
    exported_deps = [
        "//src/com/facebook/buck/io:io",
        "//src/com/facebook/buck/jvm/groovy:groovy",
        "//src/com/facebook/buck/model:model",
        "//src/com/facebook/buck/rules:build_rule",
        "//test/com/facebook/buck/rules:testutil",
        "//third-party/java/guava:guava",
    ],
    deps = [
        "//test/com/facebook/buck/jvm/java:javac-env",
        "//test/com/facebook/buck/testutil:testutil",
    ],
)

standard_java_test(
    name = "groovy",
    deps = [
        "//src/com/facebook/buck/cli:config",
        "//src/com/facebook/buck/config:config",
        "//src/com/facebook/buck/io:MorePaths.java",
        "//src/com/facebook/buck/io:io",
        "//src/com/facebook/buck/jvm/groovy:groovy",
        "//src/com/facebook/buck/rules:default_cell_path_resolver",
        "//src/com/facebook/buck/util/environment:platform",
        "//test/com/facebook/buck/testutil/integration:util",
        "//third-party/java/guava:guava",
        "//third-party/java/hamcrest:java-hamcrest",
        "//third-party/java/junit:junit",
    ],
)
