java_library(
    name = "buildables",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    deps = [
        "//src-gen:buildable-command-model",
        "//src/com/facebook/buck/core/util/log:log",
        "//src/com/facebook/buck/downwardapi/processexecutor:processexecutor",
        "//src/com/facebook/buck/external/constants:constants",
        "//src/com/facebook/buck/external/model:model",
        "//src/com/facebook/buck/step:step",
        "//src/com/facebook/buck/step/isolatedsteps:isolatedsteps",
        "//third-party/java/jsr:jsr305",
    ],
)
