load("//tools/build_rules:java_rules.bzl", "buck_java_library")

buck_java_library(
    name = "buildables",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    deps = [
        "//src-gen:buildable-command-model",
        "//src/com/facebook/buck/core/util/log:log",
        "//src/com/facebook/buck/external/constants:constants",
        "//src/com/facebook/buck/step:step",
        "//src/com/facebook/buck/step/isolatedsteps:isolatedsteps",
        "//src/com/facebook/buck/util/env:env",
        "//src/com/facebook/buck/util/environment:environment",
        "//src/com/facebook/buck/util/java:java",
    ],
)
