load("//tools/build_rules:java_rules.bzl", "java_test")
load("//tools/build_rules:python_rules.bzl", "e2e_test")

TEST_SRCS = [
    "*Test.java",
]

java_test(
    name = "endtoend",
    srcs = glob(
        TEST_SRCS,
    ),
    env = {
        "TEST_BUCK": "$(location //programs:buck)",
    },
    deps = [
        "//programs:buck",
        "//src/com/facebook/buck/util/environment:platform",
        "//test/com/facebook/buck/apple:testutil",
        "//test/com/facebook/buck/testutil:testutil",
        "//test/com/facebook/buck/testutil/endtoend:testutil",
        "//third-party/java/junit:junit",
    ],
)

e2e_test(
    name = "e2e",
    srcs = glob(["*test.py"]),
    data = "//test/com/facebook/buck/testutil/endtoend:testdata",
)
