load("//tools/build_rules:java_rules.bzl", "java_test")

TEST_SRCS = [
    "*Test.java",
]

java_test(
    name = "endtoend",
    srcs = glob(
        TEST_SRCS,
    ),
    env = {
        "TEST_BUCK": "$(location //programs:buck)",
    },
    deps = [
        "//programs:buck",
        "//src/com/facebook/buck/util/environment:platform",
        "//test/com/facebook/buck/apple:testutil",
        "//test/com/facebook/buck/testutil:testutil",
        "//test/com/facebook/buck/testutil/endtoend:testutil",
        "//third-party/java/junit:junit",
    ],
)
