java_library(
    name = "windowspipe",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/io/watchman:transport",
        "//third-party/java/guava:guava",
        "//third-party/java/jna:jna",
        "//third-party/java/jna:jna-platform",
    ],
)
