load("//tools/build_rules:java_rules.bzl", "buck_java_library")

buck_java_library(
    name = "windowspipe",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/io/watchman:transport",
        "//third-party/java/jna:jna",
        "//third-party/java/jna:jna-platform",
    ],
)
