load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "toolchain",
    srcs = glob(["*.java"]),
    exported_deps = [
        "//src/com/facebook/buck/core/toolchain:toolchain",
        "//src/com/facebook/buck/cxx/toolchain:toolchain",
        "//src/com/facebook/buck/jvm/java:support",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/util:util",
    ],
)
