java_test(
  name = 'graphql',
  srcs = glob(['*Test.java']),
  source_under_test = [
    '//src/com/facebook/buck/apple:rules',
  ],
  deps = [
    '//test/com/facebook/buck/testutil/integration:integration',
    '//third-party/java/junit:junit',
  ]
)

java_library(
  name = 'testutil',
  srcs = glob(['*.java'], excludes = ['*Test.java']),
  deps = [
    '//src/com/facebook/buck/apple:rules',
    '//src/com/facebook/buck/cli:config',
    '//src/com/facebook/buck/io:io',
    '//src/com/facebook/buck/model:model',
    '//src/com/facebook/buck/rules:build_rule',
    '//src/com/facebook/buck/timing:timing',
    '//test/com/facebook/buck/cli:FakeBuckConfig',
    '//test/com/facebook/buck/rules:testutil',
    '//test/com/facebook/buck/testutil:testutil',
    '//third-party/java/guava:guava',
  ],
  visibility = [
    '//test/...',
  ],
)
