java_library(
  name = 'fat-jar-main',
  # Maximum compatibility
  source = '6',
  target = '6',
  srcs = [
    'FatJar.java',
    'FatJarMain.java',
    '//src/com/facebook/buck/util/exportedfiles:Nullable.java',
    '//src/com/facebook/buck/util/exportedfiles:Preconditions.java',
  ],
  # Must be empty!  We package these sources and compile them into fat JARs,
  # so it's important that they don't bring along any additional dependencies.
  deps = []
)

java_library(
  name = 'config',
  srcs = [
    'JavaBuckConfig.java',
  ],
  autodeps = True,
  visibility = ['PUBLIC'],
)

java_library(
  name = 'javac-internals',
  srcs = [
    'ZipEntryJavaFileObject.java',
  ],
  autodeps = True,
)

java_library(
  name = 'javac-sink',
  srcs = [
    'JavacEventSink.java',
  ],
  autodeps = True,
  visibility = ['PUBLIC'],
)

java_immutables_library(
  name = 'support',
  srcs = [
    'AbstractJavaOptions.java',
    'AbstractJavacExecutionContext.java',
    'AbstractDirectToJarOutputSettings.java',
    'AbstractJavacOptions.java',
    'AbstractJavacVersion.java',
    'AnnotationProcessingEvent.java',
    'AnnotationProcessingParams.java',
    'BuildsAnnotationProcessor.java',
    'ClassUsageFileWriter.java',
    'ClassUsageFileWriterSerializer.java',
    'ClassUsageTracker.java',
    'DefaultClassUsageFileReader.java',
    'DefaultClassUsageFileWriter.java',
    'DiagnosticCleaner.java',
    'DiagnosticPrettyPrinter.java',
    'DirectToJarOutputSettingsSerializer.java',
    'ExternalJavaRuntimeLauncher.java',
    'ExternalJavac.java',
    'ForwardingStandardJavaFileManager.java',
    'HasClasspathEntries.java',
    'HasJavaAbi.java',
    'HasMavenCoordinates.java',
    'HasSources.java',
    'JarBackedJavac.java',
    'JavaRuntimeLauncher.java',
    'JavaLibrary.java',
    'Javac.java',
    'JavacErrorParser.java',
    'JavacEventSinkToBuckEventBusBridge.java',
    'JavacExecutionContextSerializer.java',
    'Jsr199TracingBridge.java',
    'JavaInMemoryFileManager.java',
    'JavaInMemoryFileObject.java',
    'JavaNoOpFileObject.java',
    'JarDirectoryStepHelper.java',
    'JdkProvidedInMemoryJavac.java',
    'Jsr199Javac.java',
    'MavenPublishable.java',
    'NoOpClassUsageFileWriter.java',
    'OptionsConsumer.java',
    'OutOfProcessJsr199Javac.java',
    'OutOfProcessJarBackedJavac.java',
    'OutOfProcessJdkProvidedInMemoryJavac.java',
    'OutOfProcessJavacConnectionInterface.java',
    'StandardJavaFileManagerFactory.java',
    'TracingProcessorWrapper.java',
  ],
  immutable_types = [
    'JavaOptions',
    'JavacExecutionContext',
    'DirectToJarOutputSettings',
    'JavacOptions',
    'JavacVersion',
  ],
  tests = [
    '//test/com/facebook/buck/jvm/java:integration-slow',
    '//test/com/facebook/buck/jvm/java:java',
  ],
  autodeps = True,
  provided_deps = [
    # Event API is loaded by the bootstrapper at runtime; don't need to depend on it strongly
    '//src/com/facebook/buck/event/api:api',
  ],
  visibility = ['PUBLIC'],
)

java_library(
  name = 'packagefinder',
  srcs = [
    'DefaultJavaPackageFinder.java',
    'ResourcesRootPackageFinder.java',
    'JavaPackageFinderSerializer.java',
  ],
  autodeps = True,
  visibility = ['PUBLIC'],
)

java_library(
  name = 'rules',
  srcs = [
    'BuiltInJavac.java',
    'CalculateAbi.java',
    'DefaultJavaLibrary.java',
    'DefaultSuggestBuildRules.java',
    'ForkMode.java',
    'JarArchiveDependencySupplier.java',
    'JarFattener.java',
    'JarShape.java',
    'JavaBinary.java',
    'JavaBinaryDescription.java',
    'JavacOptionsFactory.java',
    'Javadoc.java',
    'JvmLibraryArg.java',
    'JavaLibraryDescription.java',
    'JavaLibraryClasspathProvider.java',
    'JavaLibraryRules.java',
    'JavaLibraryWithTests.java',
    'JavaSourceJar.java',
    'JavaTest.java',
    'JavaTestDescription.java',
    'Keystore.java',
    'KeystoreDescription.java',
    'MavenUberJar.java',
    'PrebuiltJar.java',
    'PrebuiltJarDescription.java',
    'ZipArchiveDependencySupplier.java',
  ],
  tests = [
    '//test/com/facebook/buck/jvm/java:integration-slow',
    '//test/com/facebook/buck/jvm/java:java',
  ],
  resources = [
    'FatJar.java',
    'FatJarMain.java',
    '//src/com/facebook/buck/util/exportedfiles:Nullable.java',
    '//src/com/facebook/buck/util/exportedfiles:Preconditions.java',
  ],
  autodeps = True,
  visibility = ['PUBLIC'],
)

java_immutables_library(
  name = 'steps',
  srcs = [
    'AbstractJUnitJvmArgs.java',
    'AccumulateClassNamesStep.java',
    'BaseCompileToJarStepFactory.java',
    'CalculateAbiStep.java',
    'ClasspathChecker.java',
    'CompileToJarStepFactory.java',
    'CopyResourcesStep.java',
    'GenerateCodeCoverageReportStep.java',
    'JavacOptionsAmender.java',
    'JavacToJarStepFactory.java',
    'JacocoConstants.java',
    'JarDirectoryStep.java',
    'JavacDirectToJarStep.java',
    'JavacStep.java',
    'JUnitStep.java',
    'TestType.java',
  ],
  immutable_types = [
    'JUnitJvmArgs',
  ],
  tests = [
    '//test/com/facebook/buck/jvm/java:integration-slow',
    '//test/com/facebook/buck/jvm/java:java',
  ],
  autodeps = True,
  visibility = ['PUBLIC'],
)

java_library(
  name = 'autodeps',
  srcs = [
    'SrcRootsFinder.java',
    'JavaFileParser.java',
    'JavaSymbolFinder.java',
  ],
  autodeps = True,
  visibility = [
    '//src/com/facebook/buck/cli:cli',
    '//src/com/facebook/buck/jvm/java/autodeps:',
    '//src/com/facebook/buck/jvm/java/intellij:intellij',
    '//test/com/facebook/buck/jvm/java:java',
    '//test/com/facebook/buck/jvm/java/autodeps:autodeps',
    '//test/com/facebook/buck/jvm/java/intellij:intellij',
  ],
)
