java_library(
    name = "fat-jar-main",
    srcs = [
        "FatJar.java",
        "FatJarMain.java",
    ],
    autodeps = False,  # See deps
    # Maximum compatibility
    source = "6",
    target = "6",
    deps = [
        # Don't add more dependencies beyond what we need for Infer! We package these sources and
        # compile them into fat JARs, so it's important that they don't bring along any additional
        # dependencies.
        "//src/com/facebook/buck/util/liteinfersupport:liteinfersupport",
    ],
)

java_library(
    name = "config",
    srcs = [
        "JavaBuckConfig.java",
    ],
    autodeps = True,
    visibility = ["PUBLIC"],
)

java_library(
    name = "javac-internals",
    srcs = [
        "ZipEntryJavaFileObject.java",
    ],
    autodeps = True,
)

java_library(
    name = "javac-sink",
    srcs = [
        "JavacEventSink.java",
    ],
    autodeps = True,
    visibility = ["PUBLIC"],
)

java_immutables_library(
    name = "support",
    srcs = [
        "AbstractDirectToJarOutputSettings.java",
        "AbstractJavaOptions.java",
        "AbstractJavacExecutionContext.java",
        "AbstractJavacOptions.java",
        "AbstractJavacPluginProperties.java",
        "AbstractJavacSpec.java",
        "AbstractJavacVersion.java",
        "AnnotationProcessingEvent.java",
        "AnnotationProcessingParams.java",
        "AnnotationProcessorFactory.java",
        "BuildsAnnotationProcessor.java",
        "BuiltInJavac.java",
        "ClassUsageFileWriter.java",
        "ClassUsageFileWriterSerializer.java",
        "ClassUsageTracker.java",
        "ConstantJavacProvider.java",
        "DefaultClassUsageFileReader.java",
        "DefaultClassUsageFileWriter.java",
        "DiagnosticCleaner.java",
        "DiagnosticPrettyPrinter.java",
        "DirectToJarOutputSettingsSerializer.java",
        "ExternalJavaRuntimeLauncher.java",
        "ExternalJavac.java",
        "ExternalOrJarBackedJavacProvider.java",
        "ForwardingStandardJavaFileManager.java",
        "HasClasspathEntries.java",
        "HasJavaAbi.java",
        "HasMavenCoordinates.java",
        "HasSources.java",
        "JarBackedJavac.java",
        "JarBackedJavacProvider.java",
        "JarDirectoryStepHelper.java",
        "JarFileObject.java",
        "JavaInMemoryFileManager.java",
        "JavaInMemoryFileObject.java",
        "JavaLibrary.java",
        "JavaNoOpFileObject.java",
        "JavaRuntimeLauncher.java",
        "Javac.java",
        "JavacErrorParser.java",
        "JavacEventSinkToBuckEventBusBridge.java",
        "JavacExecutionContextSerializer.java",
        "JavacProvider.java",
        "JdkProvidedInMemoryJavac.java",
        "Jsr199Javac.java",
        "Jsr199TracingBridge.java",
        "MavenPublishable.java",
        "NoOpClassUsageFileWriter.java",
        "OptionsConsumer.java",
        "OutOfProcessJarBackedJavac.java",
        "OutOfProcessJavacConnectionInterface.java",
        "OutOfProcessJdkProvidedInMemoryJavac.java",
        "OutOfProcessJsr199Javac.java",
        "ResolvedJavacPluginProperties.java",
        "StandardJavaFileManagerFactory.java",
        "TracingProcessorWrapper.java",
    ],
    autodeps = True,
    immutable_types = [
        "JavaOptions",
        "JavacExecutionContext",
        "DirectToJarOutputSettings",
        "JavacOptions",
        "JavacVersion",
    ],
    provided_deps = [
        # Event API is loaded by the bootstrapper at runtime; don't need to depend on it strongly
        "//src/com/facebook/buck/event/api:api",
    ],
    tests = [
        "//test/com/facebook/buck/jvm/java:integration-slow",
        "//test/com/facebook/buck/jvm/java:java",
    ],
    visibility = ["PUBLIC"],
)

java_library(
    name = "packagefinder",
    srcs = [
        "DefaultJavaPackageFinder.java",
        "JavaPackageFinderSerializer.java",
        "ResourcesRootPackageFinder.java",
    ],
    autodeps = True,
    visibility = ["PUBLIC"],
)

java_library(
    name = "rules",
    srcs = [
        "BuiltInJavac.java",
        "CalculateAbi.java",
        "DefaultJavaLibrary.java",
        "DefaultJavaLibraryBuilder.java",
        "DefaultSuggestBuildRules.java",
        "ForkMode.java",
        "JarArchiveDependencySupplier.java",
        "JarFattener.java",
        "JarShape.java",
        "JavaAnnotationProcessor.java",
        "JavaAnnotationProcessorDescription.java",
        "JavaBinary.java",
        "JavaBinaryDescription.java",
        "JavaLibraryClasspathProvider.java",
        "JavaLibraryDescription.java",
        "JavaLibraryRules.java",
        "JavaLibraryWithTests.java",
        "JavaSourceJar.java",
        "JavaTest.java",
        "JavaTestDescription.java",
        "JavacFactory.java",
        "JavacOptionsFactory.java",
        "Javadoc.java",
        "JvmLibraryArg.java",
        "Keystore.java",
        "KeystoreDescription.java",
        "MavenUberJar.java",
        "PrebuiltJar.java",
        "PrebuiltJarDescription.java",
        "ZipArchiveDependencySupplier.java",
    ],
    autodeps = True,
    resources = [
        "FatJar.java",
        "FatJarMain.java",
        "//src/com/facebook/buck/util/liteinfersupport:Nullable.java",
        "//src/com/facebook/buck/util/liteinfersupport:Preconditions.java",
    ],
    tests = [
        "//test/com/facebook/buck/jvm/java:integration-slow",
        "//test/com/facebook/buck/jvm/java:java",
    ],
    visibility = ["PUBLIC"],
)

java_immutables_library(
    name = "steps",
    srcs = [
        "AbstractJUnitJvmArgs.java",
        "AccumulateClassNamesStep.java",
        "BaseCompileToJarStepFactory.java",
        "CalculateAbiStep.java",
        "ClasspathChecker.java",
        "CompileToJarStepFactory.java",
        "CopyResourcesStep.java",
        "GenerateCodeCoverageReportStep.java",
        "JUnitStep.java",
        "JacocoConstants.java",
        "JarDirectoryStep.java",
        "JavacDirectToJarStep.java",
        "JavacOptionsAmender.java",
        "JavacStep.java",
        "JavacToJarStepFactory.java",
        "TestType.java",
    ],
    autodeps = True,
    immutable_types = [
        "JUnitJvmArgs",
    ],
    tests = [
        "//test/com/facebook/buck/jvm/java:integration-slow",
        "//test/com/facebook/buck/jvm/java:java",
    ],
    visibility = ["PUBLIC"],
)

java_library(
    name = "autodeps",
    srcs = [
        "JavaFileParser.java",
    ],
    autodeps = True,
    visibility = [
        "//src/com/facebook/buck/cli:cli",
        "//src/com/facebook/buck/ide/intellij:intellij",
        "//src/com/facebook/buck/jvm/java/autodeps:",
        "//test/com/facebook/buck/ide/intellij:intellij",
        "//test/com/facebook/buck/jvm/java:java",
        "//test/com/facebook/buck/jvm/java/autodeps:autodeps",
    ],
)
