java_library(
    name = "annotations",
    srcs = glob(["*.java"]),
    exported_deps = [
        "//third-party/java/immutables:immutables",
    ],
    required_for_source_only_abi = True,
    visibility = [
        "PUBLIC",
    ],
)
