load("//tools/build_rules:java_rules.bzl", "buck_java_library")
buck_java_library(
    name = "annotations",
    srcs = glob(["*.java"]),
    required_for_source_only_abi = True,
    visibility = [
        "PUBLIC",
    ],
    exported_deps = [
        "//third-party/java/immutables:immutables",
    ],
)
