java_library(
  name = 'testutil',
  srcs = glob(['*.java'], excludes=['*Test.java']),
  deps = [
    '//src/com/facebook/buck/cli:config',
    '//src/com/facebook/buck/cxx:platform',
    '//src/com/facebook/buck/cxx:rules',
    '//src/com/facebook/buck/halide:rules',
    '//src/com/facebook/buck/model:model',
    '//src/com/facebook/buck/rules:build_rule',
    '//src/com/facebook/buck/rules/coercer:coercer',
    '//test/com/facebook/buck/cli:FakeBuckConfig',
    '//test/com/facebook/buck/cxx:testutil',
    '//test/com/facebook/buck/rules:testutil',
    '//third-party/java/guava:guava',
  ],
  visibility = [
    '//test/...',
  ],
)

java_test(
  name = 'halide',
  srcs = glob(['*Test.java']),
  deps = [
    ':testutil',
    '//src/com/facebook/buck/cli:cli',
    '//src/com/facebook/buck/cxx:platform',
    '//src/com/facebook/buck/cxx:rules',
    '//src/com/facebook/buck/graph:graph',
    '//src/com/facebook/buck/halide:rules',
    '//src/com/facebook/buck/io:io',
    '//src/com/facebook/buck/model:model',
    '//src/com/facebook/buck/rules/args:args',
    '//src/com/facebook/buck/rules:build_rule',
    '//test/com/facebook/buck/cxx:testutil',
    '//test/com/facebook/buck/model:BuildTargetFactory',
    '//test/com/facebook/buck/rules:testutil',
    '//test/com/facebook/buck/testutil:testutil',
    '//third-party/java/guava:guava',
    '//third-party/java/junit:junit',
  ],
)
