load("//tools/build_rules:java_rules.bzl", "buck_java_binary", "buck_java_library")

buck_java_library(
    name = "installer_server",
    srcs = glob(["*.java"]),
    visibility = [
        "PUBLIC",
    ],
    exported_deps = [
        "//third-party/java/grpc:grpc-netty-shaded",
        "//src-gen:installer-proto",
        "//src/com/facebook/buck/util/types:types",
    ],
)
