load("//tools/build_rules:java_rules.bzl", "buck_java_library")

buck_java_library(
    name = "installer_server",
    srcs = glob(["Install*.java"]),
    visibility = [
        "PUBLIC",
    ],
    deps = ["//third-party/java/grpc:grpc-netty-shaded",
        "//src-gen:installer-proto",
    ]
)
