/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.facebook.buck.artifact_cache.thrift;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.12.0)")
public enum FetchResultType implements org.apache.thrift.TEnum {
  UNKNOWN(0),
  HIT(100),
  MISS(101),
  CONTAINS(102),
  SKIPPED(103),
  ERROR(104),
  MISS_ONLY_IN_MEMCACHE(105),
  MISS_IN_SLA(106),
  MISS_OUT_SLA(107),
  MISS_UNKNOWN(108);

  private final int value;

  private FetchResultType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static FetchResultType findByValue(int value) { 
    switch (value) {
      case 0:
        return UNKNOWN;
      case 100:
        return HIT;
      case 101:
        return MISS;
      case 102:
        return CONTAINS;
      case 103:
        return SKIPPED;
      case 104:
        return ERROR;
      case 105:
        return MISS_ONLY_IN_MEMCACHE;
      case 106:
        return MISS_IN_SLA;
      case 107:
        return MISS_OUT_SLA;
      case 108:
        return MISS_UNKNOWN;
      default:
        return null;
    }
  }
}
