load("//tools/build_rules:java_rules.bzl", "java_test")

TEST_SRCS = [
    "*Test.java",
]

java_test(
    name = "endtoend",
    srcs = glob(
        TEST_SRCS,
    ),
    env = {
        "TEST_BUCK": "$(location //programs:buck)",
    },
    deps = [
        "//src/com/facebook/buck/core/util/log:log",
        "//src/com/facebook/buck/util/environment:environment",
        "//test/com/facebook/buck/android:testutil",
        "//test/com/facebook/buck/testutil:testutil",
        "//test/com/facebook/buck/testutil/endtoend:testutil",
        "//third-party/java/junit:junit",
        "//third-party/java/nuprocess:nuprocess",
    ],
)
