load("//tools/build_rules:java_rules.bzl", "java_immutables_library", "java_test")

TEST_SRCS = [
    "*Test.java",
]

java_test(
    name = "endtoend",
    srcs = glob(
        TEST_SRCS,
    ),
    deps = [
        "//test/com/facebook/buck/android:testutil",
        "//test/com/facebook/buck/testutil:testutil",
        "//test/com/facebook/buck/testutil/endtoend:testutil",
        "//third-party/java/junit:junit",
    ],
)
