load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "config",
    srcs = glob(["*.java"]),
    exported_deps = [
        "//src/com/facebook/buck/core/config:config",
        "//src/com/facebook/buck/core/rulekey:rulekey",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
    ],
)
