load("//tools/build_rules:java_rules.bzl", "standard_java_test")

java_library(
    name = "testutil",
    srcs = glob(
        ["*.java"],
        exclude = ["*Test.java"],
    ),
    exported_deps = [
        "//src/com/facebook/buck/core/graph/transformation:transformation",
        "//src/com/facebook/buck/util/types:types",
        "//third-party/java/guava:guava",
    ],
    visibility = ["//test/..."],
)

java_test(
    name = "transformation_unit",
    srcs = glob(
        ["*Test.java"],
        exclude = ["DefaultAsyncTransformationEngineStackUseTest.java"],
    ),
    deps = [
        ":testutil",
        "//third-party/java/junit:junit",
    ],
)

java_test(
    name = "transformation_stackuse",
    srcs = ["DefaultAsyncTransformationEngineStackUseTest.java"],
    vm_args = ["-Xss500k"],  #explicitly set a small stack for testing stack use
    deps = [
        ":testutil",
        "//third-party/java/junit:junit",
    ],
)
