load("//tools/build_rules:java_rules.bzl", "java_immutables_library", "java_test")

java_test(
    name = "impl",
    srcs = glob(["*Test.java"]),
    has_immutable_types = True,
    deps = [
        "//src/com/facebook/buck/core/graph/transformation:transformation",
        "//src/com/facebook/buck/core/rules/graphbuilder:graphbuilder",
        "//src/com/facebook/buck/core/rules/graphbuilder/impl:impl",
        "//test/com/facebook/buck/core/cell:testutil",
        "//test/com/facebook/buck/core/graph/transformation:testutil",
        "//test/com/facebook/buck/core/model:testutil",
        "//test/com/facebook/buck/core/model/targetgraph:testutil",
        "//test/com/facebook/buck/core/rules/provider:testutil",
        "//test/com/facebook/buck/core/rules/resolver/impl:testutil",
        "//test/com/facebook/buck/core/toolchain/impl:testutil",
        "//test/com/facebook/buck/rules:testutil",
        "//test/com/facebook/buck/testutil:testutil",
        "//third-party/java/junit:junit",
    ],
)
