STANDARD_TEST_SRCS = [
  '**/*Test.java',
]

java_library(
  name = 'testutil',
  srcs = glob(['**/*.java'], excludes = STANDARD_TEST_SRCS),
  deps = [
    '//lib:guava',
    '//lib:ddmlib',
    '//lib:jyson',
    '//lib:jython',
  ],
  visibility = [
    'PUBLIC',
  ],
)

java_test(
  name = 'cli',
  srcs = glob(STANDARD_TEST_SRCS),
  resources = glob(['testdata/**/*']),
  source_under_test = [
    '//src/com/facebook/buck/cli:cli',
  ],
  deps = [
    '//lib:args4j',
    '//lib:ddmlib',
    '//lib:easymock',
    '//lib:guava',
    '//lib:hamcrest-core',
    '//lib:hamcrest-library',
    '//lib:ini4j',
    '//lib:jackson-core',
    '//lib:jackson-databind',
    '//lib:junit',
    '//src/com/facebook/buck/android:rules',
    '//src/com/facebook/buck/cli:cli',
    '//src/com/facebook/buck/command:command',
    '//src/com/facebook/buck/event:event',
    '//src/com/facebook/buck/graph:graph',
    '//src/com/facebook/buck/java:rules',
    '//src/com/facebook/buck/java:support',
    '//src/com/facebook/buck/model:model',
    '//src/com/facebook/buck/parser:parser',
    '//src/com/facebook/buck/parser:project',
    '//src/com/facebook/buck/parser:support',
    '//src/com/facebook/buck/rules:rules',
    '//src/com/facebook/buck/rules:types',
    '//src/com/facebook/buck/step:step',
    '//src/com/facebook/buck/util:constants',
    '//src/com/facebook/buck/util:exceptions',
    '//src/com/facebook/buck/util:io',
    '//src/com/facebook/buck/util:util',
    '//test/com/facebook/buck/model:BuildTargetFactory',
    '//test/com/facebook/buck/parser:PartialGraphFactory',
    '//test/com/facebook/buck/rules:testutil',
    '//test/com/facebook/buck/testutil:testutil',
    '//test/com/facebook/buck/testutil/integration:integration',
    ':testutil',
  ],
)
