STANDARD_TEST_SRCS = [
  '**/*Test.java',
]

java_library(
  name = 'testutil',
  srcs = glob(['**/*.java'], excludes = STANDARD_TEST_SRCS),
  deps = [
    '//lib:guava',
    '//lib:ddmlib',
    '//lib:jyson',
    '//lib:jython',
  ],
  visibility = [
    'PUBLIC',
  ],
)

java_test(
  name = 'cli',
  srcs = glob(STANDARD_TEST_SRCS),
  vm_args = [
    '-Dbuck.path_to_buck_py=src/com/facebook/buck/parser/buck.py',
  ],
  source_under_test = [
    '//src/com/facebook/buck/cli:cli',
  ],
  deps = [
    '//lib:args4j',
    '//lib:ddmlib',
    '//lib:easymock',
    '//lib:guava',
    '//lib:jackson-core',
    '//lib:jackson-databind',
    '//lib:junit',
    '//src/com/facebook/buck/android:android',
    '//src/com/facebook/buck/cli:cli',
    '//src/com/facebook/buck/graph:graph',
    '//src/com/facebook/buck/model:model',
    '//src/com/facebook/buck/parser:core',
    '//src/com/facebook/buck/parser:parser',
    '//src/com/facebook/buck/rules:core',
    '//src/com/facebook/buck/rules:java',
    '//src/com/facebook/buck/rules:rules',
    '//src/com/facebook/buck/util:exceptions',
    '//src/com/facebook/buck/util:io',
    '//src/com/facebook/buck/util:util',
    '//test/com/facebook/buck/model:BuildTargetFactory',
    '//test/com/facebook/buck/parser:PartialGraphFactory',
    '//test/com/facebook/buck/rules:testutil',
    ':testutil',
  ],
)
