java_immutables_library(
  name = 'testutil',
  srcs = glob(
    ['*.java'],
    excludes = ['*Test.java'],
  ),
  autodeps = True,
  immutable_types = [
    'FakeHaskellConfig',
  ],
)

java_test(
  name = 'haskell',
  srcs = glob(['*Test.java']),
  autodeps = True,
)
