java_immutables_library(
  name = 'testutil',
  srcs = glob(['*.java'], excludes=['*Test.java']),
  immutable_types = [
    'FakeHaskellConfig',
  ],
  autodeps = True,
)

java_test(
  name = 'haskell',
  srcs = glob(['*Test.java']),
  autodeps = True,
)
