java_immutables_library(
    name = "testutil",
    srcs = [
        "AbstractFakeLuaConfig.java",
        "CxxLuaExtensionBuilder.java",
        "LuaBinaryBuilder.java",
        "LuaLibraryBuilder.java",
    ],
    autodeps = True,
    immutable_types = [
        "FakeLuaConfig",
    ],
    visibility = [
        "//test/...",
    ],
)

java_test(
    name = "lua",
    srcs = glob(["*Test.java"]),
    autodeps = True,
    labels = ["long_running"],
)
