java_immutables_library(
  name = 'testutil',
  srcs = [
    'CxxLuaExtensionBuilder.java',
    'LuaBinaryBuilder.java',
    'LuaLibraryBuilder.java',
  ],
  immutable_srcs = [
    'AbstractFakeLuaConfig.java',
  ],
  autodeps = True,
  visibility = [
    '//test/...',
  ],
)

java_test(
  name = 'lua',
  srcs = glob(['*Test.java']),
  autodeps = True,
)
