java_immutables_library(
  name = 'testutil',
  srcs = glob(['*.java'], excludes=['*Test.java']),
  deps = [
    '//src/com/facebook/buck/lua:lua',
    '//src/com/facebook/buck/model:model',
    '//src/com/facebook/buck/parser:rule_pattern',
    '//src/com/facebook/buck/rules:build_rule',
    '//src/com/facebook/buck/rules/coercer:coercer',
    '//test/com/facebook/buck/model:BuildTargetFactory',
    '//test/com/facebook/buck/rules:testutil',
  ],
)

java_test(
  name = 'lua',
  srcs = glob(['*Test.java']),
  deps = [
    ':testutil',
    '//src/com/facebook/buck/cli:cli',
    '//src/com/facebook/buck/cli:config',
    '//src/com/facebook/buck/io:io',
    '//src/com/facebook/buck/lua:lua',
    '//src/com/facebook/buck/model:model',
    '//src/com/facebook/buck/parser:rule_pattern',
    '//src/com/facebook/buck/rules:build_rule',
    '//src/com/facebook/buck/rules/coercer:coercer',
    '//src/com/facebook/buck/rules:rules',
    '//test/com/facebook/buck/cli:FakeBuckConfig',
    '//test/com/facebook/buck/model:BuildTargetFactory',
    '//test/com/facebook/buck/rules:testutil',
    '//test/com/facebook/buck/testutil/integration:integration',
    '//third-party/java/guava:guava',
    '//third-party/java/hamcrest:hamcrest',
    '//third-party/java/junit:junit',
  ],
)
