java_immutables_library(
    name = "haskell",
    srcs = glob(["*.java"]),
    autodeps = True,
    immutable_types = [
        "HaskellVersion",
        "HaskellCompileInput",
    ],
    visibility = ["PUBLIC"],
)
