java_immutables_library(
  name = 'testutil',
  srcs = [
    'AbstractType.java',
    'DeprecatedType.java',
  ],
  immutable_types = [
    'Type',
  ],
  autodeps = True,
  tests = [
    '//test/com/facebook/buck/immutables:test',
  ],
  visibility = [
    '//test/...',
  ],
)

java_test(
  name = 'test',
  srcs = glob(['*Test.java']),
  autodeps = True,
)
