java_immutables_library(
    name = "testutil",
    srcs = [
        "AbstractType.java",
    ],
    tests = [
        "//test/com/facebook/buck/immutables:test",
    ],
    visibility = [
        "//test/...",
    ],
    deps = [
        "//src/com/facebook/buck/util/immutables:immutables",
        "//third-party/java/immutables:immutables",
    ],
)

java_test(
    name = "test",
    srcs = glob(["*Test.java"]),
    deps = [
        "//src/com/facebook/buck/util/immutables:immutables",
        "//test/com/facebook/buck/immutables:testutil",
        "//third-party/java/guava:guava",
        "//third-party/java/immutables:immutables",
        "//third-party/java/junit:junit",
    ],
)
