load("//tools/build_rules:java_rules.bzl", "standard_java_test")

standard_java_test(
    name = "impl",
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/core/toolchain/tool/impl:impl",
        "//src/com/facebook/buck/core/toolchain/toolprovider/impl:impl",
        "//src/com/facebook/buck/cxx/toolchain/impl:impl",
        "//src/com/facebook/buck/cxx/toolchain/linker/impl:impl",
        "//test/com/facebook/buck/core/config:FakeBuckConfig",
        "//test/com/facebook/buck/core/rules/resolver/impl:testutil",
        "//test/com/facebook/buck/cxx/toolchain:testutil",
        "//test/com/facebook/buck/io/filesystem/impl:testutil",
        "//third-party/java/junit:junit",
    ],
)
