java_library(
    name = "json",
    srcs = glob(["*.java"]),
    tests = [
        "//test/com/facebook/buck/skylark/json:json",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//third-party/java/bazel:bazel",
        "//third-party/java/jackson:jackson-annotations",
        "//third-party/java/jackson:jackson-databind",
        "//third-party/java/jsr:jsr305",
    ],
)
