load("//tools/build_rules:java_rules.bzl", "buck_java_library")

buck_java_library(
    name = "signatures",
    srcs = ["DummyFunction.java"],
    visibility = ["//tools/documentation_generator/test/..."],
    deps = [
        "//starlark:bazel",
    ],
)
