python_binary(
    name = "munger",
    main = "munger.py",
    visibility = [
        "PUBLIC",
    ],
)

python_binary(
    name = "append_with_copy",
    main = "append_with_copy.py",
    visibility = [
        "PUBLIC",
    ],
)

python_test(
    name = "test",
    srcs = glob(["test_*.py"]),
    deps = [
        ":lib",
    ],
)

python_library(
    name = "lib",
    srcs = [
        "append_with_copy.py",
        "munger.py",
    ],
)
