load("//tools/build_rules:java_rules.bzl", "buck_java_library")
buck_java_library(
    name = "impl",
    srcs = glob(["*.java"]),
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/core/rules/configsetting:configsetting",
        "//src/com/facebook/buck/util/string:string",
        "//third-party/java/jsr:jsr305",
    ],
    exported_deps = [
        "//src/com/facebook/buck/core/rules/config:config",
        "//src/com/facebook/buck/core/select:select",
    ],
)
