java_library(
    name = "testutil",
    srcs = glob(
        ["*.java"],
        exclude = ["*Test.java"],
    ),
    exported_deps = [
        "//src/com/facebook/buck/android/toolchain/impl:impl",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/android:helpers",
        "//test/com/facebook/buck/android:utils",
        "//test/com/facebook/buck/config:FakeBuckConfig",
        "//test/com/facebook/buck/rules/keys/config:testutil",
        "//test/com/facebook/buck/testutil:testutil",
        "//test/com/facebook/buck/toolchain/impl:testutil",
    ],
)
