load("//tools/build_rules:module_rules.bzl", "buck_module")

buck_module(
    name = "gwt",
    srcs = glob(["*.java"]),
    provided_deps = [
        "//src/com/facebook/buck/core/description/arg:arg",
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/core/model/impl:impl",
        "//src/com/facebook/buck/core/model/targetgraph:targetgraph",
        "//src/com/facebook/buck/core/rules:rules",
        "//src/com/facebook/buck/core/util/graph:graph",
        "//src/com/facebook/buck/io:io",
        "//src/com/facebook/buck/jvm/core:core",
        "//src/com/facebook/buck/jvm/java:steps",
        "//src/com/facebook/buck/jvm/java:support",
        "//src/com/facebook/buck/jvm/java/toolchain:toolchain",
        "//src/com/facebook/buck/parser:rule_pattern",
        "//src/com/facebook/buck/shell:steps",
        "//src/com/facebook/buck/step:step",
        "//src/com/facebook/buck/step/fs:fs",
        "//third-party/java/guava:guava",
        "//third-party/java/infer-annotations:infer-annotations",
    ],
    visibility = ["//test/com/facebook/buck/features/gwt:gwt"],
)
