load("//tools/build_rules:java_rules.bzl", "buck_java_library")

buck_java_library(
    name = "testutil",
    srcs = glob(
        ["*.java"],
        exclude = [
            "*Benchmark.java",
            "*Test.java",
        ],
    ),
    visibility = ["//test/..."],
    exported_deps = [
        "//src/com/facebook/buck/event/console:console",
    ],
)
