load("//tools/build_rules:java_rules.bzl", "buck_java_library")

buck_java_library(
    name = "testutil",
    srcs = glob(["*.java"]),
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/util:util",
        "//third-party/java/guava:guava",
        "//third-party/java/junit:junit",
    ],
    exported_deps = [
        "//src/com/facebook/buck/sandbox:sandbox",
    ],
)
