load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "parser",
    srcs = glob(["*.java"]),
    exported_deps = [
        "//src/com/facebook/buck/core/graph/transformation:transformation",
    ],
    tests = [
        "//test/com/facebook/buck/core/parser:parser",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/core/files:files",
        "//src/com/facebook/buck/core/parser/buildtargetparser:buildtargetparser",
        "//src/com/facebook/buck/io/file:file",
        "//third-party/java/guava:guava",
    ],
)
