java_library(
  name = 'model',
  srcs = glob(['*.java']),
  deps = [
    '//src/com/facebook/buck/util:constants',
    '//src/com/facebook/buck/util:exceptions',
    '//src/com/facebook/buck/util:io',
    '//src/com/facebook/buck/util:util',
    '//lib:guava',
    '//lib:jackson-annotations',
    '//lib:jackson-core',
    '//lib:jackson-databind',
    '//lib:jsr305',
  ],
  exported_deps = [
    '//lib:jackson-annotations',
  ],
  visibility = ['PUBLIC'],
)
