BUILD_ID_SRCS = [ 'BuildId.java' ]

java_library(
  name = 'build_id',
  srcs = BUILD_ID_SRCS,
  autodeps = True,
  exported_deps = [
    '//third-party/java/jackson:jackson-databind',
  ],
  visibility = ['PUBLIC'],
)

java_immutables_library(
  name = 'model',
  srcs = glob(['*.java'], excludes = BUILD_ID_SRCS),
  tests = [
    '//test/com/facebook/buck/model:model',
  ],
  autodeps = True,
  exported_deps = [
    '//third-party/java/jackson:jackson-annotations',
  ],
  visibility = ['PUBLIC'],
)
