load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "config",
    srcs = glob(["*.java"]),
    exported_deps = [
        "//src/com/facebook/buck/core/rules:rules",
        "//src/com/facebook/buck/core/toolchain/tool:tool",
        "//src/com/facebook/buck/core/toolchain/toolprovider:toolprovider",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/core/config:config",
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/core/toolchain/tool/impl:impl",
        "//src/com/facebook/buck/core/toolchain/toolprovider/impl:impl",
    ],
)
