java_immutables_library(
    name = "config",
    srcs = glob(["*.java"]),
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/config:config",
        "//src/com/facebook/buck/model:model",
        "//src/com/facebook/buck/rules:build_rule",
    ],
)
