load("//tools/build_rules:java_rules.bzl", "buck_java_library")

buck_java_library(
    name = "immutables",
    srcs = glob(["*.java"]),
    required_for_source_only_abi = True,
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//third-party/java/jackson:jackson-databind",
    ],
    exported_deps = [
        "//third-party/java/immutables:immutables",
        "//third-party/java/jackson:jackson-annotations",
    ],
)
