java_library(
    name = "immutables",
    srcs = glob(["*.java"]),
    exported_deps = [
        "//third-party/java/immutables:immutables",
        "//third-party/java/jackson:jackson-annotations",
    ],
    required_for_source_only_abi = True,
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//third-party/java/jackson:jackson-databind",
    ],
)
