load("//tools/build_rules:java_rules.bzl", "standard_java_test")

standard_java_test(
    name = "command",
    deps = [
        "//src/com/facebook/buck/command:command",
        "//src/com/facebook/buck/core/build/engine/cache/manager:manager",
        "//src/com/facebook/buck/core/cell:cell",
        "//src/com/facebook/buck/core/exceptions:exceptions",
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/util/json:json",
        "//src/com/facebook/buck/util/string:string",
        "//test/com/facebook/buck/core/cell:testutil",
        "//test/com/facebook/buck/core/model:testutil",
        "//test/com/facebook/buck/core/rules/impl:testutil",
        "//test/com/facebook/buck/core/rules/resolver/impl:testutil",
        "//third-party/java/junit:junit",
    ],
)
