java_test(
  name = 'command',
  srcs = glob(['*.java']),
  source_under_test = [
    '//src/com/facebook/buck/command:command',
  ],
  deps = [
    '//lib:easymock',
    '//lib:junit',
    '//src/com/facebook/buck/command:command',
    '//test/com/facebook/buck/model:BuildTargetFactory',
    '//test/com/facebook/buck/parser:PartialGraphFactory',
    '//test/com/facebook/buck/testutil:testutil',
  ],
)
