load("//tools/build_rules:python_rules.bzl", "pytest_test")

pytest_test(
    name = "api_test",
    srcs = glob(["*test.py"]),
    resources = [
        "test_script.py",
    ],
    deps = [
        "//buck_api:api",
        "//third-party/py/pytest-asyncio:pytest-asyncio",
    ],
)

export_file(
    name = "test_script.py",
    src = "test_script.py",
    visibility = [
        "PUBLIC",
    ],
)
