load("//tools/build_rules:java_rules.bzl", "java_test")

java_test(
    name = "raw",
    srcs = glob(["*Test.java"]),
    deps = [
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/core/model/targetgraph:targetgraph",
        "//src/com/facebook/buck/core/model/targetgraph/impl:impl",
        "//src/com/facebook/buck/util/json:json",
        "//third-party/java/junit:junit",
    ],
)
