load("//tools/build_rules:java_rules.bzl", "java_test")

java_test(
    name = "core",
    srcs = glob(["*.java"]),
    deps = [
        "//src/com/facebook/buck/core/filesystems:filesystems",
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/jvm/core:core",
        "//test/com/facebook/buck/core/model:testutil",
        "//test/com/facebook/buck/testutil:testutil",
        "//third-party/java/hamcrest:java-hamcrest",
        "//third-party/java/immutables:immutables",
        "//third-party/java/junit:junit",
    ],
)
