java_library(
  name = 'steps',
  srcs = glob(['*Step.java']),
  deps = [
    '//lib:guava',
    '//lib:jsr305',
    '//src/com/facebook/buck/shell:steps',
    '//src/com/facebook/buck/step:step',
    '//src/com/facebook/buck/step/fs:fs',
    '//src/com/facebook/buck/util:io',
  ],
  visibility = [
    '//src/com/facebook/buck/android/...',
    '//test/com/facebook/buck/zip:zip',
  ],
)