genrule(
    name='build_python_lib',
    # note: this filename is important; otherwise pex won't be able to find the
    # package when starting.
    out='package-0.1-py2.7.egg',
    srcs=glob(['package/**/*.py', 'setup.py']),
    bash='python setup.py bdist_egg && cp dist/*.egg $OUT',
    cmd_exe='python.exe setup.py bdist_egg && copy dist/*.egg %OUT%',
)

prebuilt_python_library(
    name='python_lib',
    binary_src=':build_python_lib',
)

python_binary(
    name='main',
    main='main.py',
    deps=[':python_lib'],
)
