STANDARD_TEST_SRCS = [
  '**/*Test.java',
]

java_test(
  name = 'maven',
  srcs = glob(STANDARD_TEST_SRCS),
  deps = [
    ':testutil',
    '//src/com/facebook/buck/cli:config',
    '//src/com/facebook/buck/event:event',
    '//src/com/facebook/buck/file:downloader',
    '//src/com/facebook/buck/file:file',
    '//src/com/facebook/buck/io:io',
    '//src/com/facebook/buck/java:rules',
    '//src/com/facebook/buck/json:json',
    '//src/com/facebook/buck/maven:maven',
    '//src/com/facebook/buck/parser:config',
    '//src/com/facebook/buck/python:config',
    '//src/com/facebook/buck/rules:build_rule',
    '//src/com/facebook/buck/util:io',
    '//test/com/facebook/buck/cli:FakeBuckConfig',
    '//test/com/facebook/buck/event:testutil',
    '//test/com/facebook/buck/testutil/integration:integration',
    '//test/com/facebook/buck/testutil:testutil',
    '//third-party/java/aether:aether-api',
    '//third-party/java/guava:guava',
    '//third-party/java/hamcrest:hamcrest',
    '//third-party/java/jetty:jetty',
    '//third-party/java/junit:junit',
  ],
)

java_library(
  name = 'testutil',
  srcs = glob(['*.java'], excludes = STANDARD_TEST_SRCS),
  deps = [
      '//src/com/facebook/buck/maven:maven',
      '//src/com/facebook/buck/io:io',
      '//test/com/facebook/buck/testutil/integration:integration',
      '//test/com/facebook/buck/testutil:testutil',
      '//third-party/java/aether:aether-api',
      '//third-party/java/guava:guava',
      '//third-party/java/hamcrest:hamcrest',
      '//third-party/java/jetty:jetty',
      '//third-party/java/junit:junit',
  ],
  visibility = [
      'PUBLIC',
  ]
)
