# TODO(mbolin): Replace this with standard_java_test() until prebuilt_jar() supports exported_deps.
# See //third-party/java/maven:maven-model for an explanation of why this causes issues.

java_library(
    name = "testutil",
    srcs = glob(
        ["*.java"],
        excludes = ["*Test.java"],
    ),
    autodeps = True,
    exported_deps = [
        "//src/com/facebook/buck/maven:maven",
        "//test/com/facebook/buck/testutil/integration:util",
    ],
    visibility = [
        "//test/...",
    ],
)

java_test(
    name = "maven",
    srcs = glob(["*Test.java"]),
    autodeps = True,
    resources = glob(
        ["testdata/**"],
        include_dotfiles = True,
    ),
    deps = [
        "//src/com/facebook/buck/cli:config",
        "//src/com/facebook/buck/file:downloader",
        "//src/com/facebook/buck/file:file",
        "//src/com/facebook/buck/io:MorePaths.java",
        "//src/com/facebook/buck/io:executable-finder",
        "//src/com/facebook/buck/io:io",
        "//src/com/facebook/buck/json:json",
        "//src/com/facebook/buck/jvm/java:rules",
        "//src/com/facebook/buck/jvm/java:support",
        "//src/com/facebook/buck/maven:maven",
        "//src/com/facebook/buck/maven:util",
        "//src/com/facebook/buck/model:model",
        "//src/com/facebook/buck/parser:config",
        "//src/com/facebook/buck/parser:rule_pattern",
        "//src/com/facebook/buck/python:config",
        "//src/com/facebook/buck/rules/coercer:coercer",
        "//src/com/facebook/buck/rules:build_rule",
        "//src/com/facebook/buck/step:step",
        "//src/com/facebook/buck/util:object_mapper",
        "//test/com/facebook/buck/cli:FakeBuckConfig",
        "//test/com/facebook/buck/event:testutil",
        "//test/com/facebook/buck/jvm/java:testutil",
        "//test/com/facebook/buck/maven:testutil",
        "//test/com/facebook/buck/model:testutil",
        "//test/com/facebook/buck/rules:testutil",
        "//test/com/facebook/buck/testutil/integration:util",
        "//test/com/facebook/buck/testutil:testutil",
        "//third-party/java/aether:aether-api",
        "//third-party/java/args4j:args4j",
        "//third-party/java/guava:guava",
        "//third-party/java/hamcrest:java-hamcrest",
        "//third-party/java/jsr:jsr305",
        "//third-party/java/junit:junit",
        "//third-party/java/maven:maven-model",
        # This is due to the bug mentioned above.
        "//third-party/java/plexus:plexus-utils",
    ],
)
