java_test(
  name = 'macros',
  srcs = glob(['*.java']),
  source_under_test = [
    '//src/com/facebook/buck/rules/macros:macros',
  ],
  deps = [
    '//third-party/java/guava:guava',
    '//third-party/java/junit:junit',
    '//src/com/facebook/buck/rules/macros:macros',
    '//src/com/facebook/buck/model:model',
    '//src/com/facebook/buck/parser:rule_pattern',
    '//src/com/facebook/buck/rules:build_rule',
    '//src/com/facebook/buck/rules:rules',
    '//src/com/facebook/buck/util:constants',
    '//src/com/facebook/buck/util:io',
    '//test/com/facebook/buck/java:testutil',
    '//test/com/facebook/buck/model:BuildTargetFactory',
    '//test/com/facebook/buck/rules:testutil',
    '//test/com/facebook/buck/testutil:testutil',
  ],
)
