STANDARD_TEST_SRCS = [
  '*Test.java',
]

java_library(
  name = 'testutil',
  srcs = glob(['*.java'], excludes = STANDARD_TEST_SRCS),
  deps = [
    '//third-party/java/guava:guava',
    '//third-party/java/hamcrest:hamcrest',
    '//third-party/java/junit:junit',
    '//third-party/java/jackson:jackson',
  ],
  visibility = [
    'PUBLIC',
  ],
)

java_test(
  name = 'json',
  srcs = glob(STANDARD_TEST_SRCS),
  deps = [
    '//src/com/facebook/buck/io:io',
    '//src/com/facebook/buck/json:json',
    '//test/com/facebook/buck/testutil:testutil',
    '//third-party/java/gson:gson',
    '//third-party/java/guava:guava',
    '//third-party/java/hamcrest:hamcrest',
    '//third-party/java/junit:junit',
  ],
)
