standard_java_testutil(
    name = "testutil",
    exported_deps = [
        "//third-party/java/hamcrest:java-hamcrest",
        "//third-party/java/jackson:jackson-databind",
    ],
    deps = ["//src/com/facebook/buck/util:object_mapper"],
)

standard_java_test(
    name = "json",
    deps = [
        "//src/com/facebook/buck/io:io",
        "//src/com/facebook/buck/json:json",
        "//test/com/facebook/buck/testutil:testutil",
        "//third-party/java/gson:gson",
        "//third-party/java/guava:guava",
        "//third-party/java/hamcrest:java-hamcrest",
        "//third-party/java/junit:junit",
    ],
)
