java_library(
  name = 'json',
  srcs = glob(['*.java']),
  deps = [
    '//lib:guava',
    '//lib:jsr305',
    '//src/com/facebook/buck/rules:build_rule',
    '//src/com/facebook/buck/util/environment:environment',
    '//src/com/facebook/buck/util:constants',
    '//src/com/facebook/buck/util:exceptions',
    '//src/com/facebook/buck/util:io',
    '//src/com/facebook/buck/util:util',
    '//third-party/java/gson:gson',
  ],
  visibility = [
    'PUBLIC',
  ],
)
