standard_java_library(
    name = "args",
    immutable_types = [
        "StringArg",
        "StringWithMacrosArg",
    ],
    deps = [
        "//src/com/facebook/buck/model:macros",
        "//src/com/facebook/buck/model:model",
        "//src/com/facebook/buck/rules:build_rule",
        "//src/com/facebook/buck/rules:interfaces",
        "//src/com/facebook/buck/rules/macros:macros",
        "//src/com/facebook/buck/rules/macros:types",
        "//src/com/facebook/buck/shell:worker_tool",
        "//src/com/facebook/buck/util:exceptions",
        "//src/com/facebook/buck/util:util",
        "//src/com/facebook/buck/versions:translator",
    ],
)
