load("//tools/build_rules:java_rules.bzl", "buck_java_library")
buck_java_library(
    name = "plugin",
    srcs = glob(
        ["*.java"],
    ),
    visibility = ["PUBLIC"],
    exported_deps = [
        "//third-party/java/pf4j:pf4j",
    ],
)
