load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "model",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/core/util:util",
        "//src/com/facebook/buck/log/views:views",
        "//third-party/java/jackson:jackson-annotations",
        "//third-party/java/jackson:jackson-databind",
        "//third-party/java/jsr:jsr305",
    ],
    exported_deps = [
        "//src/com/facebook/buck/core/cell/name:name",
        "//src/com/facebook/buck/core/exceptions:exceptions",
        "//src/com/facebook/buck/core/filesystems:filesystems",
        "//src/com/facebook/buck/core/path:path",
        "//src/com/facebook/buck/core/rulekey:rulekey",
        "//src/com/facebook/buck/core/util/immutables:immutables",
    ],
)
