load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "model",
    srcs = glob(["*.java"]),
    exported_deps = [
        "//src/com/facebook/buck/core/exceptions:exceptions",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//third-party/java/jackson:jackson-annotations",
        "//third-party/java/jackson:jackson-databind",
        "//third-party/java/jsr:jsr305",
    ],
)
