load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "model",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    deps = [
        "//third-party/java/jsr:jsr305",
    ],
)
