java_library(
    name = "headermap",
    srcs = ["HeaderMap.java"],
    autodeps = True,
    tests = [
        "//test/com/facebook/buck/apple/clang:headermap",
    ],
    visibility = [
        "PUBLIC",
    ],
)

java_library(
    name = "printheadermap",
    srcs = ["PrintHeaderMap.java"],
    autodeps = True,
    visibility = [
        "PUBLIC",
    ],
)

java_binary(
    name = "hmaptool",
    main_class = "com.facebook.buck.apple.clang.PrintHeaderMap",
    visibility = [
        "PUBLIC",
    ],
    deps = [
        ":printheadermap",
    ],
)
