EMPTY_CONFIGS = {
  'Debug': {},
  'Release': {},
}

apple_library(
  name = 'Dep2',
  configs = EMPTY_CONFIGS,
  srcs = [],
  frameworks = [],
  deps = [],
  tests = [':Dep2Tests'],
  visibility = ['PUBLIC'],
)

apple_test(
  name = 'Dep2Tests',
  extension = 'octest',
  configs = EMPTY_CONFIGS,
  srcs = [],
  frameworks = [],
  deps = [
    ':Dep2',
  ],
)

xcode_project_config(
  name = 'project',
  project_name = 'Libraries',
  rules = [
    ':Dep2',
    ':Dep2Tests',
  ],
)
