java_library(
    name = "isolated",
    srcs = glob(["*.java"]),
    visibility = [
        "//src/com/facebook/buck/external/...",
        "//test/com/facebook/buck/...",
    ],
    deps = [
        "//src-gen:downward-model",
        "//src/com/facebook/buck/core/util/log:log",
        "//src/com/facebook/buck/downwardapi/protocol:protocol",
        "//src/com/facebook/buck/downwardapi/utils:utils",
        "//src/com/facebook/buck/event:event",
        "//src/com/facebook/buck/event:interfaces",
        "//src/com/facebook/buck/event/chrome_trace:chrome_trace",
        "//src/com/facebook/buck/step:step",
        "//src/com/facebook/buck/util:process_executor",
        "//src/com/facebook/buck/util/concurrent:concurrent",
        "//src/com/facebook/buck/util/timing:timing",
        "//third-party/java/guava:guava",
    ],
)
