load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "bgtasks",
    srcs = glob(["*.java"]),
    tests = [
        "//test/com/facebook/buck/support/bgtasks:bgtasks",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/log:api",
    ],
)
