java_library(
    name = "hashing",
    srcs = glob(["*.java"]),
    exported_deps = [
        "//src/com/facebook/buck/core/io:io",
    ],
    tests = [
        "//test/com/facebook/buck/util/hashing:hashing",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/io:io",
        "//src/com/facebook/buck/io/file:file",
        "//src/com/facebook/buck/io/filesystem:filesystem",
        "//third-party/java/guava:guava",
    ],
)
