UTIL_SRCS = [
  'FakeClock.java',
  'IncrementingFakeClock.java',
  'SettableFakeClock.java',
]

java_library(
  name = 'testutil',
  srcs = UTIL_SRCS,
  exported_deps = [
    '//src/com/facebook/buck/timing:timing',
  ],
  visibility = [
    '//test/...',
  ],
)

java_test(
  name = 'timing',
  srcs = glob(['*Test.java']),
  source_under_test = [
    ':testutil'
  ],
  deps = [
    ':testutil',
    '//third-party/java/hamcrest:hamcrest',
    '//third-party/java/junit:junit',
    '//src/com/facebook/buck/timing:timing'
  ]
)
