load("//tools/build_rules:java_rules.bzl", "buck_java_library")
buck_java_library(
    name = "collect",
    srcs = glob(["*.java"]),
    tests = [
        "//test/com/facebook/buck/util/collect:collect",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//third-party/java/guava:guava",
        "//third-party/java/jsr:jsr305",
    ],
)
