java_library(
    name = "exception",
    srcs = glob(["*.java"]),
    exported_deps = [
        "//src/com/facebook/buck/core/exceptions:exceptions",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/util/string:string",
        "//third-party/java/guava:guava",
    ],
)
