load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "elf",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/util:util",
        "//third-party/java/guava:guava",
    ],
)
