java_library(
    name = "function",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/skylark/io:io",
        "//src/com/facebook/buck/skylark/packages:packages",
        "//src/com/facebook/buck/skylark/parser/context:context",
        "//src/com/facebook/buck/util:util",
        "//src/com/facebook/buck/util/environment:platform",
        "//third-party/java/bazel:skylark-lang",
        "//third-party/java/guava:guava",
        "//third-party/java/jsr:jsr305",
    ],
)
