java_library(
    name = "isolatedsteps",
    srcs = glob(["*.java"]),
    visibility = [
        "//src/com/facebook/buck/...",
        "//test/com/facebook/buck/...",
    ],
    deps = [
    ],
    exported_deps = [
        "//src/com/facebook/buck/core/build/execution/context:context",
        "//src/com/facebook/buck/core/util/log:log",
        "//src/com/facebook/buck/step:step",
    ],
)
