standard_java_testutil(
    name = "testutil",
    exported_deps = [
        "//src/com/facebook/buck/js:js",
        "//src/com/facebook/buck/model:model",
        "//src/com/facebook/buck/model:simple_types",
        "//src/com/facebook/buck/parser:rule_pattern",
        "//src/com/facebook/buck/rules:build_rule",
        "//test/com/facebook/buck/rules:testutil",
        "//third-party/java/guava:guava",
    ],
    deps = [
        "//src/com/facebook/buck/util:util",
        "//test/com/facebook/buck/model:testutil",
        "//test/com/facebook/buck/shell:testutil",
        "//test/com/facebook/buck/testutil:testutil",
    ],
)

standard_java_test(
    name = "js",
    deps = [
        "//src/com/facebook/buck/io:io",
        "//src/com/facebook/buck/js:js",
        "//src/com/facebook/buck/model:model",
        "//src/com/facebook/buck/model:simple_types",
        "//src/com/facebook/buck/parser:rule_pattern",
        "//src/com/facebook/buck/rules:build_rule",
        "//src/com/facebook/buck/shell:worker",
        "//src/com/facebook/buck/step:step",
        "//src/com/facebook/buck/util:exceptions",
        "//src/com/facebook/buck/util:util",
        "//src/com/facebook/buck/util/environment:platform",
        "//test/com/facebook/buck/android:testutil",
        "//test/com/facebook/buck/js:testutil",
        "//test/com/facebook/buck/model:testutil",
        "//test/com/facebook/buck/rules:testutil",
        "//test/com/facebook/buck/testutil/integration:util",
        "//third-party/java/guava:guava",
        "//third-party/java/hamcrest:java-hamcrest",
        "//third-party/java/junit:junit",
    ],
)
