java_test(
  name = 'js',
  srcs = glob(['*Test.java']),
  deps = [
    '//src/com/facebook/buck/model:model',
    '//src/com/facebook/buck/util/environment:platform',
    '//test/com/facebook/buck/android:testutil',
    '//test/com/facebook/buck/model:BuildTargetFactory',
    '//test/com/facebook/buck/testutil/integration:integration',
    '//third-party/java/guava:guava',
    '//third-party/java/hamcrest:hamcrest',
    '//third-party/java/junit:junit',
  ],
)

java_library(
  name = 'testutil',
  srcs = glob(['*.java'], excludes = ['*Test.java']),
  deps = [
    '//src/com/facebook/buck/js:js',
    '//src/com/facebook/buck/model:model',
    '//src/com/facebook/buck/parser:rule_pattern',
    '//src/com/facebook/buck/rules:build_rule',
    '//test/com/facebook/buck/rules:testutil',
    '//third-party/java/guava:guava',
  ],
  visibility = [
    '//test/com/facebook/buck/...',
  ]
)
