java_library(
    name = "impl",
    srcs = glob(["*.java"]),
    exported_deps = [
        "//src/com/facebook/buck/toolchain:toolchain",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/android:helpers",
        "//src/com/facebook/buck/android/toolchain/impl:impl",
        "//src/com/facebook/buck/io:io",
        "//src/com/facebook/buck/util:exceptions",
    ],
)
