java_library(
    name = "impl",
    srcs = glob(["*.java"]),
    exported_deps = [
        "//src/com/facebook/buck/toolchain:toolchain",
    ],
    tests = [
        "//test/com/facebook/buck/toolchain/impl:impl",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/android:helpers",
        "//src/com/facebook/buck/android/toolchain/impl:impl",
        "//src/com/facebook/buck/android/toolchain/ndk/impl:impl",
        "//src/com/facebook/buck/apple:apple",
        "//src/com/facebook/buck/apple/toolchain/impl:impl",
        "//src/com/facebook/buck/file/downloader/impl:impl",
        "//src/com/facebook/buck/io:executable-finder",
        "//src/com/facebook/buck/io:io",
        "//src/com/facebook/buck/python/toolchain/impl:impl",
        "//src/com/facebook/buck/swift/toolchain/impl:impl",
        "//src/com/facebook/buck/util:exceptions",
        "//third-party/java/pf4j:pf4j",
    ],
)
