java_library(
  name = 'hash',
  srcs = glob(['*.java']),
  tests = [
    '//test/com/facebook/buck/util/hash:hash',
  ],
  deps = [
    '//third-party/java/guava:guava',
    '//third-party/java/jsr:jsr305',
  ],
  visibility = [
    'PUBLIC',
  ],
)
