load("//tools/build_rules:java_rules.bzl", "java_library_with_plugins")
load("//tools/build_rules:module_rules.bzl", "buck_module")

java_library_with_plugins(
    name = "python",
    srcs = glob(
        ["*.java"],
    ),
    provided_deps = [
        "//src/com/facebook/buck/core/description/arg:arg",
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/core/model/impl:impl",
        "//src/com/facebook/buck/core/rules:rules",
        "//src/com/facebook/buck/core/rules/impl:impl",
        "//src/com/facebook/buck/core/sourcepath/resolver/impl:impl",
        "//src/com/facebook/buck/core/toolchain/tool/impl:impl",
        "//src/com/facebook/buck/core/util/graph:graph",
        "//src/com/facebook/buck/core/util/log:log",
        "//src/com/facebook/buck/cxx:rules",
        "//src/com/facebook/buck/cxx/toolchain:toolchain",
        "//src/com/facebook/buck/cxx/toolchain/linker:linker",
        "//src/com/facebook/buck/cxx/toolchain/nativelink:nativelink",
        "//src/com/facebook/buck/event/external:external_lib",
        "//src/com/facebook/buck/file:rules",
        "//src/com/facebook/buck/io:io",
        "//src/com/facebook/buck/io/file:file",
        "//src/com/facebook/buck/io/filesystem:filesystem",
        "//src/com/facebook/buck/rules/args:args",
        "//src/com/facebook/buck/rules/coercer:coercer",
        "//src/com/facebook/buck/rules/coercer:interface",
        "//src/com/facebook/buck/rules/keys:keys",
        "//src/com/facebook/buck/rules/keys/config:config",
        "//src/com/facebook/buck/rules/macros:macros",
        "//src/com/facebook/buck/rules/macros:types",
        "//src/com/facebook/buck/rules/tool/config:config",
        "//src/com/facebook/buck/shell:rules",
        "//src/com/facebook/buck/shell:steps",
        "//src/com/facebook/buck/step:step",
        "//src/com/facebook/buck/step/fs:fs",
        "//src/com/facebook/buck/test:test",
        "//src/com/facebook/buck/test/config:config",
        "//src/com/facebook/buck/test/selectors:selectors",
        "//src/com/facebook/buck/unarchive:unarchive",
        "//src/com/facebook/buck/util:exceptions",
        "//src/com/facebook/buck/util:packaged_resource",
        "//src/com/facebook/buck/util:process_executor",
        "//src/com/facebook/buck/util:util",
        "//src/com/facebook/buck/util/json:json",
        "//src/com/facebook/buck/util/unarchive:unarchive",
        "//src/com/facebook/buck/versions:translator",
        "//src/com/facebook/buck/versions:types",
        "//src/com/facebook/buck/versions:versions",
        "//third-party/java/infer-annotations:infer-annotations",
        "//third-party/java/jackson:jackson-databind",
        "//third-party/java/stringtemplate:stringtemplate",
    ],
    resources = [
        "__test_main__.py",
        "run_inplace.py.in",
        "run_inplace_lite.py.in",
    ],
    tests = [
        "//test/com/facebook/buck/features/python:python",
    ],
    visibility = [
        "//src/com/facebook/buck/cli:main",
        "//src/com/facebook/buck/core/cell:cell",
        "//src/com/facebook/buck/cxx:rules",
        "//src/com/facebook/buck/features/...",
        "//src/com/facebook/buck/features/python/...",
        "//test/...",
    ],
    deps = [
        "//src/com/facebook/buck/features/python/toolchain:toolchain",
    ],
)

python_binary(
    name = "pex",
    main = "make_pex.py",
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//third-party/py/pex:pex",
    ],
)

buck_module(
    name = "module",
    exported_deps = [
        "//src/com/facebook/buck/features/python:python",
    ],
    module_resources = ["//src/com/facebook/buck/features/python:pex"],
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/features/python/toolchain:toolchain",
        "//src/com/facebook/buck/features/python/toolchain/impl:impl",
    ],
)
