load("//tools/build_rules:java_rules.bzl", "java_test")

java_test(
    name = "exception_handlers",
    srcs = glob(["*.java"]),
    deps = [
        "//src/com/facebook/buck/cli/exceptions/handlers:handlers",
        "//src/com/facebook/buck/core/exceptions:exceptions",
        "//src/com/facebook/buck/core/exceptions/handler:handler",
        "//src/com/facebook/buck/log:api",
        "//src/com/facebook/buck/parser/exceptions:exceptions",
        "//src/com/facebook/buck/util:process_executor",
        "//src/com/facebook/buck/util:util",
        "//test/com/facebook/buck/testutil:testutil",
        "//third-party/java/hamcrest:hamcrest-junit",
        "//third-party/java/junit:junit",
        "//third-party/java/nailgun:nailgun",
    ],
)
