load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

TYPES_SRCS = [
    "SourcePath.java",
]

java_library(
    name = "types",
    srcs = TYPES_SRCS,
    visibility = ["PUBLIC"],
    deps = [
        "//third-party/java/guava:guava",
    ],
)

SOURCE_WITH_FLAGS_SRCS = [
    "SourceWithFlags.java",
    "UnconfiguredSourceWithFlags.java",
]

java_immutables_library(
    name = "source_with_flags",
    srcs = SOURCE_WITH_FLAGS_SRCS,
    visibility = ["PUBLIC"],
    deps = [
        ":sourcepath",
        ":types",
        "//src/com/facebook/buck/core/cell/nameresolver:nameresolver",
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/core/rulekey:rulekey",
        "//src/com/facebook/buck/io/filesystem:filesystem",
        "//src/com/facebook/buck/versions:translator",
        "//third-party/java/guava:guava",
    ],
)

java_immutables_library(
    name = "sourcepath",
    srcs = glob(
        ["*.java"],
        exclude = TYPES_SRCS + SOURCE_WITH_FLAGS_SRCS,
    ),
    tests = [
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/core/cell/nameresolver:nameresolver",
        "//src/com/facebook/buck/io/filesystem:filesystem",
        "//src/com/facebook/buck/util/types:types",
        "//third-party/java/guava:guava",
        "//third-party/java/jackson:jackson-annotations",
        "//third-party/java/jackson:jackson-databind",
    ],
    exported_deps = [
        ":types",
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/core/rulekey:rulekey",
        "//src/com/facebook/buck/io/filesystem:filesystem",
    ],
)
