load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "grpc",
    srcs = glob(["*.java"]),
    exported_deps = [
        "//src/com/facebook/buck/remoteexecution:remoteexecution",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//src-gen:protobuf",
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/event:event",
        "//src/com/facebook/buck/event:interfaces",
        "//src/com/facebook/buck/io:io",
        "//src/com/facebook/buck/io/file:file",
        "//src/com/facebook/buck/io/filesystem:filesystem",
        "//src/com/facebook/buck/io/filesystem/impl:impl",
        "//src/com/facebook/buck/core/util/log:log",
        "//src/com/facebook/buck/log:log",
        "//src/com/facebook/buck/remoteexecution:remoteexecution",
        "//src/com/facebook/buck/remoteexecution/config:config",
        "//src/com/facebook/buck/remoteexecution/grpc/retry:retry",
        "//src/com/facebook/buck/remoteexecution/event:event",
        "//src/com/facebook/buck/remoteexecution/util:util",
        "//src/com/facebook/buck/util:exceptions",
        "//src/com/facebook/buck/util:io",
        "//src/com/facebook/buck/util:util",
        "//src/com/facebook/buck/util/concurrent:concurrent",
        "//src/com/facebook/buck/util/function:function",
        "//src/com/facebook/buck/util/timing:timing",
        "//third-party/java/remote-apis:remote-apis",
        # Nothing in here explicitly uses netty, but grpc picks it up dynamically when trying to
        # connect to a remote server.
        "//third-party/java/grpc:grpc-netty-shaded",
        "//third-party/java/netty-handler:netty-handler",
        "//third-party/java/netty-tcnative:netty-tcnative",
        "//third-party/java/guava:guava",
        "//third-party/java/infer-annotations:infer-annotations",
        "//third-party/java/jsr:jsr305",
    ],
)
