load("//tools/build_rules:java_rules.bzl", "java_test")

java_test(
    name = "dex",
    srcs = glob(["*.java"]),
    deps = [
        "//src/com/facebook/buck/android/dex:dex",
        "//third-party/java/guava:guava",
        "//third-party/java/junit:junit",
    ],
)
