load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "thrift",
    srcs = glob(["**/*.java"]),
    exported_deps = [
        "//src/com/facebook/buck/remoteexecution:remoteexecution",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//src-gen:thrift",
        "//src/com/facebook/buck/core/util/log:log",
        "//src/com/facebook/buck/event:event",
        "//src/com/facebook/buck/event:interfaces",
        "//src/com/facebook/buck/io:io",
        "//src/com/facebook/buck/io/file:file",
        "//src/com/facebook/buck/io/filesystem:filesystem",
        "//src/com/facebook/buck/io/filesystem/impl:impl",
        "//src/com/facebook/buck/remoteexecution:remoteexecution",
        "//src/com/facebook/buck/remoteexecution/config:config",
        "//src/com/facebook/buck/util:exceptions",
        "//src/com/facebook/buck/util:process_executor",
        "//src/com/facebook/buck/util:util",
        "//src/com/facebook/buck/util/concurrent:concurrent",
        "//src/com/facebook/buck/util/filesystem:filesystem",
        "//third-party/java/fbthrift:fbthrift",
        "//third-party/java/guava:guava",
        "//third-party/java/infer-annotations:infer-annotations",
        "//third-party/java/jsr:jsr305",
        "//third-party/java/remote-apis:remote-apis",
    ],
)
