EVENTS_SRCS = [
  'CommandEvent.java',
  'ProgressEvent.java',
]
java_library(
  name = 'events',
  srcs = EVENTS_SRCS,
  autodeps = True,
  visibility = [
    'PUBLIC',
  ],
)

RAW_CONFIG_SRCS = [
  'Config.java',
  'Inis.java',
]
java_library(
  name = 'low-level-config',
  srcs = RAW_CONFIG_SRCS,
  autodeps = True,
  visibility = [
    '//src/com/facebook/buck/io:io',
  ],
)

CONFIG_SRCS = [
  'BuckConfig.java',
  'DownloadConfig.java',
  'SlbBuckConfig.java',
  'WorkQueueExecutionOrder.java',
]
java_library(
  name = 'config',
  srcs = CONFIG_SRCS,
  autodeps = True,
  visibility = [
    '//src/com/facebook/buck/android:rules',
    '//src/com/facebook/buck/apple:rules',
    '//src/com/facebook/buck/artifact_cache:config',
    '//src/com/facebook/buck/command:command',
    '//src/com/facebook/buck/cxx:rules',
    '//src/com/facebook/buck/distributed:distributed',
    '//src/com/facebook/buck/d:d',
    '//src/com/facebook/buck/event/listener:listener',
    '//src/com/facebook/buck/go:go',
    '//src/com/facebook/buck/halide:rules',
    '//src/com/facebook/buck/lua:lua',
    '//src/com/facebook/buck/file:downloader',
    '//src/com/facebook/buck/jvm/java:autodeps',
    '//src/com/facebook/buck/jvm/java:config',
    '//src/com/facebook/buck/jvm/groovy:rules',
    '//src/com/facebook/buck/jvm/java/autodeps:autodeps',
    '//src/com/facebook/buck/jvm/java/intellij:intellij',
    '//src/com/facebook/buck/jvm/scala:rules',
    '//src/com/facebook/buck/js:js',
    '//src/com/facebook/buck/event/listener:listener',
    '//src/com/facebook/buck/ocaml:rules',
    '//src/com/facebook/buck/parser:config',
    '//src/com/facebook/buck/parser:parser',
    '//src/com/facebook/buck/python:config',
    '//src/com/facebook/buck/rage:config',
    '//src/com/facebook/buck/rules:types',
    '//src/com/facebook/buck/rust:rust',
    '//src/com/facebook/buck/test:config',
    '//src/com/facebook/buck/thrift:rules',
    '//src/com/facebook/buck/util/versioncontrol:versioncontrol',
    '//src/com/facebook/buck/util/versioncontrol:impl',
    '//test/com/facebook/buck/...',
  ]
)

java_immutables_library(
  name = 'cli',
  srcs = glob(['*.java'],
              excludes = EVENTS_SRCS + CONFIG_SRCS + RAW_CONFIG_SRCS),
  immutable_types = [
    'InstallResult',
    'ProjectPredicates',
    'TestRun',
  ],
  resources = [
    '//src/com/facebook/buck/cli/quickstart/android:android-template',
    '//src/com/facebook/buck/cli/quickstart/ios:ios-template',
  ],
  tests = [
    '//test/com/facebook/buck/cli:cli',
    '//test/com/facebook/buck/cli:cli-apple-integration',
  ],
  autodeps = True,
  provided_deps = [
    # Event API is loaded by the bootstrapper at runtime; don't need to depend on it strongly
    '//src/com/facebook/buck/event/api:api',
  ],
  visibility = [
    '//src/com/facebook/buck/event:dependencies-for-external-projects-inner',
    '//src/com/facebook/buck/event:event',
    '//test/com/facebook/buck/...',
  ],
)

java_binary(
  name = 'main',
  deps = [
    ':cli',
  ],
  visibility = [
    'PUBLIC',
  ],
)

genrule(
  name = 'main-fixed',
  out = 'main-fixed.jar',
  cmd = ' '.join([
    '$(exe //py/buck/zip:munger)',
    '--input=$(location :main)',
    '--output=$OUT',
    '--exclude=META-INF/MANIFEST.MF',
  ]),
  srcs = [
    ':main',
  ],
  visibility = [
    'PUBLIC',
  ],
)
