load("//tools/build_rules:java_rules.bzl", "buck_java_binary", "buck_java_library")

buck_java_library(
    name = "main_lib",
    srcs = glob(["*.java"]),
    visibility = [],
    deps = [
        "//src-gen:kotlincd-model",
        "//src-gen:worker-tool-model",
        "//src/com/facebook/buck/core/util/log:log",
        "//src/com/facebook/buck/downwardapi/protocol:protocol",
        "//src/com/facebook/buck/event/isolated:isolated",
        "//src/com/facebook/buck/external/log:log",
        "//src/com/facebook/buck/io/namedpipes:namedpipes",
        "//src/com/facebook/buck/jvm/cd/workertool:workertool",
        "//src/com/facebook/buck/jvm/kotlin/cd:cd",
        "//src/com/facebook/buck/step/isolatedsteps:isolatedsteps",
        "//src/com/facebook/buck/util/environment:environment",
        "//src/com/facebook/buck/util/monitoring:monitoring",
        "//src/com/facebook/buck/util/unit:unit",
        "//third-party/java/guava:guava",
        "//third-party/java/protobuf:protobuf-util",
    ]
)

buck_java_binary(
    name = "kotlincd_tool-main",
    main_class = "com.facebook.buck.jvm.kotlin.cd.workertool.",
    visibility = [
        "PUBLIC",
    ],
    deps = [
        ":main_lib",
    ],
)
