load("//tools/build_rules:java_rules.bzl", "java_library_with_plugins")

java_library_with_plugins(
    name = "rule",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/core/description:description",
        "//src/com/facebook/buck/core/description/attr:attr",
        "//src/com/facebook/buck/core/model/targetgraph:targetgraph",
        "//src/com/facebook/buck/core/rules/analysis:analysis",
        "//src/com/facebook/buck/core/rules/providers/collect/impl:impl",
    ],
    exported_deps = [
        "//src/com/facebook/buck/core/config:config",
        "//src/com/facebook/buck/core/exceptions:exceptions",
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/io:executable-finder",
        "//src/com/facebook/buck/io/filesystem:filesystem",
        "//src/com/facebook/buck/rules/keys/config:config",
        "//third-party/java/guava:guava",
        "//third-party/java/pf4j:pf4j",
    ],
)
