load("//tools/build_rules:java_rules.bzl", "buck_java_library")
buck_java_library(
    name = "utils",
    srcs = glob(["*.java"]),
    source = "8",
    target = "8",
    visibility = [
        "PUBLIC",
    ],
    deps = [
        # Do NOT add any deps here. This library is used by code that cannot depend on the rest of Buck.
    ],
)
