load("//tools/build_rules:java_rules.bzl", "java_test")

java_test(
    name = "bundle",
    srcs = glob(["*.java"]),
    deps = [
        "//src/com/facebook/buck/android/bundle:bundle",
        "//src/com/facebook/buck/step:step",
        "//src/com/facebook/buck/util/versioncontrol:versioncontrol",
        "//test/com/facebook/buck/step:testutil",
        "//test/com/facebook/buck/testutil:testutil",
        "//third-party/java/bundletool:bundletool",
        "//third-party/java/junit:junit",
    ],
)
