load(
    "//tools/build_rules:java_rules.bzl",
    "java_immutables_library",
)

java_immutables_library(
    name = "android_steps",
    srcs = glob(["*.java"]),
    visibility = [
        "//src/com/facebook/buck/android/...",
        "//src/com/facebook/buck/externalactions/...",
        "//test/com/facebook/buck/...",
    ],
    deps = [
        "//src/com/facebook/buck/android/resources:resources",
        "//src/com/facebook/buck/core/build/execution/context:context",
        "//src/com/facebook/buck/core/filesystems:filesystems",
        "//third-party/java/guava:guava",
    ],
    exported_deps = [
        "//src/com/facebook/buck/step/isolatedsteps:isolatedsteps",
        "//src/com/facebook/buck/step/isolatedsteps/shell:shell_steps",
    ],
)
