load("//tools/build_rules:java_rules.bzl", "java_immutables_library", "java_test")

java_test(
    name = "knowntypes",
    srcs = glob(["*Test.java"]),
    has_immutable_types = True,
    deps = [
        ":testutil",
        "//src/com/facebook/buck/core/sourcepath/resolver/impl:impl",
        "//src/com/facebook/buck/cxx/toolchain:toolchain",
        "//src/com/facebook/buck/cxx/toolchain/impl:impl",
        "//src/com/facebook/buck/jvm/java:rules",
        "//src/com/facebook/buck/jvm/java/toolchain:toolchain",
        "//src/com/facebook/buck/toolchain/impl:impl",
        "//src/com/facebook/buck/versions:versions",
        "//test/com/facebook/buck/config:FakeBuckConfig",
        "//test/com/facebook/buck/core/rules/resolver/impl:testutil",
        "//test/com/facebook/buck/cxx:testutil",
        "//test/com/facebook/buck/cxx/toolchain:testutil",
        "//test/com/facebook/buck/io/filesystem:testutil",
        "//test/com/facebook/buck/jvm/java:testutil",
        "//test/com/facebook/buck/model:testutil",
        "//test/com/facebook/buck/rules:testutil",
        "//test/com/facebook/buck/rules/keys:testutil",
        "//test/com/facebook/buck/rules/keys/config:testutil",
        "//test/com/facebook/buck/testutil:testutil",
        "//third-party/java/junit:junit",
    ],
)

java_library(
    name = "testutil",
    srcs = glob(
        ["*.java"],
        exclude = ["*Test.java"],
    ),
    exported_deps = [
        "//src/com/facebook/buck/config:config",
        "//src/com/facebook/buck/core/rules/knowntypes:knowntypes",
        "//src/com/facebook/buck/model:model",
        "//src/com/facebook/buck/plugin/impl:impl",
        "//src/com/facebook/buck/rules:rules",
        "//src/com/facebook/buck/step:step",
        "//test/com/facebook/buck/util:testutil",
    ],
    visibility = [
        "//test/...",
    ],
    deps = [
        "//test/com/facebook/buck/config:FakeBuckConfig",
        "//test/com/facebook/buck/sandbox:testutil",
    ],
)
