load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "file",
    srcs = glob(["*.java"]),
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/core/exceptions:exceptions",
        "//src/com/facebook/buck/core/filesystems:filesystems",
        "//src/com/facebook/buck/core/util/log:log",
        "//src/com/facebook/buck/io/pathformat:pathformat",
        "//src/com/facebook/buck/util:process_executor",
        "//src/com/facebook/buck/util:util",
        "//src/com/facebook/buck/util/environment:platform",
        "//src/com/facebook/buck/util/stream:stream",
        "//third-party/java/guava:guava",
        "//third-party/java/jsr:jsr305",
    ],
    exported_deps = [
        "//src/com/facebook/buck/core/filesystems:filesystems",
        "//src/com/facebook/buck/core/path:path",
        "//src/com/facebook/buck/io/watchman:capability",
        "//src/com/facebook/buck/io/windowsfs:windowsfs",
    ],
)
