java_test(
  name = 'abi',
  srcs = glob(['*.java']),
  source_under_test = [
    '//src/com/facebook/buck/java/abi:abi',
  ],
  deps = [
    '//third-party/java/guava:guava',
    '//third-party/java/hamcrest:hamcrest-core',
    '//third-party/java/hamcrest:hamcrest-library',
    '//third-party/java/junit:junit',
    '//src/com/facebook/buck/java/abi:abi',
    '//src/com/facebook/buck/java/abi:protocol',
    '//test/com/facebook/buck/testutil/integration:integration',
  ],
)
