java_test(
  name = 'abi',
  srcs = glob(['*.java']),
  source_under_test = [
    '//src/com/facebook/buck/java/abi:abi',
  ],
  deps = [
    '//lib:guava',
    '//lib:hamcrest-core',
    '//lib:hamcrest-library',
    '//lib:junit',
    '//src/com/facebook/buck/java/abi:abi',
    '//test/com/facebook/buck/testutil/integration:integration',
  ],
)
