load(
    "//tools/build_rules:java_rules.bzl",
    "java_test",
)

java_test(
    name = "example",
    srcs = glob(["*Test.java"]),
    deps = [
        "//test/com/facebook/buck/core/model:testutil",
        "//test/com/facebook/buck/testutil:testutil",
        "//test/com/facebook/buck/testutil/integration:util",
        "//third-party/java/junit:junit",
    ],
)
