load("//tools/build_rules:java_rules.bzl", "standard_java_test")

standard_java_test(
    name = "utils",
    deps = [
        "//src/com/facebook/buck/event:event",
        "//src/com/facebook/buck/event/utils:utils",
        "//src/com/facebook/buck/util/timing:timing",
        "//test/com/facebook/buck/util/timing:testutil",
        "//third-party/java/junit:junit",
        "//third-party/java/protobuf:protobuf",
    ],
)
