load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "android_external_actions",
    srcs = glob(["*.java"]),
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src-gen:buildable-command-model",
        "//src/com/facebook/buck/core/filesystems:filesystems",
        "//src/com/facebook/buck/external/model:model",
        "//src/com/facebook/buck/step/isolatedsteps:isolatedsteps",
        "//src/com/facebook/buck/step/isolatedsteps/android:android_steps",
        "//src/com/facebook/buck/util/json:json",
        "//third-party/java/guava:guava",
        "//third-party/java/jackson:jackson-annotations",
    ],
)
