load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "config",
    srcs = glob(
        ["*.java"],
    ),
    visibility = ["PUBLIC"],
    deps = [
        "//src-gen:protobuf",
        "//src/com/facebook/buck/artifact_cache/config:config",
        "//src/com/facebook/buck/core/exceptions:exceptions",
        "//src/com/facebook/buck/core/util/log:log",
        "//src/com/facebook/buck/io/filesystem:filesystem",
        "//src/com/facebook/buck/remoteexecution/util:util",
        "//src/com/facebook/buck/rules/modern/config:config",
    ],
    exported_deps = [
        "//src/com/facebook/buck/core/config:config",
    ],
)
