load(
    "//tools/build_rules:java_rules.bzl",
    "java_immutables_library",
)

java_immutables_library(
    name = "tools",
    srcs = glob(["*.java"]),
    visibility = [
        "//src/com/facebook/buck/cli/...",
    ],
    deps = [
        "//src/com/facebook/buck/core/rulekey:rulekey",
        "//src/com/facebook/buck/core/rules:rules",
        "//src/com/facebook/buck/core/rules/modern:modern",
        "//src/com/facebook/buck/core/sourcepath/resolver:resolver",
        "//src/com/facebook/buck/core/sourcepath/resolver/impl:impl",
        "//src/com/facebook/buck/core/util/immutables:immutables",
        "//src/com/facebook/buck/rules/modern:modern",
        "//src/com/facebook/buck/rules/modern/builders:builders",
        "//src/com/facebook/buck/util:exceptions",
        "//src/com/facebook/buck/util:util",
        "//third-party/java/guava:guava",
        "//third-party/java/jsr:jsr305",
    ],
)
