load("//tools/build_rules:module_rules.bzl", "buck_module")

buck_module(
    name = "test_module",
    srcs = glob(["*.java"]),
    provided_deps = [
        "//test/com/facebook/buck/core/module/impl:test_extension",
    ],
    visibility = ["PUBLIC"],
)
