standard_java_testutil(
    name = "testutil",
)

standard_java_test(
    name = "classes",
    deps = [
        "//src/com/facebook/buck/io:MorePaths.java",
        "//src/com/facebook/buck/io:io",
        "//src/com/facebook/buck/jvm/java/classes:classes",
        "//src/com/facebook/buck/util:util",
        "//third-party/java/guava:guava",
        "//third-party/java/junit:junit",
    ],
)
