java_test(
    name = "support",
    srcs = glob(["*Test.java"]),
    deps = [
        "//src/com/facebook/buck/support:support",
        "//test/com/facebook/buck/core/model:testutil",
        "//third-party/java/guava:guava",
        "//third-party/java/junit:junit",
    ],
)
