load("//tools/build_rules:java_rules.bzl", "buck_java_library")

buck_java_library(
    name = "json",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/util/json:json",
        "//third-party/java/jackson:jackson-databind",
    ],
    exported_deps = [
        "//src/com/facebook/buck/parser/api:api",
    ],
)
