load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "impl",
    srcs = glob(["*.java"]),
    tests = ["//test/com/facebook/buck/workertool/impl:workertool_impl"],
    visibility = ["PUBLIC"],
    deps = [
        "//src-gen:downward-model",
        "//src-gen:worker-tool-model",
        "//src/com/facebook/buck/core/build/execution/context:context",
        "//src/com/facebook/buck/core/util/log:log",
        "//src/com/facebook/buck/downwardapi/namedpipes:namedpipes",
        "//src/com/facebook/buck/downwardapi/processexecutor:processexecutor",
        "//src/com/facebook/buck/downwardapi/processexecutor/context:context",
        "//src/com/facebook/buck/downwardapi/processexecutor/handlers:handlers",
        "//src/com/facebook/buck/downwardapi/protocol:protocol",
        "//src/com/facebook/buck/event:event",
        "//src/com/facebook/buck/io/namedpipes:namedpipes",
        "//src/com/facebook/buck/util:process_executor",
        "//src/com/facebook/buck/util/env:env",
        "//src/com/facebook/buck/util/environment:environment",
        "//src/com/facebook/buck/workertool:workertool",
        "//src/com/facebook/buck/workertool/impl/request:request",
        "//src/com/facebook/buck/workertool/utils:utils",
        "//third-party/java/guava:guava",
        "//third-party/java/jsr:jsr305",
    ],
)
