java_library(
    name = "message_ipc",
    srcs = glob(["*.java"]),
    tests = [
        "//test/com/facebook/buck/message_ipc:message_ipc",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/shell:worker_process",
        "//src/com/facebook/buck/util:object_mapper",
        "//third-party/java/guava:guava",
        "//third-party/java/jackson:jackson-databind",
        "//third-party/java/jsr:jsr305",
    ],
)
