java_library(
    name = "transformation",
    srcs = glob(["*.java"]),
    tests = [
        "//test/com/facebook/buck/core/graph/transformation:transformation_stackuse",
        "//test/com/facebook/buck/core/graph/transformation:transformation_unit",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/log:api",
        "//src/com/facebook/buck/util:util",
        "//third-party/java/guava:guava",
        "//third-party/java/jsr:jsr305",
    ],
)
