android_library(
    name='src',
    srcs=glob(['src/main/java/**/*.java']),
    deps=[':res'],
    visibility=['PUBLIC'],
)

android_resource(
    name='manifest',
    manifest='src/main/AndroidManifest.xml',
    visibility=['PUBLIC'],
)

android_resource(
    name='assets',
    assets='src/main/assets',
    visibility=['PUBLIC'],
)

android_resource(
    name='res',
    res='src/main/res',
    package='com.example',
    visibility=['PUBLIC'],
)

project_config(
    src_target=':src',
    src_roots=['src/main/java']
)
