java_library(
  name = 'test-library',
  srcs = [],
  deps = [],
  source = '6',
  target = '6',
  visibility = [
    'PUBLIC',
  ],
)

genrule(
  name = 'A',
  out = 'A.txt',
)

genrule(
  name = 'B',
  cmd = '$(classpath :test-library)',
  out = 'B.txt',
  deps = [
    ':A'
  ],
)
