load("//tools/build_rules:java_rules.bzl", "standard_java_test")

standard_java_test(
    name = "filesystems",
    deps = [
        "//src/com/facebook/buck/core/filesystems:filesystems",
        "//third-party/java/junit:junit",
        "//third-party/java/junitparams:junitparams",
    ],
)
