android_resource(
  name = 'res',
  res = 'res',
  assets = 'assets',
  package = 'com.example',
  manifest = 'AndroidManifestSkeleton.xml',
)

android_aar(
  name = 'app',
  manifest_skeleton = 'AndroidManifestSkeleton.xml',
  srcs = glob(['**/*.java']),
  deps = [
    ':res',
  ],
)
