load(
    "//tools/build_rules:java_rules.bzl",
    "java_library_with_plugins",
)

java_library_with_plugins(
    name = "config",
    srcs = [
        "NullsafeConfig.java",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/core/config:config",
        "//src/com/facebook/buck/core/exceptions:exceptions",
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/core/sourcepath:types",
    ],
)
