java_library(
    name = "device",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/log:api",
        "//src/com/facebook/buck/util:process_executor",
        "//third-party/java/guava:guava",
    ],
)
