load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "objectfile",
    srcs = glob(["*.java"]),
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/io:io",
        "//src/com/facebook/buck/io/file:file",
        "//src/com/facebook/buck/util:util",
    ],
)
