java_library(
    name = "externdeps",
    srcs = glob(["*.java"]),
    deps = [
        "//src/com/facebook/buck/core/module/impl:impl",
        "//src/com/facebook/buck/core/plugin/impl:impl",
        "//test/com/facebook/buck/core/module/impl:test_extension",
        "//third-party/java/guava:guava",
        "//third-party/java/junit:junit",
        "//third-party/java/slf4j:slf4j-api",
    ],
)

java_binary(
    name = "externdeps-jar",
    main_class = "com.facebook.buck.core.module.impl.externdeps.ModuleWithExternalDependenciesTest",
    deps = [
        ":externdeps",
        "//third-party/java/slf4j:slf4j",
    ],
)

export_file(
    name = "known-hash.txt",
    visibility = [
        "PUBLIC",
    ],
)

# Replace real hash in the module jar with a known value
genrule(
    name = "meta-inf",
    out = "META-INF",
    cmd = " ".join([
        "mkdir $OUT && ",
        "cp $(location :{}) $OUT/module-binary-hash.txt".format("known-hash.txt"),
    ]),
)

zip_file(
    name = "test_module-jar-with-known-hash",
    srcs = [
        ":meta-inf",
    ],
    zip_srcs = [
        "//test/com/facebook/buck/core/module/impl/externdeps/test_module:test_module-module",
    ],
)

# Replace real hash in the module jar with a known value
zip_file(
    name = "dependent_module-jar-with-known-hash",
    srcs = [
        ":meta-inf",
    ],
    zip_srcs = [
        "//test/com/facebook/buck/core/module/impl/externdeps/dependent_module:dependent_module-module",
    ],
)

# Copy modules to a place where they can be loaded by plugin manager
genrule(
    name = "copy-test-module",
    out = "modules",
    cmd = "mkdir -p $OUT; cp $(location :test_module-jar-with-known-hash) $OUT",
    cmd_exe = "mkdir $OUT && copy $(location :test_module-jar-with-known-hash) $OUT",
)

genrule(
    name = "copy-dependent-module",
    out = "modules",
    cmd = "mkdir -p $OUT; cp $(location :dependent_module-jar-with-known-hash) $OUT",
    cmd_exe = "mkdir $OUT && copy $(location :dependent_module-jar-with-known-hash) $OUT",
)

# Running tests as a shell script to reconstruct the layout of modules and how they are loaded
python_test(
    name = "externdeps-test",
    srcs = [
        "//test/com/facebook/buck/core/module/impl:test_app.py",
    ],
    env = {
        "CMD": "java -Dpf4j.pluginsDir=$(location :copy-test-module) -Dbuck.externalPluginsDir=$(location :copy-dependent-module) -jar $(location :externdeps-jar)",
    },
)
