standard_java_library(
    name = "bser",
    tests = [
        "//test/com/facebook/buck/bser:bser",
    ],
    deps = [
        "//third-party/java/guava:guava",
        "//third-party/java/jsr:jsr305",
    ],
)
