java_library(
    name = "module",
    srcs = glob(
        ["*.java"],
    ),
    exported_deps = [
        "//third-party/java/pf4j:pf4j",
    ],
    required_for_source_only_abi = True,
    visibility = ["PUBLIC"],
)
