load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "shared",
    srcs = glob(["*.java"]),
    visibility = [
        "PUBLIC",
    ],
    deps = [
    ],
)
