load("//tools/build_rules:java_rules.bzl", "standard_java_test")

standard_java_test(
    name = "pathformat",
    deps = [
        "//src/com/facebook/buck/core/filesystems:filesystems",
        "//src/com/facebook/buck/io/pathformat:pathformat",
        "//src/com/facebook/buck/util/environment:platform",
        "//third-party/java/junit:junit",
    ],
)
