load("//tools/build_rules:java_rules.bzl", "standard_java_test")

standard_java_test(
    name = "chrome_trace",
    deps = [
        "//src-gen:thrift",
        "//src/com/facebook/buck/event/chrome_trace:chrome_trace",
        "//src/com/facebook/buck/util:util",
        "//src/com/facebook/buck/util/json:json",
        "//test/com/facebook/buck/core/config:FakeBuckConfig",
        "//test/com/facebook/buck/testutil:testutil",
        "//test/com/facebook/buck/testutil/integration:util",
        "//third-party/java/junit:junit",
    ],
)
