java_library(
    name = "testutil",
    srcs = glob(["*.java"]),
    visibility = [
        "//test/com/facebook/buck/android/...",
        "//test/com/facebook/buck/jvm/java/...",
    ],
    deps = [
        "//src/com/facebook/buck/cli:config",
        "//src/com/facebook/buck/config:config",
        "//src/com/facebook/buck/jvm/java:config",
        "//src/com/facebook/buck/zip:stream",
        "//test/com/facebook/buck/cli:FakeBuckConfig",
        "//test/com/facebook/buck/testutil/integration:util",
        "//third-party/java/junit:junit",
    ],
)
