load(
    "//tools/build_rules:java_rules.bzl",
    "java_test",
)

java_test(
    name = "remoteexecution",
    srcs = glob([
        "*.java",
    ]),
    has_immutable_types = True,
    deps = [
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/core/rules:rules",
        "//src/com/facebook/buck/remoteexecution:remoteexecution",
        "//src/com/facebook/buck/util:util",
        "//test/com/facebook/buck/core/config:testutil",
        "//third-party/java/easymock:easymock",
        "//third-party/java/junit:junit",
    ],
)
