load("//tools/build_rules:java_rules.bzl", "java_test")

java_test(
    name = "remotexeecution",
    srcs = glob([
        "*.java",
    ]),
    has_immutable_types = True,
    deps = [
        "//src/com/facebook/buck/event:interfaces",
        "//src/com/facebook/buck/event/listener/interfaces:interfaces",
        "//src/com/facebook/buck/remoteexecution:remoteexecution",
        "//src/com/facebook/buck/util:util",
        "//test/com/facebook/buck/core/config:testutil",
        "//test/com/facebook/buck/event:testutil",
        "//third-party/java/junit:junit",
    ],
)
