java_library(
    name = "windowsfs",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    deps = [
        "//third-party/java/jna:jna",
        "//third-party/java/jna:jna-platform",
    ],
)
