load(
    "//tools/build_rules:java_rules.bzl",
    "java_immutables_library",
)

java_immutables_library(
    name = "remoteexecution",
    srcs = glob(
        ["*.java"],
    ),
    tests = [
        "//test/com/facebook/buck/remoteexecution:remoteexecution",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src-gen:thrift",
        "//src/com/facebook/buck/core/build/event:event",
        "//src/com/facebook/buck/core/config:config",
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/core/util/log:log",
        "//src/com/facebook/buck/event:event",
        "//src/com/facebook/buck/event:interfaces",
        "//src/com/facebook/buck/event/listener/interfaces:interfaces",
        "//src/com/facebook/buck/log:config",
        "//src/com/facebook/buck/util:util",
        "//src/com/facebook/buck/util/concurrent:concurrent",
        "//src/com/facebook/buck/util/unit:unit",
        "//third-party/java/fbthrift:fbthrift",
    ],
)
