EMPTY_CONFIGS = {
  'Debug': {},
  'Release': {},
}

apple_binary(
  name = 'TestDepBinary',
  configs = EMPTY_CONFIGS,
  srcs = [],
  frameworks = [],
  deps = [
    ':Dep1',
    ':Dep2',
    ':Dep3',
  ],
)

apple_bundle(
  name = 'TestDep',
  deps = [':TestDepBinary'],
  binary = ':TestDepBinary',
  extension = 'app',
)

apple_library(
  name = 'Dep1',
  configs = EMPTY_CONFIGS,
  srcs = [],
  frameworks = [],
  deps = [],
  tests = [':Dep1Tests'],
  visibility = ['PUBLIC'],
)

apple_library(
  name = 'Dep2',
  configs = EMPTY_CONFIGS,
  srcs = [],
  frameworks = [],
  deps = [],
  tests = [':Dep2Tests'],
  visibility = ['PUBLIC'],
)

apple_library(
  name = 'Dep3',
  configs = EMPTY_CONFIGS,
  srcs = [],
  frameworks = [],
  deps = [],
  tests = [':Dep3Tests'],
  visibility = ['PUBLIC'],
)

apple_test(
  name = 'Dep1Tests',
  extension = 'octest',
  configs = EMPTY_CONFIGS,
  srcs = [],
  frameworks = [],
  deps = [
    ':Dep1',
  ],
)

apple_test(
  name = 'Dep2Tests',
  extension = 'octest',
  configs = EMPTY_CONFIGS,
  srcs = [],
  frameworks = [],
  deps = [
    ':Dep2',
  ],
)

apple_test(
  name = 'Dep3Tests',
  extension = 'octest',
  configs = EMPTY_CONFIGS,
  srcs = [],
  frameworks = [],
  deps = [
    ':Dep3',
  ],
)

xcode_workspace_config(
  name = 'workspace',
  src_target = ':TestDep'
)
