load("//tools/build_rules:java_rules.bzl", "standard_java_test")

standard_java_test(
    name = "apkmodule",
    deps = [
        "//src/com/facebook/buck/android:rules",
        "//src/com/facebook/buck/android/apkmodule:apkmodule",
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/core/sourcepath/resolver:resolver",
        "//src/com/facebook/buck/graph:graph",
        "//src/com/facebook/buck/jvm/java:rules",
        "//src/com/facebook/buck/parser:rule_pattern",
        "//src/com/facebook/buck/util:util",
        "//test/com/facebook/buck/android:testutil",
        "//test/com/facebook/buck/core/model:testutil",
        "//test/com/facebook/buck/core/model/targetgraph:testutil",
        "//test/com/facebook/buck/core/sourcepath:testutil",
        "//test/com/facebook/buck/jvm/java:testutil",
        "//test/com/facebook/buck/rules:testutil",
        "//test/com/facebook/buck/testutil:testutil",
        "//third-party/java/guava:guava",
        "//third-party/java/hamcrest:java-hamcrest",
        "//third-party/java/junit:junit",
    ],
)
