java_library(
    name = "detector",
    srcs = glob(["*.java"]),
    tests = [
        "//test/com/facebook/buck/parser/detector:detector",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/core/model/impl:impl",
        "//src/com/facebook/buck/core/model/tc/factory:factory",
        "//src/com/facebook/buck/util/types:types",
    ],
    exported_deps = [
        "//src/com/facebook/buck/core/cell:cell",
        "//src/com/facebook/buck/core/model/targetgraph/raw:raw",
        "//src/com/facebook/buck/core/parser/buildtargetparser:buildtargetparser",
        "//src/com/facebook/buck/parser/config:config",
    ],
)
