java_library(
    name = "context",
    srcs = glob(["*.java"]),
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//third-party/java/guava:guava",
    ],
    exported_deps = [
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/core/rules/providers/collect:collect",
    ],
)
