java_library(
    name = "impl",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/parser/api:api",
        "//src/com/facebook/buck/parser/syntax:syntax",
        "//src/com/facebook/buck/rules/coercer:coercer",
        "//third-party/java/bazel:bazel",
        "//third-party/java/jsr:jsr305",
    ],
    exported_deps = [
        "//src/com/facebook/buck/core/cell:cell",
        "//src/com/facebook/buck/core/parser/buildtargetparser:buildtargetparser",
        "//src/com/facebook/buck/core/select:select",
        "//src/com/facebook/buck/io/filesystem:filesystem",
        "//src/com/facebook/buck/rules/coercer:interface",
    ],
)
