java_test(
  name = 'junit',
  srcs = glob(['*.java']),
  resources = glob(['testdata/**/*']),
  source_under_test = [
    '//src/com/facebook/buck/junit:junit',
  ],
  deps = [
    '//lib:guava',
    '//lib:junit',
    '//src/com/facebook/buck/junit:junit',
    '//test/com/facebook/buck/testutil/integration:integration',
  ],
)
