java_test(
  name = 'junit',
  srcs = glob(['*.java']),
  resources = glob(['testdata/**'], include_dotfiles=True),
  source_under_test = [
    '//src/com/facebook/buck/junit:junit',
  ],
  deps = [
    '//lib:guava',
    '//lib:hamcrest-core',
    '//lib:hamcrest-library',
    '//lib:junit',
    '//src/com/facebook/buck/event:event',
    '//src/com/facebook/buck/junit:junit',
    '//src/com/facebook/buck/rules:rules',
    '//src/com/facebook/buck/test:test',
    '//src/com/facebook/buck/test/result/type:type',
    '//src/com/facebook/buck/util:util',
    '//test/com/facebook/buck/testutil:testutil',
    '//test/com/facebook/buck/testutil/integration:integration',
  ],
)
