java_library(
    name = "xml",
    srcs = glob(["*.java"]),
    tests = [
        "//test/com/facebook/buck/util/xml:xml",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/model:simple_types",
        "//src/com/facebook/buck/util:util",
        "//third-party/java/guava:guava",
    ],
)
