# Sources for dealing with test results.
java_library(
  name = 'test',
  srcs = glob(['*.java']),
  deps = [
    '//lib:guava',
    '//lib:jsr305',
    '//src/com/facebook/buck/model:model',
    '//src/com/facebook/buck/test/result/type:type',
    '//src/com/facebook/buck/util:io',
    '//src/com/facebook/buck/util:util',
    '//lib:jackson-annotations',
    '//lib:jackson-core',
  ],
  visibility = ['PUBLIC'],
)
