REPORT_FORMAT_SRCS = [
  'CoverageReportFormat.java',
]

java_library(
  name = 'report-format',
  srcs = REPORT_FORMAT_SRCS,
  visibility = [
    '//src/com/facebook/buck/cli:cli',
    '//src/com/facebook/buck/java:steps',
    '//test/com/facebook/buck/java:java',
  ],
)

CONFIG_SRCS = [
  'TestConfig.java',
  'AbstractTestResultSummaryVerbosity.java',
]

java_immutables_library(
  name = 'config',
  srcs = CONFIG_SRCS,
  deps = [
    '//src/com/facebook/buck/cli:config',
  ],
  visibility = [
    '//src/com/facebook/buck/cli:cli',
    '//src/com/facebook/buck/event/listener:listener',
    '//test/com/facebook/buck/event/listener:listener',
    '//test/com/facebook/buck/test:test',
  ],
)

# Sources for dealing with test results.
java_library(
  name = 'test',
  srcs = glob(
    ['*.java'],
    excludes = REPORT_FORMAT_SRCS + CONFIG_SRCS
  ),
  deps = [
    '//third-party/java/guava:guava',
    '//third-party/java/jsr:jsr305',
    '//src/com/facebook/buck/event:event',
    '//src/com/facebook/buck/model:model',
    '//src/com/facebook/buck/test/result/type:type',
    '//src/com/facebook/buck/util:io',
    '//src/com/facebook/buck/util:util',
    '//third-party/java/jackson:jackson-annotations',
    '//third-party/java/jackson:jackson-core',
  ],
  visibility = ['PUBLIC'],
)
