load("//tools/build_rules:module_rules.bzl", "buck_module")

buck_module(
    name = "rules",
    srcs = glob(["*.java"]),
    module_deps = [
        "//src/com/facebook/buck/features/filebundler:filebundler",
    ],
    provided_deps = [
        "//src/com/facebook/buck/core/cell/resolver:resolver",
        "//src/com/facebook/buck/core/description/arg:arg",
        "//src/com/facebook/buck/core/model/targetgraph:targetgraph",
        "//src/com/facebook/buck/core/rules:rules",
        "//src/com/facebook/buck/core/sourcepath/resolver:resolver",
        "//src/com/facebook/buck/event:interfaces",
        "//src/com/facebook/buck/io:io",
        "//src/com/facebook/buck/model:model",
        "//src/com/facebook/buck/parser:rule_pattern",
        "//src/com/facebook/buck/rules/keys:keys",
        "//src/com/facebook/buck/rules/modern:modern",
        "//src/com/facebook/buck/step:step",
        "//src/com/facebook/buck/step/fs:fs",
        "//src/com/facebook/buck/util:exceptions",
        "//src/com/facebook/buck/util:util",
        "//src/com/facebook/buck/util/zip:zip",
        "//src/com/facebook/buck/versions:versions",
        "//src/com/facebook/buck/zip:zip",
        "//third-party/java/guava:guava",
        "//third-party/java/infer-annotations:infer-annotations",
    ],
    tests = [
        "//test/com/facebook/buck/features/zip/rules:rules",
    ],
    visibility = [
        "//test/com/facebook/buck/cli:cli",
        "//test/com/facebook/buck/features/zip/rules:rules",
        "//test/com/facebook/buck/ide/intellij:intellij",
    ],
)
