java_immutables_library(
  name = 'go',
  srcs = glob(['*.java']),
  immutable_types = [
    'GoLinkable',
    'GoPlatform',
  ],
  autodeps = True,
  visibility = [
    '//src/com/facebook/buck/rules:types',
    '//test/com/facebook/buck/go/...',
  ],
  resources = [
    'testmaingen.go',
    'LICENSE',
  ],
)
