java_library(
  name = 'go',
  srcs = [
    'GoBinary.java',
    'GoBinaryDescription.java',
    'GoBuckConfig.java',
    'GoCompileStep.java',
    'GoDescriptors.java',
    'GoLibrary.java',
    'GoLibraryDescription.java',
    'GoLinkable.java',
    'GoLinkStep.java',
    'GoSymlinkTree.java',
    'GoTest.java',
    'GoTestDescription.java',
    'GoTestMain.java',
    'GoTestMainStep.java',
    'GoTestStep.java',
  ],
  autodeps = True,
  visibility = [
    '//src/com/facebook/buck/rules:types',
    '//test/com/facebook/buck/go/...',
  ],
  resources = [
    'testmaingen.go',
    'LICENSE',
  ],
)
