load("//tools/build_rules:java_rules.bzl", "java_immutables_library")
load("//tools/build_rules:file_alias.bzl", "file_alias")

java_immutables_library(
    name = "builders",
    srcs = glob(
        ["**/*.java"],
        exclude = ["grpc/server/**"],
    ),
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/parser:rule_pattern",
        "//src/com/facebook/buck/android:utils_api",
        "//src/com/facebook/buck/core/cell/impl:impl",
        "//src/com/facebook/buck/core/rules/build/strategy:strategy",
        "//src/com/facebook/buck/core/sourcepath/resolver/impl:impl",
        "//src/com/facebook/buck/event:event",
        "//src/com/facebook/buck/event:interfaces",
        "//src/com/facebook/buck/io:io",
        "//src/com/facebook/buck/io/file:file",
        "//src/com/facebook/buck/io/filesystem:filesystem",
        "//src/com/facebook/buck/io/filesystem/impl:impl",
        "//src/com/facebook/buck/io/windowsfs:windowsfs",
        "//src/com/facebook/buck/jvm/core:packagefinder",
        "//src/com/facebook/buck/jvm/java:config",
        "//src/com/facebook/buck/jvm/java:packagefinder",
        "//src/com/facebook/buck/log:api",
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/plugin/impl:impl",
        "//src/com/facebook/buck/core/rules:rules",
        "//src/com/facebook/buck/rules/keys:keys",
        "//src/com/facebook/buck/rules/modern:modern",
        "//src/com/facebook/buck/rules/modern/config:config",
        "//src/com/facebook/buck/slb:slb",
        "//src/com/facebook/buck/step:step",
        "//src/com/facebook/buck/util:exceptions",
        "//src/com/facebook/buck/util/concurrent:concurrent",
        "//src/com/facebook/buck/util:io",
        "//src/com/facebook/buck/util:util",
        "//src/com/facebook/buck/util/config:config",
        "//src/com/facebook/buck/util/env:env",
        "//src/com/facebook/buck/util/filesystem:filesystem",
        "//src/com/facebook/buck/util/function:function",
        "//src/com/facebook/buck/util/hashing:hashing",
        "//src/com/facebook/buck/util/timing:timing",
        "//src/com/facebook/buck/worker:worker_process",
        "//third-party/java/googleapis:googleapis",
        # Nothing in here explicitly uses netty, but grpc picks it up dynamically when trying to
        # connect to a remote server.
        "//third-party/java/grpc:grpc-netty",
        "//third-party/java/guava:guava",
        "//third-party/java/infer-annotations:infer-annotations",
        "//third-party/java/jsr:jsr305",
    ],
)

file_alias(
    name = "trampoline",
    source = "trampoline.sh",
)
