apple_library(
  name = 'one',
  srcs = [ '1.txt' ],
  deps = [
    ':two',
    ':three',
  ],
  tests = [ ':one-tests' ],
)

apple_library(
  name = 'two',
  srcs = [ '2.txt' ],
  deps = [
    ':four',
  ],
)

apple_library(
  name = 'three',
  srcs = [ '3.txt' ],
  deps = [
    ':four',
    ':five',
  ],
)

apple_library(
  name = 'four',
  srcs = [ '4.txt' ],
  deps = [
    ':six',
  ],
  tests = [
    ':four-tests',
    ':four-application-tests',
  ],
)

apple_library(
  name = 'five',
  srcs = [
    '5.txt',
    ':six',
  ],
)

apple_library(
  name = 'six',
  srcs = [ '6.txt' ],
  tests = [ ':six-tests' ],
)

apple_test(
  name = 'one-tests',
  extension = 'xctest',
  srcs = [ '1-test.txt' ],
  deps = [ ':one' ],
)

apple_test(
  name = 'four-tests',
  extension = 'xctest',
  srcs = [ '4-test.txt' ],
  deps = [ ':four' ],
)

apple_test(
  name = 'four-application-tests',
  extension = 'xctest',
  srcs = [ '4-application-test.txt' ],
  deps = [
    ':four',
    ':application-test-lib',
  ],
)

apple_test(
  name = 'six-tests',
  extension = 'xctest',
  srcs = [ '6-test.txt' ],
  deps = [ ':six' ],
)

apple_library(
  name = 'application-test-lib',
)
