java_library(
  name = 'dalvik_stats_tool',
  srcs = [
    'DalvikStatsTool.java',
  ],
  tests = [
    '//test/com/facebook/buck/dalvik:dalvik',
  ],
  deps = [
    '//third-party/java/guava:guava',
    '//third-party/java/jsr:jsr305',
    '//third-party/java/asm:asm',
  ],
  visibility = [
    'PUBLIC',
  ],
)

java_binary(
  name = 'cli_dalvik_stats_tool',
  main_class = 'com.facebook.buck.dalvik.DalvikStatsTool',
  deps = [
    ':dalvik',
  ],
)

java_library(
  name = 'dalvik',
  srcs = [
    'CanaryFactory.java',
    'DalvikAwareOutputStreamHelper.java',
    'DalvikAwareZipSplitterFactory.java',
    'DalvikAwareZipSplitter.java',
    'DalvikStatsCache.java',
    'DefaultZipOutputStreamHelper.java',
    'DefaultZipSplitterFactory.java',
    'DefaultZipSplitter.java',
    'SecondaryDexHelper.java',
    'ZipOutputStreamHelper.java',
    'ZipSplitterFactory.java',
    'ZipSplitter.java',
  ],
  tests = [
    '//test/com/facebook/buck/dalvik:dalvik',
  ],
  deps = [
    ':dalvik_stats_tool',
    '//src/com/facebook/buck/io:io',
    '//src/com/facebook/buck/java/classes:classes',
    '//src/com/facebook/buck/log:api',
    '//src/com/facebook/buck/util:exceptions',
    '//src/com/facebook/buck/util:util',
    '//src/com/facebook/buck/zip:stream',
    '//third-party/java/guava:guava',
    '//third-party/java/jsr:jsr305',
  ],
  visibility = [
    'PUBLIC',
  ],
)

java_library(
  name = 'steps',
  srcs = [
    'EstimateLinearAllocStep.java',
  ],
  tests = [
    '//test/com/facebook/buck/dalvik:dalvik',
  ],
  deps = [
    ':dalvik_stats_tool',
    '//third-party/java/guava:guava',
    '//third-party/java/jsr:jsr305',
    '//src/com/facebook/buck/io:io',
    '//src/com/facebook/buck/java/classes:classes',
    '//src/com/facebook/buck/step:step',
  ],
  visibility = [
    'PUBLIC',
  ],
)
