java_library(
  name = 'linearalloc_estimator',
  srcs = [
    'LinearAllocEstimator.java',  
  ],
  deps = [
    '//lib:guava',
    '//lib:jsr305',
    '//third-party/java/asm:asm',
  ],
)

java_binary(
  name = 'cli_linearalloc_estimator',
  main_class = 'com.facebook.buck.dalvik.LinearAllocEstimator',
  deps = [
    ':dalvik',
  ],
)

java_library(
  name = 'dalvik',
  srcs = [
    'AbstractFileLike.java',
    'CanaryFactory.java',
    'ClasspathTraversal.java',
    'ClasspathTraverser.java',
    'DalvikAwareOutputStreamHelper.java',
    'DalvikAwareZipSplitterFactory.java',
    'DalvikAwareZipSplitter.java',
    'DefaultClasspathTraverser.java',
    'DefaultZipOutputStreamHelper.java',
    'DefaultZipSplitterFactory.java',
    'DefaultZipSplitter.java',
    'FileLikeInputSupplier.java',
    'FileLike.java',
    'SecondaryDexHelper.java',
    'ZipOutputStreamHelper.java',
    'ZipSplitterFactory.java',
    'ZipSplitter.java',
  ],
  deps = [
    ':linearalloc_estimator',
    '//lib:guava',
    '//lib:jsr305',
    '//src/com/facebook/buck/util:exceptions',
    '//src/com/facebook/buck/util:io',
    '//src/com/facebook/buck/util:util',
    '//src/com/facebook/buck/zip:stream',
  ],
  visibility = [
    'PUBLIC',
  ],
)
