java_library(
  name = 'dalvik_stats_tool',
  srcs = [
    'DalvikStatsTool.java',
  ],
  autodeps = True,
  tests = [
    '//test/com/facebook/buck/dalvik:dalvik',
  ],
  visibility = [
    'PUBLIC',
  ],
)

java_binary(
  name = 'cli_dalvik_stats_tool',
  main_class = 'com.facebook.buck.dalvik.DalvikStatsTool',
  deps = [
    ':dalvik',
  ],
)

java_library(
  name = 'dalvik',
  srcs = [
    'CanaryFactory.java',
    'DalvikAwareOutputStreamHelper.java',
    'DalvikAwareZipSplitter.java',
    'DalvikAwareZipSplitterFactory.java',
    'DalvikStatsCache.java',
    'SecondaryDexHelper.java',
    'ZipOutputStreamHelper.java',
    'ZipSplitter.java',
    'ZipSplitterFactory.java',
  ],
  autodeps = True,
  tests = [
    '//test/com/facebook/buck/dalvik:dalvik',
  ],
  visibility = [
    'PUBLIC',
  ],
)

java_library(
  name = 'steps',
  srcs = [
    'EstimateDexWeightStep.java',
  ],
  autodeps = True,
  tests = [
    '//test/com/facebook/buck/dalvik:dalvik',
  ],
  visibility = [
    'PUBLIC',
  ],
)
