java_library(
    name = "rendering",
    srcs = ["SoyTemplateSkylarkSignatureRenderer.java"],
    resources = [
        "signature_template.stg",
        "table_of_contents_template.stg",
    ],
    visibility = ["//tools/documentation_generator/..."],
    deps = [
        "//third-party/java/bazel:skylark-lang",
        "//third-party/java/guava:guava",
        "//third-party/java/stringtemplate:stringtemplate",
    ],
)
