load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "retry",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/core/util/log:log",
        "//third-party/java/grpc:grpc-netty-shaded",
    ],
)
