xcode_project_config(
  name = 'project',
  project_name = 'TestApp',
  rules = [
    '//Apps/TestApp:TestApp',
    '//Libraries/Dep1:Dep1',
  ],
)

xcode_workspace_config(
  name = 'workspace',
  src_target = '//Apps/TestApp:TestApp',
)
