java_library(
  name = 'classes',
  srcs = [
    'AbstractFileLike.java',
    'ClasspathTraversal.java',
    'ClasspathTraverser.java',
    'DefaultClasspathTraverser.java',
    'FileLikeInputSupplier.java',
    'FileLike.java',
    'FileLikes.java',
  ],
  deps = [
    '//lib:guava',
    '//src/com/facebook/buck/util:io',
    '//src/com/facebook/buck/util:util',
  ],
  visibility = [
    'PUBLIC',
  ],
)
