java_library(
  name = 'classes',
  srcs = glob(['*.java']),
  deps = [
    '//third-party/java/guava:guava',
    '//src/com/facebook/buck/util:io',
    '//src/com/facebook/buck/util:util',
  ],
  visibility = [
    'PUBLIC',
  ],
)
