java_test(
  name = 'python',
  srcs = glob(['*.java']),
  source_under_test = [
    '//src/com/facebook/buck/python:rules',
  ],
  deps = [
    '//lib:guava',
    '//lib:junit',
    '//src/com/facebook/buck/model:model',
    '//src/com/facebook/buck/python:rules',
    '//src/com/facebook/buck/rules:build_rule',
    '//src/com/facebook/buck/rules:rules',
    '//src/com/facebook/buck/util:io',
    '//test/com/facebook/buck/model:BuildTargetFactory',
  ],
)
