java_library(
  name = 'testutil',
  srcs = glob(['*.java'], excludes=['*Test.java', '*Builder.java']),
  autodeps = True,
  visibility = [
    '//test/...',
  ],
)

java_library(
  name = 'builders',
  srcs = glob(['*Builder.java']),
  autodeps = True,
  visibility = [
    '//test/...',
  ],
)

java_test(
  name = 'python',
  srcs = glob(['*Test.java']),
  autodeps = True,
)
