java_library(
  name = 'testutil',
  srcs = glob(['*.java'], excludes=['*Test.java', '*Builder.java']),
  autodeps = True,
  visibility = [
    '//test/...',
  ],
)

java_library(
  name = 'builders',
  srcs = glob(['*Builder.java']),
  autodeps = True,
  visibility = [
    '//test/...',
  ],
)

java_test(
  name = 'python-binary-integration',
  srcs = ['PythonBinaryIntegrationTest.java'],
  autodeps = True,
  labels = ['long_running'],
)

java_test(
  name = 'python',
  srcs = glob(['*Test.java'], excludes=['PythonBinaryIntegrationTest.java']),
  autodeps = True,
  labels = ['long_running'],
)
