load("//tools/build_rules:java_rules.bzl", "buck_java_library")
buck_java_library(
    name = "sqlite",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/core/exceptions:exceptions",
        "//third-party/java/sqlite:sqlite",
    ],
)
