java_library(
    name = "sqlite",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/core/exceptions:exceptions",
        "//third-party/java/sqlite:sqlite",
    ],
)
