PLATFORM_SRCS = [
  'AbstractNativeLinkableInput.java',
  'Archiver.java',
  'AbstractCxxPlatform.java',
  'BsdArchiver.java',
  'ByteBufferReplacer.java',
  'CanProvideSharedNativeLinkTarget.java',
  'ClangCompiler.java',
  'ClangPreprocessor.java',
  'Compiler.java',
  'DebugPathSanitizer.java',
  'DebugSection.java',
  'DebugSectionFinder.java',
  'DebugSectionProperty.java',
  'DefaultCompiler.java',
  'DefaultPreprocessor.java',
  'GnuArchiver.java',
  'GnuLinker.java',
  'Linker.java',
  'Linkers.java',
  'NativeLinkable.java',
  'NativeLinkables.java',
  'ObjectFileScrubbers.java',
  'PosixNmSymbolNameTool.java',
  'Preprocessor.java',
  'SharedNativeLinkTarget.java',
  'SymbolNameTool.java',
  'VersionedTool.java',
  'WindowsLinker.java',
]
java_immutables_library(
  name = 'platform',
  srcs = PLATFORM_SRCS,
  autodeps = True,
  visibility = [
    'PUBLIC'
  ],
)

# This is here only so that we don't have to let rules depend on xcode.
# FrameworkPathArg depends on xcode because Javac insists on being able to see the type on which
# we're calling .toString()
java_library(
  name = 'framework_path_arg',
  srcs = ['FrameworkPathArg.java'],
  tests = [
    '//test/com/facebook/buck/cxx:cxx',
  ],
  autodeps = True,
  visibility = [
    '//test/com/facebook/buck/cxx/...',
  ],
)

java_immutables_library(
  name = 'rules',
  srcs = glob(['*.java'], excludes=PLATFORM_SRCS + ['FrameworkPathArg.java']),
  tests = [
    '//test/com/facebook/buck/cxx:cxx',
  ],
  autodeps = True,
  visibility = [
    'PUBLIC'
  ],
)
