load("//tools/build_rules:java_rules.bzl", "buck_java_library")
buck_java_library(
    name = "coercer",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/core/description/arg:arg",
        "//src/com/facebook/buck/core/starlark/rule/attr:attr",
        "//src/com/facebook/buck/rules/coercer:interface",
    ],
)
