STANDARD_TEST_SRCS = [
  '**/*Test.java',
]

java_library(
  name = 'testutil',
  srcs = glob(['*.java'], excludes = STANDARD_TEST_SRCS),
  deps = [
    '//src/com/facebook/buck/event:event',
    '//src/com/facebook/buck/graph:graph',
    '//src/com/facebook/buck/io:io',
    '//src/com/facebook/buck/model:model',
    '//src/com/facebook/buck/parser:parser',
    '//src/com/facebook/buck/rules:build_rule',
    '//src/com/facebook/buck/rules:rules',
    '//src/com/facebook/buck/shell:steps',
    '//src/com/facebook/buck/step:step',
    '//src/com/facebook/buck/timing:timing',
    '//src/com/facebook/buck/util:io',
    '//src/com/facebook/buck/util:util',
    '//test/com/facebook/buck/timing:testutil',
    '//third-party/java/guava:guava',
    '//third-party/java/hamcrest:hamcrest',
    '//third-party/java/jsr:jsr305',
    '//third-party/java/junit:junit',
    '//third-party/java/okio:okio',
  ],
  visibility = [
    '//test/...',
  ],
)

java_test(
  name = 'test',
  srcs = glob(STANDARD_TEST_SRCS),
  source_under_test = [
    ':testutil',
  ],
  deps = [
    ':testutil',
    '//src/com/facebook/buck/io:io',
    '//src/com/facebook/buck/model:model',
    '//src/com/facebook/buck/timing:timing',
    '//src/com/facebook/buck/rules:build_rule',
    '//src/com/facebook/buck/util:io',
    '//test/com/facebook/buck/model:BuildTargetFactory',
    '//test/com/facebook/buck/testutil/integration:integration',
    '//test/com/facebook/buck/timing:testutil',
    '//third-party/java/guava:guava',
    '//third-party/java/hamcrest:hamcrest',
    '//third-party/java/junit:junit',
  ],
)
