java_library(
  name = 'testutil',
  srcs = glob(['*.java']),
  deps = [
    '//lib:guava',
    '//lib:jsr305',
    '//lib:junit',
    '//src/com/facebook/buck/graph:graph',
    '//src/com/facebook/buck/rules:rules',
    '//src/com/facebook/buck/shell:core',
    '//src/com/facebook/buck/shell:shell',
  ],
  visibility = [
    '//test/com/facebook/buck/command:command',
    '//test/com/facebook/buck/command/io:io',
    '//test/com/facebook/buck/rules:rules',
    '//test/com/facebook/buck/shell:shell',
  ],
)
