STANDARD_TEST_SRCS = [
  '**/*Test.java',
]

java_library(
  name = 'testutil',
  srcs = glob(['*.java'], excludes = STANDARD_TEST_SRCS),
  deps = [
    '//lib:guava',
    '//lib:hamcrest-core',
    '//lib:hamcrest-library',
    '//lib:jsr305',
    '//lib:junit',
    '//src/com/facebook/buck/graph:graph',
    '//src/com/facebook/buck/model:model',
    '//src/com/facebook/buck/rules:build_rule',
    '//src/com/facebook/buck/rules:rules',
    '//src/com/facebook/buck/shell:steps',
    '//src/com/facebook/buck/step:step',
    '//src/com/facebook/buck/util:io',
    '//src/com/facebook/buck/util:util',
  ],
  visibility = [
    '//test/...',
  ],
)

java_test(
  name = 'test',
  srcs = glob(STANDARD_TEST_SRCS),
  source_under_test = [
    ':testutil',
  ],
  deps = [
    ':testutil',
    '//lib:guava',
    '//lib:hamcrest-core',
    '//lib:hamcrest-library',
    '//lib:junit',
    '//src/com/facebook/buck/util:io',
    '//src/com/facebook/buck/model:model',
    '//src/com/facebook/buck/rules:build_rule',
    '//test/com/facebook/buck/model:BuildTargetFactory',
    '//test/com/facebook/buck/testutil/integration:integration',
  ],
)
