java_test(
  name = 'httpserver',
  srcs = glob(['*.java']),
  source_under_test = [
    '//src/com/facebook/buck/httpserver:httpserver',
  ],
  resources = glob(['*.soy']),
  deps = [
    '//lib:easymock',
    '//lib:guava',
    '//lib:hamcrest-core',
    '//lib:hamcrest-library',
    '//lib:junit',
    '//src/com/facebook/buck/httpserver:httpserver',
    '//src/com/facebook/buck/util:constants',
    '//src/com/facebook/buck/util:io',
    '//test/com/facebook/buck/testutil:testutil',
    '//third-party/java/closure-templates:closure-templates',
    '//third-party/java/jetty:jetty',
  ],
)
