CACHE_INTEGRATION_SRCS = [
    "ServedCacheIntegrationTest.java",
]

java_test(
    name = "httpserver",
    srcs = glob(
        ["*.java"],
        excludes = CACHE_INTEGRATION_SRCS,
    ),
    autodeps = True,
    resources = glob(["*.soy"]),
    deps = [
        "//src/com/facebook/buck/httpserver:httpserver",
        "//src/com/facebook/buck/httpserver:util",
        "//src/com/facebook/buck/io:io",
        "//src/com/facebook/buck/util:constants",
        "//src/com/facebook/buck/util:object_mapper",
        "//src/com/facebook/buck/util/trace:trace",
        "//test/com/facebook/buck/testutil:testutil",
        "//third-party/java/closure-templates:closure-templates",
        "//third-party/java/easymock:easymock",
        "//third-party/java/guava:guava",
        "//third-party/java/hamcrest:java-hamcrest",
        "//third-party/java/jetty:jetty",
        "//third-party/java/junit:junit",
    ],
)

java_test(
    name = "httpserver_cache_integration_test",
    srcs = CACHE_INTEGRATION_SRCS,
    autodeps = True,
    deps = [
        "//src/com/facebook/buck/artifact_cache:artifact_cache",
        "//src/com/facebook/buck/artifact_cache:config",
        "//src/com/facebook/buck/cli:config",
        "//src/com/facebook/buck/event:interfaces",
        "//src/com/facebook/buck/httpserver:httpserver",
        "//src/com/facebook/buck/io:io",
        "//src/com/facebook/buck/rules:rule_key",
        "//src/com/facebook/buck/util:object_mapper",
        "//src/com/facebook/buck/util/environment:platform",
        "//test/com/facebook/buck/artifact_cache:testutil",
        "//test/com/facebook/buck/cli:testutil",
        "//test/com/facebook/buck/event:testutil",
        "//test/com/facebook/buck/testutil/integration:util",
        "//third-party/java/guava:guava",
        "//third-party/java/hamcrest:java-hamcrest",
        "//third-party/java/jackson:jackson-databind",
        "//third-party/java/junit:junit",
    ],
)
