load("//tools/build_rules:java_rules.bzl", "standard_java_test")

standard_java_test(
    name = "bsd",
    deps = [
        "//src/com/facebook/buck/util/bsd:bsd",
        "//src/com/facebook/buck/util/charset:charset",
        "//src/com/facebook/buck/util/immutables:immutables",
        "//third-party/java/guava:guava",
        "//third-party/java/hamcrest:java-hamcrest",
        "//third-party/java/immutables:immutables",
        "//third-party/java/jsr:jsr305",
        "//third-party/java/junit:junit",
    ],
)
