load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "registry",
    srcs = glob(["*.java"]),
    visibility = [
        "PUBLIC",
    ],
    deps = [
    ],
    exported_deps = [
        "//src/com/facebook/buck/core/model/platform:platform",
        "//src/com/facebook/buck/core/rules/config:config",
    ],
)
