java_library(
    name = "skylark",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/io/filesystem:filesystem",
        "//src/com/facebook/buck/util:util",
        "//third-party/java/bazel:skylark-lang",
    ],
)
