java_library(
    name = "skylark",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/io/filesystem:filesystem",
        "//src/com/facebook/buck/util:util",
    ],
    exported_deps = [
        "//third-party/java/bazel:bazel",
    ],
)
