EMPTY_CONFIGS = {
  'Debug': {},
  'Release': {},
}

apple_binary(
  name = 'TestAppBinary',
  configs = EMPTY_CONFIGS,
  srcs = [],
  frameworks = [],
  deps = [
    '//Libraries:Dep1',
    '//Libraries:Dep2',
  ],
)

apple_bundle(
  name = 'TestApp',
  deps = [':TestAppBinary'],
  binary = ':TestAppBinary',
  extension = 'app',
)

apple_library(
  name = 'TestAppTestsLibrary',
  configs = EMPTY_CONFIGS,
  srcs = [],
  frameworks = [],
  deps = [
    '//Libraries:Dep1',
    '//Libraries:Dep2',
  ],
)

apple_bundle(
  name = 'TestAppTests',
  extension = 'octest',
  deps = [':TestAppTestsLibrary#dynamic'],
  binary = ':TestAppTestsLibrary#dynamic',
)
  
apple_test(
  name = 'TestAppTestsTest',
  test_bundle = ':TestAppTests',
  deps = [':TestAppTests'],
  source_under_test = [':TestApp'],
)

xcode_project_config(
  name = 'project',
  project_name = 'TestApp',
  rules = [
    ':TestApp',
    ':TestAppTests',
  ],
)

xcode_workspace_config(
  name = 'workspace',
  src_target = '//Apps:TestApp'
)
