apple_bundle(
  name = 'DemoApp',
  binary = ':DemoAppBinary',
  extension = 'app',
  info_plist = 'Info.plist',
  info_plist_substitutions = {
    'LONG_VERSION_STRING': '1.0',
  },
)

apple_binary(
  name = 'DemoAppBinary',
  preprocessor_flags = ['-fobjc-arc'],
  headers = glob([
    '*.h',
  ]),
  srcs = glob([
    '*.m',
  ]),
  frameworks = [
    '$SDKROOT/System/Library/Frameworks/UIKit.framework',
    '$SDKROOT/System/Library/Frameworks/Foundation.framework',
    '$SDKROOT/usr/lib/libobjc.dylib',
  ],
)
