R_DOT_JAVA_SRCS = [
  'GenRDotJavaStep.java',
  'HasAndroidResourceDeps.java',
  'MergeAndroidResourcesStep.java',
  'UberRDotJavaUtil.java',
]
java_library(
  name = 'r',
  srcs = R_DOT_JAVA_SRCS,
  deps = [
    ':exceptions',
    '//lib:guava',
    '//src/com/facebook/buck/graph:graph',
    '//src/com/facebook/buck/java:steps',
    '//src/com/facebook/buck/java:support',
    '//src/com/facebook/buck/model:model',
    '//src/com/facebook/buck/rules:rules',
    '//src/com/facebook/buck/shell:steps',
    '//src/com/facebook/buck/step:step',
    '//src/com/facebook/buck/step/fs:fs',
    '//src/com/facebook/buck/util:constants',
    '//src/com/facebook/buck/util:exceptions',
    '//src/com/facebook/buck/util:io',
    '//src/com/facebook/buck/util:util',
  ],
  visibility = ['PUBLIC'],
)

EXCEPTION_SRCS = [
  'NoAndroidSdkException.java',
]
java_library(
  name = 'exceptions',
  srcs = EXCEPTION_SRCS,
  deps = [
    '//src/com/facebook/buck/util:exceptions',
  ],
  visibility = ['PUBLIC'],
)

RULES_SRCS = [
  'AndroidBinaryBuildRuleFactory.java',
  'AndroidBinaryRule.java',
  'AndroidDexTransitiveDependencies.java',
  'AndroidInstrumentationApk.java',
  'AndroidInstrumentationApkRuleFactory.java',
  'AndroidLibraryBuildRuleFactory.java',
  'AndroidLibraryRule.java',
  'AndroidManifestBuildRuleFactory.java',
  'AndroidManifestRule.java',
  'AndroidResourceBuildRuleFactory.java',
  'AndroidResourceRule.java',
  'AndroidTransitiveDependencies.java',
  'AndroidTransitiveDependencyGraph.java',
  'ApkGenrule.java',
  'ApkGenruleBuildRuleFactory.java',
  'GenAidlBuildRuleFactory.java',
  'GenAidlRule.java',
  'HasAndroidPlatformTarget.java',
  'NdkLibraryBuildRuleFactory.java',
  'NdkLibrary.java',
  'RobolectricTestBuildRuleFactory.java',
  'RobolectricTestRule.java',
]
java_library(
  name = 'rules',
  srcs = RULES_SRCS,
  deps = [
    ':r',
    ':steps',
    '//lib:guava',
    '//lib:jsr305',
    '//src/com/facebook/buck/cpp:rules',
    '//src/com/facebook/buck/java:rules',
    '//src/com/facebook/buck/java:support',
    '//src/com/facebook/buck/model:model',
    '//src/com/facebook/buck/parser:support',
    '//src/com/facebook/buck/rules:rules',
    '//src/com/facebook/buck/shell:steps',
    '//src/com/facebook/buck/shell:rules',
    '//src/com/facebook/buck/step:step',
    '//src/com/facebook/buck/step/fs:fs',
    '//src/com/facebook/buck/util:constants',
    '//src/com/facebook/buck/util:exceptions',
    '//src/com/facebook/buck/util:io',
    '//src/com/facebook/buck/util:util',
    '//third-party/java/aosp/src/com/android:aosp',
  ],
  visibility = ['PUBLIC'],
)

java_library(
  name = 'steps',
  srcs = glob(['*.java'], excludes = EXCEPTION_SRCS + R_DOT_JAVA_SRCS + RULES_SRCS),
  deps = [
    ':exceptions',
    '//lib:guava',
    '//lib:jsr305',
    '//lib:sdklib',
    '//src/com/facebook/buck/event:event',
    '//src/com/facebook/buck/model:model',
    '//src/com/facebook/buck/shell:steps',
    '//src/com/facebook/buck/step:step',
    '//src/com/facebook/buck/step/fs:fs',
    '//src/com/facebook/buck/util:exceptions',
    '//src/com/facebook/buck/util:io',
    '//src/com/facebook/buck/util:util',
    '//src/com/facebook/buck/util/environment:environment',
    '//third-party/java/aosp/src/com/android:aosp',
  ],
  visibility = ['PUBLIC'],
)

