EXCEPTION_SRCS = [
  'NoAndroidSdkException.java',
]
java_library(
  name = 'exceptions',
  srcs = EXCEPTION_SRCS,
  tests = [
    '//test/com/facebook/buck/android:unit',
    '//test/com/facebook/buck/android:integration',
  ],
  autodeps = True,
  exported_deps = [
    '//src/com/facebook/buck/util:exceptions',  # Inherits from HumanReadableException
  ],
  visibility = ['PUBLIC'],
)

PACKAGEABLE_SOURCES = [
  'AbstractAndroidPackageableCollection.java',
  'AndroidPackageable.java',
  'AndroidPackageableCollector.java',
]
java_immutables_library(
  name = 'packageable',
  srcs = PACKAGEABLE_SOURCES,
  tests = [
    '//test/com/facebook/buck/android:unit',
    '//test/com/facebook/buck/android:aar-integration',
    '//test/com/facebook/buck/android:binary-integration',
    '//test/com/facebook/buck/android:build-config-integration',
    '//test/com/facebook/buck/android:instrumentation-integration',
    '//test/com/facebook/buck/android:integration',
  ],
  autodeps = True,
  visibility = ['PUBLIC'],
)

RULES_SRCS = [
  'AaptPackageResources.java',
  'AbstractAndroidGraphEnhancementResult.java',
  'AndroidAar.java',
  'AndroidAarDescription.java',
  'AndroidBinaryGraphEnhancer.java',
  'AndroidBinary.java',
  'AndroidBinaryDescription.java',
  'AndroidBuckConfig.java',
  'AndroidBuildConfig.java',
  'AndroidBuildConfigDescription.java',
  'AndroidBuildConfigJavaLibrary.java',
  'AndroidInstrumentationApk.java',
  'AndroidInstrumentationApkDescription.java',
  'AndroidLibraryDescription.java',
  'AndroidLibraryGraphEnhancer.java',
  'AndroidLibrary.java',
  'AndroidManifest.java',
  'AndroidManifestDescription.java',
  'AndroidNativeLibsPackageableGraphEnhancer.java',
  'AndroidPrebuiltAar.java',
  'AndroidPrebuiltAarCollection.java',
  'AndroidPrebuiltAarDescription.java',
  'AndroidResource.java',
  'AndroidResourceDescription.java',
  'AndroidResourceHelper.java',
  'AndroidInstrumentationTest.java',
  'AndroidInstrumentationTestDescription.java',
  'AndroidTransitiveDependencyGraph.java',
  'ApkGenrule.java',
  'ApkGenruleDescription.java',
  'AssembleDirectories.java',
  'BootClasspathAppender.java',
  'ComputeExopackageDepsAbi.java',
  'CopyNativeLibraries.java',
  'DexProducedFromJavaLibrary.java',
  'DexWithClasses.java',
  'DummyRDotJava.java',
  'FilteredResourcesProvider.java',
  'IdentityResourcesProvider.java',
  'GenAidl.java',
  'GenAidlDescription.java',
  'HasAndroidResourceDeps.java',
  'MergeAndroidResourcesStep.java',
  'NativeLibraryBuildRule.java',
  'NdkLibraryDescription.java',
  'NdkLibrary.java',
  'PackageStringAssets.java',
  'PreDexedFilesSorter.java',
  'PreDexMerge.java',
  'PrebuiltNativeLibrary.java',
  'PrebuiltNativeLibraryDescription.java',
  'ProGuardConfig.java',
  'ResourcesFilter.java',
  'RobolectricTestDescription.java',
  'RobolectricTest.java',
  'RDotJava.java',
  'StripLinkable.java',
  'UnsortedAndroidResourceDeps.java',
  'UnzipAar.java',
  # This and the InstrumentationStep would make more sense in the steps
  # library, but are added here to avoid circular dependencies.
  'ApkInstallStep.java',
  'InstrumentationStep.java',
]
java_immutables_library(
  name = 'rules',
  srcs = RULES_SRCS,
  tests = [
    '//test/com/facebook/buck/android:unit',
    '//test/com/facebook/buck/android:aar-integration',
    '//test/com/facebook/buck/android:binary-integration',
    '//test/com/facebook/buck/android:build-config-integration',
    '//test/com/facebook/buck/android:instrumentation-integration',
    '//test/com/facebook/buck/android:integration',
  ],
  autodeps = True,
  exported_deps = [
    ':packageable', # AndroidLibrary implements AndroidPackageable.
    '//src/com/facebook/buck/rules:rules',
  ],
  visibility = ['PUBLIC'],
)

SPLIT_DEX_SRCS = [
  'DexSplitMode.java',
  'DexStore.java',
]

java_library(
  name = 'split_dex',
  srcs = SPLIT_DEX_SRCS,
  tests = [
    '//test/com/facebook/buck/android:unit',
    '//test/com/facebook/buck/android:binary-integration',
    '//test/com/facebook/buck/android:instrumentation-integration',
    '//test/com/facebook/buck/android:integration',
  ],
  autodeps = True,
  visibility = [
    'PUBLIC',
  ],
)

HELPERS_SRCS = [
  'AdbHelper.java',
  'BuckXmlTestRunListener.java',
  'ExopackageInstaller.java',
]

# java_library?
java_immutables_library(
  name = 'helpers',
  srcs = HELPERS_SRCS,
  tests = [
    '//test/com/facebook/buck/android:unit',
    '//test/com/facebook/buck/android:integration',
  ],
  autodeps = True,
  visibility = ['PUBLIC'],
)

UTILS_SRCS = [
  'AndroidPlatformTarget.java',
  'AndroidManifestReader.java',
  'DefaultAndroidManifestReader.java',
  'AndroidDirectoryResolver.java',
  'DefaultAndroidDirectoryResolver.java',
]

java_library(
  name = 'utils',
  srcs = UTILS_SRCS,
  tests = [
    '//test/com/facebook/buck/android:unit',
    '//test/com/facebook/buck/android:integration',
  ],
  autodeps = True,
  visibility = ['PUBLIC'],
)

java_immutables_library(
  name = 'steps',
  srcs = glob(['*.java'],
              excludes = EXCEPTION_SRCS + PACKAGEABLE_SOURCES + RULES_SRCS + SPLIT_DEX_SRCS +
                  UTILS_SRCS + HELPERS_SRCS),
  tests = [
    '//test/com/facebook/buck/android:steps',
    '//test/com/facebook/buck/android:integration',
  ],
  autodeps = True,
  exported_deps = [
    '//src/com/facebook/buck/shell:steps',
    '//src/com/facebook/buck/step:step',

    # BuckEventAndroidLogger implements com.android.common.utils.ILogger.
    '//third-party/java/aosp:aosp',
  ],
  visibility = ['PUBLIC'],
)
