java_test(
  name = 'dalvik',
  srcs = glob(['*.java']),
  source_under_test = [
    '//src/com/facebook/buck/dalvik:dalvik',
    '//src/com/facebook/buck/dalvik:dalvik_stats_tool',
    '//src/com/facebook/buck/dalvik:steps',
  ],
  deps = [
    '//third-party/java/guava:guava',
    '//third-party/java/junit:junit',
    '//src/com/facebook/buck/dalvik:dalvik',
    '//src/com/facebook/buck/dalvik:dalvik_stats_tool',
    '//src/com/facebook/buck/dalvik:steps',
    '//src/com/facebook/buck/java/classes:classes',
    '//src/com/facebook/buck/step:step',
    '//src/com/facebook/buck/util:io',
    '//test/com/facebook/buck/java:testutil',
    '//test/com/facebook/buck/step:testutil',
    '//third-party/java/asm:asm',
  ],
)
