java_test(
  name = 'dalvik',
  srcs = glob(['*.java']),
  source_under_test = [
    '//src/com/facebook/buck/dalvik:dalvik',
    '//src/com/facebook/buck/dalvik:dalvik_stats_tool',
  ],
  deps = [
    '//lib:guava',
    '//lib:junit',
    '//src/com/facebook/buck/dalvik:dalvik',
    '//src/com/facebook/buck/dalvik:dalvik_stats_tool',
  ],
)
