java_immutables_library(
    name = "simulator",
    srcs = glob(["*.java"]),
    tests = [
        "//test/com/facebook/buck/apple/simulator:simulator",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/log:api",
        "//src/com/facebook/buck/util:io",
        "//src/com/facebook/buck/util:process_executor",
        "//third-party/java/dd-plist:dd-plist",
    ],
)
