load("//tools/build_rules:java_rules.bzl", "standard_java_test")

java_library(
    name = "testutil",
    srcs = glob(
        ["*.java"],
        exclude = [
            "*Test.java",
        ],
    ),
    exported_deps = [
        "//src/com/facebook/buck/core/model/platform:platform",
    ],
    visibility = ["//test/..."],
)

standard_java_test(
    name = "platform",
    deps = [
        "//src/com/facebook/buck/core/model/platform:platform",
        "//test/com/facebook/buck/core/model:testutil",
        "//third-party/java/junit:junit",
    ],
)
