load("//tools/build_rules:java_rules.bzl", "standard_java_test")

java_library(
    name = "testutil",
    srcs = glob(
        ["*.java"],
        exclude = [
            "*Test.java",
        ],
    ),
    exported_deps = [
        "//src/com/facebook/buck/core/model/platform:platform",
    ],
    visibility = ["//test/..."],
)
