load("//tools/build_rules:java_rules.bzl", "buck_java_library")
buck_java_library(
    name = "attr",
    srcs = glob(["*.java"]),
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//third-party/java/guava:guava",
    ],
    exported_deps = [
        "//src/com/facebook/buck/core/cell:cell",
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/rules/param:param",
        "//src/com/facebook/buck/util/collect:collect",
    ],
)
