load("//tools/build_rules:java_rules.bzl", "buck_java_library")
buck_java_library(
    name = "javax",
    srcs = glob([
        "*.java",
    ]),
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/jvm/java/version/utils:utils",
    ],
)
