java_test(
  name = 'coercer',
  srcs = glob(['*.java']),
  source_under_test = [
    '//src/com/facebook/buck/rules:build_rule',
  ],
  deps = [
    '//third-party/java/guava:guava',
    '//third-party/java/junit:junit',
    '//src/com/facebook/buck/rules:build_rule',
    '//src/com/facebook/buck/model:model',
    '//src/com/facebook/buck/parser:rule_pattern',
    '//src/com/facebook/buck/util:io',
    '//test/com/facebook/buck/testutil:testutil',
  ],
)
