load("//tools/build_rules:java_rules.bzl", "standard_java_benchmark", "standard_java_test")

standard_java_test(
    name = "coercer",
    has_immutable_types = True,
    deps = [
        "//src/com/facebook/buck/core/description/arg:arg",
        "//src/com/facebook/buck/core/linkgroup:linkgroup",
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/core/model/platform/impl:impl",
        "//src/com/facebook/buck/core/rules:rules",
        "//src/com/facebook/buck/core/rules/knowntypes:knowntypes",
        "//src/com/facebook/buck/core/rules/platform:platform",
        "//src/com/facebook/buck/core/select/impl:impl",
        "//src/com/facebook/buck/core/test/rule:rule",
        "//src/com/facebook/buck/parser:parser",
        "//src/com/facebook/buck/parser/syntax:syntax",
        "//src/com/facebook/buck/query:query",
        "//src/com/facebook/buck/rules/coercer:coercer",
        "//src/com/facebook/buck/rules/keys:keys",
        "//src/com/facebook/buck/rules/macros:macros",
        "//src/com/facebook/buck/rules/macros:types",
        "//src/com/facebook/buck/versions:translator",
        "//test/com/facebook/buck/core/cell:testutil",
        "//test/com/facebook/buck/core/cell/nameresolver:testutil",
        "//test/com/facebook/buck/core/model:testutil",
        "//test/com/facebook/buck/core/rules/platform:testutil",
        "//test/com/facebook/buck/core/rules/resolver/impl:testutil",
        "//test/com/facebook/buck/core/select:testutil",
        "//test/com/facebook/buck/core/sourcepath:testutil",
        "//test/com/facebook/buck/io/file:testutil",
        "//test/com/facebook/buck/rules/keys:testutil",
        "//test/com/facebook/buck/rules/macros:testutil",
        "//test/com/facebook/buck/testutil/integration:util",
        "//test/com/facebook/buck/util:testutil",
        "//test/com/facebook/buck/versions:testutil",
        "//third-party/java/junit:junit",
    ],
)

standard_java_benchmark(
    name = "benchmark",
    deps = [
        "//src/com/facebook/buck/rules/coercer:coercer",
        "//src/com/facebook/buck/rules/macros:types",
        "//test/com/facebook/buck/core/cell:testutil",
        "//test/com/facebook/buck/io/filesystem/impl:testutil",
    ],
)
