java_library(
  name = 'api',
  srcs = glob(['*.java']),
  autodeps = False, # See below.
  deps = [
  # Don't add deps; this is a super-light library that can be used outside of Buck
  ],
  visibility = [
    'PUBLIC',
  ],
)
