load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "config",
    srcs = glob(["*.java"]),
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/command/config:config",
        "//src/com/facebook/buck/core/rules/analysis/config:config",
        "//src/com/facebook/buck/parser/options:options",
    ],
    exported_deps = [
        "//src/com/facebook/buck/core/cell:cell",
        "//src/com/facebook/buck/core/config:config",
        "//src/com/facebook/buck/io/watchman:watchman",
        "//src/com/facebook/buck/parser/api:api",
        "//src/com/facebook/buck/parser/exceptions:exceptions",
        "//src/com/facebook/buck/parser/implicit:implicit",
    ],
)
