load(
    "//tools/build_rules:java_rules.bzl",
    "standard_java_test",
)

standard_java_test(
    name = "lib",
    with_test_data = True,
    deps = [
        "//src/com/facebook/buck/core/rules/actions/lib:lib",
        "//src/com/facebook/buck/core/rules/actions/lib/args:args",
        "//test/com/facebook/buck/core/model:testutil",
        "//test/com/facebook/buck/core/rules/actions:testutil",
        "//test/com/facebook/buck/io/filesystem:testutil",
        "//test/com/facebook/buck/step/impl:testutil",
        "//test/com/facebook/buck/testutil:testutil",
        "//test/com/facebook/buck/testutil/integration:util",
        "//third-party/java/guava:guava",
        "//third-party/java/junit:junit",
    ],
)
