java_library(
    name = "args",
    srcs = glob(
        ["*.java"],
    ),
    exported_deps = [
        "//third-party/java/args4j:args4j",
        "//third-party/java/pf4j:pf4j",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//third-party/java/guava:guava",
    ],
)
