java_test(
  name = 'tracing',
  srcs = glob(['*.java']),
  deps = [
    '//src/com/facebook/buck/event:event',
    '//src/com/facebook/buck/model:model',
    '//src/com/facebook/buck/java/tracing:api',
    '//src/com/facebook/buck/java/tracing:compiler-plugin',
    '//src/com/facebook/buck/java/tracing:tracing',
    '//test/com/facebook/buck/event:testutil',
    '//test/com/facebook/buck/model:BuildTargetFactory',    
    '//third-party/java/easymock:easymock',
    '//third-party/java/guava:guava',
    '//third-party/java/junit:junit',
    '//third-party/java/jdk:compiler-tree-api',
  ],
  source_under_test = [
    '//src/com/facebook/buck/java/tracing:compiler-plugin',
    '//src/com/facebook/buck/java/tracing:tracing',
  ],
)
