standard_java_library(
    name = "distributed",
    immutable_types = [
        "DistBuildExecutorArgs",
        "DistBuildStatus",
    ],
    tests = [
        "//test/com/facebook/buck/distributed:distributed",
    ],
)
