java_immutables_library(
  name = 'distributed',
  srcs = glob(['*.java']),
  immutable_types = [
    'DistBuildStatus',
  ],
  tests = [
    '//test/com/facebook/buck/distributed:distributed',
  ],
  autodeps = True,
  visibility = [ 'PUBLIC' ],
)
