java_library(
    name = "randomizedtrial",
    srcs = glob(["*.java"]),
    exported_deps = [
        "//src/com/facebook/buck/model:build_id",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/log:api",
        "//src/com/facebook/buck/util:util",
        "//third-party/java/guava:guava",
    ],
)
