load("//tools/build_rules:java_rules.bzl", "java_immutables_library", "java_test")

java_test(
    name = "compatible",
    srcs = glob(["*Test.java"]),
    has_immutable_types = True,
    deps = [
        "//src/com/facebook/buck/core/starlark/compatible:compatible",
        "//third-party/java/junit:junit",
    ],
)
