java_library(
  name = 'tracing',
  srcs = [
    'JavacPhaseEvent.java',
  ],
  deps = [
    '//src/com/facebook/buck/event:event',
    '//src/com/facebook/buck/log:api',
    '//src/com/facebook/buck/model:model',
    '//src/com/facebook/buck/step:step',
    '//src/com/facebook/buck/util:util',
    '//third-party/java/guava:guava',
    '//third-party/java/infer-annotations:infer-annotations',
    '//third-party/java/jsr:jsr305',
  ],
  visibility = [
    '//src/com/facebook/buck/event/listener:listener',
    '//test/com/facebook/buck/event/listener:listener',
    '//test/com/facebook/buck/java/tracing:tracing',
  ],
)

java_library(
  name = 'api',
  srcs = [
    'JavacPhaseTracer.java',
  ],
  deps = [
    # Don't add deps; this is a super-light API that is loaded within javac. It can't access
    # code outside of Buck's bootstrapper.
  ],
  visibility = [
    '//src/com/facebook/buck/cli/bootstrapper:bootstrapper',
  ],
)
