EMPTY_CONFIGS = {
  'Debug': (
    '',
    {},
    '',
    {},
  ),
  'Release': (
    '',
    {},
    '',
    {},
  ),
}

apple_library(
  name = 'Dep1',
  configs = EMPTY_CONFIGS,
  srcs = [],
  frameworks = [],
  deps = [],
  visibility = ['PUBLIC'],
)

apple_library(
  name = 'Dep2',
  configs = EMPTY_CONFIGS,
  srcs = [],
  frameworks = [],
  deps = [],
  visibility = ['PUBLIC'],
)

apple_library(
  name = 'Dep3',
  configs = EMPTY_CONFIGS,
  srcs = [],
  frameworks = [],
  deps = [],
  visibility = ['PUBLIC'],
)

xcode_project_config(
  name = 'project1',
  project_name = 'Dep1',
  rules = [
    ':Dep1',
  ],
)

xcode_project_config(
  name = 'project2',
  project_name = 'Dep2',
  rules = [
    ':Dep2',
  ],
)

xcode_project_config(
  name = 'project3',
  project_name = 'Dep3',
  rules = [
    ':Dep3',
  ],
)
