java_library(
    name = "graph",
    srcs = glob(["*.java"]),
    tests = [
        "//test/com/facebook/buck/graph:graph",
    ],
    visibility = ["PUBLIC"],
    deps = ["//third-party/java/guava:guava"],
)
