PUBLIC_API_SOURCES = [
    "ArtifactCacheFactory.java",
    "AbstractArtifactInfo.java",
    "AbstractCacheResult.java",
    "AbstractNetworkCacheArgs.java",
    "ArtifactCache.java",
    "ArtifactCacheEvent.java",
    "ArtifactCacheEventFactory.java",
    "HttpArtifactCacheEvent.java",
    "DirArtifactCache.java",
    "DirArtifactCacheEvent.java",
    "ArtifactCacheConnectEvent.java",
    "CacheResultType.java",
    "NoopArtifactCache.java",
]

java_immutables_library(
    name = "artifact_cache",
    srcs = PUBLIC_API_SOURCES,
    autodeps = True,
    exported_deps = [
        "//src/com/facebook/buck/cli:config",
        "//src/com/facebook/buck/event:interfaces",
        "//src/com/facebook/buck/io:io",
        "//src/com/facebook/buck/model:build_id",
        "//src/com/facebook/buck/model:model",
        "//src/com/facebook/buck/rules:rule_key",
        "//src/com/facebook/buck/slb:slb",
        "//src/com/facebook/buck/util/immutables:immutables",
        "//third-party/java/guava:guava",
        "//third-party/java/jackson:jackson-annotations",
    ],
    immutable_types = [
        "ArtifactInfo",
        "CacheResult",
    ],
    tests = [
        "//test/com/facebook/buck/artifact_cache:artifact_cache",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/log:api",
        "//src/com/facebook/buck/log/views:views",
        "//src/com/facebook/buck/util:io",
        "//third-party/java/immutables:immutables",
        "//third-party/java/okhttp:okhttp",
        "//third-party/java/okio:okio",
    ],
)

PROTOCOL_SOURCES = [
    "HttpArtifactCacheBinaryProtocol.java",
]

java_immutables_library(
    name = "binary_protocol",
    srcs = PROTOCOL_SOURCES,
    autodeps = True,
    exported_deps = [
        "//src/com/facebook/buck/artifact_cache:artifact_cache",
        "//src/com/facebook/buck/rules:rule_key",
        "//src/com/facebook/buck/util/immutables:immutables",
        "//third-party/java/guava:guava",
    ],
    immutable_types = [
        "HttpArtifactCacheArgs",
        "FetchResponseReadResult",
        "MetadataAndPayloadReadResultInternal",
        "StoreResponseReadResult",
        "StoreWriteResult",
    ],
    tests = [
        "//test/com/facebook/buck/artifact_cache:artifact_cache",
    ],
    visibility = [
        "//src/com/facebook/buck/artifact_cache:generate_hybrid_payloads",
        "//src/com/facebook/buck/httpserver:cache_handler",
        "//test/com/facebook/buck/artifact_cache:artifact_cache",
    ],
    deps = [
        "//src/com/facebook/buck/util/hash:hash",
        "//third-party/java/immutables:immutables",
    ],
)

CONFIG_SOURCES = [
    "ArtifactCacheBuckConfig.java",
    "ArtifactCaches.java",
    "SingletonArtifactCacheFactory.java",
]

java_immutables_library(
    name = "config",
    srcs = CONFIG_SOURCES,
    autodeps = True,
    exported_deps = [
        "//src/com/facebook/buck/artifact_cache:artifact_cache",
        "//src/com/facebook/buck/cli:config",
        "//src/com/facebook/buck/event:interfaces",
        "//src/com/facebook/buck/io:io",
        "//src/com/facebook/buck/slb:slb",
        "//src/com/facebook/buck/util:util",
        "//src/com/facebook/buck/util/immutables:immutables",
        "//third-party/java/guava:guava",
        "//third-party/java/okhttp:okhttp",
        "//third-party/java/okio:okio",
    ],
    immutable_types = [
        "DirCacheEntry",
        "HttpCacheEntry",
    ],
    tests = [
        "//test/com/facebook/buck/artifact_cache:artifact_cache",
        "//test/com/facebook/buck/httpserver:httpserver_cache_integration_test",
    ],
    visibility = [
        "//src/com/facebook/buck/cli:cli",
        "//src/com/facebook/buck/httpserver:cache_handler",
        "//src/com/facebook/buck/ide/intellij:intellij",
        "//test/com/facebook/buck/artifact_cache/...",
        "//test/com/facebook/buck/cli/...",
        "//test/com/facebook/buck/httpserver:httpserver_cache_integration_test",
    ],
    deps = [
        "//src/com/facebook/buck/artifact_cache:impl",
        "//src/com/facebook/buck/event:event",
        "//src/com/facebook/buck/log:api",
        "//src/com/facebook/buck/randomizedtrial:randomizedtrial",
        "//src/com/facebook/buck/timing:timing",
        "//src/com/facebook/buck/util:exceptions",
        "//src/com/facebook/buck/util/unit:unit",
        "//third-party/java/immutables:immutables",
    ],
)

GENERATOR_SOURCE = [
    "HybridPayloadGenerator.java",
]

java_library(
    name = "impl",
    srcs = glob(
        ["*.java"],
        excludes = PUBLIC_API_SOURCES + CONFIG_SOURCES + PROTOCOL_SOURCES + GENERATOR_SOURCE,
    ),
    autodeps = True,
    exported_deps = [
        "//src-gen:thrift",
        "//src/com/facebook/buck/artifact_cache:artifact_cache",
        "//src/com/facebook/buck/event:interfaces",
        "//src/com/facebook/buck/io:io",
        "//src/com/facebook/buck/rules:rule_key",
        "//src/com/facebook/buck/slb:slb",
        "//third-party/java/guava:guava",
        "//third-party/java/okhttp:okhttp",
        "//third-party/java/okio:okio",
    ],
    tests = [
        "//test/com/facebook/buck/artifact_cache:artifact_cache",
    ],
    visibility = [
        "//test/com/facebook/buck/artifact_cache/...",
    ],
    deps = [
        "//src/com/facebook/buck/artifact_cache:binary_protocol",
        "//src/com/facebook/buck/counters:counters",
        "//src/com/facebook/buck/event:event",
        "//src/com/facebook/buck/log:api",
        "//src/com/facebook/buck/util:exceptions",
    ],
)

java_binary(
    name = "generate-hybrid-payloads",
    main_class = "com.facebook.buck.artifact_cache.HybridPayloadGenerator",
    deps = [
        ":lib-generate-hybrid-payloads",
    ],
)

java_library(
    name = "lib-generate-hybrid-payloads",
    srcs = GENERATOR_SOURCE,
    autodeps = True,
    visibility = ["PUBLIC"],
    deps = [
        "//src-gen:thrift",
        "//src/com/facebook/buck/artifact_cache:impl",
        "//src/com/facebook/buck/slb:slb",
        "//third-party/java/guava:guava",
    ],
)
