PUBLIC_API_IMMUTABLES = [
  'AbstractCacheResult.java',
]
PUBLIC_API_SOURCES = [
  'ArtifactCache.java',
  'ArtifactCacheEvent.java',
  'ArtifactCacheEventFactory.java',
  'HttpArtifactCacheEvent.java',
  'DirArtifactCacheEvent.java',
  'ArtifactCacheConnectEvent.java',
  'CacheResultType.java',
  'NoopArtifactCache.java',
]
PROTOCOL_SOURCES = [
  'HttpArtifactCacheBinaryProtocol.java'
]
CONFIG_SOURCES = [
  'ArtifactCacheBuckConfig.java',
  'ArtifactCaches.java',
]

java_immutables_library(
  name = 'artifact_cache',
  srcs = PUBLIC_API_SOURCES,
  immutable_srcs = PUBLIC_API_IMMUTABLES,
  tests = [
    '//test/com/facebook/buck/artifact_cache:artifact_cache',
  ],
  autodeps = True,
  visibility = [
    'PUBLIC',
  ],
)

java_immutables_library(
  name = 'binary_protocol',
  srcs = PROTOCOL_SOURCES,
  tests = [
    '//test/com/facebook/buck/artifact_cache:artifact_cache',
  ],
  autodeps = True,
  visibility = [
    '//src/com/facebook/buck/httpserver:cache_handler',
  ],
)

java_immutables_library(
  name = 'impl',
  srcs = glob(['*.java'],
              excludes=PUBLIC_API_SOURCES + PUBLIC_API_IMMUTABLES + \
                       CONFIG_SOURCES + PROTOCOL_SOURCES),
  tests = [
    '//test/com/facebook/buck/artifact_cache:artifact_cache',
  ],
  autodeps = True,
  exported_deps = [
    '//src/com/facebook/buck/artifact_cache:binary_protocol',
    '//src/com/facebook/buck/artifact_cache:artifact_cache',
  ],
  visibility = [
    '//test/com/facebook/buck/artifact_cache/...',
  ],
)

java_immutables_library(
  name = 'config',
  srcs = [
    'ArtifactCacheBuckConfig.java',
    'ArtifactCaches.java',
  ],
  tests = [
    '//test/com/facebook/buck/artifact_cache:artifact_cache',
    '//test/com/facebook/buck/httpserver:httpserver_cache_integration_test',
  ],
  autodeps = True,
  visibility = [
    '//src/com/facebook/buck/cli:cli',
    '//src/com/facebook/buck/httpserver:cache_handler',
    '//test/com/facebook/buck/artifact_cache/...',
    '//test/com/facebook/buck/cli/...',
    '//test/com/facebook/buck/httpserver:httpserver_cache_integration_test',
  ]
)
