java_test(
  name = 'hashing',
  srcs = glob(['*Test.java']),
  deps = [
    '//src/com/facebook/buck/hashing:hashing',
    '//src/com/facebook/buck/io:io',
    '//src/com/facebook/buck/timing:timing',
    '//src/com/facebook/buck/util/cache:cache',
    '//test/com/facebook/buck/testutil:testutil',
    '//test/com/facebook/buck/timing:testutil',
    '//third-party/java/guava:guava',
    '//third-party/java/hamcrest:hamcrest',
    '//third-party/java/jimfs:jimfs',
    '//third-party/java/junit:junit',
  ]
)
