load("//tools/build_rules:java_rules.bzl", "standard_java_test")

standard_java_test(
    name = "buildtargetpattern",
    deps = [
        "//src/com/facebook/buck/core/parser/buildtargetpattern:buildtargetpattern",
        "//third-party/java/guava:guava",
        "//third-party/java/junit:junit",
        "//third-party/java/junitparams:junitparams",
    ],
)
