java_test(
  name = 'zip',
  srcs = glob(['*.java']),
  deps = [
    '//lib:easymock',
    '//lib:guava',
    '//lib:junit',
    '//src/com/facebook/buck/shell:steps',
    '//src/com/facebook/buck/step:step',
    '//src/com/facebook/buck/step/fs:fs',
    '//src/com/facebook/buck/util:io',
    '//src/com/facebook/buck/zip:steps',
    '//test/com/facebook/buck/step:testutil',
    '//test/com/facebook/buck/testutil:testutil',
  ],
)