java_test(
  name = 'zip',
  srcs = glob(['*.java']),
  resources = [
    # The sample bytes are a class file. We use the ".properties" extension so that IJ will copy
    # the file to the output dir when compiling, allowing us to test in the IDE.
    'sample-bytes.properties',
    'macbeth.properties',
  ],
  deps = [
    '//src/com/facebook/buck/io:io',
    '//src/com/facebook/buck/model:model',
    '//src/com/facebook/buck/rules:build_rule',
    '//src/com/facebook/buck/shell:steps',
    '//src/com/facebook/buck/step:step',
    '//src/com/facebook/buck/step/fs:fs',
    '//src/com/facebook/buck/util:exceptions',
    '//src/com/facebook/buck/util/environment:platform',
    '//src/com/facebook/buck/zip:rules',
    '//src/com/facebook/buck/zip:stream',
    '//src/com/facebook/buck/zip:steps',
    '//src/com/facebook/buck/zip:unzip',
    '//test/com/facebook/buck/rules:testutil',
    '//test/com/facebook/buck/step:testutil',
    '//test/com/facebook/buck/testutil/integration:integration',
    '//test/com/facebook/buck/testutil:testutil',
    '//third-party/java/easymock:easymock',
    '//third-party/java/guava:guava',
    '//third-party/java/hamcrest:hamcrest',
    '//third-party/java/junit:junit',
    '//third-party/java/commons-compress:commons-compress',
  ],
)
