load("//tools/build_rules:java_rules.bzl", "java_test")

java_test(
    name = "output-test",
    srcs = glob(["*.java"]),
    deps = [
        "//src/com/facebook/buck/cli/output:output",
        "//third-party/java/junit:junit",
    ],
)
