load("//tools/build_rules:java_rules.bzl", "java_test")

java_test(
    name = "tool",
    srcs = glob(
        ["*.java"],
    ),
    has_immutable_types = True,
    deps = [
        "//src/com/facebook/buck/core/rules:rules",
        "//src/com/facebook/buck/core/rules/actions/lib/args:args",
        "//src/com/facebook/buck/core/rules/tool:tool",
        "//src/com/facebook/buck/core/starlark/rule/args:args",
        "//test/com/facebook/buck/core/model:testutil",
        "//test/com/facebook/buck/core/rules/impl:testutil",
        "//test/com/facebook/buck/core/rules/resolver/impl:testutil",
        "//test/com/facebook/buck/io/filesystem:testutil",
        "//test/com/facebook/buck/io/filesystem/impl:testutil",
        "//test/com/facebook/buck/rules/keys:testutil",
        "//test/com/facebook/buck/testutil:testutil",
        "//third-party/java/guava:guava",
        "//third-party/java/junit:junit",
    ],
)
