load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "common",
    srcs = glob(["*.java"]),
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/core/rulekey:rulekey",
        "//src/com/facebook/buck/core/util/immutables:immutables",
    ],
)
