load("//tools/build_rules:java_rules.bzl", "java_test")

java_test(
    name = "impl",
    srcs = glob(["*Test.java"]),
    deps = [
        "//src/com/facebook/buck/core/model/platform/impl:impl",
        "//src/com/facebook/buck/core/rules/configsetting:configsetting",
        "//src/com/facebook/buck/core/select/impl:impl",
        "//src/com/facebook/buck/parser/syntax:syntax",
        "//src/com/facebook/buck/rules/coercer:coercer",
        "//starlark:bazel",
        "//test/com/facebook/buck/core/cell:testutil",
        "//test/com/facebook/buck/core/model:testutil",
        "//test/com/facebook/buck/core/select:testutil",
        "//third-party/java/junit:junit",
    ],
)
