java_library(
    name = "stream",
    srcs = glob(["*.java"]),
    exported_deps = [
        "//src/com/facebook/buck/util/function:function",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//third-party/java/guava:guava",
    ],
)
