load("//tools/build_rules:java_rules.bzl", "buck_java_library")
buck_java_library(
    name = "stream",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    deps = [
        "//third-party/java/guava:guava",
    ],
    exported_deps = [
        "//src/com/facebook/buck/util/function:function",
    ],
)
