java_library(
    name = "computation",
    srcs = glob(["*.java"]),
    exported_deps = [
        "//src/com/facebook/buck/core/model/targetgraph:targetgraph",
        "//src/com/facebook/buck/core/rules/actions:actions",
        "//src/com/facebook/buck/core/rules/providers:providers",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//third-party/java/guava:guava",
    ],
)
