load("//tools/build_rules:java_rules.bzl", "buck_java_library")
buck_java_library(
    name = "computation",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    deps = [
        "//third-party/java/guava:guava",
    ],
    exported_deps = [
        "//src/com/facebook/buck/core/model/targetgraph:targetgraph",
        "//src/com/facebook/buck/core/model/targetgraph/raw:raw",
        "//src/com/facebook/buck/core/rules/actions:actions",
        "//src/com/facebook/buck/core/rules/providers:providers",
    ],
)
