TYPES_SRCS = [
    "AbstractQuery.java",
]

java_immutables_library(
    name = "types",
    srcs = TYPES_SRCS,
    autodeps = True,
    immutable_types = [
        "Query",
    ],
    visibility = [
        "PUBLIC",
    ],
)

standard_java_library(
    srcs = glob(
        ["*.java"],
        excludes = TYPES_SRCS,
    ),
    tests = [
        "//test/com/facebook/buck/rules/query:query",
    ],
)
