java_test(
    name = "buildables",
    srcs = glob(
        ["*Test.java"],
    ),
    resources = ["//test/com/facebook/buck/step/buildables:external_actions_bin_for_tests"],
    deps = [
        ":testutil",
        "//src-gen:buildable-command-model",
        "//src/com/facebook/buck/downwardapi/processexecutor:processexecutor",
        "//src/com/facebook/buck/external/constants:constants",
        "//src/com/facebook/buck/external/model:model",
        "//src/com/facebook/buck/jvm/java:config",
        "//src/com/facebook/buck/step:step",
        "//src/com/facebook/buck/step/buildables:buildables",
        "//src/com/facebook/buck/step/isolatedsteps:isolatedsteps",
        "//src/com/facebook/buck/util/environment:environment",
        "//test/com/facebook/buck/core/cell:testutil",
        "//test/com/facebook/buck/event:testutil",
        "//test/com/facebook/buck/external/main:testutil",
        "//test/com/facebook/buck/io/filesystem/impl:testutil",
        "//test/com/facebook/buck/testutil:testutil",
        "//test/com/facebook/buck/testutil/integration:util",
        "//third-party/java/guava:guava",
        "//third-party/java/junit:junit",
    ],
)

java_binary(
    name = "external_actions_bin_for_tests",
    visibility = ["//test/..."],
    deps = [
        ":testutil",
        "//src/com/facebook/buck/cli/bootstrapper:bootstrapper_lib",
    ],
)

java_library(
    name = "testutil",
    srcs = glob(
        ["*.java"],
        exclude = [
            "*Test.java",
        ],
    ),
    visibility = ["//test/..."],
    deps = [
        "//src-gen:buildable-command-model",
        "//src/com/facebook/buck/external/model:model",
        "//src/com/facebook/buck/step/isolatedsteps:isolatedsteps",
        "//src/com/facebook/buck/step/isolatedsteps/common:common",
        "//third-party/java/guava:guava",
    ],
)
