standard_java_test(
    name = "i18n",
    deps = [
        "//src/com/facebook/buck/i18n:i18n",
        "//src/com/facebook/buck/util/immutables:immutables",
        "//third-party/java/guava:guava",
        "//third-party/java/hamcrest:java-hamcrest",
        "//third-party/java/immutables:immutables",
        "//third-party/java/jsr:jsr305",
        "//third-party/java/junit:junit",
    ],
)
