load("//tools/build_rules:java_rules.bzl", "java_test")

java_library(
    name = "testutil",
    srcs = glob(
        ["*.java"],
        exclude = [
            "*Test.java",
        ],
    ),
    visibility = [
        "//test/...",
    ],
    deps = [
        "//src/com/facebook/buck/features/python/toolchain/impl:impl",
        "//test/com/facebook/buck/core/model:testutil",
        "//test/com/facebook/buck/core/toolchain/impl:testutil",
        "//test/com/facebook/buck/rules/keys/config:testutil",
        "//test/com/facebook/buck/testutil:testutil",
    ],
)

java_test(
    name = "impl",
    srcs = glob(["*Test.java"]),
    deps = [
        ":testutil",
        "//src/com/facebook/buck/core/rules:rules",
        "//src/com/facebook/buck/core/sourcepath/resolver/impl:impl",
        "//src/com/facebook/buck/features/python/toolchain/impl:impl",
        "//src/com/facebook/buck/io:io",
        "//src/com/facebook/buck/util:exceptions",
        "//src/com/facebook/buck/util/environment:platform",
        "//test/com/facebook/buck/core/config:FakeBuckConfig",
        "//test/com/facebook/buck/core/model:testutil",
        "//test/com/facebook/buck/core/rules/resolver/impl:testutil",
        "//test/com/facebook/buck/core/toolchain/impl:testutil",
        "//test/com/facebook/buck/io:testutil",
        "//test/com/facebook/buck/rules:testutil",
        "//test/com/facebook/buck/rules/keys/config:testutil",
        "//test/com/facebook/buck/testutil:testutil",
        "//test/com/facebook/buck/testutil/integration:util",
        "//test/com/facebook/buck/util:testutil",
        "//third-party/java/guava:guava",
        "//third-party/java/junit:junit",
    ],
)
