load("//tools/build_rules:java_rules.bzl", "buck_java_library")
buck_java_library(
    name = "impl",
    srcs = glob(["*.java"]),
    tests = [
        "//test/com/facebook/buck/core/graph/transformation/executor/impl:impl",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/core/util/log:log",
        "//third-party/java/guava:guava",
    ],
    exported_deps = [
        "//src/com/facebook/buck/core/graph/transformation/executor:executor",
    ],
)
