android_binary(
  name = 'app',
  manifest = 'AndroidManifest.xml',
  target = 'Google Inc.:Google APIs:16',
  keystore = ':debug_keystore',
  deps = [
    '//java/com/sample/lib:lib',
    '//res/com/sample/base:base',
  ],
)

android_binary(
  name = 'app_mdpi',
  manifest = 'AndroidManifest.xml',
  target = 'Google Inc.:Google APIs:16',
  keystore = ':debug_keystore',
  deps = [
    '//java/com/sample/lib:lib',
    '//res/com/sample/base:base',
  ],
  resource_filter = ['mdpi']
)

android_binary(
  name = 'app_hdpi_xhdpi',
  manifest = 'AndroidManifest.xml',
  target = 'Google Inc.:Google APIs:16',
  keystore = ':debug_keystore',
  deps = [
    '//java/com/sample/lib:lib',
    '//res/com/sample/base:base',
  ],
  resource_filter = ['hdpi', 'xhdpi']
)

keystore(
  name = 'debug_keystore',
  store = 'debug.keystore',
  properties = 'debug.keystore.properties',
)

project_config(
  src_target = ':app',
)
