android_binary(
  name = 'app',
  manifest = 'AndroidManifest.xml',
  target = 'Google Inc.:Google APIs:16',
  keystore = '//keystores:debug',
  deps = [
    '//java/com/sample/lib:lib',
    '//res/com/sample/base:base',
  ],
)

android_binary(
  name = 'app_mdpi',
  manifest = 'AndroidManifest.xml',
  target = 'Google Inc.:Google APIs:16',
  keystore = '//keystores:debug',
  deps = [
    '//java/com/sample/lib:lib',
    '//res/com/sample/base:base',
  ],
  resource_filter = ['mdpi']
)

android_binary(
  name = 'app_hdpi_xhdpi',
  manifest = 'AndroidManifest.xml',
  target = 'Google Inc.:Google APIs:16',
  keystore = '//keystores:debug',
  deps = [
    '//java/com/sample/lib:lib',
    '//res/com/sample/base:base',
  ],
  resource_filter = ['hdpi', 'xhdpi']
)

android_binary(
  name = 'app_comp_str',
  manifest = 'AndroidManifest.xml',
  target = 'Google Inc.:Google APIs:16',
  keystore = '//keystores:debug',
  deps = [
    '//java/com/sample/lib:lib',
    '//res/com/sample/base:base',
  ],
  resource_compression = 'enabled_with_strings_as_assets',
)

android_binary(
  name = 'app_comp_str_xhdpi',
  manifest = 'AndroidManifest.xml',
  target = 'Google Inc.:Google APIs:16',
  keystore = '//keystores:debug',
  deps = [
    '//java/com/sample/lib:lib',
    '//res/com/sample/base:base',
  ],
  resource_compression = 'enabled_with_strings_as_assets',
  resource_filter = ['xhdpi']
)

android_binary(
  name = 'app_res_lib_dep',
  manifest = 'AndroidManifest.xml',
  target = 'Google Inc.:Google APIs:16',
  keystore = '//keystores:debug',
  deps = [
      '//res/com/sample/base:base_with_lib_dep',
  ],
)

android_binary(
  name = 'app_with_multiple_rdot_java_packages',
  manifest = 'AndroidManifest.xml',
  target = 'Google Inc.:Google APIs:16',
  keystore = '//keystores:debug',
  deps = [
    '//java/com/sample/lib:lib',
    '//java/com/sample2:lib',
    '//res/com/sample/base:base',
  ],
)

project_config(
  src_target = ':app',
)
