java_test(
  name = 'test',
  srcs = glob(['*Test.java']),
  deps = [
    '//third-party/java/guava:guava',
    '//third-party/java/junit:junit',
    '//src/com/facebook/buck/cli:config',
    '//src/com/facebook/buck/test/result/type:type',
    '//src/com/facebook/buck/test:config',
    '//src/com/facebook/buck/test:test',  
    '//test/com/facebook/buck/cli:FakeBuckConfig',
    '//test/com/facebook/buck/cli:testutil',
    '//test/com/facebook/buck/testutil/integration:integration',
  ],
)
