java_test(
  name = 'test',
  srcs = glob(['*Test.java']),
  deps = [
    '//lib:junit',
    '//src/com/facebook/buck/test:test',  
  ],
  source_under_test = [
    '//src/com/facebook/buck/test:test',  
  ],
)
