java_library(
    name = "testutil",
    srcs = glob(["*.java"]),
    exported_deps = [
        "//src/com/facebook/buck/android/toolchain:toolchain",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/apple/toolchain:toolchain",
        "//src/com/facebook/buck/model:model",
        "//src/com/facebook/buck/toolchain/impl:impl",
    ],
)
