java_library(
  name = 'coverage',
  srcs = ['ReportGenerator.java',],
  deps = [
    '//third-party/java/jacoco:jacoco',
  ],
)

java_binary(
  name = 'report-generator',
  main_class = 'com.facebook.buck.java.ReportGenerator',
  blacklist = [
    '.*SF',
    '.*RSA',
  ],
  deps = [
    ':coverage',
  ],
  visibility = [
    '//programs:bucklib',
  ]
)

java_library(
  name = 'config',
  srcs = [
    'JavaBuckConfig.java',
  ],
  deps = [
    ':support',
    '//third-party/java/guava:guava',
    '//src/com/facebook/buck/cli:config',
    '//src/com/facebook/buck/util:exceptions',
    '//src/com/facebook/buck/util:io',
  ],
  visibility = ['PUBLIC'],
)

java_library(
  name = 'classhash',
  srcs = [
    'HasJavaClassHashes.java',
  ],
  deps = [
    '//third-party/java/guava:guava',
    '//src/com/facebook/buck/model:model',
  ],
  visibility = ['PUBLIC'],
)

java_library(
  name = 'support',
  srcs = [
    'AbiWritingAnnotationProcessingDataDecorator.java',
    'AnnotationProcessingDataDecorator.java',
    'AnnotationProcessingDataDecorators.java',
    'AnnotationProcessingParams.java',
    'HasClasspathEntries.java',
    'HasJavaAbi.java',
    'JavaLibrary.java',
    'JavacVersion.java',
    'JavacOptions.java',
    'JavaCompilerEnvironment.java',
  ],
  deps = [
    ':classhash',
    '//third-party/java/guava:guava',
    '//third-party/java/jsr:jsr305',
    '//src/com/facebook/buck/java/abi:protocol',
    '//src/com/facebook/buck/model:model',
    '//src/com/facebook/buck/rules:build_rule',
    '//src/com/facebook/buck/rules:rules',
    '//src/com/facebook/buck/util:constants',
    '//src/com/facebook/buck/util:exceptions',
    '//src/com/facebook/buck/util:io',
  ],
  visibility = ['PUBLIC'],
)

java_library(
  name = 'packagefinder',
  srcs = [
    'DefaultJavaPackageFinder.java',
    'JavaPackageFinder.java',
    'ResourcesRootPackageFinder.java',
  ],
  deps = [
    '//third-party/java/guava:guava',
    '//src/com/facebook/buck/util:exceptions',
  ],
  visibility = ['PUBLIC'],
)

java_library(
  name = 'rules',
  srcs = [
    'Classpaths.java',
    'DefaultJavaLibrary.java',
    'GwtModule.java',
    'JavaBinary.java',
    'JavaBinaryDescription.java',
    'JavaLibraryDescription.java',
    'JavaLibraryClasspathProvider.java',
    'JavaLibraryRules.java',
    'JavaSourceJar.java',
    'JavaTest.java',
    'JavaTestDescription.java',
    'Keystore.java',
    'KeystoreDescription.java',
    'PrebuiltJar.java',
    'PrebuiltJarDescription.java',
  ],
  deps = [
    ':classhash',
    ':packagefinder',
    ':steps',
    ':support',
    '//third-party/java/guava:guava',
    '//third-party/java/jsr:jsr305',
    '//src/com/facebook/buck/android:packageable',
    '//src/com/facebook/buck/event:event',
    '//src/com/facebook/buck/graph:graph',
    '//src/com/facebook/buck/java/abi:protocol',
    '//src/com/facebook/buck/log:log',
    '//src/com/facebook/buck/model:model',
    '//src/com/facebook/buck/parser:rule_pattern',
    '//src/com/facebook/buck/rules:build_rule',
    '//src/com/facebook/buck/rules:rules',
    '//src/com/facebook/buck/test:test',
    '//src/com/facebook/buck/shell:steps',
    '//src/com/facebook/buck/step:step',
    '//src/com/facebook/buck/step/fs:fs',
    '//src/com/facebook/buck/test/selectors:selectors',
    '//src/com/facebook/buck/util:constants',
    '//src/com/facebook/buck/util:exceptions',
    '//src/com/facebook/buck/util:io',
    '//src/com/facebook/buck/util:util',
    '//src/com/facebook/buck/zip:steps',
    '//src/com/facebook/buck/test/result/type:type',
    '//third-party/java/infer-annotations:infer-annotations',
  ],
  visibility = ['PUBLIC'],
)

java_library(
  name = 'steps',
  srcs = [
    'AccumulateClassNamesStep.java',
    'CalculateAbiStep.java',
    'CopyResourcesStep.java',
    'ExternalJavacStep.java',
    'GenerateCodeCoverageReportStep.java',
    'JarDirectoryStep.java',
    'JarDirectoryStepHelper.java',
    'JavacErrorParser.java',
    'JavacInMemoryStep.java',
    'JavacStep.java',
    'JavacStepUtil.java',
    'JUnitStep.java',
    'NullJavacStep.java',
    'TestType.java',
    'ZipEntryJavaFileObject.java',
  ],
  deps = [
    ':packagefinder',
    ':report-generator',
    ':support',
    '//third-party/java/guava:guava',
    '//third-party/java/jsr:jsr305',
    '//src/com/facebook/buck/dalvik:dalvik_stats_tool',
    '//src/com/facebook/buck/java/abi:protocol',
    '//src/com/facebook/buck/java/abi2:abi2',
    '//src/com/facebook/buck/java/classes:classes',
    '//src/com/facebook/buck/event:event',
    '//src/com/facebook/buck/log:log',
    '//src/com/facebook/buck/model:model',
    '//src/com/facebook/buck/rules:build_rule',
    '//src/com/facebook/buck/rules:rules',
    '//src/com/facebook/buck/shell:steps',
    '//src/com/facebook/buck/step:step',
    '//src/com/facebook/buck/step/fs:fs',
    '//src/com/facebook/buck/test:report-format',
    '//src/com/facebook/buck/test/selectors:selectors',
    '//src/com/facebook/buck/util:constants',
    '//src/com/facebook/buck/util:exceptions',
    '//src/com/facebook/buck/util:io',
    '//src/com/facebook/buck/util:util',
    '//src/com/facebook/buck/zip:stream',
    '//src/com/facebook/buck/zip:unzip',
  ],
  visibility = ['PUBLIC'],
)

java_library(
  name = 'autodeps',
  srcs = [
    'SrcRootsFinder.java',
    'JavaFileParser.java',
    'JavaSymbolFinder.java',
  ],
  deps = [
    ':packagefinder',
    ':rules',
    ':support',
    '//third-party/java/guava:guava',
    '//third-party/java/eclipse:eclipse_jdt',
    '//src/com/facebook/buck/android:rules',
    '//src/com/facebook/buck/cli:config',
    '//src/com/facebook/buck/event:event',
    '//src/com/facebook/buck/json:json',
    '//src/com/facebook/buck/model:model',
    '//src/com/facebook/buck/rules:build_rule',
    '//src/com/facebook/buck/util:constants',
    '//src/com/facebook/buck/util:io',
  ],
  visibility = [
    '//src/com/facebook/buck/cli:cli',
    '//test/com/facebook/buck/java:java',
  ],
)
