java_library(
    name = "api",
    srcs = glob(["*.java"]),
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/jvm/java/lang/model:model",
        "//src/com/facebook/buck/util/liteinfersupport:liteinfersupport",

        # Don't add deps that aren't already in the plugin; this is a super-light library that can be
        # used outside of Buck
    ],
)
