java_immutables_library(
  name = 'listener',
  srcs = glob(['*.java']),
  tests = [
    '//test/com/facebook/buck/event/listener/integration:integration',
    '//test/com/facebook/buck/event/listener:listener',
  ],
  autodeps = True,
  visibility = [
    'PUBLIC',
  ],
)
