CACHE_RATE_STATS_SRCS = [ 'CacheRateStatsKeeper.java' ]
java_library(
  name = 'CacheRateStatsKeeper',
  srcs = CACHE_RATE_STATS_SRCS,
  autodeps = True,
  visibility = [
    'PUBLIC',
  ],
)

BROADCAST_EVENT_LISTENER_SCRS = ['BroadcastEventListener.java']
java_library(
    name = 'BroadcastEventListener',
    srcs = BROADCAST_EVENT_LISTENER_SCRS,
    autodeps = True,
    visibility = [
      'PUBLIC',
    ],
)

java_immutables_library(
  name = 'listener',
  srcs = glob(['*.java'], excludes=CACHE_RATE_STATS_SRCS + BROADCAST_EVENT_LISTENER_SCRS),
  immutable_types = [
    'EventPair',
    'ProxyBuckEvent',
  ],
  tests = [
    '//test/com/facebook/buck/event/listener/integration:integration',
    '//test/com/facebook/buck/event/listener:listener',
  ],
  autodeps = False,
  deps = [
      ':CacheRateStatsKeeper',
      "//src-gen:thrift",
      "//src/com/facebook/buck/android:steps",
      "//src/com/facebook/buck/artifact_cache:artifact_cache",
      "//src/com/facebook/buck/cli:events",
      "//src/com/facebook/buck/i18n:i18n",
      "//src/com/facebook/buck/json:json",
      "//src/com/facebook/buck/jvm/java:support",
      "//src/com/facebook/buck/jvm/java/tracing:tracing",
      "//src/com/facebook/buck/log:api",
      "//src/com/facebook/buck/log:log",
      "//src/com/facebook/buck/parser:parser",
      "//src/com/facebook/buck/rules:build_rule",
      "//src/com/facebook/buck/step:step",
      "//src/com/facebook/buck/util:constants",
      "//src/com/facebook/buck/util:exceptions",
      "//src/com/facebook/buck/util:tristate",
      "//src/com/facebook/buck/util:util",
      "//src/com/facebook/buck/util/concurrent:concurrent",
      "//src/com/facebook/buck/util/environment:platform",
      "//third-party/java/immutables:processor",
      "//third-party/java/jackson:jackson-core",
  ],
  exported_deps = [
      "//src/com/facebook/buck/cli:config",
      "//src/com/facebook/buck/counters:counters",
      "//src/com/facebook/buck/distributed:distributed",
      "//src/com/facebook/buck/event:event",
      "//src/com/facebook/buck/event/external:external_lib",
      "//src/com/facebook/buck/httpserver:httpserver",
      "//src/com/facebook/buck/io:io",
      "//src/com/facebook/buck/model:build_id",
      "//src/com/facebook/buck/model:model",
      "//src/com/facebook/buck/rules:rules",
      "//src/com/facebook/buck/slb:slb",
      "//src/com/facebook/buck/test:config",
      "//src/com/facebook/buck/test:test",
      "//src/com/facebook/buck/test/result/type:type",
      "//src/com/facebook/buck/test/selectors:selectors",
      "//src/com/facebook/buck/timing:timing",
      "//src/com/facebook/buck/util:io",
      "//src/com/facebook/buck/util/environment:environment",
      "//src/com/facebook/buck/util/immutables:immutables",
      "//src/com/facebook/buck/util/network:network",
      "//src/com/facebook/buck/util/network/hostname:hostname",
      "//src/com/facebook/buck/util/unit:unit",
      "//src/com/facebook/buck/util/versioncontrol:versioncontrol",
      "//third-party/java/guava:guava",
      "//third-party/java/jackson:jackson-databind",
      "//third-party/java/jsr:jsr305",
   ],
  visibility = [
    'PUBLIC',
  ],
)
