#!/bin/bash

# Copyright 2016-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

DIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
if ! test -d "$DIR"; then
  echo Cannot locate directory containing GHCi iserv script; exit 1
fi

LD_PRELOAD=<preload_libs> PATH=<binutils_path>:"$PATH" <ghci_iserv_path> "$@"
