load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "resources",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/command/config:config",
        "//src/com/facebook/buck/core/config:config",
    ],
    exported_deps = [
        "//src/com/facebook/buck/util/concurrent:concurrent",
    ],
)
