EMPTY_CONFIGS = {
  'Debug': {},
  'Release': {},
}

apple_library(
  name = 'Dep1',
  configs = EMPTY_CONFIGS,
  srcs = [],
  frameworks = [],
  deps = [],
  tests = [':Dep1Tests'],
  visibility = ['PUBLIC'],
)

apple_test(
  name = 'Dep1Tests',
  extension = 'octest',
  configs = EMPTY_CONFIGS,
  srcs = [],
  frameworks = [],
  deps = [
    ':Dep1',
  ],
)

xcode_project_config(
  name = 'project',
  project_name = 'Libraries',
  rules = [
    ':Dep1',
    ':Dep1Tests',
  ],
)
