apple_library(
  name = 'TestLibrary',
  srcs = ['lib.m'],
  exported_headers = ['lib.h'],
  frameworks = [
  	'$SDKROOT/System/Library/Frameworks/CoreFoundation.framework',
  	'$SDKROOT/System/Library/Frameworks/Foundation.framework',
    '$PLATFORM_DIR/Developer/Library/Frameworks/XCTest.framework',
  ],
  visibility = ['//Apps/...'],
)
