load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "config",
    srcs = glob(
        ["*.java"],
    ),
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/core/config:config",
        "//src/com/facebook/buck/core/exceptions:exceptions",
        "//src/com/facebook/buck/core/util/log:log",
    ],
)
