# Make these certs available for running tests elsewhere in repo
filegroup(
    name = "kotlinc",
    srcs = [
        "libexec/build.txt",
        "libexec/lib/jvm-abi-gen.jar",
        "libexec/lib/kotlin-annotation-processing.jar",
        "libexec/lib/kotlin-compiler.jar",
        "libexec/lib/kotlin-reflect.jar",
        "libexec/lib/kotlin-script-runtime.jar",
        "libexec/lib/kotlin-stdlib.jar",
    ],
)

prebuilt_jar(
    name = "annotation-processing",
    binary_jar = "libexec/lib/kotlin-annotation-processing.jar",
    visibility = [
        "//test/com/facebook/buck/...",
    ],
)

prebuilt_jar(
    name = "compiler",
    binary_jar = "libexec/lib/kotlin-compiler.jar",
    visibility = [
        "//test/com/facebook/buck/...",
    ],
)

prebuilt_jar(
    name = "jvm-abi-gen",
    binary_jar = "libexec/lib/jvm-abi-gen.jar",
    visibility = [
        "//test/com/facebook/buck/...",
    ],
)

prebuilt_jar(
    name = "reflect",
    binary_jar = "libexec/lib/kotlin-reflect.jar",
    visibility = [
        "//test/com/facebook/buck/...",
    ],
)

prebuilt_jar(
    name = "script-runtime",
    binary_jar = "libexec/lib/kotlin-script-runtime.jar",
    visibility = [
        "//test/com/facebook/buck/...",
    ],
)

prebuilt_jar(
    name = "stdlib",
    binary_jar = "libexec/lib/kotlin-stdlib.jar",
    visibility = [
        "//test/com/facebook/buck/...",
    ],
)
