java_test(
  name = 'xcspec',
  srcs = glob(['*.java']),
  resources = glob(['testdata/**']),
  deps = [
    '//src/com/facebook/buck/apple/xcode/xcspec:xcspec',
    '//test/com/facebook/buck/testutil/integration:integration',
    '//third-party/java/guava:guava',
    '//third-party/java/junit:junit',
  ]
)
