load("//tools/build_rules:java_rules.bzl", "standard_java_test")

standard_java_test(
    name = "param",
    deps = [
        "//src/com/facebook/buck/rules/param:param",
        "//third-party/java/junit:junit",
    ],
)
