python_binary(
  name = 'diff_rulekeys',
  main_module = 'diff_rulekeys',
  deps = [
    ':diff_rulekeys_lib',
  ],
)

python_library(
  name = 'diff_rulekeys_lib',
  base_module = '',
  srcs = [
    'diff_rulekeys.py',
  ],
  deps = [
    '//third-party/py/argparse:argparse',
  ],
  visibility = [
    '//scripts/...',
  ],
)

python_test(
  name = 'diff_rulekeys_test',
  srcs = [
    'diff_rulekeys_test.py',
  ],
  deps = [
    ':diff_rulekeys_lib',
  ]
)
