#!/bin/bash
set -x

git stash save -u

function finish {
  git stash pop
}

trap finish EXIT

REPO_ROOT_DIR="$(git rev-parse --show-toplevel)"

FORMAT_JAR_VERSION="1.6"
FORMAT_JAR_NAME="google-java-format-${FORMAT_JAR_VERSION}-all-deps.jar"
FORMAT_JAR_URL="https://github.com/google/google-java-format/releases/download/google-java-format-${FORMAT_JAR_VERSION}/${FORMAT_JAR_NAME}"
FORMAT_JAR_LOCATION="${HOME}/${FORMAT_JAR_NAME}"

wget -O "${FORMAT_JAR_LOCATION}" "${FORMAT_JAR_URL}"

for file_in_revision in $(git diff --name-only --diff-filter=AM HEAD..${TRAVIS_BRANCH}); do
  echo "Checking ${file_in_revision}"

  [ -f "${file_in_revision}" ] || continue

  "${REPO_ROOT_DIR}/scripts/check-java-file-format" "${FORMAT_JAR_LOCATION}" "${file_in_revision}"
done

if [ "$(git status --porcelain)" ]; then
  echo "Some files are not formatted properly."
  git diff
  git checkout -- .
  exit 1
fi
