load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "toolchain",
    srcs = glob(["*.java"]),
    exported_deps = [
        "//src/com/facebook/buck/model:model",
        "//src/com/facebook/buck/rules:build_rule",
        "//src/com/facebook/buck/toolchain:toolchain",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/rules:source_path",
    ],
)
