load("//tools/build_rules:java_rules.bzl", "standard_java_test")

standard_java_test(
    name = "impl",
    deps = [
        "//src/com/facebook/buck/core/rulekey:rulekey",
        "//src/com/facebook/buck/core/rules:rules",
        "//src/com/facebook/buck/core/sourcepath:sourcepath",
        "//src/com/facebook/buck/core/sourcepath/resolver/impl:impl",
        "//src/com/facebook/buck/core/toolchain/tool/impl:impl",
        "//src/com/facebook/buck/rules/args:args",
        "//src/com/facebook/buck/rules/keys:keys",
        "//src/com/facebook/buck/shell:rules",
        "//src/com/facebook/buck/util/cache:cache",
        "//test/com/facebook/buck/core/model/targetgraph:testutil",
        "//test/com/facebook/buck/core/rules/resolver/impl:testutil",
        "//test/com/facebook/buck/model:testutil",
        "//test/com/facebook/buck/rules:testutil",
        "//test/com/facebook/buck/rules/keys:testutil",
        "//test/com/facebook/buck/shell:testutil",
        "//test/com/facebook/buck/testutil:testutil",
        "//third-party/java/guava:guava",
        "//third-party/java/junit:junit",
    ],
)
