android_binary(
  name = 'app',
  manifest = 'AndroidManifest.xml',
  keystore = '//keystores:debug',
  deps = [
    '//java/com/sample/lib:lib',
    '//js:app#dev',
    '//res/com/sample/base:base',
  ],
)
