load("//tools/build_rules:java_rules.bzl", "standard_java_test")

standard_java_test(
    name = "factory",
    deps = [
        "//src/com/facebook/buck/core/model/tc/factory:factory",
        "//test/com/facebook/buck/core/cell:testutil",
        "//test/com/facebook/buck/io/filesystem/impl:testutil",
        "//third-party/java/junit:junit",
    ],
)
