load("//tools/build_rules:java_rules.bzl", "buck_java_library")
buck_java_library(
    name = "param",
    srcs = glob(["*.java"]),
    required_for_source_only_abi = True,
    visibility = [
        "//src/com/facebook/buck/...",
        "//test/com/facebook/buck/...",
    ],
    deps = [
        "//third-party/java/guava:guava",
        "//third-party/java/jackson:jackson-annotations",
    ],
)
