load("//tools/build_rules:java_rules.bzl", "standard_java_test")

standard_java_test(
    name = "file",
    deps = [
        "//src/com/facebook/buck/io:io",
        "//src/com/facebook/buck/io/file:file",
        "//src/com/facebook/buck/io/filesystem:filesystem",
        "//src/com/facebook/buck/util:util",
        "//src/com/facebook/buck/util/environment:platform",
        "//test/com/facebook/buck/io/filesystem:testutil",
        "//test/com/facebook/buck/testutil:testutil",
        "//test/com/facebook/buck/testutil/integration:util",
        "//test/com/facebook/buck/util:testutil",
        "//third-party/java/guava:guava",
        "//third-party/java/jimfs:jimfs",
        "//third-party/java/junit:junit",
    ],
)

java_library(
    name = "testutil",
    srcs = glob(
        ["*.java"],
        exclude = [
            "*Test.java",
        ],
    ),
    visibility = ["//test/..."],
    deps = [
        "//third-party/java/guava:guava",
    ],
)
