java_library(
    name = "filesystem_lib",
    srcs = glob(["*.java"]),
    visibility = [
        # `BuckUnixPath` needs to be visible in `MorePaths.dropInternalCaches`
        "//src/com/facebook/buck/io/file:file",
        "//src/com/facebook/buck/cli/bootstrapper/...",
        "//test/...",
    ],
)
