load("//tools/build_rules:java_rules.bzl", "standard_java_test")

standard_java_test(
    name = "rule",
    deps = [
        "//src/com/facebook/buck/core/test/rule:rule",
        "//src/com/facebook/buck/util/json:json",
        "//test/com/facebook/buck/model:testutil",
        "//third-party/java/guava:guava",
        "//third-party/java/hamcrest:hamcrest-junit",
        "//third-party/java/junit:junit",
    ],
)
