load("//tools/build_rules:java_rules.bzl", "java_library_with_plugins")

java_library_with_plugins(
    name = "test_module",
    srcs = glob(["*.java"]),
    provided_deps = [
        "//src/com/facebook/buck/module:module",
        "//test/com/facebook/buck/module/impl:test_extension",
    ],
    visibility = ["PUBLIC"],
)

# Module is a jar with a hash, in this case we have only a jar without a file with hash
java_binary(
    name = "test_module-module",
    visibility = ["PUBLIC"],
    deps = [
        ":test_module",
    ],
)
