load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "files",
    srcs = glob(["*.java"]),
    tests = ["//test/com/facebook/buck/core/files:files"],
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/core/graph/transformation:transformation",
        "//src/com/facebook/buck/core/util/log:log",
        "//src/com/facebook/buck/io/file:file",
        "//src/com/facebook/buck/io/filesystem:filesystem",
        "//src/com/facebook/buck/io/watchman:watchman",
        "//src/com/facebook/buck/util:util",
        "//third-party/java/guava:guava",
    ],
)
