load("//tools/build_rules:export_files.bzl", "export_files")

export_files(
    [
        "expected_dummy_function.soy",
        "expected_dummy_toc.soy",
        "expected_dummy_function_with_kwargs.soy",
        "expected_dummy_function_without_args.soy",
        "expected_dummy_function_with_braces_inside.soy",
    ],
    visibility = ["//tools/documentation_generator/test/..."],
)
