load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "computation",
    srcs = glob(["*.java"]),
    exported_deps = [
        "//src/com/facebook/buck/config:config",
        "//src/com/facebook/buck/core/cell:cell",
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/core/model/actiongraph:actiongraph",
        "//src/com/facebook/buck/core/rulekey:rulekey",
        "//src/com/facebook/buck/core/rules/resolver/impl:impl",
        "//src/com/facebook/buck/event:interfaces",
        "//src/com/facebook/buck/log/thrift:thrift",
        "//src/com/facebook/buck/rules:rules",
        "//src/com/facebook/buck/rules/keys/config:config",
    ],
    tests = [
        "//test/com/facebook/buck/core/model/actiongraph/computation:computation",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/core/rules/transformer/impl:impl",
        "//src/com/facebook/buck/core/sourcepath/resolver/impl:impl",
        "//src/com/facebook/buck/event:event",
        "//src/com/facebook/buck/graph:graph",
        "//src/com/facebook/buck/log:api",
        "//src/com/facebook/buck/rules:cli",
        "//src/com/facebook/buck/rules/keys:keys",
        "//src/com/facebook/buck/util:util",
        "//src/com/facebook/buck/util/timing:timing",
    ],
)
