load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "computation",
    srcs = glob(["*.java"]),
    tests = [
        "//test/com/facebook/buck/core/model/actiongraph/computation:computation",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/core/model/platform/impl:impl",
        "//src/com/facebook/buck/core/rules/analysis/cache:cache",
        "//src/com/facebook/buck/core/rules/analysis/impl:impl",
        "//src/com/facebook/buck/core/rules/config/registry/impl:impl",
        "//src/com/facebook/buck/core/rules/transformer/impl:impl",
        "//src/com/facebook/buck/core/sourcepath/resolver/impl:impl",
        "//src/com/facebook/buck/core/util/graph:graph",
        "//src/com/facebook/buck/core/util/log:log",
        "//src/com/facebook/buck/event:event",
        "//src/com/facebook/buck/rules/keys:keys",
        "//src/com/facebook/buck/util:util",
        "//src/com/facebook/buck/util/timing:timing",
    ],
    exported_deps = [
        "//src/com/facebook/buck/core/cell:cell",
        "//src/com/facebook/buck/core/config:config",
        "//src/com/facebook/buck/core/graph/transformation/executor:executor",
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/core/model/actiongraph:actiongraph",
        "//src/com/facebook/buck/core/rulekey:rulekey",
        "//src/com/facebook/buck/core/rules:rules",
        "//src/com/facebook/buck/core/rules/analysis:analysis",
        "//src/com/facebook/buck/core/rules/analysis/config:config",
        "//src/com/facebook/buck/core/rules/resolver/impl:impl",
        "//src/com/facebook/buck/event:interfaces",
        "//src/com/facebook/buck/log/thrift:thrift",
        "//src/com/facebook/buck/rules/keys/config:config",
    ],
)
