load("//tools/build_rules:java_rules.bzl", "java_test")

java_test(
    name = "linkgroup",
    srcs = glob(["*Test.java"]),
    deps = [
        "//src/com/facebook/buck/core/linkgroup:linkgroup",
        "//src/com/facebook/buck/core/model/targetgraph:targetgraph",
        "//src/com/facebook/buck/core/parser/buildtargetparser:buildtargetparser",
        "//src/com/facebook/buck/core/parser/buildtargetpattern:buildtargetpattern",
        "//test/com/facebook/buck/core/cell:testutil",
        "//test/com/facebook/buck/core/model:testutil",
        "//test/com/facebook/buck/core/model/targetgraph:testutil",
        "//test/com/facebook/buck/cxx:testutil",
        "//test/com/facebook/buck/io/filesystem/impl:testutil",
        "//third-party/java/junit:junit",
    ],
)
