load("//tools/build_rules:java_rules.bzl", "java_test")

java_test(
    name = "lib",
    srcs = glob(
        ["*.java"],
    ),
    has_immutable_types = True,
    deps = [
        "//src/com/facebook/buck/core/rules/providers/lib:lib",
        "//third-party/java/guava:guava",
        "//third-party/java/junit:junit",
    ],
)
