load("//tools/build_rules:java_rules.bzl", "java_test")

java_test(
    name = "lib",
    srcs = glob(
        ["*.java"],
    ),
    has_immutable_types = True,
    deps = [
        "//src/com/facebook/buck/core/model/impl:impl",
        "//src/com/facebook/buck/core/rules/actions/lib:lib",
        "//src/com/facebook/buck/core/rules/actions/lib/args:args",
        "//src/com/facebook/buck/core/rules/providers/lib:lib",
        "//src/com/facebook/buck/core/starlark/rule/args:args",
        "//test/com/facebook/buck/core/model:testutil",
        "//test/com/facebook/buck/core/rules/actions:testutil",
        "//test/com/facebook/buck/core/starlark/compatible:testutil",
        "//test/com/facebook/buck/io/filesystem/impl:testutil",
        "//third-party/java/guava:guava",
        "//third-party/java/junit:junit",
    ],
)
