java_library(
  name = 'step',
  srcs = glob(['*.java']),
  deps = [
    '//lib:guava',
    '//src/com/facebook/buck/android:exceptions',
    '//src/com/facebook/buck/debug:debug',
    '//src/com/facebook/buck/util:exceptions',
    '//src/com/facebook/buck/util:io',
    '//src/com/facebook/buck/util:util',
  ],
  visibility = [ 'PUBLIC' ],
)
