load(
    "//tools/build_rules:java_rules.bzl",
    "java_immutables_library",
)

TEST_STEP_SRCS = ["AbstractTestStep.java"]

java_immutables_library(
    name = "test_step",
    srcs = TEST_STEP_SRCS,
    visibility = ["PUBLIC"],
    deps = [
        ":step",
        "//src/com/facebook/buck/downwardapi/processexecutor:processexecutor",
    ],
    exported_deps = [
        "//src/com/facebook/buck/core/build/execution/context:context",
    ],
)

java_immutables_library(
    name = "step",
    srcs = glob(
        ["*.java"],
        exclude = TEST_STEP_SRCS,
    ),
    tests = [
        "//test/com/facebook/buck/step:step",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//src-gen:remoteexecution-protobuf",
        "//src/com/facebook/buck/core/cell:cell",
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/core/model/impl:impl",
        "//src/com/facebook/buck/core/toolchain:toolchain",
        "//src/com/facebook/buck/core/util/log:log",
        "//src/com/facebook/buck/event:interfaces",
        "//src/com/facebook/buck/event/external:external_lib",
        "//src/com/facebook/buck/util:process_executor",
        "//src/com/facebook/buck/util:util",
        "//src/com/facebook/buck/util/json:json",
        "//src/com/facebook/buck/util/string:string",
        "//third-party/java/jackson:jackson-annotations",
        "//third-party/java/remote-apis:remote-apis",
    ],
    exported_deps = [
        "//src/com/facebook/buck/android/device:device",
        "//src/com/facebook/buck/core/build/execution/context:context",
    ],
)
