java_test(
  name = 'cpp',
  srcs = glob(['*.java']),
  deps = [
    '//lib:guava',
    '//lib:junit',
    '//src/com/facebook/buck/cpp:rules',
    '//src/com/facebook/buck/model:model',
    '//src/com/facebook/buck/rules:rules',
    '//src/com/facebook/buck/util:io',
    '//src/com/facebook/buck/util:util',
    '//test/com/facebook/buck/model:BuildTargetFactory',
    '//test/com/facebook/buck/testutil:testutil',
  ],
  source_under_test = [
    '//src/com/facebook/buck/cpp:rules',
  ],
)
