load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "lib",
    srcs = glob(["*.java"]),
    tests = [
        "//test/com/facebook/buck/core/rules/actions/lib:lib",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//third-party/java/guava:guava",
    ],
    exported_deps = [
        "//src/com/facebook/buck/core/rules/actions:actions",
        "//src/com/facebook/buck/core/rules/actions/lib/args:args",
    ],
)
