java_library(
    name = "build_type",
    srcs = [
        "BuildType.java",
    ],
    autodeps = True,
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/log:api",
        "//third-party/java/guava:guava",
    ],
)
