java_library(
    name = "build_type",
    srcs = [
        "BuildType.java",
    ],
    autodeps = True,
    exported_deps = ["//third-party/java/guava:guava"],
    visibility = [
        "PUBLIC",
    ],
    deps = ["//src/com/facebook/buck/log:api"],
)
