load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "impl",
    srcs = glob(["*.java"]),
    tests = [
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/command/config:config",
        "//src/com/facebook/buck/core/toolchain/impl:impl",
        "//src/com/facebook/buck/core/util/log:log",
        "//src/com/facebook/buck/io/file:file",
        "//src/com/facebook/buck/rules/keys/config/impl:impl",
        "//src/com/facebook/buck/util:util",
        "//src/com/facebook/buck/util/stream:stream",
    ],
    exported_deps = [
        "//src/com/facebook/buck/core/cell:cell",
        "//src/com/facebook/buck/core/parser/buildtargetparser:buildtargetparser",
    ],
)
