java_library(
    name = "model",
    srcs = glob(["*.java"]),
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/jvm/java/version:version",
        "//src/com/facebook/buck/util/liteinfersupport:liteinfersupport",

        # Don't add deps that aren't already in the bootstrapper; any dependencies
        # here will pollute the compiler and annotation processor class loaders
    ],
)
