load("//tools/build_rules:java_rules.bzl", "buck_java_library")

buck_java_library(
    name = "model",
    srcs = glob(["*.java"]),
    extra_arguments = [
        "--add-exports",
        "jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/jvm/java/version/utils:utils",
        "//src/com/facebook/buck/util/liteinfersupport:liteinfersupport",

        # Don't add deps that aren't already in the bootstrapper; any dependencies
        # here will pollute the compiler and annotation processor class loaders
    ],
)
