java_test(
  name = 'simple',
  srcs = [
    'SimpleTest.java',
  ],
  deps = [
    ':junit',
  ],
)

prebuilt_jar(
  name = 'junit',
  binary_jar = 'junit-4.11.jar',
  deps = [
    ':hamcrest-core',
    ':hamcrest-library',
  ],
)

prebuilt_jar(
  name = 'hamcrest-core',
  binary_jar = 'hamcrest-core-1.3.jar',
)

prebuilt_jar(
  name = 'hamcrest-library',
  binary_jar = 'hamcrest-library-1.3.jar',
)
