load("//tools/build_rules:java_rules.bzl", "java_immutables_library", "standard_java_test")

java_immutables_library(
    name = "testutil",
    srcs = [
        "FilegroupBuilder.java",
    ],
    visibility = [
        "//test/...",
    ],
    deps = [
        "//src/com/facebook/buck/core/rules:rules",
        "//src/com/facebook/buck/core/sourcepath:sourcepath",
        "//src/com/facebook/buck/features/filegroup:filegroup",
        "//src/com/facebook/buck/rules/modern:modern",
        "//test/com/facebook/buck/core/model/targetgraph:testutil",
    ],
)

standard_java_test(
    name = "filegroup",
    with_test_data = True,
    deps = [
        "//src/com/facebook/buck/features/filebundler:filebundler",
        "//src/com/facebook/buck/features/filegroup:filegroup",
        "//test/com/facebook/buck/testutil:testutil",
        "//test/com/facebook/buck/testutil/integration:util",
        "//third-party/java/junit:junit",
    ],
)
