java_test(
  name = 'integration',
  srcs = glob(['*.java']),
  source_under_test = [
    '//src/com/facebook/buck/event/listener:listener',
  ],
  deps = [
    '//third-party/java/hamcrest:hamcrest-core',
    '//third-party/java/hamcrest:hamcrest-library',
    '//third-party/java/junit:junit',
    '//src/com/facebook/buck/event/listener:listener',
    '//test/com/facebook/buck/testutil/integration:integration',
  ],
)
