load("//tools/build_rules:java_rules.bzl", "standard_java_test")

standard_java_test(
    name = "scuba",
    deps = [
        "//src/com/facebook/buck/event/listener/scuba:scuba",
        "//third-party/java/junit:junit",
    ],
)
