load("//tools/build_rules:java_rules.bzl", "standard_java_test")

standard_java_test(
    name = "scuba",
    deps = [
        "//src/com/facebook/buck/artifact_cache:artifact_cache",
        "//src/com/facebook/buck/event:event",
        "//src/com/facebook/buck/event:interfaces",
        "//src/com/facebook/buck/event/listener/scuba:scuba",
        "//third-party/java/guava:guava",
        "//third-party/java/junit:junit",
    ],
)
