load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "transformer",
    srcs = [
        "TargetNodeToBuildRuleTransformer.java",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/core/rules/providers/collect/impl:impl",
        "//third-party/java/guava:guava",
    ],
    exported_deps = [
        "//src/com/facebook/buck/core/cell:cell",
        "//src/com/facebook/buck/core/model/targetgraph:targetgraph",
        "//src/com/facebook/buck/core/model/targetgraph/raw:raw",
        "//src/com/facebook/buck/core/rules:rules",
    ],
)
