load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "transformer",
    srcs = [
        "TargetNodeToBuildRuleTransformer.java",
    ],
    exported_deps = [
        "//src/com/facebook/buck/core/cell:cell",
        "//src/com/facebook/buck/rules:build_rule",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//third-party/java/guava:guava",
    ],
)
