standard_java_library(
    name = "perf",
    exported_deps = [
        "//src/com/facebook/buck/event:interfaces",
        "//src/com/facebook/buck/log:log",
        "//src/com/facebook/buck/util:process_executor",
        "//third-party/java/guava:guava",
        "//third-party/java/jsr:jsr305",
    ],
    deps = ["//src/com/facebook/buck/log:api"],
)
