java_library(
    name = "perf",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/core/util/log:log",
        "//src/com/facebook/buck/event:interfaces",
        "//src/com/facebook/buck/event/external:external_lib",
        "//src/com/facebook/buck/log:log",
        "//src/com/facebook/buck/util:process_executor",
        "//third-party/java/guava:guava",
        "//third-party/java/jsr:jsr305",
    ],
)
