standard_java_library(
    name = "offline",
    immutable_types = [
        "ScribeData",
    ],
    deps = [
        "//src/com/facebook/buck/counters:counters",
        "//src/com/facebook/buck/event:interfaces",
        "//src/com/facebook/buck/io:BuckPaths",
        "//src/com/facebook/buck/io:io",
        "//src/com/facebook/buck/log:api",
        "//src/com/facebook/buck/model:build_id",
        "//src/com/facebook/buck/util:object_mapper",
        "//src/com/facebook/buck/util/network:network",
        "//third-party/java/jackson:jackson-annotations",
        "//third-party/java/jackson:jackson-databind",
    ],
)
