java_library(
    name = "common",
    srcs = glob(["*.java"]),
    visibility = [
        "//src/com/facebook/buck/android:",
        "//src/com/facebook/buck/android/toolchain/...",
    ],
    exported_deps = [
        "//src/com/facebook/buck/util/types:types",
        "//third-party/java/guava:guava",
    ],
)
