load("//tools/build_rules:java_rules.bzl", "buck_java_library")

buck_java_library(
    name = "common",
    srcs = glob(["*.java"]),
    visibility = [
        "//src/com/facebook/buck/android:",
        "//src/com/facebook/buck/android/toolchain/...",
        "//test/com/facebook/buck/android:",
        "//test/com/facebook/buck/android/toolchain/...",
    ],
    exported_deps = [
        "//src/com/facebook/buck/util/types:types",
        "//third-party/java/guava:guava",
    ],
)
