android_library(
    name = "exopackage",
    srcs = glob(["*.java"]),
    provided_deps = [
        "//android/androidx/fragment/app:fragment_stub",
    ],
    source = "7",
    target = "7",
    visibility = [
        "//android/com/facebook/buck/android/support/...",
    ],
)
