kotlin_library(
    name = "importer",
    srcs = glob(["*.kt"]),
    visibility = [
        "//test/com/facebook/buck/multitenant/...",
    ],
    deps = [
        ":RuleTypeFactory",
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/core/model/targetgraph/raw:raw",
        "//src/com/facebook/buck/multitenant/fs:fs",
        "//src/com/facebook/buck/multitenant/service:service",
        "//src/com/facebook/buck/rules/visibility:visibility",
        "//src/com/facebook/buck/util/json:json",
        "//third-party/java/guava:guava",
        "//third-party/java/jackson:jackson-core",
        "//third-party/java/jackson:jackson-databind",
    ],
)

# This rule is only visible within this package by design. See Javadoc.
java_library(
    name = "RuleTypeFactory",
    srcs = [
        "RuleTypeFactory.java",
    ],
    visibility = [
        "//test/com/facebook/buck/multitenant/...",
    ],
    deps = [
        "//src/com/facebook/buck/core/model:model",
    ],
)
