java_immutables_library(
  name = 'timing',
  srcs = glob(['*.java']),
  immutable_types = [
    'AbsolutePerfTime',
    'RelativePerfTime',
  ],
  autodeps = True,
  visibility = [
    'PUBLIC',
  ],
)
