standard_java_library(
    name = "timing",
    exported_deps = ["//src/com/facebook/buck/util/immutables:immutables"],
    deps = [
        "//src/com/facebook/buck/util:util",
        "//third-party/java/immutables:immutables",
    ],
)
