load("//tools/build_rules:java_rules.bzl", "standard_java_test")

standard_java_test(
    name = "context",
    deps = [
        "//src/com/facebook/buck/core/build/execution/context/actionid:actionid",
        "//src/com/facebook/buck/downwardapi/processexecutor/context:context",
        "//src/com/facebook/buck/downwardapi/protocol:protocol",
        "//src/com/facebook/buck/event:event",
        "//src/com/facebook/buck/event:interfaces",
        "//src/com/facebook/buck/event/isolated:isolated",
        "//test/com/facebook/buck/util/timing:testutil",
        "//third-party/java/guava:guava",
        "//third-party/java/junit:junit",
    ],
)
