java_library(
  name = 'python',
  srcs = glob(['*.java']),
  deps = [
    '//lib:guava',
    '//src/com/facebook/buck/model:model',
    '//src/com/facebook/buck/parser:core',
    '//src/com/facebook/buck/rules:core',
    '//src/com/facebook/buck/shell:shell',
    '//src/com/facebook/buck/step:step',
    '//src/com/facebook/buck/step/fs:fs',
    '//src/com/facebook/buck/util:util',
  ],
  visibility = [
    '//src/com/facebook/buck/parser:parser',
  ],
)
