java_binary(
  name = 'dxanalysis',
  main_class = 'com.facebook.buck.tools.dxanalysis.DxAnalysisMain',
  deps = [
    ':lib',
  ],
)

java_library(
  name = 'lib',
  srcs = glob(['*.java']),
  autodeps = True,
)
