java_library(
  name = 'autodeps',
  srcs = glob(['*.java']),
  # JavaDepsFinder is verified via AutodepsCommandIntegrationTest.
  #
  # Because the bulk of the logic to test in JavaDepsFinder requires a TargetGraph,
  # and it is considerably easier to define a TargetGraph by creating sample projects
  # under testdata/ than it is to  construct one programmatically, it makes
  # sense to use Buck's integration test framework to verify JavaDepsFinder rather
  # than a conventional unit test. Since the integration test framework is generally
  # driven by running a Buck subcommand, it makes sense for AutodepsCommandIntegrationTest
  # to be responsible for verifying JavaDepsFinder.
  tests = [
    '//test/com/facebook/buck/cli:cli',
  ],
  autodeps = True,
  visibility = [ 'PUBLIC' ],
)
