SYMBOL_EXTRACTOR_SRCS = [
    "Symbols.java",
    "SymbolExtractor.java",
]

java_library(
    name = "SymbolExtractor",
    srcs = SYMBOL_EXTRACTOR_SRCS,
    autodeps = True,
    exported_deps = [
        "//src/com/facebook/buck/jvm/java:autodeps",
        "//third-party/java/guava:guava",
        "//third-party/java/jackson:jackson-databind",
    ],
    visibility = [
        "PUBLIC",
    ],
)

java_library(
    name = "autodeps",
    srcs = glob(
        ["*.java"],
        excludes = SYMBOL_EXTRACTOR_SRCS,
    ),
    autodeps = True,
    exported_deps = [
        "//src/com/facebook/buck/autodeps:model",
        "//src/com/facebook/buck/cli:config",
        "//src/com/facebook/buck/io:io",
        "//src/com/facebook/buck/jvm/java:autodeps",
        "//src/com/facebook/buck/jvm/java/autodeps:SymbolExtractor",
        "//src/com/facebook/buck/model:model",
        "//src/com/facebook/buck/rules:build_rule",
        "//src/com/facebook/buck/rules:interfaces",
        "//src/com/facebook/buck/rules:rules",
        "//src/com/facebook/buck/step:step",
        "//src/com/facebook/buck/util:process_executor",
        "//third-party/java/guava:guava",
        "//third-party/java/jackson:jackson-databind",
    ],
    tests = [
        # JavaDepsFinder is verified via AutodepsCommandIntegrationTest.
        #
        # Because the bulk of the logic to test in JavaDepsFinder requires a TargetGraph,
        # and it is considerably easier to define a TargetGraph by creating sample projects
        # under testdata/ than it is to  construct one programmatically, it makes
        # sense to use Buck's integration test framework to verify JavaDepsFinder rather
        # than a conventional unit test. Since the integration test framework is generally
        # driven by running a Buck subcommand, it makes sense for AutodepsCommandIntegrationTest
        # to be responsible for verifying JavaDepsFinder.
        "//test/com/facebook/buck/cli:cli",
        "//test/com/facebook/buck/jvm/java/autodeps:autodeps",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/android:rules",
        "//src/com/facebook/buck/jvm/java:config",
        "//src/com/facebook/buck/jvm/java:rules",
        "//src/com/facebook/buck/jvm/java:support",
        "//src/com/facebook/buck/parser:rule_pattern",
        "//src/com/facebook/buck/step/fs:fs",
        "//src/com/facebook/buck/util:object_mapper",
        "//src/com/facebook/buck/util:util",
        "//third-party/java/jsr:jsr305",
    ],
)
