java_immutables_library(
  name = 'xcode',
  srcs = [
    'GidGenerator.java',
    'XcodeprojSerializer.java',
    'XCScheme.java',
  ] + glob(['util/*.java', 'xcodeproj/*.java']),
  immutable_types = [
    'xcodeproj.CopyFilePhaseDestinationSpec',
    'xcodeproj.ProductType',
  ],
  tests = [
    '//test/com/facebook/buck/apple/xcode:xcode',
  ],
  autodeps = True,
  visibility = [
    'PUBLIC',
  ],
)
