standard_java_library(
  srcs = [
    'GidGenerator.java',
    'XcodeprojSerializer.java',
    'XCScheme.java',
  ] + glob(['util/*.java', 'xcodeproj/*.java']),
  immutable_types = [
    'xcodeproj.CopyFilePhaseDestinationSpec',
    'xcodeproj.ProductType',
  ],
  tests = [
    '//test/com/facebook/buck/apple/xcode:xcode',
  ],
)
