java_library(
  name = 'feed',
  srcs = [
    'FeedActivity.java',
    'FeedStoryRenderer.java',
  ],
  deps = [
    '//testdata/com/facebook/feed/model:model',
  ],
)

# This is commented out for now because running `buck test --all` to
# test Buck would pick up this BUILD file and infer that that it is
# building an Android project, which would result in it setting the
# -bootclasspath for Android, which excludes classes that Buck needs,
# such as javax.tools.JavaCompiler. Parser should be updated so that
# BUILD_FILE_NAME can be injected so that test build files can be
# named something different, such as TEST_BUILD, so that fake BUILD
# files can be parsed exclusively for testing.

#android_binary(
#  name = 'app',
#  manifest = 'AndroidManifest.xml',
#  target = 'Google Inc.:Google APIs:19',
#  deps = [
#    '//testdata/com/facebook/feed:feed',
#  ],
#)
