load("//tools/build_rules:java_rules.bzl", "standard_java_test")

standard_java_test(
    name = "protocol",
    deps = [
        "//src-gen:downward-model",
        "//src/com/facebook/buck/downwardapi/protocol:protocol",
        "//third-party/java/junit:junit",
    ],
)
