android_library(
    name = "agent-lib",
    srcs = glob(["*.java"]),
    # Because this code gets dx'd, we restrict the source to Java 6 so that
    # trying to use something like try-with-resources is a compile-time error.
    source = "6",
    target = "6",
    deps = [
        # Do not add other deps here.  The agent should remain very small.
        "//src/com/facebook/buck/android/agent/util:util",
    ],
)

java_library(
    name = "manifest-as-resource",
    resources = [
        "AndroidManifest.xml",
    ],
    visibility = [
        "//test/...",
    ],
)

java_binary(
    name = "agent-for-host",
    main_class = "com.facebook.buck.android.agent.AgentMain",
    deps = [
        ":agent-lib",
    ],
)

android_binary(
    name = "agent",
    keystore = ":debug_keystore",
    manifest = "AndroidManifest.xml",
    deps = [
        ":agent-lib",
        "//src/com/facebook/buck/android/agent/native:native",
    ],
)

keystore(
    name = "debug_keystore",
    properties = "debug.keystore.properties",
    store = "debug.keystore",
)
