android_library(
  name = 'agent-lib',
  srcs = glob(['*.java']),
  # Because this code gets dx'd, we restrict the source to Java 6 so that
  # trying to use something like try-with-resources is a compile-time error.
  source = '6',
  target = '6',
  deps = [
    '//src/com/facebook/buck/android/agent/util:util',
    # Do not add other deps here.  The agent should remain very small.
  ],
)

java_library(
  name = 'manifest-as-resource',
  resources = [
    'AndroidManifest.xml',
  ],
  visibility = [
    '//test/...',
  ],
)

java_binary(
  name = 'agent-for-host',
  main_class = "com.facebook.buck.android.agent.AgentMain",
  deps = [
    ':agent-lib',
  ],
)

android_binary(
  name = 'agent',
  manifest = 'AndroidManifest.xml',
  target = 'Google Inc.:Google APIs:19',
  keystore = ':debug_keystore',
  deps = [
    ':agent-lib',
    '//src/com/facebook/buck/android/agent/native:native',
  ],
)

keystore(
  name = 'debug_keystore',
  store = 'debug.keystore',
  properties = 'debug.keystore.properties',
)
