load("//tools/build_rules:java_rules.bzl", "java_library_with_plugins")

java_library_with_plugins(
    name = "toolchain",
    srcs = glob(["*.java"]),
    exported_provided_deps = [
        "//src/com/facebook/buck/model:model",
        "//src/com/facebook/buck/core/rules/impl:impl",
        "//src/com/facebook/buck/toolchain:toolchain",
        "//src/com/facebook/buck/core/toolchain/tool:tool",
    ],
    provided_deps = [
        "//src/com/facebook/buck/core/sourcepath/resolver:resolver",
    ],
    visibility = ["PUBLIC"],
)
