load("//tools/build_rules:export_files.bzl", "export_files")

java_library(
    name = "moduleclass",
    srcs = glob(["*.java"]),
    deps = [
        "//src/com/facebook/buck/core/module/impl:impl",
        "//src/com/facebook/buck/core/plugin/impl:impl",
        "//test/com/facebook/buck/core/module/impl:test_extension",
        "//third-party/java/guava:guava",
        "//third-party/java/junit:junit",
        "//third-party/java/slf4j:slf4j-api",
    ],
)

java_binary(
    name = "moduleclass-jar",
    main_class = "com.facebook.buck.core.module.impl.modulewithdeps.ModuleWithDependenciesTest",
    deps = [
        ":moduleclass",
        "//third-party/java/slf4j:slf4j",
    ],
)

export_files(["known-hash.txt"])

# Replace real hash in the module jar with a known value
genrule(
    name = "test_module-jar-with-known-hash",
    out = "test_module.jar",
    cmd = " ".join([
        "$(exe //py/buck/zip:append_with_copy)",
        "$(location {}) $OUT".format("//test/com/facebook/buck/core/module/impl/modulewithdeps/test_module:test_module-module"),
        "META-INF/module-binary-hash.txt $(location :{})".format("known-hash.txt"),
    ]),
)

# Replace real hash in the module jar with a known value
genrule(
    name = "dependent_module-jar-with-known-hash",
    out = "dependent_module.jar",
    cmd = " ".join([
        "$(exe //py/buck/zip:append_with_copy)",
        "$(location {}) $OUT".format("//test/com/facebook/buck/core/module/impl/modulewithdeps/dependent_module:dependent_module-module"),
        "META-INF/module-binary-hash.txt $(location :{})".format("known-hash.txt"),
    ]),
)

# Copy modules to a place where they can be loaded by plugin manager
genrule(
    name = "copy-modules",
    out = "modules",
    cmd = "mkdir -p $OUT; cp $(location :test_module-jar-with-known-hash) $(location :dependent_module-jar-with-known-hash) $OUT",
    cmd_exe = "mkdir $OUT && copy $(location :test_module-jar-with-known-hash) $OUT && copy $(location :dependent_module-jar-with-known-hash) $OUT",
)

# Running tests as a shell script to reconstruct the layout of modules and how they are loaded
sh_test(
    name = "moduleclass-test",
    args = [
        "java",
        "-Dpf4j.pluginsDir=$(location :copy-modules)",
        "-jar",
        "$(location :moduleclass-jar)",
    ],
    test = "//test/com/facebook/buck/core/module/impl:run.sh",
)
