
java_test(
  name = 'model',
  srcs = glob(includes = ['*.java'], excludes = ['BuildTargetFactory.java']),
  deps = [
    ':BuildTargetFactory',
    '//src/com/facebook/buck/cli:config',
    '//src/com/facebook/buck/io:io',
    '//src/com/facebook/buck/jvm/java:rules',
    '//src/com/facebook/buck/model:model',
    '//src/com/facebook/buck/parser:parser',
    '//src/com/facebook/buck/rules:build_rule',
    '//src/com/facebook/buck/rules:rules',
    '//src/com/facebook/buck/util:constants',
    '//src/com/facebook/buck/util:exceptions',
    '//src/com/facebook/buck/util:util',
    '//test/com/facebook/buck/jvm/java:testutil',
    '//test/com/facebook/buck/rules:testutil',
    '//test/com/facebook/buck/testutil/integration:integration',
    '//third-party/java/easymock:easymock',
    '//third-party/java/hamcrest:hamcrest',
    '//third-party/java/jsr:jsr305',
    '//third-party/java/junit:junit',
    '//third-party/java/guava:guava',
  ],
)

java_library(
  name = 'BuildTargetFactory',
  srcs = [
    'BuildTargetFactory.java',
  ],
  deps = [
    '//src/com/facebook/buck/io:io',
    '//src/com/facebook/buck/model:model',
    '//src/com/facebook/buck/util:constants',
    '//src/com/facebook/buck/util:util',
    '//test/com/facebook/buck/testutil:testutil',
    '//third-party/java/guava:guava',
#    '//third-party/java/jimfs:jimfs',
    '//third-party/java/jsr:jsr305',
  ],
  visibility = [
    '//test/...',
  ])
