
java_test(name = 'model',
  srcs = glob(includes = ['*.java'], excludes = ['BuildTargetFactory.java']),
  deps = [
    ':BuildTargetFactory',
    '//src/com/facebook/buck/io:io',
    '//src/com/facebook/buck/java:rules',
    '//src/com/facebook/buck/model:model',
    '//src/com/facebook/buck/parser:parser',
    '//src/com/facebook/buck/rules:build_rule',
    '//src/com/facebook/buck/rules:rules',
    '//src/com/facebook/buck/util:exceptions',
    '//src/com/facebook/buck/util:util',
    '//test/com/facebook/buck/java:testutil',
    '//test/com/facebook/buck/rules:testutil',
    '//third-party/java/easymock:easymock',
    '//third-party/java/hamcrest:hamcrest',
    '//third-party/java/junit:junit',
    '//third-party/java/guava:guava',
  ],
  source_under_test = [
    '//src/com/facebook/buck/model:model',
  ],
)

java_library(
  name = 'BuildTargetFactory',
  srcs = [
    'BuildTargetFactory.java',
  ],
  deps = [
    '//third-party/java/guava:guava',
    '//src/com/facebook/buck/model:model',
    '//src/com/facebook/buck/util:constants',
    '//src/com/facebook/buck/util:util',
  ],
  visibility = [
    '//test/...',
  ])
