// @generated
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cd/resources/proto/kotlincd.proto

package com.facebook.buck.cd.model.kotlin;

@javax.annotation.Generated(value="protoc", comments="annotations:LibraryJarCommandOrBuilder.java.pb.meta")
public interface LibraryJarCommandOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kotlincd.api.v1.LibraryJarCommand)
    com.google.protobuf.MessageOrBuilder {
}
