load("//tools/build_rules:java_rules.bzl", "standard_java_test")

standard_java_test(
    name = "exceptions",
    deps = [
        "//src/com/facebook/buck/core/exceptions:exceptions",
        "//src/com/facebook/buck/util/string:string",
        "//third-party/java/guava:guava",
        "//third-party/java/junit:junit",
    ],
)
