load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "impl",
    srcs = glob(["*.java"]),
    tests = [
        "//test/com/facebook/buck/core/rules/transformer/impl:impl",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/core/description/impl:impl",
        "//src/com/facebook/buck/core/rules/analysis/computation:computation",
        "//src/com/facebook/buck/core/rules/analysis/impl:impl",
        "//src/com/facebook/buck/core/rules/providers/collect/impl:impl",
        "//src/com/facebook/buck/core/rules/tool:tool",
        "//src/com/facebook/buck/io/file:file",
        "//src/com/facebook/buck/rules/query:query",
        "//src/com/facebook/buck/rules/query:utils",
        "//src/com/facebook/buck/util/stream:stream",
        "//third-party/java/guava:guava",
    ],
    exported_deps = [
        "//src/com/facebook/buck/core/model/targetgraph:targetgraph",
        "//src/com/facebook/buck/core/rules/impl:impl",
        "//src/com/facebook/buck/core/rules/transformer:transformer",
    ],
)
