load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "worker_job_params",
    srcs = [
        "AbstractWorkerJobParams.java",
        "AbstractWorkerProcessIdentity.java",
        "AbstractWorkerProcessParams.java",
    ],
    visibility = ["PUBLIC"],
)

java_library(
    name = "worker_pool_factory",
    srcs = [
        "WorkerProcessPoolFactory.java",
    ],
    visibility = ["PUBLIC"],
    deps = [
        ":worker_job_params",
        ":worker_process",
        "//src/com/facebook/buck/event:event",
        "//src/com/facebook/buck/event:interfaces",
        "//src/com/facebook/buck/event/external:external_lib",
        "//src/com/facebook/buck/io:io",
        "//src/com/facebook/buck/io/filesystem:filesystem",
        "//src/com/facebook/buck/step:step",
        "//src/com/facebook/buck/util:process_executor",
        "//src/com/facebook/buck/util:util",
        "//src/com/facebook/buck/util/environment:platform",
        "//third-party/java/guava:guava",
    ],
)

java_immutables_library(
    name = "worker_process",
    srcs = [
        "AbstractWorkerJobResult.java",
        "AbstractWorkerProcessCommand.java",
        "WorkerProcess.java",
        "WorkerProcessPool.java",
        "WorkerProcessProtocol.java",
        "WorkerProcessProtocolZero.java",
    ],
    tests = [
        "//test/com/facebook/buck/shell:shell",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/core/exceptions:exceptions",
        "//src/com/facebook/buck/io:io",
        "//src/com/facebook/buck/io/filesystem:filesystem",
        "//src/com/facebook/buck/log:api",
        "//src/com/facebook/buck/util:exceptions",
        "//src/com/facebook/buck/util:process_executor",
        "//src/com/facebook/buck/util:util",
        "//src/com/facebook/buck/util/concurrent:concurrent",
        "//third-party/java/gson:gson",
    ],
)
