java_test(
  name = 'concurrent',
  srcs = glob(['*Test.java']),
  deps = [
    ':testutil',
    '//src/com/facebook/buck/model:model',
    '//src/com/facebook/buck/util/concurrent:concurrent',
    '//third-party/java/guava:guava',
    '//third-party/java/hamcrest:hamcrest',
    '//third-party/java/junit:junit',
  ],
)

java_library(
  name = 'testutil',
  srcs = [
    'FakeListeningExecutorService.java',
    'ExplicitRunExecutorService.java',
  ],
  deps = [
    '//third-party/java/guava:guava',
  ],
  visibility = [
    'PUBLIC',
  ],
)
