java_library(
    name = "impl",
    srcs = glob(["*.java"]),
    exported_deps = [
        "//src/com/facebook/buck/core/toolchain/toolprovider:toolprovider",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/model:model",
        "//src/com/facebook/buck/rules:build_rule",
    ],
)
