java_library(
    name = "concat",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    exported_deps = [
        "//third-party/java/guava:guava",
        "//third-party/java/jsr:jsr305",
    ],
)
