load("//tools/build_rules:java_rules.bzl", "java_test")

java_test(
    name = "bgtasks",
    srcs = glob(["*Test.java"]),
    has_immutable_types = True,
    deps = [
        ":testutil",
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/core/util/immutables:immutables",
        "//src/com/facebook/buck/core/util/log:log",
        "//src/com/facebook/buck/util:util",
        "//third-party/java/guava:guava",
        "//third-party/java/jsr:jsr305",
        "//third-party/java/junit:junit",
    ],
)

java_library(
    name = "testutil",
    srcs = glob(
        ["*.java"],
        exclude = ["*Test.java"],
    ),
    visibility = ["//test/..."],
    deps = [
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/core/util/log:log",
        "//src/com/facebook/buck/util/types:types",
        "//third-party/java/guava:guava",
    ],
    exported_deps = [
        "//src/com/facebook/buck/support/bgtasks:bgtasks",
    ],
)
