load(
    "//tools/build_rules:java_rules.bzl",
    "standard_java_test",
)

standard_java_test(
    name = "rule",
    deps = [
        "//src/com/facebook/buck/core/model/impl:impl",
        "//src/com/facebook/buck/core/toolchain/rule:rule",
        "//src/com/facebook/buck/features/dotnet:dotnet",
        "//src/com/facebook/buck/util/json:json",
        "//test/com/facebook/buck/core/model:testutil",
        "//test/com/facebook/buck/testutil:testutil",
        "//test/com/facebook/buck/testutil/integration:util",
        "//third-party/java/guava:guava",
        "//third-party/java/hamcrest:java-hamcrest",
        "//third-party/java/jetty:jetty",
        "//third-party/java/junit:junit",
    ],
)
