java_library(
    name = "testutil",
    srcs = glob(
        ["*.java"],
        excludes = ["*Test.java"],
    ),
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/io:io",
        "//src/com/facebook/buck/util:process_executor",
        "//src/com/facebook/buck/worker:worker_process",
        "//test/com/facebook/buck/testutil:testutil",
        "//test/com/facebook/buck/util:testutil",
        "//third-party/java/guava:guava",
    ],
)

standard_java_test(
    name = "worker",
    deps = [
        ":testutil",
        "//src/com/facebook/buck/io:io",
        "//src/com/facebook/buck/util:exceptions",
        "//src/com/facebook/buck/util:process_executor",
        "//src/com/facebook/buck/util:util",
        "//src/com/facebook/buck/util/environment:platform",
        "//src/com/facebook/buck/worker:worker_process",
        "//test/com/facebook/buck/testutil:testutil",
        "//test/com/facebook/buck/testutil/integration:util",
        "//test/com/facebook/buck/util:testutil",
        "//third-party/java/gson:gson",
        "//third-party/java/guava:guava",
        "//third-party/java/junit:junit",
    ],
)
