load("//tools/build_rules:module_rules.bzl", "buck_module")

buck_module(
    name = "supermodule",
    srcs = glob(["*.java"]),
    provided_deps = [
        "//src/com/facebook/buck/core/description/arg:arg",
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/core/model/targetgraph:targetgraph",
        "//src/com/facebook/buck/core/rules:rules",
        "//src/com/facebook/buck/core/sourcepath/resolver:resolver",
        "//src/com/facebook/buck/event:interfaces",
        "//src/com/facebook/buck/io:io",
        "//src/com/facebook/buck/rules/keys:keys",
        "//src/com/facebook/buck/rules/modern:modern",
        "//src/com/facebook/buck/step:step",
        "//src/com/facebook/buck/step/fs:fs",
        "//src/com/facebook/buck/util:util",
        "//src/com/facebook/buck/util/zip:zip",
        "//src/com/facebook/buck/util/zip/collect:collect",
        "//src/com/facebook/buck/versions:versions",
        "//third-party/java/guava:guava",
        "//third-party/java/infer-annotations:infer-annotations",
    ],
    tests = [
        "//test/com/facebook/buck/features/supermodule:supermodule",
    ],
    visibility = [
        "//test/com/facebook/buck/features/supermodule/...",
        "//test/com/facebook/buck/rules/modern:subclass_exclusion",
    ],
)
