load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "actiongraph",
    srcs = glob(["*.java"]),
    exported_deps = [
        "//src/com/facebook/buck/core/rules:rules",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/core/util/immutables:immutables",
    ],
)
