java_immutables_library(
  name = 'cache',
  srcs = glob(['*.java']),
  tests = [
    '//test/com/facebook/buck/util/cache:cache',
  ],
  deps = [
    '//src/com/facebook/buck/hashing:hashing',
    '//src/com/facebook/buck/io:io',
    '//src/com/facebook/buck/log:api',
    '//src/com/facebook/buck/model:model',
    '//third-party/java/guava:guava',
    '//third-party/java/jsr:jsr305',
  ],
  visibility = [
    'PUBLIC',
  ],
)
