standard_java_library(
  immutable_types = [
    'LuaBinaryPackageComponents',
    'LuaNativeExecutableStarter',
    'LuaPackageComponents',
    'LuaScriptStarter',
  ],
  resources = [
    'native-starter.cpp.in',
    'starter.lua.in',
  ],
  tests = [
    '//test/com/facebook/buck/lua:lua',
  ],
)
