java_library(
  name = 'shell',
  srcs = glob(['*.java']),
  deps = [
    '//lib:guava',
    '//lib:jsr305',
    '//src/com/facebook/buck/model:model',
    '//src/com/facebook/buck/step:step',
    '//src/com/facebook/buck/util:io',
    '//src/com/facebook/buck/util:util',
  ],
  visibility = [
    'PUBLIC',
  ],
)
