standard_java_library(
    name = "command",
    immutable_types = [
        "BuildExecutionResult",
    ],
    tests = [
        "//test/com/facebook/buck/cli:cli",
    ],
    visibility = [
        "//src/com/facebook/buck/cli:cli",
        "//src/com/facebook/buck/distributed:distributed",
        "//test/com/facebook/buck/cli:cli",
    ],
)
