java_library(
    name = "exceptions",
    srcs = glob([
        "*.java",
    ]),
    exported_deps = ["//src/com/facebook/buck/util:exceptions"],
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/model:model",
        "//src/com/facebook/buck/util:exceptions",
    ],
)
