java_library(
    name = "exceptions",
    srcs = glob([
        "*.java",
    ]),
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/core/exceptions:exceptions",
        "//src/com/facebook/buck/core/model:model",
        "//third-party/java/jsr:jsr305",
    ],
)
