java_test(
  name = 'slb',
  srcs = glob(['*.java']),
  deps = [
    '//src/com/facebook/buck/slb:slb',
    '//src/com/facebook/buck/timing:timing',
    '//third-party/java/easymock:easymock',
    '//third-party/java/guava:guava',
    '//third-party/java/junit:junit',
    '//third-party/java/okhttp:okhttp',
  ],
  visibility = [
    'PUBLIC',
  ]
)
