TEST_SRCS = [
  'FakeBuckEventListener.java',
  'TestEventConfigerator.java',
]

java_library(
  name = 'testutil',
  srcs = TEST_SRCS,
  deps = [
    '//lib:guava',
    '//src/com/facebook/buck/event:event',
    '//src/com/facebook/buck/timing:timing',
  ],
  visibility = [
    '//test/...',
  ],
)
