java_test(
  name = 'event',
  srcs = glob(['*Test.java']),
  source_under_test = [
    '//src/com/facebook/buck/event:event',
  ],
  deps = [
    ':testutil',
    '//lib:junit',
    '//src/com/facebook/buck/event:event',
  ],
)

java_library(
  name = 'testutil',
  srcs = [
    'BuckEventBusFactory.java',
    'FakeBuckEventListener.java',
    'TestEventConfigerator.java',
  ],
  deps = [
    '//lib:guava',
    '//src/com/facebook/buck/event:event',
    '//src/com/facebook/buck/timing:timing',
  ],
  visibility = [
    '//test/...',
  ],
)
