java_test(
  name = 'event',
  srcs = glob(['*Test.java']),
  deps = [
    ':testutil',
    '//src/com/facebook/buck/artifact_cache:artifact_cache',
    '//src/com/facebook/buck/event:event',
    '//src/com/facebook/buck/graph:graph',
    '//src/com/facebook/buck/java:rules',
    '//src/com/facebook/buck/model:model',
    '//src/com/facebook/buck/parser:parser',
    '//src/com/facebook/buck/rules:build_rule',
    '//src/com/facebook/buck/rules:rules',
    '//src/com/facebook/buck/test:test',
    '//src/com/facebook/buck/test/result/type:type',
    '//src/com/facebook/buck/test/selectors:selectors',
    '//src/com/facebook/buck/timing:timing',
    '//src/com/facebook/buck/util/concurrent:concurrent',
    '//src/com/facebook/buck/util:exceptions',
    '//test/com/facebook/buck/java:testutil',
    '//test/com/facebook/buck/model:BuildTargetFactory',
    '//test/com/facebook/buck/timing:testutil',
    '//test/com/facebook/buck/rules:testutil',
    '//third-party/java/guava:guava',
    '//third-party/java/junit:junit',
    '//third-party/java/hamcrest:hamcrest',
    '//third-party/java/jackson:jackson-core',
    '//third-party/java/jackson:jackson-databind',
  ],
)

java_library(
  name = 'testutil',
  srcs = [
    'BuckEventBusFactory.java',
    'FakeBuckEventListener.java',
    'TestEventConfigerator.java',
  ],
  deps = [
    '//third-party/java/guava:guava',
    '//src/com/facebook/buck/event:event',
    '//src/com/facebook/buck/model:model',
    '//src/com/facebook/buck/timing:timing',
  ],
  visibility = [
    '//test/...',
  ],
)
