load(
    "//tools/build_rules:java_rules.bzl",
    "java_test",
)

java_test(
    name = "processexecutor",
    srcs = glob(["*.java"]),
    deps = [
        "//src-gen:downward-model",
        "//src/com/facebook/buck/core/util/log:log",
        "//src/com/facebook/buck/downwardapi/namedpipes:namedpipes",
        "//src/com/facebook/buck/downwardapi/processexecutor:processexecutor",
        "//src/com/facebook/buck/downwardapi/processexecutor/context:context",
        "//src/com/facebook/buck/downwardapi/processexecutor/handlers:handlers",
        "//src/com/facebook/buck/downwardapi/protocol:protocol",
        "//src/com/facebook/buck/event:event",
        "//src/com/facebook/buck/event/chrome_trace:chrome_trace",
        "//src/com/facebook/buck/io/namedpipes:namedpipes",
        "//src/com/facebook/buck/step:step",
        "//test/com/facebook/buck/downwardapi/testutil:testutil",
        "//test/com/facebook/buck/event:testutil",
        "//test/com/facebook/buck/testutil:testutil",
        "//test/com/facebook/buck/util:testutil",
        "//test/com/facebook/buck/util/timing:testutil",
        "//third-party/java/guava:guava",
        "//third-party/java/junit:junit",
    ],
)
