java_library(
    name = "eventhandler",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    exported_deps = [
        "//src/com/facebook/buck/core/exceptions:exceptions",
        "//src/com/facebook/buck/event:interfaces",
        "//starlark:bazel",
        "//third-party/java/guava:guava",
        "//third-party/java/jsr:jsr305",
    ],
)
