java_library(
  name = 'autodeps',
  srcs = ['AutodepsWriter.java'],
  autodeps = True,
  visibility = [ 'PUBLIC' ],
)

java_library(
  name = 'model',
  srcs = ['DepsForBuildFiles.java'],
  autodeps = True,
  visibility = [ 'PUBLIC' ],
)
