java_test(
  name = 'counters',
  srcs = glob(['*.java']),
  deps = [
    '//src/com/facebook/buck/counters:counters',
    '//src/com/facebook/buck/event:event',
    '//third-party/java/easymock:easymock',
    '//third-party/java/guava:guava',
    '//third-party/java/hamcrest:hamcrest',
    '//third-party/java/junit:junit',
  ],
  visibility = [
    'PUBLIC',
  ]
)
