java_library(
  name = 'source',
  srcs = glob(['*.java']) + [
    '//src/com/facebook/buck/util/exportedfiles:Nullable.java',
    '//src/com/facebook/buck/util/exportedfiles:Preconditions.java',
  ],
  tests = [
    '//test/com/facebook/buck/jvm/java/abi/source:source',
  ],
  autodeps = False,  # see below
  deps = [
    # This module is loaded as a plugin into the compiler itself; don't take dependencies on Buck
    # internals or large libraries like Guava
  ],
  provided_deps = [
    # Tools.jar is the compiler itself, and will already be present at runtime;
    # we compile against a stub.
    '//third-party/java/jdk:compiler-tree-api',
  ],
  visibility = [
    '//src/com/facebook/buck/jvm/java/plugin:javac-plugin',
    '//test/com/facebook/buck/jvm/java/abi/source:source',
  ],
)