standard_java_test(
    name = "filesystem",
    deps = [
        "//src/com/facebook/buck/io:io",
        "//src/com/facebook/buck/io/filesystem:skylark",
        "//src/com/facebook/buck/util:util",
        "//test/com/facebook/buck/testutil:testutil",
        "//third-party/java/bazel:skylark-lang",
        "//third-party/java/guava:guava",
        "//third-party/java/junit:junit",
    ],
)
