java_library(
    name = "testutil",
    srcs = glob(
        ["*.java"],
        excludes = ["*Test.java"],
    ),
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/io:io",
        "//src/com/facebook/buck/io/filesystem/impl:impl",
        "//src/com/facebook/buck/util/config:config",
    ],
)
