java_test(
  name = 'source',
  srcs = glob(['*Test.java']),
  autodeps = True,
  provided_deps = [
    # Tools.jar is the compiler itself, and will already be present at runtime;
    # we compile against a stub.
    '//third-party/java/jdk:compiler-tree-api',
  ],
)

java_library(
  name = 'testutil',
  srcs = glob(['*.java'], excludes=['*Test.java']),
  autodeps = True,
  provided_deps = [
    # Tools.jar is the compiler itself, and will already be present at runtime;
    # we compile against a stub.
    '//third-party/java/jdk:compiler-tree-api',
  ],
)