load("//tools/build_rules:java_rules.bzl", "java_test")

java_test(
    name = "source",
    srcs = glob(["*Test.java"]),
    provided_deps = [
        # Tools.jar is the compiler itself, and will already be present at runtime;
        # we compile against a stub.
        "//third-party/java/jdk:compiler-tree-api",
    ],
    required_for_source_only_abi = True,
    deps = [
        "//src/com/facebook/buck/jvm/java/abi/source:source",
        "//src/com/facebook/buck/jvm/java/abi/source/api:api",
        "//src/com/facebook/buck/jvm/java/lang/model:model",
        "//src/com/facebook/buck/jvm/java/plugin/adapter:adapter",
        "//src/com/facebook/buck/util:util",
        "//src/com/facebook/buck/util/immutables:immutables",
        "//test/com/facebook/buck/jvm/java/abi/source:testutil",
        "//test/com/facebook/buck/jvm/java/plugin/adapter:testutil",
        "//test/com/facebook/buck/jvm/java/testutil/compiler:compiler",
        "//third-party/java/asm:asm",
        "//third-party/java/guava:guava",
        "//third-party/java/hamcrest:java-hamcrest",
        "//third-party/java/immutables:immutables",
        "//third-party/java/jackson:jackson-databind",
        "//third-party/java/jsr:jsr305",
        "//third-party/java/junit:junit",
    ],
)

java_library(
    name = "testutil",
    srcs = glob(
        ["*.java"],
        exclude = ["*Test.java"],
    ),
    provided_deps = [
        # Tools.jar is the compiler itself, and will already be present at runtime;
        # we compile against a stub.
        "//third-party/java/jdk:compiler-tree-api",
    ],
    deps = [
        "//src/com/facebook/buck/jvm/java:support",
        "//src/com/facebook/buck/jvm/java/abi:abi",
        "//src/com/facebook/buck/jvm/java/abi/source:source",
        "//src/com/facebook/buck/jvm/java/abi/source/api:api",
        "//src/com/facebook/buck/jvm/java/lang/model:model",
        "//src/com/facebook/buck/jvm/java/plugin/adapter:adapter",
        "//src/com/facebook/buck/jvm/java/plugin/api:api",
        "//test/com/facebook/buck/jvm/java/testutil/compiler:compiler",
        "//third-party/java/asm:asm",
        "//third-party/java/guava:guava",
        "//third-party/java/jsr:jsr305",
        "//third-party/java/junit:junit",
    ],
)
