java_library(
  name = 'junit',
  srcs = glob(['*.java']),
  deps = [
    # IMPORTANT! This library limits itself to types that are available in both the JDK and Android
    # Java API. The objective is to limit the set of files added to the ClassLoader that runs the
    # test, as not to interfere with the results of the test.
    '//lib:junit',
  ],
  visibility = [
    '//test/com/facebook/buck/junit:junit',
  ],
)
