java_immutables_library(
  name = 'slb',
  srcs = glob(['*.java']),
  immutable_types = [
    'ClientSideSlbConfig',
    'PerServerData',
    'ServerHealthManagerEventData',
  ],
  autodeps = True,
  visibility = [
    'PUBLIC',
  ],
)
