load("//tools/build_rules:java_rules.bzl", "java_immutables_library", "java_test")

TEST_SRCS = [
    "*Test.java",
]

java_test(
    name = "endtoend",
    srcs = glob(
        TEST_SRCS,
    ),
    deps = [
        "//programs:buck",
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/doctor:doctor",
        "//src/com/facebook/buck/doctor/config:config",
        "//src/com/facebook/buck/util:util",
        "//src/com/facebook/buck/util/environment:platform",
        "//test/com/facebook/buck/cli:testutil",
        "//test/com/facebook/buck/testutil:testutil",
        "//test/com/facebook/buck/testutil/endtoend:testutil",
        "//third-party/java/junit:junit",
    ],
)
