OUT_OF_PROCESS_SRCS = [
    "Main.java",
    "MainOutOfProcessJavac.java",
    "OutOfProcessInvocationReceiver.java",
    "OutOfProcessJavacEventSink.java",
]

java_library(
    name = "oop_javac",
    srcs = glob(["*.java"]),
    tests = [
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/event/api:api",
        "//src/com/facebook/buck/jvm/java:javac-compilation-mode",
        "//src/com/facebook/buck/jvm/java:javac-sink",
        "//src/com/facebook/buck/jvm/java:support",
        "//src/com/facebook/buck/message_ipc:message_ipc",
        "//src/com/facebook/buck/model:model",
        "//src/com/facebook/buck/parser:rule_pattern",
        "//src/com/facebook/buck/rules:build_rule",
        "//src/com/facebook/buck/rules:interfaces",
        "//src/com/facebook/buck/rules:source_path_interface",
        "//src/com/facebook/buck/util:process_executor",
        "//src/com/facebook/buck/util:util",
        "//src/com/facebook/buck/worker:worker_process",
        "//third-party/java/guava:guava",
        "//third-party/java/jackson:jackson-databind",
        "//third-party/java/jsr:jsr305",
    ],
)
