load("//tools/build_rules:java_rules.bzl", "standard_java_test")

standard_java_test(
    name = "memory",
    deps = [
        "//src/com/facebook/buck/util/memory:memory",
        "//third-party/java/junit:junit",
    ],
)
