java_immutables_library(
    name = "config",
    srcs = glob(["*.java"]),
    autodeps = True,
    immutable_types = [
        "DoctorConfig",
        "DoctorSuggestion",
        "DoctorEndpointRequest",
        "DoctorEndpointResponse",
    ],
    tests = [
        "//test/com/facebook/buck/doctor:doctor",
    ],
    visibility = [
        "PUBLIC",
    ],
)
