java_immutables_library(
  name = 'config',
  srcs = glob(['*.java'],),
  immutable_types = [
    'DoctorConfig',
    'DoctorSuggestion',
    'DoctorEndpointRequest',
    'DoctorEndpointResponse',
  ],
  autodeps = True,
  tests = [
   '//test/com/facebook/buck/doctor:doctor',
  ],
  visibility = [
    'PUBLIC'
  ]
)
