java_immutables_library(
    name = "config",
    srcs = glob(["*.java"]),
    autodeps = True,
    exported_deps = [
        "//src/com/facebook/buck/cli:config",
        "//src/com/facebook/buck/config:config",
        "//src/com/facebook/buck/model:build_id",
        "//src/com/facebook/buck/util/immutables:immutables",
        "//third-party/java/guava:guava",
        "//third-party/java/jackson:jackson-databind",
    ],
    immutable_types = [
        "DoctorConfig",
        "DoctorSuggestion",
        "DoctorEndpointRequest",
        "DoctorEndpointResponse",
    ],
    tests = [
        "//test/com/facebook/buck/doctor:doctor",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = ["//third-party/java/immutables:immutables"],
)
