load("//tools/build_rules:java_rules.bzl", "java_library_with_plugins")

java_library_with_plugins(
    name = "impl",
    srcs = glob(
        ["*.java"],
    ),
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/core/rules/impl:impl",
        "//src/com/facebook/buck/core/rules/tool:tool",
        "//third-party/java/guava:guava",
    ],
)
