load("//tools/build_rules:java_rules.bzl", "standard_java_test")

java_library(
    name = "testutil",
    srcs = glob(
        ["*.java"],
        exclude = ["*Test.java"],
    ),
    exported_deps = [
        "//src-gen:thrift",
        "//src/com/facebook/buck/manifestservice:manifestservice",
        "//third-party/java/guava:guava",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/io:io",
        "//src/com/facebook/buck/io/filesystem/impl:impl",
        "//src/com/facebook/buck/util/config:config",
    ],
)

standard_java_test(
    name = "cache",
    deps = [
        "//src/com/facebook/buck/core/config:config",
        "//src/com/facebook/buck/core/exceptions:exceptions",
        "//src/com/facebook/buck/core/util/log:log",
        "//src/com/facebook/buck/event:event",
        "//src/com/facebook/buck/io:io",
        "//src/com/facebook/buck/parser:parser",
        "//src/com/facebook/buck/parser/api:api",
        "//src/com/facebook/buck/parser/cache:cache",
        "//src/com/facebook/buck/parser/cache/impl:cache",
        "//src/com/facebook/buck/parser/cache/json:json",
        "//src/com/facebook/buck/parser/exceptions:exceptions",
        "//src/com/facebook/buck/skylark/io:io",
        "//src/com/facebook/buck/util:util",
        "//src/com/facebook/buck/util/config:config",
        "//test/com/facebook/buck/core/config:FakeBuckConfig",
        "//test/com/facebook/buck/event:testutil",
        "//test/com/facebook/buck/io/filesystem/impl:testutil",
        "//test/com/facebook/buck/parser/cache/impl:testutil",
        "//test/com/facebook/buck/testutil:testutil",
        "//third-party/java/junit:junit",
    ],
)
