load("//tools/build_rules:java_rules.bzl", "standard_java_test")

standard_java_test(
    name = "event",
    deps = [
        "//src/com/facebook/buck/core/test/event:event",
        "//test/com/facebook/buck/test:testutil",
        "//third-party/java/guava:guava",
        "//third-party/java/junit:junit",
    ],
)
