# Note that we deliberately avoid the use of java_immutables_library()
# in this package because we discourage the use of Guava collections
# in com.facebook.buck.query because it interacts badly with the Kotlin
# code in com.facebook.buck.multitenant.
java_library(
    name = "query",
    srcs = glob(["*.java"]),
    tests = [
        "//test/com/facebook/buck/query:query",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/core/sourcepath:types",
        "//src/com/facebook/buck/util/string:string",
        "//third-party/java/guava:guava",
        "//third-party/java/jsr:jsr305",
    ],
)
