load("//tools/build_rules:java_rules.bzl", "standard_java_test")

standard_java_test(
    name = "concat",
    deps = [
        "//src/com/facebook/buck/rules/coercer/concat:concat",
        "//third-party/java/junit:junit",
    ],
)
