android_binary(
  name = 'app',
  manifest = 'AndroidManifest.xml',
  target = 'Google Inc.:Google APIs:19',
  keystore = '//keystores:debug',
  deps = [
    '//java/com/sample/lib:lib',
    '//res/com/sample/base:base',
  ],
)

project_config(
  src_target = ':app',
)
