load("//tools/build_rules:java_rules.bzl", "standard_java_test")

standard_java_test(
    name = "sha1",
    deps = [
        "//src/com/facebook/buck/util/sha1:sha1",
        "//third-party/java/guava:guava",
        "//third-party/java/junit:junit",
    ],
)
