java_test(
  name = 'parcelable',
  srcs = glob(['*.java']),
  source_under_test = [
    '//src/com/facebook/buck/parcelable:parcelable',
  ],
  deps = [
    '//third-party/java/guava:guava',
    '//third-party/java/junit:junit',
    '//src/com/facebook/buck/parcelable:parcelable',
  ],
)
