java_test(
  name = 'parcelable',
  srcs = glob(['*.java']),
  source_under_test = [
    '//src/com/facebook/buck/parcelable:parcelable',
  ],
  deps = [
    '//src/com/facebook/buck/parcelable:parcelable',
    '//test/com/facebook/buck/testutil/integration:integration',
    '//third-party/java/guava:guava',
    '//third-party/java/junit:junit',
  ],
)
