java_test(
  name = 'parcelable',
  srcs = glob(['*.java']),
  source_under_test = [
    '//src/com/facebook/buck/parcelable:parcelable',
  ],
  deps = [
    '//lib:guava',
    '//lib:junit',
    '//src/com/facebook/buck/parcelable:parcelable',
  ],
)
