load("//tools/build_rules:java_rules.bzl", "java_test")

java_test(
    name = "zip",
    srcs = glob(["*Test.java"]),
    resources = [
        # Generated as: echo "1" > test.so && zip -0 test.zip test.so && zipalign 4 test.zip aligned.4.zip
        "aligned.4.zip",
        # Generated as: echo "1" > test.so && zip -0 -X test.zip test.so && zipalign 4 test.zip aligned.4.zip
        "aligned.4.no_extra.zip",
        # Generated as: echo "1" > test.so && zip -0 test.zip test.so && zipalign -p 4 test.zip aligned.page.zip
        "aligned.page.zip",
        "macbeth.dat",
        "sample-bytes.dat",
    ],
    source_only_abi_deps = ["//src/com/facebook/buck/util/zip:zip"],
    deps = [
        "//src/com/facebook/buck/io:io",
        "//src/com/facebook/buck/io/file:file",
        "//src/com/facebook/buck/io/filesystem/impl:impl",
        "//src/com/facebook/buck/jvm/java/version:version",
        "//src/com/facebook/buck/util/environment:platform",
        "//src/com/facebook/buck/util/unarchive:unarchive",
        "//src/com/facebook/buck/util/zip:zip",
        "//test/com/facebook/buck/io/filesystem:testutil",
        "//test/com/facebook/buck/testutil:testutil",
        "//test/com/facebook/buck/testutil/integration:util",
        "//third-party/java/commons-compress:commons-compress",
        "//third-party/java/guava:guava",
        "//third-party/java/junit:junit",
    ],
)
