java_test(
    name = "zip",
    srcs = glob(["*Test.java"]),
    resources = [
        # The sample bytes are a class file. We use the ".properties" extension so that IJ will copy
        # the file to the output dir when compiling, allowing us to test in the IDE.
        "macbeth.properties",
        "sample-bytes.properties",
    ],
    deps = [
        "//src/com/facebook/buck/io:io",
        "//src/com/facebook/buck/io/file:file",
        "//src/com/facebook/buck/io/filesystem/impl:impl",
        "//src/com/facebook/buck/util/environment:platform",
        "//src/com/facebook/buck/util/zip:zip",
        "//test/com/facebook/buck/testutil:testutil",
        "//test/com/facebook/buck/testutil/integration:util",
        "//third-party/java/commons-compress:commons-compress",
        "//third-party/java/guava:guava",
        "//third-party/java/junit:junit",
    ],
)
