java_library(
  name = 'unit',
  srcs = glob(['*.java']),
  tests = [
    '//test/com/facebook/buck/util/unit:unit',
  ],
  deps = [
    '//third-party/java/guava:guava',
    '//src/com/facebook/buck/util:util',
  ],
  visibility = [
    'PUBLIC',
  ],
)
