java_library(
    name = "unit",
    srcs = glob(["*.java"]),
    exported_deps = [
        "//src/com/facebook/buck/util/types:types",
    ],
    tests = [
        "//test/com/facebook/buck/util/unit:unit",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/util:util",
        "//third-party/java/guava:guava",
    ],
)
