load("//tools/build_rules:java_rules.bzl", "standard_java_test")

standard_java_test(
    name = "python",
    deps = [
        "//src/com/facebook/buck/android:rules",
        "//src/com/facebook/buck/features/project/intellij:intellij",
        "//src/com/facebook/buck/features/python:python",
        "//test/com/facebook/buck/core/model:testutil",
        "//test/com/facebook/buck/core/model/targetgraph:testutil",
        "//test/com/facebook/buck/features/project/intellij:testutil",
        "//test/com/facebook/buck/features/python:builders",
        "//test/com/facebook/buck/io/filesystem/impl:testutil",
        "//test/com/facebook/buck/jvm/java:testutil",
        "//third-party/java/junit:junit",
    ],
)
