load("//tools/build_rules:java_rules.bzl", "buck_java_library")
buck_java_library(
    name = "impl",
    srcs = glob(["*.java"]),
    visibility = [
        "//src/com/facebook/buck/downwardapi/processexecutor:processexecutor",
    ],
    deps = [
        "//src/com/facebook/buck/core/util/log:log",
        "//src/com/facebook/buck/downwardapi/processexecutor/context:context",
        "//src/com/facebook/buck/downwardapi/processexecutor/handlers:handlers",
        "//src/com/facebook/buck/event:interfaces",
        "//third-party/java/guava:guava",
    ],
    exported_deps = [
        "//src-gen:downward-model",
    ],
)
