include_defs('//third-party/java/javacc/DEFS')

javacc_parser_library(
  name = 'xcconfig',
  srcs = glob(['*.java', '*.jj']),
  deps = [
    '//lib:guava',
    '//lib:jsr305',
    '//src/com/facebook/buck/util:exceptions',
    '//src/com/facebook/buck/util:io',
  ],
  visibility = ['PUBLIC'],
)
