load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "modern",
    srcs = glob(["*.java"]),
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/core/rulekey:rulekey",
        "//src/com/facebook/buck/core/sourcepath:sourcepath",
        "//src/com/facebook/buck/util/function:function",
    ],
)
