load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "impl",
    srcs = glob(["*.java"]),
    exported_deps = [
        "//src/com/facebook/buck/rules/keys/config:config",
    ],
    visibility = [
        "//src/com/facebook/buck/cli:cli",
        "//src/com/facebook/buck/core/cell/impl:impl",
        "//test/...",
    ],
    deps = [
        "//src/com/facebook/buck/core/config:config",
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/module/impl:impl",
    ],
)
