load(
    "//tools/build_rules:java_rules.bzl",
    "java_immutables_library",
)

java_immutables_library(
    name = "common",
    srcs = glob(["*.java"]),
    visibility = [
        "//src/com/facebook/buck/...",
        "//test/com/facebook/buck/...",
    ],
    deps = [
        "//src/com/facebook/buck/io/file:file",
    ],
    exported_deps = [
        "//src/com/facebook/buck/io/filesystem/impl:impl",
        "//src/com/facebook/buck/step/isolatedsteps:isolatedsteps",
    ],
)
