ocaml_binary(
    name='main',
    srcs=[
        'main.ml'
    ],
    deps=[
        ':plus_lib'
    ],
    warnings_flags='-27',
)

ocaml_library(
    name = 'plus_lib',
    srcs = [
        'plus/plus.ml',
    ],
    warnings_flags='-27',
    visibility = [
        'PUBLIC',
    ]
)

ocaml_binary(
    name = 'plus',
    srcs = [
        'plus/main.ml',
    ],
    deps = [
        ':plus_lib',
    ],
    visibility = [
        'PUBLIC',
    ]
)
