standard_java_library(
    name = "i18n",
    exported_deps = [
        "//src/com/facebook/buck/util/immutables:immutables",
        "//third-party/java/guava:guava",
        "//third-party/java/jsr:jsr305",
    ],
    immutable_types = [
        "NumberFormatterCacheKey",
    ],
    deps = ["//third-party/java/immutables:immutables"],
)
