java_immutables_library(
  name = 'event',
  srcs = glob(['*.java']),
  tests = [
    '//test/com/facebook/buck/event:event',
  ],
  autodeps = True,
  provided_deps = [
    # Event API is loaded by the bootstrapper at runtime; don't need to depend on it strongly
    '//src/com/facebook/buck/event/api:api',
  ],
  exported_deps = [
    '//src/com/facebook/buck/event/external:external_lib',
  ],
  visibility = [
    'PUBLIC',
  ],
)
