java_library(
  name = 'b',
  srcs = ['B.java'],
  # This rule is missing the following dependency:
  # deps = ['//java/com/example/a:a'],
)

# Same as above, but as a test rather than a library.
java_test(
  name = 'test',
  srcs = ['B.java'],
)
