load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "name",
    srcs = glob(["*.java"]),
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/core/util:util",
        "//third-party/java/jackson:jackson-databind",
    ],
)
