load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "name",
    srcs = [
        "AbstractRelativeCellName.java",
    ],
    visibility = [
        "PUBLIC",
    ],
)
