load("//tools/build_rules:java_rules.bzl", "java_immutables_library", "java_test")

java_test(
    name = "provider",
    srcs = glob(["*Test.java"]),
    has_immutable_types = True,
    deps = [
        "//test/com/facebook/buck/model:testutil",
        "//test/com/facebook/buck/rules:testutil",
        "//test/com/facebook/buck/rules/provider:testutil",
        "//test/com/facebook/buck/testutil:testutil",
        "//third-party/java/junit:junit",
    ],
)

java_immutables_library(
    name = "testutil",
    srcs = glob(
        ["*.java"],
        exclude = ["*Test.java"],
    ),
    exported_deps = [
        "//src/com/facebook/buck/model:model",
        "//src/com/facebook/buck/rules:rules",
        "//src/com/facebook/buck/step:step",
    ],
    visibility = [
        "//test/...",
    ],
)
