#!/bin/bash

if [[ "$OSTYPE" =~ ^darwin ]]; then
  # This is OS X.
  $BUCK_PROJECT_ROOT/node/binaries/os_x_node_executable "$@"
else
  # This is not OS OX: assume Linux.
  $BUCK_PROJECT_ROOT/node/binaries/linux_node_executable "$@"
fi
