load("//tools/build_rules:java_rules.bzl", "standard_java_test")

java_library(
    name = "testutil",
    srcs = glob(
        ["*.java"],
        exclude = glob(["*Test.java"]),
    ),
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/config:config",
        "//src/com/facebook/buck/cxx/toolchain:toolchain",
        "//src/com/facebook/buck/cxx/toolchain/linker:linker",
        "//src/com/facebook/buck/io:io",
        "//src/com/facebook/buck/model:model",
        "//src/com/facebook/buck/rules:cli",
        "//src/com/facebook/buck/rules:rules",
        "//src/com/facebook/buck/rules:types",
        "//src/com/facebook/buck/util/config:config",
        "//src/com/facebook/buck/util/environment:platform",
        "//test/com/facebook/buck/config:FakeBuckConfig",
        "//test/com/facebook/buck/io/filesystem:testutil",
        "//test/com/facebook/buck/rules:testutil",
        "//test/com/facebook/buck/toolchain/impl:testutil",
        "//third-party/java/guava:guava",
    ],
)

standard_java_test(
    name = "toolchain",
    visibility = [
        "PUBLIC",
    ],
    with_test_data = True,
    deps = [
        ":testutil",
        "//src/com/facebook/buck/config:config",
        "//src/com/facebook/buck/cxx/toolchain:toolchain",
        "//src/com/facebook/buck/cxx/toolchain/linker:linker",
        "//src/com/facebook/buck/io:io",
        "//src/com/facebook/buck/model:model",
        "//src/com/facebook/buck/rules:build_rule",
        "//src/com/facebook/buck/rules:cli",
        "//src/com/facebook/buck/rules:rule_key",
        "//src/com/facebook/buck/rules:rules",
        "//src/com/facebook/buck/rules:source_path",
        "//src/com/facebook/buck/rules/keys:keys",
        "//src/com/facebook/buck/util/cache/impl:impl",
        "//src/com/facebook/buck/util/environment:platform",
        "//test/com/facebook/buck/config:FakeBuckConfig",
        "//test/com/facebook/buck/rules:testutil",
        "//test/com/facebook/buck/rules/keys:testutil",
        "//test/com/facebook/buck/testutil:testutil",
        "//test/com/facebook/buck/testutil/integration:util",
        "//test/com/facebook/buck/util/timing:testutil",
        "//third-party/java/guava:guava",
        "//third-party/java/hamcrest:hamcrest-junit",
        "//third-party/java/junit:junit",
    ],
)
