load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "attr",
    srcs = glob(["*.java"]),
    plugins = [
        "//starlark:starlark-annot-processor",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/core/starlark/rule/attr/impl:impl",
        "//starlark:bazel",
        "//third-party/java/guava:guava",
    ],
    exported_deps = [
        "//src/com/facebook/buck/core/starlark/rule/attr:attr",
    ],
)
