load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "attr",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/core/cell:cell",
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/core/starlark/rule/attr/impl:impl",
        "//src/com/facebook/buck/rules/coercer:coercer",
        "//src/com/facebook/buck/rules/coercer:interface",
        "//src/com/facebook/buck/skylark/io:io",
        "//src/com/facebook/buck/skylark/packages:packages",
        "//src/com/facebook/buck/skylark/parser/context:context",
        "//third-party/java/bazel:bazel",
        "//third-party/java/guava:guava",
    ],
    exported_deps = [
        "//src/com/facebook/buck/core/starlark/rule/attr:attr",
    ],
)
