STANDARD_TEST_SRCS = [
  '*Test.java',
]

java_library(
  name = 'testutil',
  srcs = glob(['*.java'], excludes = STANDARD_TEST_SRCS),
  deps = [
    '//lib:guava',
    '//lib:jsr305',
    '//src/com/facebook/buck/util:io',
    '//src/com/facebook/buck/util:util',
  ],
  visibility = [
    'PUBLIC',
  ],
)

java_test(
  name = 'util',
  srcs = glob(STANDARD_TEST_SRCS),
  source_under_test = [
    '//src/com/facebook/buck/util:constants',
    '//src/com/facebook/buck/util:exceptions',
    '//src/com/facebook/buck/util:io',
    '//src/com/facebook/buck/util:network',
    '//src/com/facebook/buck/util:util',
  ],
  deps = [
    ':testutil',
    '//lib:easymock',
    '//lib:guava',
    '//lib:hamcrest-core',
    '//lib:hamcrest-library',
    '//lib:junit',
    '//third-party/java/commons-compress:commons-compress',
    '//src/com/facebook/buck/util:exceptions',
    '//src/com/facebook/buck/util:io',
    '//src/com/facebook/buck/util:network',
    '//src/com/facebook/buck/util:util',
    '//src/com/facebook/buck/util/environment:platform',
    '//test/com/facebook/buck/testutil:testutil',
    '//test/com/facebook/buck/testutil/integration:integration',
  ],
)
