java_test(
  name = 'util',
  srcs = glob(['*.java']),
  source_under_test = [
    '//src/com/facebook/buck/util:util',
  ],
  deps = [
    '//lib:easymock',
    '//lib:guava',
    '//lib:junit',
    '//src/com/facebook/buck/util:exceptions',
    '//src/com/facebook/buck/util:util',
    '//src/com/facebook/buck/util:io',
  ],
)
