java_immutables_library(
  name = 'testutil',
  srcs = glob(
    ['*.java'],
    excludes = ['*Test.java'],
  ),
  autodeps = True,
  immutable_types = [
    'FakeListeningProcessState',
  ],
  visibility = [
    '//test/...',
  ],
)

java_test(
  name = 'util',
  srcs = glob(['*Test.java']),
  autodeps = True,
)
