load("//tools/build_rules:java_rules.bzl", "buck_java_library")
buck_java_library(
    name = "collect",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    exported_deps = [
        "//src/com/facebook/buck/core/rules/providers:providers",
        "//src/com/facebook/buck/core/rules/providers/lib:lib",
        "//starlark:bazel",
    ],
)
