java_library(
    name = "collect",
    srcs = glob(["*.java"]),
    exported_deps = [
        "//src/com/facebook/buck/core/rules/providers:providers",
        "//src/com/facebook/buck/core/rules/providers/lib:lib",
        "//third-party/java/bazel:bazel",
    ],
    visibility = ["PUBLIC"],
)
