CONSTANT_SRCS = [
    "BuckConstant.java",
]

java_library(
    name = "constants",
    srcs = CONSTANT_SRCS,
    visibility = ["PUBLIC"],
    deps = [],
)

EXCEPTION_SRCS = [
    "ExceptionWithHumanReadableMessage.java",
    "HumanReadableException.java",
    "WatchmanWatcherException.java",
]

java_library(
    name = "exceptions",
    srcs = EXCEPTION_SRCS,
    autodeps = True,
    tests = [
        "//test/com/facebook/buck/util:util",
    ],
    visibility = ["PUBLIC"],
)

IO_SRCS = [
    "AbstractCharsetProcessListener.java",
    "AbstractDirectoryCleanerArgs.java",
    "AnsiEnvironmentChecking.java",
    "BestCompressionGZIPOutputStream.java",
    "DefaultFilteredDirectoryCopier.java",
    "DirectoryCleaner.java",
    "FilteredDirectoryCopier.java",
    "LineIterating.java",
    "LineProcessorRunnable.java",
    "ListeningCharsetDecoder.java",
    "ListeningCharsetEncoder.java",
    "PkillProcessManager.java",
    "SimpleProcessListener.java",
    "TimeFormat.java",
    "UnixUserIdFetcher.java",
    "UserIdFetcher.java",
]

java_immutables_library(
    name = "io",
    srcs = IO_SRCS,
    autodeps = True,
    immutable_types = [
        "DirectoryCleanerArgs",
    ],
    tests = [
    ],
    visibility = ["PUBLIC"],
)

PROCESS_EXECUTOR_SRCS = [
    "AbstractProcessExecutorParams.java",
    "AbstractProcessResourceConsumption.java",
    "Ansi.java",
    "BgProcessKiller.java",
    "CapturingPrintStream.java",
    "Console.java",
    "ContextualProcessExecutor.java",
    "DefaultProcessExecutor.java",
    "DirtyPrintStreamDecorator.java",
    "ForwardingProcessListener.java",
    "InputStreamConsumer.java",
    "Libc.java",
    "LineFetcher.java",
    "ListeningProcessExecutor.java",
    "PrintStreamProcessExecutorFactory.java",
    "ProcessExecutor.java",
    "ProcessExecutorSerializer.java",
    "ProcessExecutorFactory.java",
    "ProcessHelper.java",
    "ProcessManager.java",
    "ProcessRegistry.java",
    "Threads.java",
    "Verbosity.java",
]

java_immutables_library(
    name = "process_executor",
    srcs = PROCESS_EXECUTOR_SRCS,
    immutable_types = [
        "ProcessExecutorParams",
    ],
    tests = [
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/log:api",
        "//src/com/facebook/buck/util:util",
        "//src/com/facebook/buck/util/concurrent:concurrent",
        "//src/com/facebook/buck/util/environment:platform",
        "//third-party/java/immutables:immutables",
        "//third-party/java/jna:jna",
        "//third-party/java/jna:jna-platform",
        "//third-party/java/nuprocess:nuprocess",
        "//third-party/java/oshi:oshi-core",
    ],
)

WATCHMAN_WATCHER_SRCS = [
    "WatchmanWatcher.java",
]

java_library(
    name = "watchman",
    srcs = WATCHMAN_WATCHER_SRCS,
    autodeps = True,
    visibility = [
        "//src/com/facebook/buck/cli:cli",
        "//src/com/facebook/buck/parser:config",
        "//test/...",
    ],
)

OBJECT_MAPPER_SRCS = [
    "ObjectMappers.java",
]

java_library(
    name = "object_mapper",
    srcs = OBJECT_MAPPER_SRCS,
    autodeps = True,
    visibility = [
        "PUBLIC",
    ],
)

PACKAGED_RESOURCE_SRCS = [
    "PackagedResource.java",
]

java_library(
    name = "packaged_resource",
    srcs = PACKAGED_RESOURCE_SRCS,
    autodeps = True,
    visibility = [
        "PUBLIC",
    ],
)

java_immutables_library(
    name = "util",
    srcs = glob(
        excludes = CONSTANT_SRCS + EXCEPTION_SRCS + IO_SRCS +
                   WATCHMAN_WATCHER_SRCS + OBJECT_MAPPER_SRCS +
                   PACKAGED_RESOURCE_SRCS + PROCESS_EXECUTOR_SRCS,
        includes = ["*.java"],
    ),
    autodeps = True,
    immutable_types = [
        "SampleRate",
        "PatternAndMessage",
    ],
    tests = [
        "//test/com/facebook/buck/util:util",
    ],
    visibility = [
        "PUBLIC",
    ],
)
