CONSTANT_SRCS = [
  'BuckConstant.java',
]
java_library(
  name = 'constants',
  srcs = CONSTANT_SRCS,
  visibility = [ 'PUBLIC' ],
  deps = [
    '//third-party/java/guava:guava',
    '//third-party/java/jsr:jsr305',
  ],
)


EXCEPTION_SRCS = [
  'ExceptionWithHumanReadableMessage.java',
  'HumanReadableException.java',
  'WatchmanWatcherException.java',
]
java_library(
  name = 'exceptions',
  srcs = EXCEPTION_SRCS,
  deps = [
    '//third-party/java/guava:guava',
    '//third-party/java/jsr:jsr305',
  ],
  visibility = [ 'PUBLIC' ],
)


IO_SRCS = [
  'AbstractProcessExecutorParams.java',
  'Ansi.java',
  'AnsiEnvironmentChecking.java',
  'BestCompressionGZIPOutputStream.java',
  'Console.java',
  'CapturingPrintStream.java',
  'DirtyPrintStreamDecorator.java',
  'InputStreamConsumer.java',
  'LineFetcher.java',
  'PkillProcessManager.java',
  'ProcessManager.java',
  'ProcessExecutor.java',
  'Threads.java',
  'UserIdFetcher.java',
  'UnixUserIdFetcher.java',
  'Verbosity.java',
]
java_immutables_library(
  name = 'io',
  srcs = IO_SRCS,
  deps = [
    ':constants',
    ':escaper',
    ':exceptions',
    '//third-party/java/guava:guava',
    '//third-party/java/jsr:jsr305',
    '//src/com/facebook/buck/io:io',
    '//src/com/facebook/buck/log:api',
    '//src/com/facebook/buck/util/environment:platform',
    '//src/com/facebook/buck/zip:stream',
  ],
  visibility = [ 'PUBLIC' ],
)

ESCAPER_SRCS = [
 'Escaper.java',
 'WindowsCreateProcessEscape.java',
]
java_library(
  name = 'escaper',
  srcs = ESCAPER_SRCS,
  deps = [
    '//src/com/facebook/buck/util/environment:platform',
    '//third-party/java/guava:guava',
  ],
  visibility = [
    'PUBLIC',
  ],
)

WATCHMAN_WATCHER_SRCS = [
  'ProjectFilesystemWatcher.java',
  'WatchmanWatcher.java',
]
java_library(
  name = 'watchman',
  srcs = WATCHMAN_WATCHER_SRCS,
  deps = [
    ':exceptions',
    ':util',
    '//src/com/facebook/buck/event:event',
    '//src/com/facebook/buck/io:io',
    '//src/com/facebook/buck/log:api',
    '//src/com/facebook/buck/timing:timing',
    '//third-party/java/guava:guava',
    '//third-party/java/jackson:jackson-core',
    '//third-party/java/jackson:jackson-databind',
    '//third-party/java/jsr:jsr305',
  ],
  visibility = [
    '//src/com/facebook/buck/cli:cli',
    '//test/com/facebook/buck/util:util',
  ],
)

java_immutables_library(
  name = 'util',
  srcs = glob(
    includes = ['*.java'],
    excludes = CONSTANT_SRCS + ESCAPER_SRCS + EXCEPTION_SRCS + IO_SRCS +
               WATCHMAN_WATCHER_SRCS),
  deps = [
    ':constants',
    ':exceptions',
    ':io',
    '//src/com/facebook/buck/hashing:hashing',
    '//src/com/facebook/buck/io:io',  # While we move classes
    '//src/com/facebook/buck/log:api',
    '//src/com/facebook/buck/zip:stream',
    '//third-party/java/aosp:aosp',
    '//third-party/java/ini4j:ini4j',
    '//third-party/java/jsr:jsr305',
  ],
  visibility = [
    'PUBLIC',
  ],
)

sh_test(
  name = 'one_project_filesystem_test',
  test = 'one_project_filesystem_test.sh',
)
