<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="FrameworkDetectionExcludesConfiguration" detection-enabled="false" />
  <component name="ProjectRootManager" version="2" languageLevel="%languageLevel%" assert-keyword="true" jdk-15="%jdk15%" project-jdk-name="%jdkName%" project-jdk-type="%jdkType%">
%if(outputUrl)%    <output url="file://$PROJECT_DIR$/%outputUrl%" />
%endif%  </component>
</project>
