java_library(
    name = "resolver",
    srcs = [
        "CellPathResolver.java",
    ],
    exported_deps = [
        "//src/com/facebook/buck/core/model:model",
        "//third-party/java/guava:guava",
    ],
    visibility = [
        "PUBLIC",
    ],
)
