java_library(
    name = "tracing",
    srcs = [
        "JavacPhaseEvent.java",
        "JavacPhaseEventLogger.java",
        "TranslatingJavacPhaseTracer.java",
    ],
    autodeps = True,
    exported_deps = [
        # Have to export this manually. `buck autodeps` does not export it because it is in the
        # provided_deps. This should be fixed in `buck autodeps`.
        ":api",
        "//src/com/facebook/buck/event:interfaces",
        "//src/com/facebook/buck/jvm/java:javac-sink",
        "//src/com/facebook/buck/model:model",
        "//src/com/facebook/buck/util:util",
        "//third-party/java/guava:guava",
        "//third-party/java/jsr:jsr305",
    ],
    provided_deps = [
        # The API module is part of the bootstrapper at runtime; don't need to depend on it directly
        ":api",
    ],
    tests = [
        "//test/com/facebook/buck/jvm/java/tracing:tracing",
    ],
    visibility = [
        "//src/com/facebook/buck/event/listener:listener",
        "//src/com/facebook/buck/jvm/java:support",
        "//test/com/facebook/buck/event/listener:listener",
        "//test/com/facebook/buck/jvm/java/tracing:tracing",
    ],
    deps = [
        "//src/com/facebook/buck/jvm/java/plugin:plugin",
        "//src/com/facebook/buck/log:api",
    ],
)

java_library(
    name = "compiler-plugin",
    srcs = [
        "TracingTaskListener.java",
    ],
    autodeps = False,  # see below
    provided_deps = [
        # Tools.jar is the compiler itself, and will already be present at runtime;
        # don't need to depend on it strongly.
        "//third-party/java/jdk:compiler-tree-api",

        # The API module is part of the bootstrapper at runtime; don't need to depend on it directly
        ":api",
    ],
    tests = [
        "//test/com/facebook/buck/jvm/java/tracing:tracing",
    ],
    visibility = [
        "//src/com/facebook/buck/jvm/java/plugin:javac-plugin",
        "//test/com/facebook/buck/jvm/java/tracing:tracing",
    ],
    deps = [
        # This module is loaded as a plugin into the compiler itself; don't take dependencies on Buck
        # internals (outside of stuff designed for use in plugins) or large libraries like Guava
        "//src/com/facebook/buck/jvm/java/plugin/adapter:adapter",
        "//src/com/facebook/buck/util/liteinfersupport:liteinfersupport",
    ],
)

java_library(
    name = "api",
    srcs = [
        "JavacPhaseTracer.java",
    ],
    autodeps = False,  # see below
    visibility = [
        "//src/com/facebook/buck/cli/bootstrapper:bootstrapper_lib",
        "//src/com/facebook/buck/intellij/...",
        "//src/com/facebook/buck/jvm/java:support",
        "//test/com/facebook/buck/jvm/java/tracing:tracing",
    ],
    deps = [
        # This is a super-light API that is loaded into Buck's bootstrapper. As such, be very careful
        # what you put here as it can pollute the classpath for annotation processors. In particular,
        # don't put any deps on third-party libraries or parts of Buck that might need third-party
        # libraries.

        # This dep is safe because it's designed for use in compiler plugins like annotation processors
        # and has no third-party dependencies.
        "//src/com/facebook/buck/util/liteinfersupport:liteinfersupport",
    ],
)
