java_library(
    name = "utils",
    srcs = glob(["*.java"]),
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/external/model:model",
        "//src/com/facebook/buck/externalactions/model:model",
        "//src/com/facebook/buck/util/json:json",
        "//third-party/java/guava:guava",
    ],
)
