kotlin_library(
    name = "fs",
    srcs = glob(["*.kt"]),
    tests = [
        "//test/com/facebook/buck/multitenant/fs:fs",
    ],
    visibility = [
        "//src/com/facebook/buck/multitenant/...",
        "//test/com/facebook/buck/multitenant/...",
    ],
    deps = [
        "//third-party/java/guava:guava",
    ],
)
