standard_java_library(
    name = "elf",
    exported_deps = [
        "//src/com/facebook/buck/model:simple_types",
        "//third-party/java/guava:guava",
    ],
    deps = ["//src/com/facebook/buck/util:util"],
)
