sh_binary(
  name = 'overwrite_sh',
  main = 'overwrite.sh',
  resources = [
    'dummy_resource',
  ],
  visibility = [
    'PUBLIC',
  ],
)

genrule(
  name = 'overwrite',
  cmd = '$(exe //:overwrite_sh) > $OUT',
  out = 'dummy.txt',
  deps = [
    '//:overwrite_sh',
  ],  
)
