load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "config",
    srcs = glob(["*.java"]),
    exported_deps = [
        "//src/com/facebook/buck/util:process_executor",
        "//src/com/facebook/buck/util/environment:platform",
        "//src/com/facebook/buck/util/randomizedtrial:randomizedtrial",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/io/file:file",
        "//src/com/facebook/buck/io/filesystem:filesystem",
        "//src/com/facebook/buck/log:api",
        "//src/com/facebook/buck/model:model",
        "//src/com/facebook/buck/parser:rule_pattern",
        "//src/com/facebook/buck/rules:interfaces",
        "//src/com/facebook/buck/rules:rule_key",
        "//src/com/facebook/buck/rules:source_path",
        "//src/com/facebook/buck/util:exceptions",
        "//src/com/facebook/buck/util:io",
        "//src/com/facebook/buck/util:util",
        "//src/com/facebook/buck/util/cache:cache",
        "//src/com/facebook/buck/util/config:config",
        "//src/com/facebook/buck/util/environment:platform",
        "//src/com/facebook/buck/util/network/hostname:hostname",
        "//third-party/java/infer-annotations:infer-annotations",
    ],
)
