java_library(
    name = "handler",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/util:util",
        "//third-party/java/guava:guava",
    ],
)
