load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "main_lib",
    srcs = glob(["*.java"]),
    tests = ["//test/com/facebook/buck/jvm/java/stepsbuilder/javacd/main:main"],
    visibility = ["PUBLIC"],
    deps = [
        "//src-gen:downward-model",
        "//src-gen:javacd-model",
        "//src-gen:worker-tool-model",
        "//src/com/facebook/buck/cli/bootstrapper:bootstrapper_lib",
        "//src/com/facebook/buck/core/util/log:log",
        "//src/com/facebook/buck/downwardapi/protocol:protocol",
        "//src/com/facebook/buck/downwardapi/utils:utils",
        "//src/com/facebook/buck/event/isolated:isolated",
        "//src/com/facebook/buck/external/log:log",
        "//src/com/facebook/buck/io/namedpipes:namedpipes",
        "//src/com/facebook/buck/jvm/core:core",
        "//src/com/facebook/buck/jvm/java/stepsbuilder/javacd:javacd",
        "//src/com/facebook/buck/step/isolatedsteps:isolatedsteps",
        "//src/com/facebook/buck/util:process_executor",
        "//src/com/facebook/buck/util/environment:environment",
        "//src/com/facebook/buck/util/timing:timing",
        "//src/com/facebook/buck/workertool/utils:utils",
        "//third-party/java/guava:guava",
    ],
)

java_binary(
    name = "main",
    main_class = "com.facebook.buck.jvm.java.stepsbuilder.javacd.main.JavaCDWorkerToolMain",
    visibility = ["PUBLIC"],
    deps = [":main_lib"],
)
