load("//tools/build_rules:buck2.bzl", "enable_buck2_bootstrap_prebuilts")
load("//tools/build_rules:java_rules.bzl", "java_immutables_library", "buck_java_binary")

java_immutables_library(
    name = "main_lib",
    srcs = glob(["*.java"]),
    tests = ["//test/com/facebook/buck/jvm/java/stepsbuilder/javacd/main:main"],
    visibility = [
        "//src/com/facebook/buck/cli:cli",
        "//test/com/facebook/buck/...",
    ],
    deps = [
        "//src-gen:downward-model",
        "//src-gen:javacd-model",
        "//src-gen:worker-tool-model",
        "//src/com/facebook/buck/core/rules/pipeline:pipeline",
        "//src/com/facebook/buck/core/util/log:log",
        "//src/com/facebook/buck/downwardapi/protocol:protocol",
        "//src/com/facebook/buck/downwardapi/utils:utils",
        "//src/com/facebook/buck/event/isolated:isolated",
        "//src/com/facebook/buck/external/log:log",
        "//src/com/facebook/buck/io/namedpipes:namedpipes",
        "//src/com/facebook/buck/jvm/cd/serialization:serialization",
        "//src/com/facebook/buck/jvm/cd/serialization/java:java",
        "//src/com/facebook/buck/jvm/java:steps",
        "//src/com/facebook/buck/jvm/java:support",
        "//src/com/facebook/buck/jvm/java/stepsbuilder:stepsbuilder",
        "//src/com/facebook/buck/jvm/java/stepsbuilder/javacd:javacd",
        "//src/com/facebook/buck/step/isolatedsteps:isolatedsteps",
        "//src/com/facebook/buck/step/isolatedsteps/java:java",
        "//src/com/facebook/buck/util/environment:environment",
        "//src/com/facebook/buck/util/monitoring:monitoring",
        "//src/com/facebook/buck/util/perf:perf",
        "//src/com/facebook/buck/util/unit:unit",
        "//src/com/facebook/buck/workertool/utils:utils",
        "//third-party/java/args4j:args4j",
        "//third-party/java/guava:guava",
    ],
)

alias(
    name = "javacd_tool",
    actual = ":javacd_tool_prebuilt" if enable_buck2_bootstrap_prebuilts() else ":javacd_tool-main",
    visibility = ["PUBLIC"],
)

buck_java_binary(
    name = "javacd_tool-main",
    main_class = "com.facebook.buck.jvm.java.stepsbuilder.javacd.main.JavaCDMain",
    visibility = [
        "PUBLIC",
    ],
    deps = [
        ":main_lib",
    ],
)

[
  export_file(
      name = "javacd_tool_prebuilt_jar",
      src = "javacd_tool_prebuilt.jar",
  ),
  command_alias(
      name = "javacd_tool_prebuilt",
      exe = "fbsource//third-party/toolchains/jdk:java",
      args = [
        "-jar",
        "$(location :javacd_tool_prebuilt_jar)",
      ],
      visibility = ["PUBLIC"],
  )
] if enable_buck2_bootstrap_prebuilts() else []
