load("//tools/build_rules:java_rules.bzl", "standard_java_test")

standard_java_test(
    name = "common",
    deps = [
        "//src/com/facebook/buck/core/build/execution/context:context",
        "//src/com/facebook/buck/core/cell/name:name",
        "//src/com/facebook/buck/core/filesystems:filesystems",
        "//src/com/facebook/buck/io/filesystem:filesystem",
        "//src/com/facebook/buck/step/isolatedsteps/common:common",
        "//src/com/facebook/buck/util/stream:stream",
        "//test/com/facebook/buck/step:testutil",
        "//test/com/facebook/buck/testutil:testutil",
        "//test/com/facebook/buck/testutil/integration:util",
        "//third-party/java/guava:guava",
        "//third-party/java/junit:junit",
    ],
)
