load("//tools/build_rules:java_rules.bzl", "standard_java_test")

standard_java_test(
    name = "json",
    deps = [
        "//src/com/facebook/buck/skylark/json:json",
        "//third-party/java/bazel:skylark-lang",
        "//third-party/java/guava:guava",
        "//third-party/java/jackson:jackson-databind",
        "//third-party/java/junit:junit",
    ],
)
