java_library(
  name = 'rules',
  srcs = glob(['*.java']),
  deps = [
    '//lib:guava',
    '//lib:jsr305',
    '//src/com/facebook/buck/model:model',
    '//src/com/facebook/buck/parser:support',
    '//src/com/facebook/buck/rules:rules',
    '//src/com/facebook/buck/shell:steps',
    '//src/com/facebook/buck/step:step',
    '//src/com/facebook/buck/step/fs:fs',
    '//src/com/facebook/buck/util:io',
  ],
  visibility = ['PUBLIC'],
)
