load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "bsd",
    srcs = glob(["*.java"]),
    tests = [
        "//test/com/facebook/buck/util/bsd:bsd",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/core/exceptions:exceptions",
        "//src/com/facebook/buck/util:exceptions",
        "//src/com/facebook/buck/util:util",
        "//src/com/facebook/buck/util/charset:charset",
    ],
)
