standard_java_testutil(
    name = "testutil",
)

standard_java_test(
    name = "hostname",
    deps = [
        "//src/com/facebook/buck/util:process_executor",
        "//src/com/facebook/buck/util/network/hostname:hostname",
        "//test/com/facebook/buck/testutil:testutil",
        "//third-party/java/hamcrest:java-hamcrest",
        "//third-party/java/junit:junit",
    ],
)
