load("//tools/build_rules:java_rules.bzl", "java_test", "java_immutables_library")

java_test(
    name = "impl",
    srcs = glob(["*Test.java"]),
    deps = [
        "//src/com/facebook/buck/core/toolchain/impl:impl",
        "//src/com/facebook/buck/util:exceptions",
        "//test/com/facebook/buck/core/config:FakeBuckConfig",
        "//test/com/facebook/buck/io/filesystem/impl:testutil",
        "//test/com/facebook/buck/rules/keys/config:testutil",
        "//test/com/facebook/buck/util:testutil",
        "//third-party/java/junit:junit",
    ],
)

java_immutables_library(
    name = "testutil",
    srcs = glob(
        ["*.java"],
        exclude = ["*Test.java"],
    ),
    exported_deps = [
        "//src/com/facebook/buck/core/toolchain:toolchain",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/core/toolchain/impl:impl",
        "//src/com/facebook/buck/util/environment:platform",
        "//test/com/facebook/buck/core/config:FakeBuckConfig",
    ],
)
