load("//tools/build_rules:java_rules.bzl", "standard_java_test")

standard_java_test(
    name = "pojoizer",
    deps = [
        "//src/com/facebook/buck/skylark/parser/pojoizer:pojoizer",
        "//third-party/java/guava:guava",
        "//third-party/java/junit:junit",
    ],
)
