java_library(
    name = "annotations",
    srcs = glob(["*.java"]),
    required_for_source_only_abi = True,
    visibility = [
        "//src/com/facebook/buck/core/...",
        "//src/com/facebook/buck/rules/modern/...",
    ],
)
