load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "description",
    srcs = glob(["*.java"]),
    exported_deps = [
        "//src/com/facebook/buck/config:config",
        "//src/com/facebook/buck/core/cell/resolver:resolver",
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/core/rules:rules",
        "//src/com/facebook/buck/core/rules/type:type",
        "//src/com/facebook/buck/sandbox:sandbox",
        "//src/com/facebook/buck/toolchain:toolchain",
        "//src/com/facebook/buck/versions:types",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/core/rules/type/impl:impl",
        "//src/com/facebook/buck/util:util",
        "//src/com/facebook/buck/util/collect:collect",
        "//third-party/java/guava:guava",
    ],
)
