load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "description",
    srcs = glob(["*.java"]),
    exported_deps = [
        "//src/com/facebook/buck/core/config:config",
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/core/model/impl:impl",
        "//src/com/facebook/buck/core/rules:rules",
        "//src/com/facebook/buck/core/toolchain:toolchain",
        "//src/com/facebook/buck/sandbox:sandbox",
        "//src/com/facebook/buck/versions:types",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//third-party/java/guava:guava",
    ],
)
