java_library(
    name = "description",
    srcs = glob(["*.java"]),
    exported_deps = [
        "//src/com/facebook/buck/core/rules:rules",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/util:util",
        "//src/com/facebook/buck/util/collect:collect",
        "//third-party/java/guava:guava",
    ],
)
