load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "apkmodule",
    srcs = glob(["*.java"]),
    exported_deps = [
        "//src/com/facebook/buck/core/model/targetgraph:targetgraph",
        "//src/com/facebook/buck/core/rulekey:rulekey",
    ],
    tests = [
        "//test/com/facebook/buck/android/apkmodule:apkmodule",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/graph:graph",
        "//src/com/facebook/buck/io:io",
        "//src/com/facebook/buck/io/filesystem:filesystem",
        "//src/com/facebook/buck/jvm/java/classes:classes",
        "//src/com/facebook/buck/util:util",
    ],
)
