load("//tools/build_rules:java_rules.bzl", "buck_java_library")
buck_java_library(
    name = "java",
    srcs = glob(["*.java"]),
    visibility = [
        "//src/com/facebook/buck/jvm/java/...",
    ],
    deps = [
        "//src-gen:javacd-model",
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/core/model/impl:impl",
        "//src/com/facebook/buck/core/rules/common:common",
        "//src/com/facebook/buck/jvm/cd/serialization:util",
        "//src/com/facebook/buck/jvm/cd/serialization:serialization",
        "//src/com/facebook/buck/jvm/java:config",
        "//src/com/facebook/buck/jvm/java:support",
        "//src/com/facebook/buck/step/isolatedsteps/java:java",
        "//src/com/facebook/buck/jvm/java/version:version",
        "//src/com/facebook/buck/util/types:types",
        "//third-party/java/guava:guava",
    ],
)
