java_test(
    name = "impl",
    srcs = glob([
        "*Test.java",
    ]),
    run_test_separately = True,
    deps = [
        "//src/com/facebook/buck/rules:build_rule",
        "//src/com/facebook/buck/swift/toolchain:toolchain",
        "//src/com/facebook/buck/swift/toolchain/impl:impl",
        "//test/com/facebook/buck/testutil/integration:util",
        "//third-party/java/guava:guava",
        "//third-party/java/junit:junit",
    ],
)
