load("//tools/build_rules:java_rules.bzl", "java_test")

java_test(
    name = "impl",
    srcs = glob([
        "*Test.java",
    ]),
    run_test_separately = True,
    deps = [
        "//src/com/facebook/buck/core/rules:rules",
        "//src/com/facebook/buck/core/toolchain/tool/impl:impl",
        "//src/com/facebook/buck/swift/toolchain:toolchain",
        "//src/com/facebook/buck/swift/toolchain/impl:impl",
        "//test/com/facebook/buck/core/sourcepath:testutil",
        "//test/com/facebook/buck/testutil:testutil",
        "//test/com/facebook/buck/testutil/integration:util",
        "//third-party/java/guava:guava",
        "//third-party/java/junit:junit",
    ],
)
