load("//tools/build_rules:java_rules.bzl", "java_test")

java_test(
    name = "fix",
    srcs = glob(
        ["*Test.java"],
    ),
    deps = [
        "//src/com/facebook/buck/support/fix:fix",
        "//src/com/facebook/buck/util:util",
        "//src/com/facebook/buck/util/environment:platform",
        "//src/com/facebook/buck/util/json:json",
        "//third-party/java/guava:guava",
        "//third-party/java/hamcrest:hamcrest-junit",
        "//third-party/java/junit:junit",
    ],
)
