STANDARD_TEST_SRCS = [
  '**/*Test.java',
]

java_test(
  name = 'buck_job',
  srcs = glob(STANDARD_TEST_SRCS),
  deps = [
    '//src-gen:thrift',
    '//third-party/java/thrift:libthrift',
    '//third-party/java/junit:junit',
  ],
)
