load("//tools/build_rules:java_rules.bzl", "java_immutables_library")

java_immutables_library(
    name = "collect",
    srcs = glob(["*.java"]),
    tests = [
        "//test/com/facebook/buck/util/zip/collect:collect",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/core/exceptions:exceptions",
        "//src/com/facebook/buck/io/filesystem:filesystem",
        "//src/com/facebook/buck/io/pathformat:pathformat",
        "//src/com/facebook/buck/util:util",
        "//src/com/facebook/buck/util/unarchive:unarchive",
        "//src/com/facebook/buck/util/zip:zip",
    ],
)
