apple_resource(
    name = 'TestHostAppResources',
    dirs = [],
    files = glob(['host_app/*.png']),
)

apple_binary(
    name = 'TestHostBinary',
    srcs = ['host_app/TestHostApp.m'],
    headers = ['host_app/TestHostApp.h'],
    frameworks = [
        '$SDKROOT/System/Library/Frameworks/Foundation.framework',
        '$SDKROOT/System/Library/Frameworks/UIKit.framework',
    ],
)

apple_bundle(
    name = 'TestHostApp',
    binary = ':TestHostBinary',
    deps = [':TestHostAppResources'],
    tests = [':AppTest'],
    extension = 'app',
    info_plist = 'host_app/TestHostApp.plist',
)

apple_test(
    name = 'AppTest',
    test_host_app = ':TestHostApp',
    extension = 'xctest',
    srcs = ['test/AppTest.m'],
    info_plist = 'test/AppTest.plist',
    frameworks = [
        '$SDKROOT/System/Library/Frameworks/Foundation.framework',
        '$PLATFORM_DIR/Developer/Library/Frameworks/XCTest.framework',
        '$SDKROOT/System/Library/Frameworks/UIKit.framework',
    ],
)
