load("//tools/build_rules:java_rules.bzl", "standard_java_test")

standard_java_test(
    name = "impl",
    deps = [
        "//src/com/facebook/buck/io:watchman",
        "//src/com/facebook/buck/io/filesystem/skylark:skylark",
        "//src/com/facebook/buck/skylark/function:function",
        "//src/com/facebook/buck/skylark/io:io",
        "//src/com/facebook/buck/skylark/io/impl:impl",
        "//src/com/facebook/buck/util:process_executor",
        "//test/com/facebook/buck/cli:testutil",
        "//test/com/facebook/buck/io:testutil",
        "//test/com/facebook/buck/testutil:testutil",
        "//test/com/facebook/buck/util/timing:testutil",
        "//third-party/java/bazel:skylark-lang",
        "//third-party/java/guava:guava",
        "//third-party/java/hamcrest:java-hamcrest",
        "//third-party/java/junit:junit",
    ],
)
