java_library(
    name = "processexecutor",
    srcs = glob(["*.java"]),
    tests = [
        "//test/com/facebook/buck/downwardapi/processexecutor:processexecutor",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//src/com/facebook/buck/core/model:model",
        "//src/com/facebook/buck/core/util/log:log",
        "//src/com/facebook/buck/downwardapi/namedpipes:namedpipes",
        "//src/com/facebook/buck/downwardapi/processexecutor/context:context",
        "//src/com/facebook/buck/downwardapi/processexecutor/handlers:handlers",
        "//src/com/facebook/buck/downwardapi/protocol:protocol",
        "//src/com/facebook/buck/downwardapi/utils:utils",
        "//src/com/facebook/buck/event:interfaces",
        "//src/com/facebook/buck/io/namedpipes:namedpipes",
        "//src/com/facebook/buck/util:process_executor",
        "//src/com/facebook/buck/util:util",
        "//src/com/facebook/buck/util/concurrent:concurrent",
        "//third-party/java/jsr:jsr305",
    ],
)
